### ISSUE TITLE
maxExtreme updates when dragging left handle

### ISSUE THREAD

**Issue by slawekkolodziej** [highslide-software/highcharts.com#1185]
Take a look at this demo: http://jsfiddle.net/uZqsp/3/ Current extremes are reported to the div. As you can see max is set to 2008-09-10. Now, when you move the left handle maximum extreme changes too.

Reported here: http://highslide.com/forum/viewtopic.php?f=12&t=19730

**Comment by pawelfus** [comment]
Works fine since 1.3.x: http://jsfiddle.net/uZqsp/6/
