### ISSUE TITLE
Scrollbar breaking after hiding all series when navigator disabled

### ISSUE THREAD

**Issue by mhardik** [highslide-software/highcharts.com#1195]
Hiding All Series and then Trying to show all or any one causing chart breaking.
Chart does not work.

How to reproduce: Hide all series. Then move slider to left. 
(As all series are hidden the will be no tick positions on x Axis).

Then Unhide all or anyone, Chart gets break and needs to be reloaded.

Fiddle:
http://jsfiddle.net/mhardik/27Tau/11/

**Comment by vickychijwani** [comment]
As a *partial* workaround, the navigator can be left as enabled and then "hidden" by increasing the height of the chart sufficiently so the navigator gets clipped by the chart container's parent (the parent of the container has `overflow: hidden` set). See this demo (click the "Show / hide navigator" button once): http://jsfiddle.net/vickychijwani/z4kgsfnp/

However, this also hides the scrollbar itself, so the only way to move around the chart is by dragging, but still this could be a reasonable compromise for some scenarios (like mine -- I want users to be able to hide the navigator dynamically to gain back precious vertical space).

**Comment by pawelfus** [comment]
**Workaround:**

Instead of disabling navigator by `navigator.enabled = false`, set: `navigator.height = 0`. Then in CSS hide remaining elements:

.highcharts-navigator-handle-left, .highcharts-navigator-handle-right, .highcharts-navigator {
    display: none;
}

Working demo: http://jsfiddle.net/z4kgsfnp/4/
