### ISSUE TITLE
Highstock vertical plotbands 

### ISSUE THREAD

**Issue by stefbast** [highslide-software/highcharts.com#1375]
When using  v1.2.4 and the code http://jsfiddle.net/pVgwM/
The plotbands are not drawn when the start date of the plotband is not visible on the chart. 
When changing the fromDate of the chart to a date before the startdate of the plotband the plotband is visible.

This issue is not present on the  v1.1.4.

**Comment by pawelfus** [comment]
Fixed since 2.0.0: http://jsfiddle.net/pVgwM/2/
