### ISSUE TITLE
Multiple panes - min for yAxis

### ISSUE THREAD

**Issue by pawelfus** [highslide-software/highcharts.com#1387]
Example: http://jsfiddle.net/8z5CQ/

As you can see, bottom spline is rendered outside the axis.

**Comment by highslide-software** [comment]
First demo: We recommend to use percentages for `yAxis.top` and `yAxis.height` for a better adaptation of the actual plot size. Percentages were not implemented by the time of this bug report.

Second demo: As noted under #1317, `yAxis.top` and `yAxis.height` is not officially supported in Highcharts, only Highstock. But we can make the clipping work in Highcharts by borrowing a snippet from Highstock: http://jsfiddle.net/highcharts/9hwMJ/6/
