### ISSUE TITLE
Chart - addPoint misaligned labels

### ISSUE THREAD

**Issue by sebastianbochan** [highslide-software/highcharts.com#1419]
In case when min/max value are set for xAxis, and we use addPoint, then xAxis labels are misaligned. 

Compare: 
http://jsfiddle.net/JDxLk/4/
http://jsfiddle.net/JDxLk/5/

Offset is solution, but it looks like a bug in calculating.

**Comment by pawelfus** [comment]
Works fine in 4.x: http://jsfiddle.net/JDxLk/8/
