### ISSUE TITLE
Series disappear if one of it is disabled per default 

### ISSUE THREAD

**Issue by fsteiger** [highslide-software/highcharts.com#1648]
The Problem exists for series with irregular times. The visible charts show up on start and after the animation they disappear.

I added an example http://jsfiddle.net/yW7LZ/1/.

Tested with the following browser and the latest highchart lib version:
- Iron Version 25.0.1400.0 (185000)
- Chrome Version 25.0.1364.172 m

**Comment by pawelfus** [comment]
With Chrome 44 works fine: http://jsfiddle.net/yW7LZ/4/ ;)
