### ISSUE TITLE
setExtremes doesn't pass dates correctly when there's no data

### ISSUE THREAD

**Issue by iweindesmedt** [highslide-software/highcharts.com#1655]
when setting a custom range exceeding a data range, setExtremes event object gets passed at least 1 invalid date.

http://jsfiddle.net/HTLKM/2/

Steps to reproduce:
- click OK
- drag an area so there's at least a part without a blue line in it
- an alert pops up, there should be the min and max date you've selected but there's at least 1 Invalid Date

**Comment by pawelfus** [comment]
Still present in 2.1.7. Here min and max are set as `UNDEFINED`, while (most probably) should be set as `dataMin` and `dataMax`:

[2.1.7: parts/Axis.js#L1349-L1354](https://github.com/highslide-software/highcharts.com/blob/highstock-v2.1.7/js/parts/Axis.js#L1349-L1354)

**Comment by highslide-software** [comment]
@pawelfus Yes that's probably valid. If you fix this, check against  #1734 and #1946 for regression.

**Comment by pawelfus** [comment]
> how can you retrieve the actual range the user selected?

Use `chart.events.selection` event: http://jsfiddle.net/HTLKM/14/

**Comment by pawelfus** [comment]
Replacing `UNDEFINED` with `dataMin/Max` breaks #3104, but works fine with #1734 & #1946. checking..
