### ISSUE TITLE
Huge values on y axis labels when graph is vertically "squashed"

### ISSUE THREAD

**Issue by tumbao** [highslide-software/highcharts.com#1797]
If you decrease the containers height until the graph becomes a line (or almost a line), the y axis labels values become huge and very far from the actual values in the series: http://jsfiddle.net/highcharts/MWWKu/

Notice that the highest value in the series is 216.4, and the y axis label is 10k!

**Comment by pawelfus** [comment]
Works fine with 4.1.8.
