### ISSUE TITLE
MouseOut event

### ISSUE THREAD

**Issue by slawekkolodziej** [highslide-software/highcharts.com#182]
Browser hangs while trying to update point on mouseout, it works correctly on mouseover.
Example: http://jsfiddle.net/5eDPS/1 Forum thread: http://highslide.com/forum/viewtopic.php?f=9&t=8921

**Comment by balticSD** [comment]
Bug is still there ...and we have 2014 until...

**Comment by balticSD** [comment]
Nice, that was fast after all for me ^^ Thanks!
Can you tell when this goes to a stable Version? ( I don't want to build it by my self :P )

**Comment by highslide-software** [comment]
It will be part of the next maintenance release, due within a few weeks.

**Comment by macejmic** [comment]
Hi guys, unfortunately there is still a bug. It's very specific use case I guess so it's not obvious in the first place. Everything was working good until I've added ```` tooltip: { enabled: false } ```` option.

http://jsfiddle.net/6sqL0zam/16/

**Comment by babblu** [comment]
Still we have this issue when tooltip  { enabled : false}. How can we reopen this issue ?

**Comment by baisusua** [comment]
Bug is still there ... 2017

**Comment by TorsteinHonsi** [comment]
I can't reproduce this with http://jsfiddle.net/6sqL0zam/16/. Can you see it with this fiddle? Which browser are you using?

**Comment by mthb-cg** [comment]
In this version you would expect the alert to trigger when moving off of the point, correct? It's failing to trigger. http://jsfiddle.net/c52thown/9/. This seems to still be an issue 2021

**Comment by mthb-cg** [comment]
With this fiddle using "stickyTracking: false" the mouseOut event should print "mouseOut" on the console when the mouse moves off of a point. It doesn't seem to be working: http://jsfiddle.net/ftduvxo6/9/

**Comment by raf18seb** [comment]
Hi @mthb-cg, the chart from your demo is working fine with `stickyTracking: false` and `stickyTracking: true`. Could you double check and provide the exact steps to reproduce?
Also, notice that you are using `stickyTracking` twice (the above takes precendence):
```js
plotOptions: {
    scatter: {
        stickyTracking: true
    },
    series: {
        stickyTracking: false,
        point: {
        ...
```

**Comment by mthb-cg** [comment]
Hi @raf18seb, my apologies. I meant to set both stickyTracking: false. In that case it seems to still have the sticyTracking: true behavior.

**Comment by mthb-cg** [comment]
My apologies, here's an updated chart. The issue only occurs when updating states using react in the events. The mouseOut event doesn't seem to have the "stickyTracking: false" property apply to it and it is triggered when it leaves the chart area. https://stackblitz.com/edit/react-vrshrm?file=index.js

**Comment by raf18seb** [comment]
@mthb-cg, your problem seems to be related to the React wrapper, could you create a ticket here? https://github.com/highcharts/highcharts-react/issues
Thanks!

**Comment by mthb-cg** [comment]
Done, thank you! https://github.com/highcharts/highcharts-react/issues/318
