### ISSUE TITLE
Innersize Pie in percentage.

### ISSUE THREAD

**Issue by zeoc** [highslide-software/highcharts.com#2077]
Hi,

specifying innersizer in percent works fine excepts when the pie is little.
innersize percent seems to be related to plot aera "height" only...

I need percentage innersize but related to pie size not to plot area or another way to b sure that innersize will be correctly interpreted to display a donut...

Thanks.

**Comment by alex321** [comment]
Has this issue actually been fixed as I am experiencing the same problem with v.4.1.5.? Resizing still makes the Donut chart extremely thin. It seems that changing the width is causing that.

**Comment by highslide-software** [comment]
It turns out the percentage `innerSize` isn't respected when the `size` isn't set, and is adjusted dynamically to fit data labels: http://jsfiddle.net/highcharts/77pwwurz/. Drag the resize handle to view the effect.
