### ISSUE TITLE
xAxis Crosshair Not Appearing in Compare Mode Percentage (Highstock)

### ISSUE THREAD

**Issue by hbokha** [highslide-software/highcharts.com#2150]
Line 8899 highstock.src.js.

if (series.modifyValue) { // #1205
  val = series.modifyValue(val);
}

Only the yAxis value is being modified in compare mode, not the xAxis.

Potential Change:

if (series.modifyValue && i) {
  val = series.modifyValue(val);
}

**Comment by pawelfus** [comment]
Could you setup demo? Also, why x-value should be modified too?
