### ISSUE TITLE
xAxis.update() breaks selectable ranges in rangeSelector (Highstock)

### ISSUE THREAD

**Issue by 3Ue** [highslide-software/highcharts.com#2151]
http://jsfiddle.net/9ffBx/4/

1. Click on one of the buttons below to update the first xAxis
2. Click on the "All" rangeSelector button

Result: You still see the data for 3 month instead of the whole range.

It seems to be connected with the rangeSelector.selected. If you select the "All" button initially, the problem does not occur.

http://jsfiddle.net/9ffBx/5/

**Comment by pawelfus** [comment]
Works properly in 2.1.8: http://jsfiddle.net/9ffBx/7/
