### ISSUE TITLE
Chart bounding box change every chart redraw

### ISSUE THREAD

**Issue by keepsimple** [highslide-software/highcharts.com#2184]
Playing with gauge chart happened this:

http://jsfiddle.net/LLExL/1765/

Browser: Chrome 29.0.1547.57 portable

**Comment by pawelfus** [comment]
It updated in 4.1.x versions too, but this is correct, see: http://jsfiddle.net/LLExL/5013/ - as you can see, the box contains data label, which can be wider because of decimals in the value.
