### ISSUE TITLE
[bug] Export menu does not respect the  theme!

### ISSUE THREAD

**Issue by hansgru** [highslide-software/highcharts.com#2191]
The export menu does not respect the selected theme.

This visible even on the official HighCharts demos: just change the theme to "gray" for any of the examples that expose the export button and you'll see that the background hasn't adapted the the gray theme.

regards.

**Comment by pawelfus** [comment]
Tested with: http://www.highcharts.com/demo/line-basic/dark-unica - works fine, probably old exporting server was responsible for that.
