### ISSUE TITLE
Problem when zooming in yAxis when max is set

### ISSUE THREAD

**Issue by sebastianbochan** [highslide-software/highcharts.com#2193]
When the max property is set for yAxis, the zooming is not working as expected.

Check this sample:

http://jsfiddle.net/YDFcT/

If I zoom from 0.79 to 0.7, so the top value is over the max value in the showed series points, the zoom will show the range from 0.9 to 0.7, not 0.79 to 0.7. I think it's related to max property set to 0.9.

**Comment by pawelfus** [comment]
Fixed since 2.x versions: http://jsfiddle.net/YDFcT/1/
