### ISSUE TITLE
highstock plotLine label with useHTML:true scroll bugged with navigator

### ISSUE THREAD

**Issue by sskachkov** [highslide-software/highcharts.com#2223]
http://jsfiddle.net/6nHMV/2/
try to set interval to 72 hours and scroll with navigator, plotLine scrolls fine, but plotLine  label is bugged
note: if you set useHTML to false, then problem disappears

**Comment by pawelfus** [comment]
Fixed since 2.0.0: http://jsfiddle.net/6nHMV/4/
