### ISSUE TITLE
pointPlacement - single column

### ISSUE THREAD

**Issue by sebastianbochan** [highslide-software/highcharts.com#2308]
It seems that pointPlacement doens't work for single column. (pointRange has no influence as well)

http://jsfiddle.net/dargno/3YMyq/

**Comment by kpfeifer** [comment]
This issue is still existing. Can you please provide a fix for it.

**Comment by highslide-software** [comment]
Actually it looks like it has never worked, but it is working with the latest development branch: http://jsfiddle.net/highcharts/3YMyq/1/

**Comment by kpfeifer** [comment]
Thanks for the quick reply. When will the next official highcharts version (4.1?) will be available?

**Comment by highslide-software** [comment]
You're welcome! It should only be a few weeks away now.​

**Comment by GeorgeBailey** [comment]
What is the estimated time of this fix arriving in the stable release? (4.1?)

**Comment by vcarel** [comment]
Is this issue fixed? I'm on highcharts@10.3.3 and I still have it.

**Comment by karolkolodziej** [comment]
@vcarel could you please share an example and explain where it doesn't work?
