### ISSUE TITLE
Exception in resizing an area chart after updating a series

### ISSUE THREAD

**Issue by rottem** [highslide-software/highcharts.com#2327]
In the following demo http://jsfiddle.net/p2RYM/, run it, press the buttons "hide legend" and then "resize".
an exception is thrown and the chart is not displayed.
This happens on chrome and on firefox.

**Comment by pawelfus** [comment]
Any specific reason to set `redraw` to false for updating first series? I think, there should be `true` to apply changes.

Anyway, works fine in 2.1.7: http://jsfiddle.net/p2RYM/1/
