### ISSUE TITLE
resize issue - highstock

### ISSUE THREAD

**Issue by sebastianbochan** [highslide-software/highcharts.com#2364]
In the highstock, when we resizing, navigator disappears.

http://jsfiddle.net/8nenL/7/
http://jsfiddle.net/8nenL/5/

HS 3.0.6,
Chrome: the newest branch

**Comment by pawelfus** [comment]
It's caused by setting `navigator.top = 330`, and later setting height = 200. Of course, navigator won't be visible in such case, simply remove that `top` option: http://jsfiddle.net/8nenL/8/
