### ISSUE TITLE
Scatter - zoom error

### ISSUE THREAD

**Issue by sebastianbochan** [highslide-software/highcharts.com#2371]
In case when data is not sorted via x, ascdening, zooming of points on edge, doesn't show points. 

Compare: 
http://jsfiddle.net/mxWmN/4/
http://jsfiddle.net/mxWmN/5/

Try to zoom right point on the edge.

**Comment by pawelfus** [comment]
Looks like fixed by #1655. See: http://jsfiddle.net/mxWmN/6/
