### ISSUE TITLE
x/yLow and x/yHigh in range charts

### ISSUE THREAD

**Issue by pawelfus** [highslide-software/highcharts.com#2409]
Example: http://jsfiddle.net/Y3vez/

yLow and yHigh doesn't work in above example (are just ignored). When using inverted chart, xLow and yLow are ignored. 

The reason is that only one of them (x or y) position is set, see [this](https://github.com/highslide-software/highcharts.com/blob/63fc29df9254d3f8854c23804f64742ec1738d57/js/parts-more/AreaRangeSeries.js#L171).

**Comment by ToddRopog** [comment]
Any chance this will get fixed? I just ran into it myself.
