### ISSUE TITLE
Scatter chart  - zooming into certain points gives blank chart.

### ISSUE THREAD

**Issue by fchoudhary** [highslide-software/highcharts.com#2427]
![d1322-e](https://f.cloud.github.com/assets/5852250/1465927/8757e19c-4569-11e3-8e3b-f718bf9384a8.png)
![d1322-f](https://f.cloud.github.com/assets/5852250/1465929/8e1644f6-4569-11e3-891f-c956fcd74d53.png)

Same issue is also found on hgihchart's scatter chart example,http://jsfiddle.net/gh/get/jquery/1.9.1/highslide-software/highcharts.com/tree/master/samples/highcharts/demo/scatter/

Zoom into Top blue point  - (Male 177.8cm, 116.4 kg)

**Comment by pawelfus** [comment]
Looks like fixed by #1655. See: http://jsfiddle.net/amedpejg/
