### ISSUE TITLE
Highstock: no disabled state within buttonTheme.states

### ISSUE THREAD

**Issue by simpixelated** [highslide-software/highcharts.com#2428]
There's no documentation for the allowed states within the [rangeSelector.buttonTheme.states](http://api.highcharts.com/highstock#rangeSelector.buttonTheme) object, but if you look at [the code](https://github.com/highslide-software/highcharts.com/blob/master/js/highstock.src.js#L19507-L19508), it only passes "hover" and "select" to renderer.button():
```js
buttons[i] = renderer.button(
    rangeOptions.text,
    buttonLeft,
    chart.plotTop - 25,
    function () {
        rangeSelector.clickButton(i, rangeOptions);
        rangeSelector.isActive = true;
    },
    buttonTheme,
    states && states.hover,
    states && states.select
)
.css({
    textAlign: 'center'
})
.add();
```
**By default, the disabledState style.color is set to "#CCC", which will clash with custom fill colors.**

renderer.button() already has parameters for disabledState, so this should just be a matter of adding it to the function call.
```js
button: function (text, x, y, callback, normalState, hoverState, pressedState, disabledState, shape) {
```

**Comment by ggrillone** [comment]
+1

**Comment by TorsteinHonsi** [comment]
It is actually implemented, see http://jsfiddle.net/highcharts/sq87o47t/.

I've added a commented-out block in the demo, and will add this information also to the API docs.
