### ISSUE TITLE
Point.update() does not redraw with negativeColor

### ISSUE THREAD

**Issue by joemoore989** [highslide-software/highcharts.com#2484]
http://jsfiddle.net/kCHpY/

Click on the "Update First Point" button several times until the value becomes negative. Should become red, but remains green.

If you hover the mouse over the point, it then renders in red correctly.

**Comment by pawelfus** [comment]
Duplicate #4267. Fixed on bugfix branch, see: http://jsfiddle.net/kCHpY/5/
