### ISSUE TITLE
Shared tooltip does not display on gauge

### ISSUE THREAD

**Issue by steakchaser** [highslide-software/highcharts.com#2575]
Here's an example of a gauge with a shared tooltip.  The tooltip does not display and actually the formatter is never being triggered.

Works fine with 3.0.1, but is not working with 3.0.8.

http://jsfiddle.net/tjmoretto/y9p2Y/

**Comment by sebastianbochan** [comment]
Tooltip in solid gauge doens't work in 4.1.5, but in 4.1.4 works well.

**Comment by Ornithologist** [comment]
bump

**Comment by highslide-software** [comment]
It works with the latest master: http://jsfiddle.net/highcharts/y9p2Y/7/
