### ISSUE TITLE
some parts stay visible when container visibility:hidden

### ISSUE THREAD

**Issue by iweindesmedt** [highslide-software/highcharts.com#2597]
not sure if this is related to svg issues
http://jsfiddle.net/LLExL/2296/

expected behavior would be for the container and all its descendants to be completely hidden

**Comment by cbaket** [comment]
still no solution?

**Comment by NaWer** [comment]
Persist with dataLabels enabled : 
http://jsfiddle.net/RUbSa/4/
Can we reopen this bug ?
