### ISSUE TITLE
Tooltip doesn't disappear

### ISSUE THREAD

**Issue by sebastianbochan** [highslide-software/highcharts.com#2688]
1. Run example http://jsfiddle.net/buBY5/2/
2. Hover on left top bubble,
3. Move cursor to bottom, tooltip disappears, its fine
4. Back to step 2
5. Move cursor to right / right bottom, tooltip doesn't disappear

Browser Chrome on mobile devices / desktop versions

**Comment by pawelfus** [comment]
Works fine in 4.1.7+
