### ISSUE TITLE
Printing/Downloading Zoom-Buttons wrong

### ISSUE THREAD

**Issue by SaschaM1234** [highslide-software/highcharts.com#2752]
JSFiddle:
http://jsfiddle.net/gh/get/jquery/1.9.1/highslide-software/highcharts.com/tree/master/samples/stock/demo/basic-line/ 

Issue:
I want to download the chart in zoom mode. In the downloaded png/jpg/pdf, the zoom-button i selected is not displayed as active. Sometimes it happens directly at the first download and sometimes after 2-3 times downloading the chart (with different zooms).

Reproduce:
1.Click on zoom-button '6m'
2.Download the chart as(png/jpg/pdf)
3.Zoom button in the downloaded png/jpg/pdf is not selected

**Comment by sebastianbochan** [comment]
Works since 4.1.8.
