### ISSUE TITLE
Chart.destroy() leads to error w/ custom exporting buttons like 1822

### ISSUE THREAD

**Issue by gmathijssen** [highslide-software/highcharts.com#2775]
Hi,

I have a similar case as https://github.com/highslide-software/highcharts.com/issues/1822, but in my case the exportDivElements are tried to be deleted twice, because the destroyExport event is fired twice
```
 for (i = 0; i < chart.exportDivElements.length; i++) {
	elem = chart.exportDivElements[i];

	// Remove the event handler
	removeEvent(elem, 'mouseleave');

	// Remove inline events
	chart.exportDivElements[i] = elem.onmouseout = elem.onmouseover = elem.ontouchstart = elem.onclick = null;

	// Destroy the div by moving to garbage bin
	discardElement(elem);
}
```

Can elem be tested for null here as well?

Thanks,
Guus

**Comment by larrydahooster** [comment]
I had a problem with "a.onContainerClick is not a function" too. I was able to reproduce the bug. It somehow has to do with the event-command-chain. By clicking on the export-button, which is located within the 'container', first the click event on the button gets triggered. But then there is still the onContainerClick event in the pipeline. If you destroy the chart in your button-click-method, the onContainerClick function is called afterwards on a null object, cause the chart does no longer exist. I solved this problem, by decoupling the chart.destroy() action from synchronous program-flow by placing it in setTimeout(function(){...}, 20 ); and the error is gone.

**Comment by sebastianbochan** [comment]
+1

**Comment by aliyazdani** [comment]
I'm experiencing this error - we are generating custom button when our React component mounts/updates.  We are using v5.0.10.

**Comment by pawelfus** [comment]
Hi @aliyazdani 

Could you recreate issue in jsFiddle? The example posted by me is fine. If this is a Highcharts bug, then React doesn't matter, standalone Highcharts example should be enough.

**Comment by aliyazdani** [comment]
@pawelfus - i used @larrydahooster's setTimeout to disrupt the sync flow and the error has disappeared now.  My react component with the chart was re-rendering and so the original chart was gone when the onContainerClick event was triggered.
