### ISSUE TITLE
Crosshair with multiple series

### ISSUE THREAD

**Issue by pawelfus** [highslide-software/highcharts.com#2816]
See example: http://jsfiddle.net/2H9m3/5/

Try to hover **from bottom** of the chart on 8.Jan/10.Jan - crosshair find the closest point as triangle one, while should be point for 8. Jan. See image (cursor was on 7th on Jan).

![screen shot 2014-03-14 at 3 04 56 pm](https://f.cloud.github.com/assets/1453926/2421425/a9c2b562-ab81-11e3-92a2-5337d2c11c18.png)

**Comment by stephanevanraes** [comment]
Original issue fixed in latest master branch.
