### ISSUE TITLE
Exception during Tooltip.getAnchor

### ISSUE THREAD

**Issue by kzoon** [highslide-software/highcharts.com#2839]
See http://jsfiddle.net/kzoon/9P82V/6/

Move your mouse around a lot and eventually you get an Exception

The Exception originates in the code change of #2830.

Uncaught TypeError: Cannot read property 'yAxis' of undefined highcharts.src.js:8748
(anonymous function) highcharts.src.js:8748
each.Array.forEach.i highcharts.src.js:1004
Tooltip.getAnchor highcharts.src.js:8747
Pointer.runPointActions highcharts.src.js:9205
Pointer.onContainerMouseMove highcharts.src.js:9537
container.onmousemove highcharts.src.js:9639

**Comment by pawelfus** [comment]
Can not reproduce - is it still broken in 4.1.7 version?

**Comment by kzoon** [comment]
I can'nt reproduce it anymore. So it seems the issue got fixed...

**Comment by pawelfus** [comment]
Yes, probably when new logic for tooltip was implemented. Reopen, if you spot the issue again.
