### ISSUE TITLE
IE11 - marker symbol issue 

### ISSUE THREAD

**Issue by sebastianbochan** [highslide-software/highcharts.com#2854]
In case when we use svg fil as marker symbol, then is not displayed in the IE11.

http://jsfiddle.net/HyLgU/

IE11.0.9600.16428

**Comment by sebastianbochan** [comment]
+1 

Highmaps: http://jsfiddle.net/1kfakdc1/1/

**Comment by highslide-software** [comment]
I tested the OP's demo in IE10 and Edge (don't have IE11 at the moment). The SVG wouldn't load from the clipart site, but it works with our logo: http://jsfiddle.net/highcharts/HyLgU/1/.

The second demo, with Highmaps, also loads the enormous black X in the background, using both IE10 and Edge...

Can you confirm this @sebastianbochan , that IE10 and Edge works, but IE11 doesn't?

**Comment by highslide-software** [comment]
PS: I didn't realize I can run IE11 _and_ Edge on my new Win10 machine. And yes, I can reproduce the issue on IE11.

**Comment by highslide-software** [comment]
Minimal demo: http://jsfiddle.net/highcharts/m5bz10vn/

**Comment by highslide-software** [comment]
#### Workaround
Set the width and height of the symbol explicitly in the options: http://jsfiddle.net/highcharts/HyLgU/1/. The core problem is that IE11 isn't able to read the image's natural width and height.
