### ISSUE TITLE
Set the lowest min and highest max value for an axis

### ISSUE THREAD

**Issue by ejain** [highslide-software/highcharts.com#2858]
Should be able to tell Highcharts that it is free to choose appropriate min and max values for the axes, as long as it stays within a specific range (e.g. not below 0 and not above 100). Looks odd to have e.g. negative tick mark values when showing values that can't ever be negative.

**Comment by pawelfus** [comment]
Implemented by:

- [Axis.floor](http://api.highcharts.com/highcharts#yAxis.floor)
- [Axis.ceiling](http://api.highcharts.com/highcharts#yAxis.ceiling)
