### ISSUE TITLE
Multi axes, chart inverted set to true, yAxis with only one value => label axis value displays in stairs

### ISSUE THREAD

**Issue by SarahCap** [highslide-software/highcharts.com#2862]
Hi,

With multi axes and chart inverted set to true, when I have an yAxis with one value we obtained this chart : 

![image](https://cloud.githubusercontent.com/assets/7113666/2565395/e98ca754-b8b3-11e3-8bb6-07d7e330924e.png)

If I remove inverted set to true or if i put another value in the yAxis the bug disappear.

Additionnaly, if i put alignTicks set to false the bug disappear but the display is not what I want.

http://jsfiddle.net/A6PZs/

**Comment by sebastianbochan** [comment]
Works since 4.1.0
