### ISSUE TITLE
xAxis - logarithm - line is cut

### ISSUE THREAD

**Issue by sebastianbochan** [highslide-software/highcharts.com#2869]
The probelm is when we have many points, then line is cut like here
http://jsfiddle.net/RLJS7/1/

Turbothreshold doesnt solve problem

Problem doesnt appear in the 3.0.2
http://jsfiddle.net/RLJS7/2/

**Comment by pawelfus** [comment]
Works fine since 4.1.0: http://jsfiddle.net/RLJS7/6/
