### ISSUE TITLE
Cannot setData on hidden series after reset

### ISSUE THREAD

**Issue by rinatio** [highslide-software/highcharts.com#2885]
Given I have a series with `data: [1,2,3]`, then I do following steps:

1. Hide series with `series.setVisible(false)`
2. Reset series with `series.setDat([])`
3. Set series data with `series.setData([3,2,1])`

I get the following error:

```
Uncaught TypeError: Property 'update' of object #<Object> is not a function
```

![screen shot 2014-04-07 at 6 45 36 pm](https://cloud.githubusercontent.com/assets/426879/2632326/50260820-be63-11e3-9148-7df508632068.png)

Here's a [jsfiddle](http://jsfiddle.net/rinatio/NMwL5/) (subsequently click "Toggle visible", "Reset" and "Set new data")

**Comment by sebastianbochan** [comment]
Works since 4.1.0
