### ISSUE TITLE
navigator handles below its xaxis labels

### ISSUE THREAD

**Issue by iweindesmedt** [highslide-software/highcharts.com#2908]
http://jsfiddle.net/LLExL/2589/
drag the handles, the labels cover the handles

**Comment by sebastianbochan** [comment]
Workaround - set zIndex in xaxis labels:

navigator: {
        height: 20,
        xAxis: {
            labels: {
                zIndex: 1
            }
        }
    },

**Comment by iweindesmedt** [comment]
okay workaround, thanks.

(fyi, the jsfiddle contains a .local domain)
