### ISSUE TITLE
drilldown: category label style corrupted when resize

### ISSUE THREAD

**Issue by JoeKuan** [highslide-software/highcharts.com#2916]
1. Clicks the on 'basic drilldown' jsfiddle example link from the drilldown API documentation.
http://jsfiddle.net/gh/get/jquery/1.7.2/highslide-software/highcharts.com/tree/master/samples/highcharts/drilldown/basic/

2. Animals and Fruits are underline. Clicks on either of them to drilldown to another chart

3. Resizes the chart and you should see the first two category labels change to bold and underline style

**Comment by sebastianbochan** [comment]
Works since 4.1.0.
