### ISSUE TITLE
dataGrouping.smoothed adds extra point

### ISSUE THREAD

**Issue by pawelfus** [highslide-software/highcharts.com#2920]
Example: http://jsfiddle.net/dbGH7/5/

Click button to force smoothed dataGrouping - on a chart we will see straight lines to the left and right side of the chart.

**Comment by KacperMadej** [comment]
Might be a connected issue - line forced to bend outside the visible area?
Example: http://jsfiddle.net/b7ggbzj7/

**Comment by sebastianbochan** [comment]
+1
