### ISSUE TITLE
Drilldown called twice on dataLabel click

### ISSUE THREAD

**Issue by pawelfus** [highslide-software/highcharts.com#2922]
Example: http://jsfiddle.net/2yx7L/3/

Click on dataLabel (5/2/4) and in console you will see that drilldown event is called twice. 

When click on xAxis.label or column, it's called only once (correct).

**Comment by jojoinside** [comment]
Hello,

This issue has been opened some time ago but I still get the same bug theses days.

* Drilldown sync
  * Column http://jsfiddle.net/y8uaeodm/
    * Only 1 event when click on an area, a label or avalue
  * Pie http://jsfiddle.net/zg5chdg5/
    * Only 1 event when click on an area or a label
* Drilldown async
  * Column http://jsfiddle.net/q8949fbu/
    * Only 1 event when click on an area or a label
    * **2 events when click on a value**
  * Pie http://jsfiddle.net/a0ycmaxn/
    * Only 1 event when click on an area
    * **2 events when click on a label**

The problem with the 2 events, is that the 2 event throw an error **Cannot read property 'xAxis' of null** in file at line : 
https://github.com/highslide-software/highcharts.com/blob/5d125aa6c7fc16d08ddca489c0349ae5eb527403/js/modules/drilldown.src.js#L123

**Comment by pzgz** [comment]
This doesn't actually fix the issue if there are more than one series in charts.

**Comment by sabau** [comment]
I'm still experimentig a problem related to this one, in Highmaps with 2 level of drilldown. I'll try to replicate the issue into a jsfiddle
