### ISSUE TITLE
Highmaps legend blurred when using (chrome) browser zoom out zoom in

### ISSUE THREAD

**Issue by ronanquillevere** [highslide-software/highcharts.com#2925]
In chrome 34

(could not reproduce in FF 24)

If you zoom out, then zoom in (using the browser zoom functionnality). The legend gets blurred (seems like displayed twice in fact)

http://jsfiddle.net/d2JA4/

![blur](https://cloud.githubusercontent.com/assets/656195/2740734/bb308c02-c6d9-11e3-9927-c370496e5411.png)

**Comment by sebastianbochan** [comment]
Working since 4.1.8.
