### ISSUE TITLE
Highstock + Highmaps

### ISSUE THREAD

**Issue by gevgeny** [highslide-software/highcharts.com#2938]
When adding Highstock and Highmaps to one page get error 16 "Highcharts already defined in the page" (See console of [the fiddle](http://jsfiddle.net/7vy49/)).
When trying to modify [example with Maps module](http://jsfiddle.net/highcharts/WzVkV/light/) to replace highcharts with highstock get wrong data displayng (black color of the map). See [the fiddle](http://jsfiddle.net/WzVkV/19/)

**Comment by pawelfus** [comment]
Works fine with 4.1.8/2.1.8/1.1.8 version: http://jsfiddle.net/07u676k6/6/
