### ISSUE TITLE
Column series tooltip position when using yAxis.top

### ISSUE THREAD

**Issue by aidaskasperavicius** [highslide-software/highcharts.com#2955]
Tooltip for column data series is misplaced when yAxis top is specified.

Looks like point.tooltipPos calculation ignores yAxis top value.
(line 15398 in highcharts.src.js v4.0.1)

Most likely the same applies when using xAxis.left.

Demo:
http://jsfiddle.net/5A5UG/3/

**Comment by pawelfus** [comment]
Fixed since 4.1.0: http://jsfiddle.net/5A5UG/5/
