### ISSUE TITLE
Axis.setTitle causes background to disappear on a solid gauge

### ISSUE THREAD

**Issue by myrosia** [highslide-software/highcharts.com#2965]
http://jsfiddle.net/d9gs3/1

This is exactly the same as the standard solid gauge demo, except one line is added in the setInterval function, 120:

 chart.yAxis[0].setTitle({text: "Dynamic speed"});

Both the speed gauge and the rpm gauge should have a gray background, and it is initially rendered for both. But after the setTitle is executed for speed, the gray background on it disappears.

**Comment by bthivierge** [comment]
Has there been a fix for this yet?

**Comment by highslide-software** [comment]
Duplicate of #3176 (fixed). 

Demo with fix: http://jsfiddle.net/highcharts/7XM6D/3/

**Comment by McKennaHH** [comment]
I updated my fiddle and the background stays, thats greate. But, the max label is still moving if the max value changes.
http://jsfiddle.net/rS74J/1/

**Comment by bthivierge** [comment]
I have the same problem with the max value.

**Comment by highslide-software** [comment]
For the max value, see #3747 (not a bug).

**Comment by McKennaHH** [comment]
Ok thx, this looks much better and is working now.
