### ISSUE TITLE
BR in exported file

### ISSUE THREAD

**Issue by sebastianbochan** [highslide-software/highcharts.com#2988]
In the 3.0 version <br> tag in the title, was exported, but in the current version (4.0.1) not.

3.0.10 - http://jsfiddle.net/jvq8K/3/
4.0 - http://jsfiddle.net/jvq8K/4/

**Comment by sebastianbochan** [comment]
The allowHTML does not cover <br> in subtitles.

Example: http://jsfiddle.net/jvq8K/5/

**Comment by highslide-software** [comment]
Apparently the `exporting.scale` setting doesn't work for HTML content, so in order to get a matching scale we need to set it to 1: http://jsfiddle.net/jvq8K/6/

**Comment by highslide-software** [comment]
@gvaartjes This is a regression since running PhantomJS 2.0 on the export server. With the old server, the HTML is scaled correctly: http://jsfiddle.net/highcharts/jvq8K/7/.

**Comment by gvaartjes** [comment]
Maybe we have to scale the SVG instead of using the zoompage. Zoompage is not scaling the content of the foreignobject

**Comment by highslide-software** [comment]
Since the OP here points to a version long before the `allowHTML` feature, I'm closing this issue and redirecting to #4648.
