### ISSUE TITLE
series color in tooltip with gradient

### ISSUE THREAD

**Issue by pawelfus** [highslide-software/highcharts.com#2995]
Example: http://jsfiddle.net/4rTBY/418/

Markers inside tooltip are black. In `pointFormat`, when we use `{series.color}` fill color will be empty.

**Comment by marizmelo** [comment]
Any news on this? I want to use a custom HTML tooltip and get at least one of the colors form the gradient and display on it. Thanks.

**Comment by pawelfus** [comment]
For now, workaround is to use `tooltip.formatter`, for example: http://jsfiddle.net/4rTBY/888/

Code: 

            formatter: function () {
                var str = [];

                $.each(this.points, function (i, p) {
                    str.push(
                        '<span style="color:',
                  		 p.series.color.stops[0][1],
                        '">',
                   		 p.series.name,
                        '</span>: <b>',
                   		 p.y,
                        '</b><br>'
                    );
                });
                return str.join('');
            },
            shared: true
        }

**Comment by Philzen** [comment]
Is there any update on this issue? I was just in the middle of reworking a site to use gradients (which look sooo much nicer), but reworking all tooltips (where some of them still call the defaultFormatter) seems really tedious.

Also, i have charts that mix gradients and plain colors, so the workaround becomes even more complex.

IMHO it would be a relatively small change to the Highcharts formatter code to check if `series.color` is an object, and when it is, render `series.color.stops[0][1]` instead.

**Comment by Philzen** [comment]
> For now, workaround is to use `tooltip.formatter`, for example: http://jsfiddle.net/4rTBY/888/

Also, your jsfiddle example uses `xpointformat` instead of a formatter function. `xpointformat` comes new to me, I cannot seem to find it in the API docs not via web search – maybe you could elaborate on its meaning somewhere in the (API) docs=

**Comment by KacperMadej** [comment]
The issue is closed as resolved and was closed by a commit that implemented the functionality - here's a demo showing more clearly that it works using a gradient with a stronger contrast: http://jsfiddle.net/BlackLabel/g6sotku1/
