### ISSUE TITLE
HighStock: reflow not working properly

### ISSUE THREAD

**Issue by slozier** [highslide-software/highcharts.com#2998]
When making a chart wider and calling reflow, the series ends up being cropped.

Example:
http://jsfiddle.net/vHfN3/1/

**Comment by kirava** [comment]
+1

**Comment by raff77** [comment]
+1

**Comment by highslide-software** [comment]
#### Workaround
If you disable animation on the series it works: http://jsfiddle.net/highcharts/vHfN3/2/
