### ISSUE TITLE
Tooltip does not always show (with useHTML)

### ISSUE THREAD

**Issue by awallat** [highslide-software/highcharts.com#3059]
I created a StackedColumn-Chart with big tooltips and found a bug when the "useHTML" option is used. What happens is that a disappearing tooltip is still there and occupies the area where it was shown. This results in that we are not able to trigger any tooltip within that space. In the case that the tooltip covers the whole chart, then it's not possible trigger any tooltip anymore since the whole chart is blocked by the invisible tooltip container.

Check out this fiddle and produce the following steps:
http://jsfiddle.net/SgkZ7/
1. Hover over the bottom green chart of "Apples" so that the tooltip appears
2. Move out from that column and wait for the tooltip to disappear
3. Hover over the gray column of "Apples" where the former tooltip appeared.
4. No tooltip is shown!
5. If you move up or down (outside of the former tooltip container) then a tooltip will eventually be shown.

**Comment by pawelfus** [comment]
Works fine with 4.1.7: http://jsfiddle.net/SgkZ7/1/
