### ISSUE TITLE
Tooltip not showing (dataGrouping)

### ISSUE THREAD

**Issue by sp4m** [highslide-software/highcharts.com#3083]
This is more of a usability issue than a bug.

Line
The grouped points are clearly visible because of the markers and it's apparent that the first point isn't within range: http://jsfiddle.net/ySMe3/

Column
The user has no way of knowing why the first column isn't displaying a tooltip: http://jsfiddle.net/ySMe3/2/

I'm aware of the smoothed option but I don't think it provides a very good solution to the problem.

**Comment by omnilord** [comment]
Happens with Barcharts, as well: http://jsfiddle.net/94a1ngnh/2/
And, depending on the width of the screen or browser, you may or may not see the tooltip at all.

**Comment by highslide-software** [comment]
Closing the original issue, doesn't seem to happen anymore.

**Comment by highslide-software** [comment]
New issue for the bar chart created at #4149
