### ISSUE TITLE
Rotated labels - bar chart

### ISSUE THREAD

**Issue by sebastianbochan** [highslide-software/highcharts.com#3140]
It looks like a rotation is buggy in HC 4.0.x and 3.0.10

HC: 3.0.10 - http://jsfiddle.net/SKRBW/1/
HC: 4.0.1 - http://jsfiddle.net/SKRBW/

**Comment by pawelfus** [comment]
Looks properly with 4.1.8: http://jsfiddle.net/SKRBW/7/

**Comment by KacperMadej** [comment]
Looks broken in 4.1.9: http://jsfiddle.net/SKRBW/9/

**Comment by highslide-software** [comment]
Breaks since b2d4aed
