### ISSUE TITLE
shared tooltip leaves hovered points

### ISSUE THREAD

**Issue by jardakotesovec** [highslide-software/highcharts.com#3185]
Using shared tooltip and returning false in tooltipFormatter cause the problem that points are still selected even if user leaves the chart area. It works fine if tooltip is not shared or tooltipFormatter does not return false.   

http://jsfiddle.net/ZdZ98/1/

I return false for points that I don't want to show tooltip for (as suggested in docs).

**Comment by pawelfus** [comment]
Works fine since 4.1.6+ : http://jsfiddle.net/ZdZ98/2/
