### ISSUE TITLE
[Highstock] yAxis crosshair on 2nd series is generating errors

### ISSUE THREAD

**Issue by lemonbutter** [highslide-software/highcharts.com#3189]
When I add a second series whit its own yAxis below the main chart, the yAxis crosshair is sometimes shown, sometimes not. When it disapears the following error is in the console.

highstock.src.js:2729
Error: Invalid value for <path> attribute d="undefined"

Here the fiddle
v2.0.1: http://jsfiddle.net/Gn3qG/
masterbranche: http://jsfiddle.net/Gn3qG/1/

**Comment by KacperMadej** [comment]
Issue still present - 2.0.4

**Comment by stephanevanraes** [comment]
Fixed on current master branch.
