### ISSUE TITLE
Update colorAxis

### ISSUE THREAD

**Issue by pawelfus** [highslide-software/highcharts.com#3207]
Example: http://jsfiddle.net/TMQaL/

Axis is updated, colors on map too, unfortunatetly legend isn't changed.

**Comment by paulo-raca** [comment]
I've opened a separate issue for the exporting bug: #3874

**Comment by deepaksri81** [comment]
@mehtayash I would like to have the same type of legends, please let me know how to modify it. as In my case it's showing like this, but I would like to have with % signs and also first one should be =0%.
 
![image](https://user-images.githubusercontent.com/16019597/39118997-141b0b4a-46eb-11e8-8a11-d124abf0773d.png)

**Comment by pawelfus** [comment]
Hi @deepaksri81 

Please, contact our support: https://www.highcharts.com/support

To answer your question: use [`colorAxis.dataClasses.name`](https://api.highcharts.com/highmaps/colorAxis.dataClasses.name), demo: https://jsfiddle.net/BlackLabel/7z1L4dj7/
