### ISSUE TITLE
Hiding tooltip affects highlighted points

### ISSUE THREAD

**Issue by iansullivan88** [highslide-software/highcharts.com#3215]
[Example Fiddle](http://jsfiddle.net/KtS4p/)

1. Highlight various points on the above chart - points on both series are highlighted
2. Hovering over June should hide the tooltip - only one point has a highlighted marker
3. The next date you hover over will only have a single point highlighted even though it is a shared tooltip

![image](https://cloud.githubusercontent.com/assets/7151163/3446158/646c5906-013e-11e4-8fa7-e46c6dd0f3d0.png)

**Comment by pawelfus** [comment]
Works fine in 4.1.7: http://jsfiddle.net/KtS4p/1/
