### ISSUE TITLE
Resize  - series not end on ticks

### ISSUE THREAD

**Issue by sebastianbochan** [highslide-software/highcharts.com#3265]
Steps to reproduce
1. run http://jsfiddle.net/ddygC/3/
2. serie is on min and max, correct
3. resize vertically, quite slowly
4. in about half distance, serie gets gap (like maxPadding) and on end on tick

![zrzut ekranu 2014-07-17 o 15 16 24](https://cloud.githubusercontent.com/assets/2115686/3613148/95253838-0db4-11e4-8994-34b7b42a9ff0.png)

**Comment by pawelfus** [comment]
`endOnTick` forces chart to end on tick, which is 22. That creates 'extra' padding on top.
