### ISSUE TITLE
Long rotated X-Axis labels get cut

### ISSUE THREAD

**Issue by ohadPA** [highslide-software/highcharts.com#3312]
Long X-Axis titles get cut on the left side when rotated.
Ideal solution would be wrapping the title into 2 lines, none suggested.

Applies to all browsers, can be reproduced on every chart type with an x-axis.

JsFiddle:
http://jsfiddle.net/hdH55/

Image:
![bar x-axis titles](https://cloud.githubusercontent.com/assets/8350646/3796298/c1efeb90-1bc6-11e4-8bc9-c97ca8d4d6fd.PNG)

**Comment by ohadPA** [comment]
Thanks for the ultimate solution released this week with version 4.1!
Bug can be closed for all that I concern.
Thanks again!

**Comment by DongShi** [comment]
what is the ultimate solution mentioned above? @ohadPA @TorsteinHonsi 
It seems in the latest release you can still meet the problem, if you choose to hide Y axis, like the following:


![image](https://user-images.githubusercontent.com/5009987/93590565-53604f80-f9e1-11ea-9a25-c1170d03ca6b.png)
