### ISSUE TITLE
Gauge chart alters style of polar charts in the same page 

### ISSUE THREAD

**Issue by jimr** [highslide-software/highcharts.com#3318]
JSFiddle here: http://jsfiddle.net/whubr/7k5wojhb/

The polar line chart should have a solid white background and no border, but instead has a border and the same gradient background as the gauge. If you remove the gauge (http://jsfiddle.net/whubr/7k5wojhb/1/) or initialize it after the polar line chart (http://jsfiddle.net/whubr/7k5wojhb/2/), the appearance of the line chart is as expected.

The ordering of the container divs doesn't seem to make any difference.

**Comment by philippe-jung** [comment]
Bug still exists in current version (4.1.6).
