### ISSUE TITLE
bar - negativeColor not applied on hover

### ISSUE THREAD

**Issue by sebastianbochan** [highslide-software/highcharts.com#3320]
In case when we define the color for negativeColor, on hover event, color back to "default"

Example: http://jsfiddle.net/466nu/

**Comment by KacperMadej** [comment]
This is also visible for line, area, scatter type series.
Area example: http://jsfiddle.net/3Lbdzsjc/

**Comment by pawelfus** [comment]
Duplicate of #3636, so it should be fixed by [this commit](https://github.com/highslide-software/highcharts.com/commit/4e9821d610b2467f86cc15ed8029a7b9ee3dad35).
