### ISSUE TITLE
Issue with timezones/utc and pointIntervals

### ISSUE THREAD

**Issue by philfreo** [highslide-software/highcharts.com#3329]
Goal: have points represent periods like `week` or `month` (longer than `day`) and have the appropriate tooltips like "Week of" or "January 2013" rather than just the date. I also want each point to represent the start of a week/month in *local time*

Problem: when trying to have periods in local time, combined with useUTC: false, the tooltips don't work.

Please carefully read through the comments in the HTML & JS here and I think you'll see the problem:
http://jsfiddle.net/philfreo/w8c3L2pd/1/

This line causes the problem: https://github.com/highslide-software/highcharts.com/blob/4af0bb07e7c84d05f8e2ff542e6d89c436eecf84/js/highcharts.src.js#L8921

**Comment by philfreo** [comment]
(Sorry for the delay - just digging back into this again)

If I combine the last 2 jsfiddles to test all the various intervals in one place...

http://jsfiddle.net/krourcnt/

a) it still doesn't work properly (e.g. the April tooltip in the By Month graph improperly shows a Day/Time)
b) it seems like I shouldn't need so much custom code (shouldn't you allow pointInterval month/year in core Highcarts?)

**Comment by highslide-software** [comment]
The `pointIntervalUnit` option is now added to the 4.1 candidate. See http://jsfiddle.net/highcharts/krourcnt/1/.

a) This works with the latest branch.
b) The tooltip header formatter for quarters and weeks must still be added programmatically.

**Comment by philfreo** [comment]
Thanks. And what is the explanation for needing the custom tooltip formatter for weeks/quarter? Couldn't you argue that this should be the default and that it should use `dateTimeLabelFormats.week` and `dateTimeLabelFormats.quarter` ?

**Comment by philfreo** [comment]
Any word on this?

**Comment by highslide-software** [comment]
Yes possibly... Except if you are acutally assigning data for January, April etc...

**Comment by philfreo** [comment]
> Yes possibly... Except if you are acutally assigning data for January, April etc...

That sounds like a much less common scenario than people using `pointIntervalUnit === 'month'` and `pointInterval  === 3` for quarters. The default tooltip formatting should probably cover the most common use case, no? The same applies to a `pointIntervalUnit` of `week`.

Typically if people just want monthly data they wouldn't say `pointInterval === 3`, right?

**Comment by eskimoblood** [comment]
What is the state of the day light saving time offset issue. When I test it with code from one of the latest fiddle in threat i seems to be fixed, the latest version from the CDN still add the offset. Example: http://jsfiddle.net/2s0grfeb/

**Comment by TorsteinHonsi** [comment]
This is officially released. In your fiddle, I can't see a difference between using the CDN script or the commented-out one from GitHub...

**Comment by eskimoblood** [comment]
This is what I get for the CDN version: 
![google chrome - github com - - screen shot 31 mar 2016 14 41 30](https://cloud.githubusercontent.com/assets/72060/14175940/c32aa60c-f74e-11e5-8d31-79d2aac8c342.png)


note the `01:00` after the date, this does not happen in the other version.

**Comment by TorsteinHonsi** [comment]
Ok, it actually shows the correct value because you're starting in winter time and add 24 hours repeatedly. What you probably want to do is to set the data points on local midnight instead of using pointInterval.

**Comment by eskimoblood** [comment]
Ok, so there is no way to prevent this when using `pointInterval`? Any plans to add `pointInterval: 'day'`, like `add(1, 'day')` in momentJS, cause this would be the expected behaviour.

**Comment by TorsteinHonsi** [comment]
No, currently `pointIntervalUnit` only supports `month` and `year`. 

> Any plans to add pointInterval: 'day', like add(1, 'day') in momentJS, cause this would be the expected behaviour.

That would be _pointIntervalUnit_: 'day'. And I agree, it would be useful. I'm looking at it right away.

**Comment by TorsteinHonsi** [comment]
Done. See http://jsfiddle.net/highcharts/2s0grfeb/1/, and compare to the other series that has a hard 24h interval. Note that this demo is tested on a browser in Central European Time, the CST crossover being March 28.

A related problem now appears with the tooltip showing `00:00` for every date. See #5128.

**Comment by eskimoblood** [comment]
Thanks, thats was fast. When is this feature planed to be released?

**Comment by TorsteinHonsi** [comment]
You're welcome! It will be released within a few weeks.
