### ISSUE TITLE
Misaligned bars

### ISSUE THREAD

**Issue by pawelfus** [highslide-software/highcharts.com#3355]
I think it was once reported, but couldn't find it. Example: http://jsfiddle.net/aL2qmd90/

As you can see, bars are translated to the left by ~1px.

**Comment by kzoon** [comment]
Still no news? It really is a quite annoying bug

**Comment by highslide-software** [comment]
Normalized demo: http://jsfiddle.net/highcharts/aL2qmd90/2/

I tried modifying the crispifying like the following, but it made many other charts fail. For example http://jsfiddle.net/highcharts/aL2qmd90/3/. 

In ColumnSeries.js, find this:
```js
		if (chart.renderer.isVML && chart.inverted) {
			yCrisp += 1;
		}
```
Replace it with:
```js
		if (chart.inverted) {
			yCrisp += chart.renderer.isVML ? 1 : -1;
		}
```'

**Comment by kzoon** [comment]
Thanks for solving this issue!
