### ISSUE TITLE
RangeSelector buttons enable issue

### ISSUE THREAD

**Issue by kgdinesh** [highslide-software/highcharts.com#3375]
RangeSelector behaves inconsistently if the data for chart exactly matches one of the specified range values.

I've reproduced this here, http://jsbin.com/ruvif/1/edit (Contains data for exactly "2h" period)

Do the following:
1. Select "2h" and notice that 'All" get disabled.
2. Switch back to "1h", "All" will now be re-enabled.
3. Now select "All", notice that "2h" gets enabled as well and will continue to be enabled even if you switch to "1h" (until, you click "2h" again)

Kindly fix this issue / provide a workaround.

**Comment by arjunasuresh3** [comment]
+1

**Comment by shreyasrk** [comment]
+1

**Comment by shreyasrk** [comment]
@kgdinesh Can you post that temporary solution that you mentioned?

**Comment by highslide-software** [comment]
FYI, here's the OP demo with the fix applied: http://jsbin.com/xobarabuwi/edit?html,js,output

**Comment by mitar** [comment]
This fix breaks past behavior and now buttons never select event if you have a range which equals them selected. See #4761 for more information.
