### ISSUE TITLE
minPadding and maxPadding in colorAxis

### ISSUE THREAD

**Issue by pawelfus** [highslide-software/highcharts.com#3379]
Example: http://jsfiddle.net/09kfooz9/
Expected result should be just like here: http://jsfiddle.net/GA2Yf/6/
Meanwhile we have extra padding on left and right side of the colorAxis. Which also points (arrow) wrong colors in legend.

**Comment by ciarancourtney** [comment]
Hi, Is there any visibility on a fix for this?

**Comment by martinf55** [comment]
I had the same problem. The reason for it

In the heatmap.src.js, the ColorAxis definition at lines 91-94 is:

```javascript
		// Override original axis properties
		this.isXAxis = true;
		this.horiz = horiz;
		this.zoomEnabled = false;
```

Setting the colorAxis.isXAxis = true means that Axis.setAxisTranslation() at highcharts.src.js:7236 will go on to use the seriesPointRange to apply a minPointOffset and move the ticks in from the ends of the gradient.

The workaround for my purpose was to comment out line 92 in heatmap.src.js:

```javascript
		// this.isXAxis = true;
```

The ticks and the arrow then properly extend to the end of the gradient, so the values match with their assigned colors.

Can someone verify the purpose of this line? It seems like a bug to say the colorAxis is an xAxis?
