### ISSUE TITLE
Plot band that stretches from minimum y value does not display

### ISSUE THREAD

**Issue by thomasttvo** [highslide-software/highcharts.com#3388]
This happens when the height of the axis that contains the band is not an integer (dynamically calculated)

Issue originates from number rounding in these lines in getPlotLinePath():
x1 = x2 = mathRound(translatedValue + transB);
y1 = y2 = mathRound(cHeight - translatedValue - transB);

**Comment by pawelfus** [comment]
Works correctly in 4.1.8: http://jsfiddle.net/10onvd1q/4/
