### ISSUE TITLE
tspan added around series name after series.update({name:"another name"}) called

### ISSUE THREAD

**Issue by lapolonio** [highslide-software/highcharts.com#3410]
When a graph originally renders the format of series name is:
```
<g class="highcharts-legend-item">
    ...
    <text>
         Series Name
    </text>
</g>
```
after `series.update({name:"another name"})` is called structure is:
```
<g class="highcharts-legend-item">
    ...
    <text>
        <tspan>another name</tspan>
    </text>
</g>
```

tspan shouldn't be there

**Comment by pawelfus** [comment]
Any specific reasons, why tspan shouldn't be there? 
Note: right now it's consistent, tspan always exists: http://jsfiddle.net/oxxwxqan/

**Comment by lapolonio** [comment]
i was having issues with automated testing
