### ISSUE TITLE
Highcharts legend transform error when legend item's text is short

### ISSUE THREAD

**Issue by natee** [highslide-software/highcharts.com#3455]
When all items of the legend has a short text,for example,'A,B,C,D..',then the navigation is longer than the legend and you won't see the page down button for the legend's transform 'x' is error.
You can see it here.
http://jsfiddle.net/83r3y9j7/

**Comment by pawelfus** [comment]
Workaround: set `legend.width = 60`, see: http://jsfiddle.net/83r3y9j7/1/
