### ISSUE TITLE
Labels are not visible anymore even though there is enough space

### ISSUE THREAD

**Issue by martijnAenova** [highslide-software/highcharts.com#3458]
http://jsfiddle.net/g8h7urbn/1/

When you check the jsfiddle sample then you see bars without a label although there is room to put some text there. Why is it removed at all. E.g. the label "Oranges and Tomatoes" is now missing, but there is room to put e.g. the beginning from the label there: "Oranges...". Or is there a way to configure the text?

**Comment by highslide-software** [comment]
Closing this, Highcharts 4.1 will be out soon. Verified: http://jsfiddle.net/g8h7urbn/4/
