### ISSUE TITLE
Drilldown doesn't work in StockChart

### ISSUE THREAD

**Issue by baselsalam** [highslide-software/highcharts.com#3475]
I can't seem to get drilldown working on stockchart.
See this jsfiddle: http://jsfiddle.net/ymrzjpkp/

If you just comment out the "StockChart" line, it works.

There's a JS error seen on load, not sure if its related:
'Uncaught TypeError: Cannot read property 'getBBox' of undefined'

**Comment by sebastianbochan** [comment]
Works since HS 2.1.0 and DD 4.1.0
