### ISSUE TITLE
Too large margin when labels are rotated

### ISSUE THREAD

**Issue by KacperMadej** [highslide-software/highcharts.com#3479]
When I rotate my x-axis labels 270 degrees and set align to left, the automatically calculated bottom margin is too large (equal to the bottom margin calculated for align = right).

See http://jsfiddle.net/kzoon/ws5xttpy/2/

I would expect the same behaviour as here: http://jsfiddle.net/kzoon/xmm06m6f/1/

**Comment by kzoon** [comment]
Any chance of solving this issue? I keep running into it and I can't use the workaround , because I also have axis-title and legend (of variable height) below my charts.

**Comment by highslide-software** [comment]
Turns out auto-detection isn't trivial, and in some cases people may want the current functionality, for example in combination with setting a higher y offset. So I added a new option, `labels.reserveSpace` that can be set to false: http://jsfiddle.net/highcharts/ws5xttpy/7/
