### ISSUE TITLE
The range selector doesn't appear.

### ISSUE THREAD

**Issue by gkjgithub** [highslide-software/highcharts.com#3486]
Version: Highstock 2.0.4
Browser: Firefox 32.0.3

After browser finished loading, the range selector doesn't appear, but when drag navigator, it does. The code is simple:

```javascript
$(function (){
    $('#chartContainer').highcharts('StockChart',{
        navigator :{
            adaptToUpdatedData : false,
        },
        scrollbar:{
            enabled : false
        },
        rangeSelector :{
            selected : 3
        },
        series : [{}]
    });
    var chart = $('#chartContainer').highcharts();
    $.getJSON('http://www.highcharts.com/samples/data/jsonp.php?filename=range.json&callback=?',
    function (data){
        chart.series[0].setData(data);
    });
});
```

**Comment by odarriba** [comment]
I've the same problem loading by AJAX around 20.000 points (using HighStock). These points are grouped well and the default zoom level applied, but the buttons didn't show until I make a zoom manually (or open developer console)
