### ISSUE TITLE
Polar chart axis label overlap

### ISSUE THREAD

**Issue by KacperMadej** [highslide-software/highcharts.com#3506]
The data labels in my polar chart overlap. See http://jsfiddle.net/kzoon/orejxmqm/1/

Labels on the left hand side get align 'right' , those on the right hand side 'left'. But near the to and bottom the label align is 'center', causing them to overlap.

The problem gets worse when the number of labels increases: http://jsfiddle.net/kzoon/bh1tnokf/2/

**Comment by frodelau** [comment]
Hi,
we are struggling with the same issue. Are there any updates on a fix for this label overlap?

**Comment by highslide-software** [comment]
This demo shows dynamically where it goes wrong: http://jsfiddle.net/highcharts/oecx9bau/

**Comment by kzoon** [comment]
I use this workaround for this issue, which simply sets a very small bracket for align center:

    HighCharts.wrap(HighCharts.Tick.prototype, 'getLabelPosition', function (proceed, x, y, label, horiz, labelOptions, tickmarkOffset, index, step) {
        var axis = this.axis,
		optionsY = labelOptions.y,
		ret,
		align = labelOptions.align,
		angle = ((axis.translate(this.pos) + axis.startAngleRad + Math.PI / 2) / Math.PI * 180) % 360;

        if (axis.isRadial) {
            ret = axis.getPosition(this.pos, (axis.center[2] / 2) + Highcharts.pick(labelOptions.distance, -25));

            // Automatically rotated
            if (labelOptions.rotation === 'auto') {
                label.attr({
                    rotation: angle
                });

                // Vertically centered
            } else if (optionsY === null) {
                optionsY = axis.chart.renderer.fontMetrics(label.styles.fontSize).b - label.getBBox().height / 2;

            }

            // Automatic alignment
            if (align === null) {
                if (axis.isCircular) {

                    //KZ20141117: smaller brackets for align center
                    //  if (angle > 20 && angle < 160) {
                    if (angle > 1 && angle < 179) {
                        align = 'left'; // right hemisphere
                        //} else if (angle > 200 && angle < 340) {
                    } else if (angle > 181 && angle < 359) {
                        align = 'right'; // left hemisphere
                    } else {
                        align = 'center'; // top or bottom
                    }
                } else {
                    align = 'center';
                }
                label.attr({
                    align: align
                });
            }

            ret.x += labelOptions.x;
            ret.y += optionsY;

        } else {
            ret = proceed.call(this, x, y, label, horiz, labelOptions, tickmarkOffset, index, step);
        }
        return ret;
    });

**Comment by simon2k** [comment]
Thanks @kzoon I see that increasing size of the chart & using your piece of code does the job! :+1: :)

**Comment by highslide-software** [comment]
The initial problem with centered labels on top and bottom is resolved in the commit above. See http://jsfiddle.net/highcharts/oecx9bau/1/.

The remaining problem now is that labels are still squished when there are too many categories. The fiddle shows an attempt at resolving this through the new overlapping-datalabels module file, but it doesn't work.
