### ISSUE TITLE
Highstock: scrolling continue even when end is reached

### ISSUE THREAD

**Issue by Vangi** [highslide-software/highcharts.com#3543]
Here is how can you reproduce the bug from http://jsfiddle.net/Vangi/f4paczmk/5/:
1. Zoom-in to data in the chart
2. Click on the right arrow button to move the scrollbar to the right
The problem: When the scrollbar is to the end and when right arrow button is clicked then the scrollbar returns back.

And here is the an animated GIF to see the actions of the described problem:
![2014-10-28_11-01-43](https://cloud.githubusercontent.com/assets/1262644/4806650/74231fce-5e8b-11e4-862a-880e65270686.gif)

Is this a bug or there is a solution?

**Comment by highslide-software** [comment]
Normalized size and zoom: http://jsfiddle.net/highcharts/f4paczmk/7/
