### ISSUE TITLE
3d pie chart hangs the browser when all the data points are zero

### ISSUE THREAD

**Issue by boker** [highslide-software/highcharts.com#3545]
http://jsfiddle.net/highcharts/Qgn59/

If you include the highcharts-3d.js and use the options3d: { enabled: true}... you will see the browser hang.

**Comment by salunkenagesh14** [comment]
This issue is getting reproduced .
Example : http://jsfiddle.net/px38b76w/1/

**Comment by highslide-software** [comment]
It's fixed in the master branch, see http://jsfiddle.net/mdxkfgm4/
