### ISSUE TITLE
Wrong slice label displaying on 3d pie

### ISSUE THREAD

**Issue by augun** [highslide-software/highcharts.com#3549]
While running the code on http://jsfiddle.net/uhydP/225/ , the label 8.87% is moved to the black area.
It is the same code as on http://jsfiddle.net/jugal/uhydP/ which works fine, just without 3d options added.

**Comment by augun** [comment]
Dear Torstein,
Are there any solutions for this kind of issue?

**Comment by pawelfus** [comment]
Duplicate of #3259
