### ISSUE TITLE
reversed legend property doesn't work

### ISSUE THREAD

**Issue by domurtag** [highslide-software/highcharts.com#3554]
According to [the docs](http://api.highcharts.com/highcharts#legend.reversed), the `reversed` property of the legend should reverse the order of the items therein. Therefore, if I add the property
````
legend {
    reversed: true
}
````

to [this demo](http://jsfiddle.net/gh/get/jquery/1.9.1/highslide-software/highcharts.com/tree/master/samples/highcharts/demo/heatmap/) I would expect the numbers in the legend on the right to increase from bottom to top, but it doesn't seem to change anything.

**Comment by pawelfus** [comment]
Example: http://jsfiddle.net/q2g4wcnk/ (multiple series on the one chart). 

- `legend.reversed` reorder items
- `colorAxis.reversed` reorder colorAxis item
