### ISSUE TITLE
Problem with zoom in map on addPoint and setData 

### ISSUE THREAD

**Issue by KacperMadej** [highslide-software/highcharts.com#3570]
Problem with zoom in map on addPoint and setData.

jsFiddle: http://jsfiddle.net/js7vu66a/7/

Steps:
1- zoom in using the + button
2- click add country
3- zoom out using the - button
3- click empty map
---> Map zooms out too much

You can notice that when zoomed in addPoint will cause additional zoom in.

**Comment by oysteinmoseng** [comment]
Seems to be closed by commit above.
