### ISSUE TITLE
pointPlacement not working for single data

### ISSUE THREAD

**Issue by jagdipa** [highslide-software/highcharts.com#3578]
It is best to view to this example : http://jsfiddle.net/2Lrwxh6g/1/ - the top code has 4 variables with comments on what works and what doesn't.

The problem is that the pointPlacement does not work when there is just a single column and a single value in the line data.

**Comment by pawelfus** [comment]
Sorry, I missed your comment. Just for future reference: using master branch in production isn't the best idea, since may contain some unreported bugs.
