### ISSUE TITLE
Point.update() issue when turboThreshold exceeded

### ISSUE THREAD

**Issue by nuclearwessel** [highslide-software/highcharts.com#3604]
I encountered a situation where series would display properly when added but disappeared after updating if the data length exceeded the turboThreshold parameter. Pretty sure I isolated it to the Point.update() function replacing what was a properly formatted array data point (Ex. [0, 0]) with an object (Ex. {x: 0, y: 0}), which the series update would treat as invalid and throw error 12 at me. I realize I can up the turboThreshold to something huge but seemed to defeat the purpose just to let updates work.

I did a simple workaround by checking for an array type and reassigning the value as needed but don't really have the time to test all the possible issues that may cause. If anyone else runs into this, https://github.com/highslide-software/highcharts.com/blob/7377b2c8e2717ab35339b501ac3bbebac81b7400/js/highcharts.src.js#L14617
```
seriesOptions.data[i] = point.options;
```

to

```
if (isArray(seriesOptions.data[i])) {
    seriesOptions.data[i][0] = point.options.x;
    seriesOptions.data[i][1] = point.options.y;
} else {
    seriesOptions.data[i] = point.options;
}
```

**Comment by vickychijwani** [comment]
Having the same issue here with `Series#addPoint` (Highstock 2.1.5). I tracked it down to [this line](https://github.com/highslide-software/highcharts.com/blob/7377b2c8e2717ab35339b501ac3bbebac81b7400/js/highcharts.src.js#L12327). It appears the `optionsToObject` function is replacing my array data point of the form `[1431962610723, 0]` with an object and then throwing the turbo threshold error (error 12).

**Comment by vickychijwani** [comment]
Apparently the error has something to do with the fact that we're attaching custom properties to a Highcharts series. @nuclearwessel I know it's been some time, but if you're still looking into this you might want to check if you're attaching your own properties to objects owned by Highcharts.

**Comment by highslide-software** [comment]
Also no problem here: http://jsfiddle.net/9tnfkcuy/.

I'm closing the issue, please reopen if you have a live demo.

**Comment by vickychijwani** [comment]
@highslide-software is there a recommended way to attach custom data to Highcharts objects? We need to attach some data to a live series so we can retrieve it later.

**Comment by highslide-software** [comment]
As long as you avoid property names used internally I can't see that is should lead to problems. You can either attach custom properties to the options object, or the Series itself.

**Comment by vickychijwani** [comment]
I have a live demo for you, use whichever is simpler to work with (both do exactly the same things):

http://jsfiddle.net/vickychijwani/kwnrszgp/1/
http://jsfiddle.net/vickychijwani/kwnrszgp/4/

**Comment by vickychijwani** [comment]
Hi @highslide-software, did you get a chance to look at the live demo in my previous comment? Please consider re-opening this issue.

**Comment by vickychijwani** [comment]
Also, I can confirm that this has nothing to do with attaching custom data to Highcharts.Series (I was mistaken earlier), this is reproducible even if I maintain that data separately.
