### ISSUE TITLE
Axis labels -  unnecessary wrapping of labels when step > 1

### ISSUE THREAD

**Issue by KacperMadej** [highslide-software/highcharts.com#3607]
Axis labels with step 2 or more includes invisible labels in calculating the need for wrapping labels in more than 1 line (avoid overlapping of labels).

Example: http://jsfiddle.net/4cd5kvv4/3/

**Comment by pawelfus** [comment]
Works fine in 4.1.7: http://jsfiddle.net/4cd5kvv4/5/
