### ISSUE TITLE
3d pie - slice rendered incorrectly when innerSize is larger than the size of a pie

### ISSUE THREAD

**Issue by KacperMadej** [highslide-software/highcharts.com#3632]
When we are setting a height for 3D doughnut less than 250 it will not render properly.
Example: http://jsfiddle.net/01jrtLqm/

**Comment by KacperMadej** [comment]
Shouldn't be innerSize disallowed to be larger than the size? This could solve the issue.

Any way, the problem is not present after this commit https://github.com/highslide-software/highcharts.com/commit/650eee6ca9f3c1c4ae1b345997041840eb164de5
Example: http://jsfiddle.net/01jrtLqm/1/
Related to #3323 

Better demo for this issue: http://jsfiddle.net/4axtrtv2/
Still solved by mentioned commit: http://jsfiddle.net/4axtrtv2/1/

**Comment by highslide-software** [comment]
> Shouldn't be innerSize disallowed to be larger than the size? This could solve the issue.

Yes, that makes sense.

**Comment by highslide-software** [comment]
@KacperMadej Did you make any code changes to this issue?

**Comment by KacperMadej** [comment]
I did not make any code changes to this issue. After the commit https://github.com/highslide-software/highcharts.com/commit/650eee6ca9f3c1c4ae1b345997041840eb164de5 I am no longer able to recreate the issue. In a chart with correct innerSize (not larger than a size of a pie) issue is not visible. Should I add a limitation in code to prevent innerSize from being set as a value larger than a pie size? If yes, should be a innerSize decreased to the same (or other?) value as a size? or should those values be swapped (innerSize <-> size)?

**Comment by highslide-software** [comment]
I am not sure. I guess you can take a look at the problem, and if it doesn't add too much code, add a limitation in the code. I guess decreasing the innerSize to the same value as the size would make more sense.

**Comment by KacperMadej** [comment]
Doesn't look like it adds too much code - limitation added. Commit https://github.com/highslide-software/highcharts.com/commit/de685deeb20b6d590471dd2fa55ae57cb01e553f
