### ISSUE TITLE
Series (negative) color settings ignored on column hover

### ISSUE THREAD

**Issue by mbalonso** [highslide-software/highcharts.com#3636]
Given a column chart that has series w/negative values and a negativeColor setting, when you mouseover one of the columns w/a negative value, it changes the color of the column to the positive color. 

Example: http://jsfiddle.net/malonso/7q97ao6y/1/

That fiddle was forked from http://jsfiddle.net/gh/get/jquery/1.9.1/highslide-software/highcharts.com/tree/master/samples/highcharts/demo/column-negative/ with the only difference being the addition of 'color' and 'negativeColor' attributes for a single series.

FWIW - This does *NOT* happen in 3.0.9 but does happen in 3.0.10 and 4.0.x.

**Comment by Cederman** [comment]
I do not mean to reopen this issue, but I notice the same behaviour for timeseries chart I just made using the current version. http://jsfiddle.net/0tn7vzwe/

**Comment by stannius** [comment]
This bug still reproduces for line charts as well. http://jsfiddle.net/wrow9fud/1/

**Comment by mbalonso** [comment]
@Cederman @stannius - I will try reopening this but if there is not any activity here in a day or so, it is probably worth opening a new issue as I doubt anyone is paying attention to this thread anymore.

**Comment by pawelfus** [comment]
We are trying to close duplicated topics, so reopening sounds very reasonable. With reopened ticket we also receive with full history of changes.

**Comment by pawelfus** [comment]
*Internal note:*
Fix should also consider all zones, not only positive/negative colors.

**Comment by pawelfus** [comment]
Note: fix above works altogether with [this commit](https://github.com/highslide-software/highcharts.com/commit/3b8da66bebea56f4a961c34746d74e6ac0814d2b).
