### ISSUE TITLE
Gauge chart point.update() doesn't respect animation = false argument 

### ISSUE THREAD

**Issue by thecontstruct** [highslide-software/highcharts.com#3638]
It would seem that you can't turn animations off for data point updates with gauge charts like this:
```
chart.series[0].data[0].update(newVal, true, false);
```
ex: http://jsfiddle.net/1n7p0nye/

Doing the same thing on a column chart works as expected.
ex: http://jsfiddle.net/dwee9das/

**Comment by pawelfus** [comment]
Works fine: 4.1.5+. http://jsfiddle.net/1n7p0nye/2/
