### ISSUE TITLE
Scatter markers displaced by 1px after hovering

### ISSUE THREAD

**Issue by Jollyfant** [highslide-software/highcharts.com#3643]
Some markers in scatter plots are displaced by 1px after being hovered over. This happens for the first few markers in the preview consistently, but not for all markers. Look closely to see this irregular behavior.

Preview: http://jsfiddle.net/6rdzoegq/1/
Tested on Firefox 33.1 with similar behavior on Chrome.

Edit: reproducible on Firefox and IE if the browser window is maximized. Reproducible on Chrome if the browser window is not maximized.

Edit II: It happens for "type: line" too and not just scatter data. Some markers shift slightly when hovering over them. After that, they remain in their new position for good.

Edit III: It happens irregularly on most charts that I come across depending on browser window dimensions etc. Easiest method is to take a screenshot of a chart, hover over some markers and then take another screenshot to see the change. Before and after marker movement the plotX and plotY values remain unchanged. I'm clueless as to what may be causing this.

Jolly

**Comment by highslide-software** [comment]
Closed by 8c154994b61633a11dfe6ec11dbf971f7f6da311
