### ISSUE TITLE
Export server: multiple text-shadow definitions leave duplicated elements

### ISSUE THREAD

**Issue by highslide-software** [highslide-software/highcharts.com#3649]
1. Open http://jsfiddle.net/highcharts/kyzh8pz6/ 
2. Through the export menu, download the chart as PNG.
3. Observe the duplicated text (see image)

![chart](https://cloud.githubusercontent.com/assets/227836/5392452/8435c840-8126-11e4-9f30-32a121ecde97.png)

We observed that this doesn't happen when downloading the export as SVG and running the PNG conversion through the command line.

#### Workaround
Avoid multiple text-shadow definitions. Instead of `text-shadow: 0 0 3px black, 0 0 3px black`, use `text-shadow: 0 0 3px black`.

**Comment by highslide-software** [comment]
@gvaartjes Can you check if this still happens with PhantomJS 2.0? If it doesn't, we can use double definitions with HC 4.1.

**Comment by gvaartjes** [comment]
The result with converting with phantomjs 2.0 attached
![chart](https://cloud.githubusercontent.com/assets/951644/6135048/b36537b2-b165-11e4-89aa-9a9452fd7bd0.png)

**Comment by gvaartjes** [comment]
But the fiddle above, http://jsfiddle.net/highcharts/kyzh8pz6/ is still not working with phantomjs v2.0

**Comment by highslide-software** [comment]
Shoot

**Comment by highslide-software** [comment]
Since this is an immensely useful feature for labels, I guess the best option is to disable the double definition in exported charts. Then at least we don't have to work around the issue in charts rendered on screen.

**Comment by gvaartjes** [comment]
Agreeing on that.

**Comment by gvaartjes** [comment]
Strange thing: 
1. Exporting via Highcharts
2. Copy request parameter _svg_ from webconsole
3. paste in copied _svg_ string in *export_server*/demo page 
4. press Download
5. Now we have a svg with correct dropshadow! 

This needs more investigating..

**Comment by highslide-software** [comment]
Closed by b8d6a49f569dbd403074c6a3bf760c13651fa824

**Comment by pawelfus** [comment]
Still a bit problematic with textShadow and 4.1.5 version: http://jsfiddle.net/3gvwcdjp/13/

Export to jpeg/png and get duplicated label: 
![chart 48](https://cloud.githubusercontent.com/assets/1453926/7452497/74b642e2-f25e-11e4-9e65-2e3316035b97.jpeg)

**Comment by highslide-software** [comment]
See #3974. We have a proposed solution that works around the problem on iOS, but PhantomJS still displays the problem. We will check with PhantomJS 2.

**Comment by pawelfus** [comment]
Ok, thanks for the info. Sometimes it's hard to keep on track all tickets.

**Comment by highslide-software** [comment]
I made a commit, 97de814, that fixes this problem on Retina displays, but on exported charts it still applies. However, once we have updated the export server to PhantomJS 2, this here issue will be resolved too. We are only waiting for the authors to provide Linux compatible builds of PhantomJS 2.

**Comment by sebastianbochan** [comment]
Pie chart example: http://jsfiddle.net/n96c5pbu/1/

**Comment by highslide-software** [comment]
Yes, the export server is still not updated

**Comment by JohnMcAvinue** [comment]
Any ideas when the export server will be updated to eliminate this issue?

**Comment by gvaartjes** [comment]
@JohnMcAvinue @highslide-software   We're sadly still waiting for the official release of PhantomJS 2, which is still not available.

**Comment by JohnMcAvinue** [comment]
@gvaartjes Thanks. Do you know if it's imminent? Just need an idea about timeframes for getting this fixed

**Comment by gvaartjes** [comment]
Sorry John for taking this so long time. 

We're working setting up an new linux server which can support unofficial distro of pjhantomjs 2. I'm working with a timeframe of two weeks (No guarantees..).

**Comment by JohnMcAvinue** [comment]
Hi Gert,

Thanks for your email. No problem about it taking time - I appreciate all
your efforts with this great component! The only reason I ask is because
there's a bug raised against me and I need to be able to give a time frame.

Thanks,
John

John

**Comment by gvaartjes** [comment]
Hi John, it's taking a bit longer time, but all is looking good. Today we had a successful build of the server on Amazon. It needs some polishing on the system administrator side still. But we're almost there.

**Comment by JohnMcAvinue** [comment]
Great stuff Gert. Thanks to you and your team for all the hard work. It's really appreciated!

John

**Comment by gvaartjes** [comment]
Today I rolled out PhantomJS version 2  on the export server.

I have tested these fiddles. 

http://jsfiddle.net/n96c5pbu/1/
http://jsfiddle.net/3gvwcdjp/13/
http://jsfiddle.net/highcharts/kyzh8pz6/

I confirmed that multiple text-shadow definitions no longer leave duplicated elements. 

Thx for the patience to resolve this issue.

Gert

**Comment by CarlaTeo** [comment]
I've just generated a svg image from examples http://jsfiddle.net/n96c5pbu/1/ and http://jsfiddle.net/3gvwcdjp/13/ and the problem I had is still happening.

If you open the images in a text editor you can see that the legend in the pie chart and the title in the column chart are duplicated.
It seems most image viewers can handle this, but when I use these images with tcpdf the problem is visible:

![sem titulo](https://cloud.githubusercontent.com/assets/9220147/10248143/219d7b22-68f4-11e5-8336-9ad35eccdaec.png)

**Comment by JohnMcAvinue** [comment]
It's working perfectly for me - thank you very much!

**Comment by CarlaTeo** [comment]
Just to be sure, it seems you don't intend to treat the problem I reported as a bug, right?

 I just need to know because if that is the case I'll make a patch to solve that instead of waiting for a fix

**Comment by highslide-software** [comment]
Hi @CarlaTeo, sorry for not replying, I thought it was another case of the same issue, which is fixed now.

Anyway, I can't replicate your problem. What browser are you using? Here's what I did:
1. Opened Chrome
2. Opened http://jsfiddle.net/n96c5pbu/1/. FYI, it's running Highcharts 4.1.9 that was launched yesterday.
3. Downloaded as SVG
4. Inspected in a text editor. The legend markup shows no duplication of text:

```xml
	<g class="highcharts-legend" transform="translate(149,345)">
		<g>
			<g>
				<g class="highcharts-legend-item" transform="translate(8,3)">
					<text style="color:#333333;font-size:12px;font-weight:bold;cursor:pointer;width:200;fill:#333333;" text-anchor="start" x="21" y="15">
						<tspan>(100,00%) Multimercados Juros</tspan>
						<tspan dy="15" x="21">e Moedas</tspan>
						<title>(100,00%) Multimercados Juros e Moedas</title>
					</text>
					<rect fill="#7cb5ec" height="12" width="16" x="0" y="4"/>
				</g>
				<g class="highcharts-legend-item" transform="translate(241.96875,3)">
					<text style="color:#333333;font-size:12px;font-weight:bold;cursor:pointer;width:200;fill:#333333;" text-anchor="start" x="21" y="15">Total</text>
					<rect fill="#434348" height="12" width="16" x="0" y="4"/>
				</g>
			</g>
		</g>
	</g>
```

**Comment by CarlaTeo** [comment]
Hi, Torstein,

Thank you for your reply.
I didn't know this \<title\> \<tsan\> thing was a normal feature of SVG images (http://stackoverflow.com/questions/19236738/using-ellipsis-with-svgs-tspan).
That is why I said the text was duplicated.

So I guess the problem is really with TCPDF library that always render these texts twice. 

Sorry for bothering.

**Comment by highslide-software** [comment]
Okay, no worries! 

The `title` has its own tag in SVG, while in HTML it is an attribute.

**Comment by RIGUPTA2** [comment]
> Hi, Torstein,
> 
> Thank you for your reply.
> I didn't know this <title> thing was a normal feature of SVG images (http://stackoverflow.com/questions/19236738/using-ellipsis-with-svgs-tspan).
> That is why I said the text was duplicated.
> 
> So I guess the problem is really with TCPDF library that always render these texts twice.
> 
> Sorry for bothering.



> Hi, Torstein,
> 
> Thank you for your reply.
> I didn't know this <title> thing was a normal feature of SVG images (http://stackoverflow.com/questions/19236738/using-ellipsis-with-svgs-tspan).
> That is why I said the text was duplicated.
> 
> So I guess the problem is really with TCPDF library that always render these texts twice.
> 
> Sorry for bothering.

Hello Carla,
I am facing similar issue with mpdf library. Was your problem solved of duplicate text rendered in generated image. If yes, how? Kindly share.

**Comment by CarlaTeo** [comment]
> > Hi, Torstein,
> > Thank you for your reply.
> > I didn't know this <title> thing was a normal feature of SVG images (http://stackoverflow.com/questions/19236738/using-ellipsis-with-svgs-tspan).
> > That is why I said the text was duplicated.
> > So I guess the problem is really with TCPDF library that always render these texts twice.
> > Sorry for bothering.
> 
> Hello Carla,
> I am facing similar issue with mpdf library. Was your problem solved of duplicate text rendered in generated image. If yes, how? Kindly share.

@RIGUPTA2 Unfortunately, it has been so long ago I am not sure... Maybe I did a regex to parse and remove the <title> tag. ¯\_( ツ)_/¯.

**Comment by RIGUPTA2** [comment]
No problems, I found a way out and posted my solution here also.
[Link](https://stackoverflow.com/questions/28563073/when-using-canvg-to-convert-highchart-svg-into-png-all-text-appears-twice-how)
Thanks for your reply.
