### ISSUE TITLE
minorGridLine rendered outside the plotting area

### ISSUE THREAD

**Issue by pawelfus** [highslide-software/highcharts.com#3652]
Example: http://jsfiddle.net/jqgjrh3r/2/

Simply use left handler of scrollbar to change extremes and observe the right side of the plotting area:
![screen shot 2014-12-12 at 11 39 52 am](https://cloud.githubusercontent.com/assets/1453926/5410326/a24ce0e8-81f3-11e4-9283-696e2855d262.png)

**Comment by pawelfus** [comment]
+1

**Comment by highslide-software** [comment]
The regression happened after 8e82937

**Comment by pawelfus** [comment]
Works fine in 4.1.7.
