### ISSUE TITLE
Imprecise hover over small areas in maps

### ISSUE THREAD

**Issue by oysteinmoseng** [highslide-software/highcharts.com#3683]
When hovering over small areas, the wrong area is often selected. Seen in demos of admin2 maps for Netherlands, Germany, Norway, and others (e.g. http://jsfiddle.net/gh/get/jquery/1.11.0/highslide-software/highcharts.com/tree/master/samples/mapdata/countries/no/no-all-all). 

Problem seems directly linked to the size of the SVG elements, and increasing chart size / zooming in beyond a certain point fixes the issue.

Problem exists in both latest Chrome, Firefox and IE.

**Comment by pawelfus** [comment]
Explanation note: tracker for tooltip is set also for dataLabels, which can be disabled: 

        Highcharts.seriesTypes.map.prototype.trackerGroups = ['group'];

And events can be disabled for SVG elements:

    .highcharts-data-labels {
         pointer-events: none;   
    }

Demo: http://jsfiddle.net/45ck22z4/

**Comment by highslide-software** [comment]
Duplicate of #4362, but Pawel's workaround is a good one for visible data labels.
