### ISSUE TITLE
Documentation incomplete googleSpreadsheetWorksheet

### ISSUE THREAD

**Issue by ronanquillevere** [highslide-software/highcharts.com#3685]
Hello,

I think the documentation for new option data.googleSpreadsheetWorksheet is incomplete

As the option is not a parent, I think the return type should be filled with a value (string ?) for us to know what to put in this field. Plus the example does not show how to use this option, it only show an example with googleSpreadsheetKey so there is no way to guess.

Found that because my GWT automatic wrapper could not generate the new corresponding code.

```javascript

name: "data--googleSpreadsheetWorksheet",
fullname: "data.googleSpreadsheetWorksheet",
title: "googleSpreadsheetWorksheet",
parent: "data",
isParent: false,
extending: null,
excluding: null,
returnType: null,
defaults: null,
values: null,
since: "4.0",
description: "The Google Spreadsheet worksheet to use in combination with <a href="#data.googleSpreadsheetKey">googleSpreadsheetKey</a>. The available id's from your sheet can be read from <code>https://spreadsheets.google.com/feeds/worksheets/{key}/public/basic</code>",
demo: "<a href="http://jsfiddle.net/gh/get/jquery/1.7.2/highslide-software/highcharts.com/tree/master/samples/highcharts/data/google-spreadsheet/" target="_blank">Load a Google Spreadsheet</a>",
seeAlso: null,
deprecated: false
```

Sorry to add this on this bug, but as we are talking returnType could you also please have a look to that thread on your forum also :
http://forum.highcharts.com/post111151.html#p111151

I raised a question about return type for plotOptions.series.states but I got no official answer.

Thanks

**Comment by highslide-software** [comment]
Thanks, returnType added.
