### ISSUE TITLE
Date handling different depending on whether more or less than 1000 data points

### ISSUE THREAD

**Issue by AWilco** [highslide-software/highcharts.com#3686]
I've struggled with the exact description of this bug, so I'm going with my original issue.

I have a chart with a variable number of data points, where the x axis is a date. I created my data in the following format:

    [[new Date(2014,1,1), 101.5],[new Date(2014,1,2), 101.5],.... ]

With data of more than 1000 points, this plots correctly. However with data less than 1000 points, the dates are not plotted correctly. http://jsfiddle.net/m3chpvus/ shows what happens. This is a modification of your demo fiddle http://jsfiddle.net/gh/get/jquery/1.9.1/highslide-software/highcharts.com/tree/master/samples/highcharts/demo/spline-irregular-time/ . 

The reason for this is because over 1000 points "turbo" mode assigns the date into the X value of the created point object without checking what it is (highcharts.js 12890). In non-turbo mode the first Item in the array is checked to see if it is a string or a number, and is ignored otherwise. (highcharts.src.js 12334). A Date object is neither and so is ignored.

The use of the date object as an X value works, because its used as 

    (val - localMin)

in the translate function, which coerces it to its correct timestamp number.

For me, there are a couple of ways to "resolve" this.

1. Highcharts doesn't support actual date objects, only timestamps. The fact that they work in Turbo mode is unintended.

2. rather than doing a typeof(xValue) == 'number' check, do a isFinite(xValue) or isFinite(xValue-0) check at 12337. This is because what we actually want to know is have we a value that can be converted into a finite number later on? 

Note; xValue+0 wouldn't work with dates, at least in chrome, because both the date and 0 would be converted to a string. This may be a sign that date handling is a little ropey and you would want to stick to timestamp numbers.

**Comment by sebastianbochan** [comment]
You should use timestamps, instead of string. The new Date(1970,  9,  9) returns: 
Fri Oct 09 1970 00:00:00 GMT+0100 (CET) but Date.UTC(1970,8,9) returns timestamp, which is correct.

**Comment by AWilco** [comment]
@sebastianbochan  
I'm happy to use number timestamps rather than the Date object, but your response is incorrect. But your interpretation of the functions is wrong.

new Date(1970,9, 9) returns a javascript Date object. This is 'special' object that stores a date value. It can be co-erced into a string (which is what happens when you try and view it in a console, hence what you see), but it can also be co-erced into a number, and other formats. Date.UTC() returns an actual number, not a date object.

When working with x axis values that are dates, it is non-obvious from the documentation that you cannot supply actual Date objects, which are commonly generated from other libraries, but must instead convert this to numbers yourself. This problem is exacerbated by the fact that it does work in some instances but not others. 

I'm happy that the issue can be closed, but I think the documentation can be updated to clarify that use of actual Date objects as x values is not supported.

**Comment by highslide-software** [comment]
The docs already says a Number is expected, but I have added a small
explanation for datetimes:
http://api.highcharts.com/highcharts#series.data.x​

**Comment by AWilco** [comment]
Okay thanks.
