### ISSUE TITLE
Candlestick and ohlc rendered out of bounds

### ISSUE THREAD

**Issue by maximenicot74** [highslide-software/highcharts.com#3689]
I don't think this as been reported.

I've used this plugin to make my axis scalable : http://www.highcharts.com/plugin-registry/single/20/Scalable%20Y-Axis

I'm using that within a chart with 2 axis, displayed the same way as a quotes/volumes chart.
And I've figured out that candlestick and ohlc are rendered out of their y-axis after having scaled the axis. Here is a live example : http://jsfiddle.net/0dxvav2d/
You can switch the series type at line 71.

**Comment by highslide-software** [comment]
Moved this to https://github.com/RolandBanguiran/highcharts-scalable-yaxis/issues/6
