### ISSUE TITLE
FAQ 404

### ISSUE THREAD

**Issue by sogen** [highslide-software/highcharts.com#3699]
In here:
http://www.highcharts.com/docs/getting-started/frequently-asked-questions#non-ascii

clicking 
```
HOW DO I ADD DATA FROM A MYSQL DATABASE?
See Preprocessing data from a database.
```
has this link:
http://www.highcharts.com/docs/working-with-data/preprocessing-data-from-a-database

goes to a 404.

**Comment by highslide-software** [comment]
Fixed, thanks for reporting.
