### ISSUE TITLE
Black background displayed in the chart in after upgrade from version 3.0.10 to version 4.0.0.

### ISSUE THREAD

**Issue by simon2k** [highslide-software/highcharts.com#3705]
Hi guys,

After upgrading highcharts, from version 3.10 to version 4.0.0, I have a small issue with displaying the chart.

Here's working example for reproducing the issue: http://jsfiddle.net/co8hc59w/3/

Basically, when the chart has too small width, firstly, it displays the black colour in the background, and secondly it displays range from 0 to 100 instead of 20 to 80.

Similar issue is while rendering a different chart in pdf: https://www.dropbox.com/s/qpj803685c2oh9n/Screenshot%202015-01-05%2020.37.07.png?dl=0
However, I don't have example in jsfiddle.

Cheers

**Comment by simon2k** [comment]
I see, it's related to the length of name for series: http://jsfiddle.net/co8hc59w/4/

**Comment by highslide-software** [comment]
Two things cause the black area:

1. You have set `alternateGridColor` to `"null"`, which is an unknown named color, so the browser draws it as black. What you probably meant is `null`, without the quotes.

2. As dictated by the default `tickPixelInterval`, Highcharts extends the axis to the nearest ticks, which is 0 and 100. To prevent this, set `startOnTick` and `endOnTick` to `false`. 

Corrected chart: http://jsfiddle.net/co8hc59w/5/
