### ISSUE TITLE
Solid gauge - setsize call - serie disappears

### ISSUE THREAD

**Issue by sebastianbochan** [highslide-software/highcharts.com#3708]
Example: http://jsfiddle.net/w10hdf9f/2/

**Comment by stephanevanraes** [comment]
This has something to do with how the solid gauges decides on it's color, if you inspect the chart you will see that after resize the fill is set to 'none'.  (offending lines would be 186 to 189 in solid-gauge.src.js)

Also, related to this, setting a color on the series level of a solidgauge does not seem to have an effect, setting it on the point works: http://jsfiddle.net/stephanevanraes/w10hdf9f/3/

**Comment by seiyria** [comment]
@highslide-software any idea when this change will propagate as a tag so it can be pulled with bower?

**Comment by highslide-software** [comment]
It will be released with Highcharts 4.1 within a few weeks.​

**Comment by roydondsouza** [comment]
@highslide-software  If I want this change in 4.0.4 will the fix break the existing functionality?

**Comment by seiyria** [comment]
No, it works fine. I'd rather wait for an actual patch though; hopefully it comes sooner rather than later!
