### ISSUE TITLE
Crash when hide/show linked series

### ISSUE THREAD

**Issue by ValentinH** [highslide-software/highcharts.com#3709]
This  46bf910 commit for #3702 has broken a working behavior when using linked series:

if we have 2 series, A and B, and B is linkedTo A, if B is hidden at first and we show it, we get the same error as described in this issue.
Here is a fiddle showing the problem: http://jsfiddle.net/cd1d1j1v/1/ .
I understand that the way to show/hide a serie is not the best one, but I'm using the angular-directive and this is how it use it...

**Comment by pawelfus** [comment]
Simple prevent series from updating points on setData (param: `updatePoints`, see [API](http://api.highcharts.com/highcharts#Series.setData)): http://jsfiddle.net/cd1d1j1v/2/

**Comment by ValentinH** [comment]
Indeed this works, but I am using highcharts-ng and the setData is called in all case (hiding or updating for instance)...

I have patched my highcharts file like this (at [this line](https://github.com/highslide-software/highcharts.com/blob/master/js/highcharts.src.js#L13316)):
```js
each(data, function (point, i) {
	if(typeof(oldData[i].update) === 'function')
		oldData[i].update(point, false, null, false);
});		 			
```

**Comment by pawelfus** [comment]
If you want to avoid editing code, then use this snippet:

    (function (H) {
        H.wrap(H.Series.prototype, 'setData', function (p, data, redraw, animation, updatePoints) {
            p.call(this, data, redraw, animation, false);
        });
    })(Highcharts)

Demo: http://jsfiddle.net/cd1d1j1v/4/

**Comment by ValentinH** [comment]
This brings the same problem as your first workaround, I can't set globally `updatePoints=false` because in some case points need to be updated and in some case they don't. Yet, Highcharts-ng have a single call to setData...
