### ISSUE TITLE
checkboxClick not handled for pie charts

### ISSUE THREAD

**Issue by adion** [highslide-software/highcharts.com#3712]
It doesn't seem that pie charts support the `checboxClick` handler even though the documentation [states otherwise](http://api.highcharts.com/highcharts#plotOptions.pie.events.checkboxClick). The [demo](http://jsfiddle.net/gh/get/jquery/1.7.2/highslide-software/highcharts.com/tree/master/samples/highcharts/plotoptions/series-events-checkboxclick/) referenced from the documentation actually points to a line series chart, so [here's a fiddle](http://jsfiddle.net/qro0dq8h/1/) that demonstrates the issue I'm seeing.

**Comment by adion** [comment]
@highslide-software Thank! Any chance of getting this merged into a release?

**Comment by highslide-software** [comment]
Yes, it will be part of the next release.

**Comment by adion** [comment]
@highslide-software Ok, great. When is that scheduled to be released?

**Comment by highslide-software** [comment]
No date is set yet, but it's a matter of weeks. Until then, you can apply
the patch to Highcharts 4.0.4.​
