### ISSUE TITLE
Range selector input from and to not responding after loosing focus

### ISSUE THREAD

**Issue by KacperMadej** [highslide-software/highcharts.com#3713]
After you change the date in one of the boxes and you click somewhere else in the chart so the box loses focus, you cannot change the date in the box anymore. You first have to click in the other box than the one you edited, then you can change the other one.

Example: http://jsfiddle.net/5mdor6qd/

**Comment by sebastianbochan** [comment]
+1

**Comment by facboy** [comment]
this is still a problem in 4.1.4.  it happens on the demo site: http://www.highcharts.com/stock/demo/basic-line

**Comment by highslide-software** [comment]
The unwanted behaviour is that the input keeps focus after clicking on the chart, outside the input. The `onblur` event is fired, but still it keeps focus. This in turn makes the `focus()` call not trigger an `onfocus` event, so the input isn't displayed again. This counter-intuitive behaviour is the same for Chrome and Firefox at least. However, if we click outside the chart, the input is really blurred to the bug doesn't happen. This fix will make sure the input is focused even if it has focus from before.

**Comment by highslide-software** [comment]
Closed by 872c94e5e
