### ISSUE TITLE
Points missing and navigator disabled

### ISSUE THREAD

**Issue by nathan1990** [highslide-software/highcharts.com#3714]
see http://jsfiddle.net/mv0ho53q/2/

We have charts which can have a 'X 'number of points at irregular date time intervals but we wish to set a default zoom of 3 months this is because there could potentially be a lot of data returned.

As you can see from the above JS fiddle the first point is missing and the navigation slider is disabled. If you remove the range selector like so 
http://jsfiddle.net/mv0ho53q/3/

All the points return but still some of the navigator buttons are disabled along with the slider. I understand that if there is no data for the button range e.g. 1M then the button is disabled but there is data for 1Y and ALL but these are disabled

**Comment by highslide-software** [comment]
It is the default value of `xAxis.minRange` that kicks in. If you set that option lower, it works: http://jsfiddle.net/highcharts/mv0ho53q/4/
