### ISSUE TITLE
how to hide the data by click the same name in different series data?

### ISSUE THREAD

**Issue by joostshao** [highslide-software/highcharts.com#3715]
http://www.highcharts.com/demo/column-stacked-and-grouped
this is the demo page.
but i change the data,
just like this:

   series: [{
            name: '张三',
            data: [5, 3, 4, 7, 2],
            stack: '男'
        }, {
            name: '李四',
            data: [3, 4, 4, 2, 5],
            stack: '男'
        }, {
            name: '张三',
            data: [2, 5, 6, 2, 1],
            stack: '女'
        }, {
            name: '李四',
            data: [3, 0, 4, 4, 3],
            stack: '女'
        }]

but when i click the name 张三，i want to hide the all data in stack['男','女‘]。

but i do not know how to implient it .....

**Comment by stephanevanraes** [comment]
You are looking for the 'linkedTo' property: http://api.highcharts.com/highcharts#plotOptions.series.linkedTo
