### ISSUE TITLE
Running setData alters original data array

### ISSUE THREAD

**Issue by highslide-software** [highslide-software/highcharts.com#3717]
Demo: http://jsfiddle.net/highcharts/75Luh3pe/

Click the buttons in succession. The second time `myBar.one` is applied, its content is replaced.

**Comment by highslide-software** [comment]
Not sure it's a bug anyway... By slicing it, performance and memory usage will suffer, and also there may be cases where implementers want to do changes on the original array. So the recommended use when referencing the same array will be to work on a copy of the array: http://jsfiddle.net/highcharts/75Luh3pe/1/

**Comment by highslide-software** [comment]
A general plugin takes care of copying both the data array and each of its point configs:

```js
    Highcharts.wrap(Highcharts.Series.prototype, 'setData', function (proceed, data, r, a, u) {
        // Make a copy of the array
        data = data.slice();
        // Make a copy of each object config
        Highcharts.each(data, function (point, i) {
            if (typeof point === 'object') {
                data[i] = Highcharts.merge(point);
            }
        });
        proceed.call(this, data, r, a, u);
    });
```

**Comment by Under-Warz** [comment]
Thanks !!!
