### ISSUE TITLE
HighStock Chart Reporting Wrong Number on Hover

### ISSUE THREAD

**Issue by lafav1jr** [highslide-software/highcharts.com#3720]
Please visit this JSFiddle for the example: http://jsfiddle.net/8s0q2L05/.

There are 2 series, Series 1 has type = line, and Series 2 has type = column. When I change both series to line, the issue is no longer there.

If you hover over October 27th, the value should read 304. However, it is reporting 53.714, which isn't even in the dataset.

**Comment by highslide-software** [comment]
You probably want to disable data grouping. See http://jsfiddle.net/highcharts/8s0q2L05/1/ .
