### ISSUE TITLE
Rotated dataLabels x-position

### ISSUE THREAD

**Issue by pawelfus** [highslide-software/highcharts.com#3723]
Example: http://jsfiddle.net/e6g6owt8/

DataLabels are translated (x-position) by a few pixels. Of course we can set `dataLabels.x` to prevent this however it would be nice to have this always properly displayed, especially when we change font size.

**Comment by highslide-software** [comment]
I agree - it would be like the axis labels where rotation center adapts.

The following demo, using a slider, shows pretty well how it is today: http://jsfiddle.net/highcharts/e6g6owt8/1/. It would be better if the text were rotated around its vertical center.

**Comment by pawelfus** [comment]
In SVG, we can use simple `alignment-baseline` attribute, like this: http://jsfiddle.net/e6g6owt8/2/ Not sure about VML, though.. In above demo, after using slider, force chart to redraw (resize window or hide/show legend) to apply alignment.

**Comment by pawelfus** [comment]
Even easier example: http://jsfiddle.net/e6g6owt8/3/

**Comment by highslide-software** [comment]
Yes, good point! Of course there are considerations to do like VML, and also where the label is aligned etc.
