### ISSUE TITLE
point.onMouseOver is not a function 

### ISSUE THREAD

**Issue by barneycarroll** [highslide-software/highcharts.com#3724]
I have a corner case where Pointer is malfunctioning: as part of `runPointActions`, [`point.onMouseOver(e)`] is invoked when it is not set. At this stage, all of the `point`'s properties are `null`.

The error occurs intermittently after I `preventDefault` on a chart's `selection` event and then manually `setExtremes` on several charts. It's more likely to occur on heavily-populated stock charts.

Sadly, I'm not able to reduce the test case.

**Comment by highslide-software** [comment]
So the point is probably destroyed at this stage. Would a simple check for that function help? Find this code: 
```js
			// a new point is hovered, refresh the tooltip
			if (point && point !== hoverPoint) {

				// trigger the events
				point.onMouseOver(e);

			}
```

... and replace it with this:
```js
			// a new point is hovered, refresh the tooltip
			if (point && point !== hoverPoint && point.onMouseOver) {

				// trigger the events
				point.onMouseOver(e);

			}
```

**Comment by barneycarroll** [comment]
@highslide-software Torstein, thanks for your swift reply. This fixes everything for me. Happy to close this unless you think it deserves more insight?
