### ISSUE TITLE
Disable sorting for series

### ISSUE THREAD

**Issue by gitnik** [highslide-software/highcharts.com#3725]
There is currently no possibility to disable sorting for series. I am running into major performance problems when using multiple thousands data points on a highstock chart. Just the stableSort function alone takes 20+ seconds

**Comment by highslide-software** [comment]
I haven't heard of any problems with this before. In [this sample](http://jsfiddle.net/highcharts/nze5jqe6/), I run three series, each with 10 000 points. According to the Chrome profiler, the stableSort method takes 1ms.

Can you give us more details to reproduce it?

**Comment by gitnik** [comment]
This was apparently caused by the chrowme dev tools. Disabling them made everything behave accordingly
