### ISSUE TITLE
Y-axis labels animation during series toggle is not correct after resize

### ISSUE THREAD

**Issue by venkat2cool** [highslide-software/highcharts.com#3726]
Issue:

If the chart is resized and then a series is toggled, the y axis label fly in from a different location and the animation looks broken. Here is a jsFiddle: http://jsfiddle.net/bqr8qLxa/

Steps to reproduce:
1. Click 'Toggle Series' a few times and observe that the animation of the y-axis labels is perfect. 
2. Now click the +/- icons to resize the chart.
3. Now try clicking the 'Toggle Series' button. You will notice that the labels fly in from left/right.

Workaround:

If the setSize method is called again after about 100ms, it works fine. 
Working jsFiddle: http://jsfiddle.net/2oot7s97/

**Comment by stephanevanraes** [comment]
Note: if you first press +, then immediately - and then start toggling you get a similar effect.  Seems that somehow the labels are moving in from their 'original' position.

**Comment by highslide-software** [comment]
Now it fails when _not_ resizing: http://jsfiddle.net/highcharts/1c83qhx7/

**Comment by venkat2cool** [comment]
I see that the code change made by Stephane has been reverted but I don't see any other change to fix this issue. Will there be a fix for this? Is there any other commit where this issue has been fixed?

**Comment by pawelfus** [comment]
You can try to use simple workaround: http://jsfiddle.net/bqr8qLxa/2/ (update old chart's width and height after all animations of resizing are done).

Internal note:
Shouldn't `fireEndResize` update that values in such case? Or these are stored on purpose?
