### ISSUE TITLE
dataLabels and tooltip zindex bug

### ISSUE THREAD

**Issue by reyhappen** [highslide-software/highcharts.com#3727]
I set:
```javascript
plotOptions: {
        pie: {
            showInLegend: true,
            allowPointSelect: true,
            cursor: 'pointer',
            dataLabels: {
                enabled: true,
                color: '#000000',
                connectorColor: '#000000'
                ,style:{
                	backgroundColor: '#f00'
                }
		,zIndex: 1
                ,useHTML: true
                ,format: '<b class="chartdatalabel ellipsis">{point.name}</b>: {point.percentage:.2f} %'
            }
      }
}
```
in Highcharts JS v4.0.4 (2014-09-02).
when the tooltip shows, the dataLabels's overridden the tooltip!!!
![cliped](https://cloud.githubusercontent.com/assets/3281751/5755874/6fd20a7e-9ce4-11e4-95f8-cd8a787e3456.jpg)

**Comment by highslide-software** [comment]
It's the `useHTML` feature again, see http://www.highcharts.com/docs/chart-concepts/labels-and-string-formatting#html

**Comment by eperret** [comment]
Is there a way to force the tooltip to be in HTML format as well?

**Comment by pawelfus** [comment]
You can render inner tooltip in html too, see [tooltip.useHTML](http://api.highcharts.com/highcharts#tooltip.useHTML). 

However, this will still render background/border/shadows in SVG. I suggest to disable this options and create them in HTML tooltip formatter. Unfortunately pointer will be lost.
