### ISSUE TITLE
Area and Bar charts adding additional day to series offsetting data

### ISSUE THREAD

**Issue by harvolev** [highslide-software/highcharts.com#3730]
Creating an Area or Bar chart with an odd number of days for XAxis labels, greater than 8 it seems, the chart will add an extra day causing the actual series data to be drawn with a gap from the edge of the chart. This makes the graph appear inaccurate while the data from the series is loaded with the correct dates the labels give that extra range and no data in the chart for those added dates.

I would like to only have labels for dates that are in the series added.

**Comment by highslide-software** [comment]
You didn't give a live sample, but I think I understand your problem. 

The thing is that there isn't a one-to-one relation between points and labels on the datetime X-axis. It becomes obvious when you have lots of points: http://www.highcharts.com/demo/line-time-series.

The line series only looks at the min and max, and by default uses the `tickPixelInterval` option to place ticks in the right position. 

You have lots of options on the axis to increase control. For instance, you can set the `tickInterval` to one day, and add `min` and `max` options for the `xAxis`. 

But if you want the labels to display one-to-one to the points, you need to use a category axis. Read more at http://www.highcharts.com/docs/chart-concepts/axes => What axis type should I use.
