### ISSUE TITLE
Polar Chart :: Setting width for labels

### ISSUE THREAD

**Issue by simon2k** [highslide-software/highcharts.com#3731]
Hi guys, 

I have an issue. The idea is that I'd like to set width for the labels displayed next to the circle of the polar chart. I tried to apply styles for the labels, but it doesn't work: by setting "300px", not just number: 300.

By having a lot of labels, the chart is getting quite unreadable. Here's working example of the issue: http://jsfiddle.net/acm1vneq/

**Comment by stephanevanraes** [comment]
The `width`setting you are trying to use is not defined so logically it does not do anything. You could extend Highcharts and capture the result of the method that defines the bounding box for the label and have the result overwritten with a predefined width. 
Roughly like this: http://jsfiddle.net/stephanevanraes/acm1vneq/1/

**Comment by simon2k** [comment]
Thanks!

**Comment by pawelfus** [comment]
It does work when we set directly `step: 1`, examples:

- http://jsfiddle.net/acm1vneq/2/
- http://jsfiddle.net/acm1vneq/3/
