### ISSUE TITLE
Add item(s) to export menus 

### ISSUE THREAD

**Issue by ValentinH** [highslide-software/highcharts.com#3735]
Currently, I only see a way to override the default export menus: http://jsfiddle.net/gh/get/jquery/1.7.2/highslide-software/highcharts.com/tree/master/samples/highcharts/exporting/buttons-contextbutton-menuitems/ .

I think it would be really great to be able to simply add some entries.

So far I have tried to do this using this kind of code:
```js
Highcharts.getOptions.exporting.buttons.contextButton.menuItems.push({
    separator: true
});
Highcharts.getOptions.exporting.buttons.contextButton.menuItems.push({
    text: 'Download data as CSV file',
    onclick: self.downloadCSVData
});
```
but it adds the menu item to all my charts (of course) and I would like to add it to only one of them...

How could this be done using to current code?

**Comment by highslide-software** [comment]
Hi,

This is our bug tracker. For general tech support, please see www.highcharts.com/support.
