### ISSUE TITLE
HTML for categories with no space in text in columnrange charts is missing the surrounding tspan tag

### ISSUE THREAD

**Issue by asftissot** [highslide-software/highcharts.com#3736]
See this jsfiddle: http://jsfiddle.net/wbja5hkj/3/.

The chart has 4 categories on the x-axis.  3 contains spaces in them and one does not.  The HTML for the one that does not have a space gets generated wihtout a surrounding tspan tag which causes the style defined in the CSS for ".highcharts-axis-labels tspan" not to be picked up. 

If you add a space in label3 (e.,g 'label 3') in the jsfiddle, the tspan tag gets added and the styling gets picked up properly. If you remove the space in the other labels, the tspan gets removed and the styling is not applied to them.

**Comment by highslide-software** [comment]
The `tspan` is skipped because it is not needed for single words. For styling, you should skip the `tspan` selector alltogether: 

http://jsfiddle.net/highcharts/wbja5hkj/4/

**Comment by asftissot** [comment]
That’s not very coder friendly.  The html used to display elements should be consistent for all elements.  If you consider that a feature, that’s not a good one.

Florence
