### ISSUE TITLE
Bar chart series order mismatches vertical legend order

### ISSUE THREAD

**Issue by dylanPowers** [highslide-software/highcharts.com#3737]
Using your [basic bar chart example](http://jsfiddle.net/gh/get/jquery/1.9.1/highslide-software/highcharts.com/tree/master/samples/highcharts/demo/bar-basic/), you can see that the vertical legend item order is reversed from the ordering of the charted bars. I think you'll agree that it would be easier to digest the data if the item ordering matched.

**Comment by stephanevanraes** [comment]
The legend is independent from the type of chart and will always start with the first series (in a vertical legend this is on top) while bar series are renderered bottom-up.  The legend should be rendered consistent over all types regardless of the type.

You can however change the order of the items in the legend using the `reversed: true` option,
http://api.highcharts.com/highcharts#legend.reversed

**Comment by highslide-software** [comment]
It is also complicated by features like reversed axes and positive/negative stacks.

**Comment by dylanPowers** [comment]
Thanks guys. I missed seeing the reversed option which works for my purposes. Maybe the bar series should be rendered top-down? I suppose that's the real issue here.

**Comment by sebastianbochan** [comment]
+1

**Comment by highslide-software** [comment]
The thing is that the X axis in a bar chart is reversed by default, so the categories are reversed but the bars within each category is not. Until the fix for #1251, a reversed axis caused reversing of bars within the group, but that changed, probably inintentionally. I am creating a new fix for both issues.

**Comment by sebastianbochan** [comment]
Seems that still incorrect for 3d charts: http://jsfiddle.net/ckzv754n/7/

**Comment by sebastianbochan** [comment]
Feedback from user:

"*1. The y-axis order for bar chart values "looks" incorrect and is not the
behaviour that most users will expect. For example, the horizontal bar
order uses bottom-to-top order. This is theoretically correct from an axis
ordering perspective as the values are plotted going upwards from the
y-axis original (zero). However this is not what most users expect and will
be interpreted as not correct.*


*2. Additionally the plot order for individual bar graph sub-items within a
category group is incorrect, and specifically does not match the bar
category group, which is correctly plotted in top-to-bottom order.*
*This can be seen in the example at **http://jsfiddle.net/Akixi/**ckzv754n/*
<http://jsfiddle.net/Akixi/ckzv754n/>* where the category items for Apples,
Oranges, Pears, etc. are ordered correctly in top-to-bottom order but the
sub-items for John, Joe, etc., are shown in the wrong order.*


*3. Microsoft Excel also used to draw bar graphs incorrectly with the
bottom-to-top behaviour. Many users disliked this functionality (though one
should note that at least Excel's bar category/group order was consistent
with sub-item order) and MS added options to reverse the order (see
attached). More information on this can be seen here: *
*http://peltiertech.com/bar-**chart-categories-backwards/*
<http://peltiertech.com/bar-chart-categories-backwards/>*.*
"

**Comment by highslide-software** [comment]
As far as I can understand this now works as the user expects (after the fix), but we still have the problem with the Z index on 3D charts?

**Comment by highslide-software** [comment]
I had to revert the fix. A full fix needs to handle the Z index of the 3D columns as well.
