### ISSUE TITLE
Highmaps county map for one state

### ISSUE THREAD

**Issue by infernobass7** [highslide-software/highcharts.com#3746]
I don't know if there is a better way but I am having trouble getting a county map for just one state to show up. I used the example for county and modified it to show only the counties of Maryland. However, everything works except one error that get and I cannot find why I am getting it. It is "Cannot read property 'path' of undefined Highmaps.js 283" 

Here is a link to the page that I am getting this issue: http://www.uppershoreregionalcouncil.org/youthdashboard/working/map.php

**Comment by highslide-software** [comment]
Here is how to set up the Maryland map: http://jsfiddle.net/gh/get/jquery/1.11.0/highslide-software/highcharts.com/tree/master/samples/mapdata/countries/us/us-md-all

PS: This is our issue tracker. For general support issues, please see www.highcharts.com/support.
