### ISSUE TITLE
Changing Gauge max, moves the max label around.

### ISSUE THREAD

**Issue by bthivierge** [highslide-software/highcharts.com#3747]
When I update my max, the max label moves around the Gauge. 
Let the example play for a few updates.
http://jsfiddle.net/rS74J/1/

**Comment by highslide-software** [comment]
What happens is that ticks are placed on round numbers, while your axis not necessarily ends on a round number. In order to have the label placed excactly on axis.max, use the `tickPositioner` callback: 

http://jsfiddle.net/highcharts/rS74J/2/
