### ISSUE TITLE
Documentation error/mismatch for plotbands

### ISSUE THREAD

**Issue by devldevelopment** [highslide-software/highcharts.com#3753]
According to:
http://www.highcharts.com/docs/chart-concepts/plot-bands-and-plot-lines

PlotBands are defined as:
xAxis: {
  ...,
  plotBands: {
    color: 'orange', // Color value
    from: 3, // Start of the plot band
    to: 4 // End of the plot band
  },
  plotLines: {
    color: 'red', // Color value
    dashStyle: 'longdashdot', // Style of the plot line. Default to solid
    value: 3, // Value of where the line will appear
    width: 2 // Width of the line    
  }
}

Which causes errors particularly in angular integration.

But they should be defined in an array:
http://api.highcharts.com/highcharts#xAxis.plotBands 

 plotBands: [{...}]

**Comment by highslide-software** [comment]
Thanks for reporting, it's fixed now.
