### ISSUE TITLE
Don't set style="cursor: ew-resize" on `<body>` during scrollbar drag

### ISSUE THREAD

**Issue by philfreo** [highslide-software/highcharts.com#3755]
The mouse pointer/cursor is the left-right resize icon when dragging the horizontal scrollbar.

I wanted to disable this since it doesn't correspond with native OS/browser scrollbar behavior.

I tried in CSS:

```
    rect.highcharts-background,
    g.highcharts-scrollbar {
        cursor: default;
    }
```

However it looks like Highstock sets `style="cursor: ew-resize"` on `<body>` during scroll. I would like to stop this!

**Comment by highslide-software** [comment]
I changed this behaviour with 200d38b64c. Now the ew-resize cursor only applies to the shaded area on the navigator plot, not the scrollbar itself. Also the cursor on the navigator plot can be disabled by CSS: 
http://jsfiddle.net/highcharts/g1zk19ot/
