### ISSUE TITLE
Column chart Scale re calculates after legend is enabled disabled for first time

### ISSUE THREAD

**Issue by salunkenagesh14** [highslide-software/highcharts.com#3757]
The scale of column chart re-calculates when the legend is enabled and disabled for the first time.

Example : http://jsfiddle.net/j91f4ubz/1/

**Comment by highslide-software** [comment]
The axis ticks uses different approximations so the tick positions are not guaranteed to be the same for the initial rendering and subsequent redraws. In your specific case, it is better with the Highcharts 4.1 candidate, but other cases may be different: http://jsfiddle.net/highcharts/j91f4ubz/2/
