### ISSUE TITLE
Heatmap - series.setData()

### ISSUE THREAD

**Issue by pawelfus** [highslide-software/highcharts.com#3758]
Demo: http://jsfiddle.net/1sb8xguk/2/

Simply click on the button, when we have different number of points, extremes are miscalculated. 

Workaround is to call `setExtremes(min-0.5, max+0.5)`, for example: http://jsfiddle.net/1sb8xguk/3/

**Comment by yeoupooh** [comment]
I had the same problem.
http://jsfiddle.net/yeoupooh/nmfo1vg9/

**Comment by highslide-software** [comment]
A simpler workaround is to define the series' `pointRange`: http://jsfiddle.net/1sb8xguk/4/
