### ISSUE TITLE
Exported charts distorted with negative colors

### ISSUE THREAD

**Issue by highslide-software** [highslide-software/highcharts.com#3759]
Demo: http://jsfiddle.net/highcharts/rocxb9zv/

In the export menu, download as PNG. The axis labels and markers are misplaced. The title and the legend is not visible, probably also misplaced outside the viewport.

Now if you download to SVG, it looks good. This indicates that the bug lies in the way PhantomJS renders the SVG, influenced by some of the tranformations and clipping done for negative colors.

We may fix the problem either in the Phantom script, or in Highcharts by defining the clip in a way that does not throw off Phantom. 

The issue is increasingly relevant with Highcharts 4.1 and the new Zones feature.

**Comment by gvaartjes** [comment]
Confirmed that exporting  http://jsfiddle.net/highcharts/rocxb9zv/ with the export server running phantomjs v2 results in a correct image.

**Comment by highslide-software** [comment]
Duplicate of #3649

**Comment by frazsundal** [comment]
Any work around or fix for this issue?
