### ISSUE TITLE
Drilldown chart breaks when drilling 2x down and 2x up when used with 3+ series

### ISSUE THREAD

**Issue by meineckej** [highslide-software/highcharts.com#3773]
Example: http://jsfiddle.net/9vfuy19b/
To reproduce: click on "Animals", on Cats" and then 2x the back-button -> messed up chart, errors on console
Environment: Chrome
I have observed that issue in our application and then reproduced it jsfiddle. The issue does not seem to appear with just 2 series, or with just drilling down and up once.

**Comment by highslide-software** [comment]
This is already fixed in dev branch: http://jsfiddle.net/highcharts/9vfuy19b/1/

**Comment by meineckej** [comment]
Thanks! Can you give me a hint to how it was fixed / the commit? Can I patch 4.0.4 to fix this for us until the next release?

**Comment by highslide-software** [comment]
If you do a seach for drilldown in the issues you'll find it. Look for recently closed issues.
