### ISSUE TITLE
Transparent marker not moved after zooming

### ISSUE THREAD

**Issue by kuflash** [highslide-software/highcharts.com#3774]
Hi! For example: http://jsfiddle.net/kuflash/n6buh1o6/2/
[First state (not zooming).](https://www.dropbox.com/s/om59iyao7l88b23/_1.png?dl=0) Transparent marker correctly located
[Second state (is zooming).](https://www.dropbox.com/s/1btftcz200tcbiy/_2.png?dl=0) Transparent marker not correctly located
On our project is completely transparent marker leaves [unclear where](https://www.dropbox.com/s/3wbyyn5vkq00uso/_3.png?dl=0)
I think this is a bug. Hope you fix it.

**Comment by pawelfus** [comment]
Thanks for reporting! Indeed, it's a bug, we have reported it also here: #3916
