### ISSUE TITLE
Gauge - dial looses some of style options after point.update

### ISSUE THREAD

**Issue by KacperMadej** [highslide-software/highcharts.com#3779]
In gauge type series - dial looses some of style options (colors, border width) after point.update

Example: http://jsfiddle.net/xvydwz9o/

**Comment by pawelfus** [comment]
Looks fine on a master branch: http://jsfiddle.net/xvydwz9o/1/

**Comment by highslide-software** [comment]
Probably duplicate of #4284.

**Comment by KacperMadej** [comment]
Not working for master branch: http://jsfiddle.net/xvydwz9o/2/

**Comment by highslide-software** [comment]
Workaround: Set the new value as an integer, not in an object syntax.
