### ISSUE TITLE
Feature request: tooltip formatter templates instead of function for better usage with JSON

### ISSUE THREAD

**Issue by nordfjord** [highslide-software/highcharts.com#3790]
Hey, I love using your software, There is however one caveat I have run into with regards to tooltip#formatter. I'm trying to host chart configs server side which means they get sent to the client in a JSON format. JSON being a data interchange format does not support functions.

In my current use case the existence of some sort of rudimentary templating would solve all my problems.

for example
```js
"tooltip": {
    "formatter": function(){
        return this.series.yAxis.categories[ point.y ] + ' between <b>' + this.series.xAxis.categories[ point.x ] '</b> and <br> there were <b>' + this.point.value + '</b> sessions started';
}
```

might be better expressed as

```js
"tooltip": {
    "formatter": "<%= series.yAxis.categories[ point.y ] %> between <b><%= series.xAxis.categories[ point.x ] %></b> and <br> there were <b> <%= point.value %></b> sessions started"
}
```

Any thoughts?

**Comment by highslide-software** [comment]
Thanks for your thoughts. We already have templating, see the `tooltip.headerFormat`, `tooltip.pointFormat` and `tooltip.footerFormat` options.

**Comment by nordfjord** [comment]
Alright, I've been trying to use those, but I think that the feature really does need work, I for instance don't have access to the Math object and bracket notation does not work in `tooltip.pointFormat` meaning I can't simply replace my formatter functions with a template when transitioning to JSON.

Regards,
Einar
