### ISSUE TITLE
Dealing with large numbers on yAxis

### ISSUE THREAD

**Issue by Vangi** [highslide-software/highcharts.com#3793]
As I understood (http://stackoverflow.com/questions/28147523/dealing-with-large-numbers-on-yaxis) there is a limitation in Highstock for numbers bigger than 1.7976931348623157e+119. Nothing is displayed into the chart (http://jsfiddle.net/s6gscza2/2/). Also you can see the error in the demo:

```
Uncaught RangeError: toFixed() digits argument must be between 0 and 20 at highstock.js:11 
Da at highstock.js:12 
Ma at highstock.js:220 
Ba.tooltipFormatter at highstock.js:386 
Ba.tooltipFormatter at highstock.js:152 
(anonymous function) at highstock.js:23 
each.Array.forEach.g at highstock.js:152 
Jb.defaultFormatter at highstock.js:154 
Jb.refresh at highstock.js:160 
$a.reset at highstock.js:195 
ya.redraw at highstock.js:206 
ya.setSize at highstock.js:204 d
```

**Comment by highslide-software** [comment]
The fix doesn't make your demo work, as your last point is at `Number.MAX_VALUE`. However, if you reduce it to +e308 it works: http://jsfiddle.net/highcharts/s6gscza2/4/
