### ISSUE TITLE
Highcharts has missing markers at the top for very specific heights

### ISSUE THREAD

**Issue by dgucwa** [highslide-software/highcharts.com#3799]
http://jsfiddle.net/wa3c0c9u/1/

The three charts in my link are almost exactly the same, except they have heights of 250, 251, and 249 respectively.

Depending on which browser I use, sometimes the line markers on the 100-line will be missing on one of the 3 graphs.

When I look at it in Chrome 37.0.2062.120 on Ubuntu, I see that issue with the first graph only. In Firefox 27.0.1, I see the issue with the second graph only.

**Comment by pawelfus** [comment]
Works with latests Chrome and Firefox - could you confirm?

**Comment by highslide-software** [comment]
Closing this, please reopen if new information comes in.
