### ISSUE TITLE
PieChart adjustMargins causes an error

### ISSUE THREAD

**Issue by yonzzu** [highslide-software/highcharts.com#3800]
Line 10385 in latest highcharts.js from Github causes an error:
alignment = options.align[0] + options.verticalAlign[0] + options.layout[0];
Uncaught TypeError: Cannot read property '0' of undefined

options has value "false" so it is not able to get values for align, verticalAlign nor layout. 

Stack trace:
Legend.adjustMargins (highcharts.js:10385)
Chart.getMargins (highcharts.js:11507)
Chart.render (highcharts.js:11984)
Chart.firstRender (highcharts.js:12187)
Chart.init (highcharts.js:10914)
Chart (highcharts.js:10817)

**Comment by pawelfus** [comment]
Why `options` has value `false` ? To disable legend you should set `legend.enabled = false`.

**Comment by yonzzu** [comment]
Good point, it seems to work after that change. 

So previous code:
legend: false,

Updated code (that works):
legend: {
enabled: false
}

The main difference here is that both ways have worked so far, but the old(?) way causes this error with the latest version. 

Here's a jsFiddle about the issue.
http://jsfiddle.net/yonzzu/k2ohtg4f/

**Comment by pawelfus** [comment]
`legend.enabled` option exists since I remember, there wasn't "old" way for disabling legend. See [docs](http://api.highcharts.com/highcharts#legend.enabled).
