### ISSUE TITLE
Pie chart gradient position not recalculated on resize

### ISSUE THREAD

**Issue by saibotsivad** [highslide-software/highcharts.com#3801]
**To reproduce**

Using the [JSFiddle](http://jsfiddle.net/gh/get/jquery/1.9.1/highslide-software/highcharts.com/tree/master/samples/highcharts/demo/pie-gradient/) from the Highcharts demo of a pie chart with a gradient, change the stops to something more drastic (for easier visibility):

    stops: [
        [0, Highcharts.Color(color).brighten(0.7).get('rgb')],
        [1, Highcharts.Color(color).brighten(-0.7).get('rgb')]
    ]

Change the browser window size so that the pie chart is redrawn at different sizes.

**What happens**

The position of the gradient stays absolute positioned within the element `container`. E.g.:

![screen shot 2015-02-10 at 3 09 42 pm](https://cloud.githubusercontent.com/assets/91254/6136565/4aae838c-b137-11e4-998e-6c4d96948e27.png)
![screen shot 2015-02-10 at 3 09 59 pm](https://cloud.githubusercontent.com/assets/91254/6136564/4aab1364-b137-11e4-938f-0471b2de7b03.png)

**What I expect to happen**

The center of the gradient should be recalculated whenever the pie chart is resized, to position and size itself relative to the circle.

**Additional details**

Highcharts JS v4.0.4 (2014-09-02) (from the JSFiddle example)
Chrome 40.0.2214.94 (64-bit)
Mac OSX 10.10.2 (retina display)

Possibly related to https://github.com/highslide-software/highcharts.com/issues/1695

**Comment by ti-dev** [comment]
I also have this issue, so it would be great if there will be a fix soon.

**Comment by highslide-software** [comment]
Minimal demo: http://jsfiddle.net/highcharts/bLqpt3gk/

**Comment by highslide-software** [comment]
_Internal note:_

The `setRadialReference` method has to be called on the graphic on update in the PieSeries.drawPoints method. In addition to that, the fill must be set again in order to re-compute the gradient.

**Comment by sebastianbochan** [comment]
+1

**Comment by highslide-software** [comment]
Demo with the fix applied: http://jsfiddle.net/highcharts/bLqpt3gk/1/

**Comment by ti-dev** [comment]
This fix is not included in Highcharts 4.1.8? It is not mentioned in the changelogs and the issue still occurs in my environment with Highcharts 4.1.8. Will it be included in the next release?

**Comment by highslide-software** [comment]
Sorry for that. For some reason the commit was accidentally done on a side branch. It is now cherry-picked to the master.
