### ISSUE TITLE
3d charts - huge height issue

### ISSUE THREAD

**Issue by sebastianbochan** [highslide-software/highcharts.com#3814]
Let's compare two charts:
- http://jsfiddle.net/tpbosg1x/
- http://jsfiddle.net/tpbosg1x/1/
The first one is our of range and labels are misaligned.

**Comment by stephanevanraes** [comment]
3d bars are currently not supported, only pie, scatter and regular column

**Comment by pawelfus** [comment]
Can we have extra info about supported types? I know we have it the [docs](http://www.highcharts.com/docs/chart-concepts/3d-charts), but short note in the [API](http://api.highcharts.com/highcharts#chart.options3d) would be great :)

**Comment by highslide-software** [comment]
Also, 3D rendering should be skipped altogether in cases where inversion is not supported.
