### ISSUE TITLE
Tooltip does not work for dynamically added points

### ISSUE THREAD

**Issue by eric-2d** [highslide-software/highcharts.com#3816]
I have a live updating Highstock chart and the tooltip cease to function amost immediately.
I noticed the same behavior in the Highchart demo with the [following fiddle]
(http://jsfiddle.net/gh/get/jquery/1.9.1/highslide-software/highcharts.com/tree/master/samples/highcharts/demo/dynamic-update/).
Looks like the tooltip will not work for new points IF the tooltip is visible when a new point is inserted.
Tested under Firefox(35.0) and Chrome (40.0.2214.111 (64-bit)) for Linux (Fedora 20)

Interestingly enough, [this fiddle] (http://jsfiddle.net/owk1Lere/2/) does not have the problem.

The difference between the two seems to be series.addPoint() vs series.update().

Unfortunately I need to use addPoint().
Final observation: the tooltip reappears after a certain amount of time, only to disappear again a few seconds later.

**Comment by jonathanbull** [comment]
I'm also seeing this in the latest version of the highchart and highstock libraries. The bug seems to occur intermittently on redrawn data.

**Comment by eric-2d** [comment]
Good point about the latest version.
Tested with version 4.0 and the same example [works fine] (http://jsfiddle.net/85tw1dsg/)
I can do with 4.0.

**Comment by eric-2d** [comment]
Similarly I pointed my project to "http://code.highcharts.com/stock/1.2.4/highstock.js", and the problem is gone.

**Comment by Joshua-F** [comment]
You can see the problem happening on the [Demo](http://www.highcharts.com/stock/demo/dynamic-update) as well.
