### ISSUE TITLE
Highstock ordinal not working 2.1.0

### ISSUE THREAD

**Issue by it-can** [highslide-software/highcharts.com#3818]
Hi,

when updating to the latest highstock, it seems that the ordinal setting is not working anymore:

Latest version 2.1.0:
http://jsfiddle.net/vo6tgf74/

Version 2.0.4:
http://jsfiddle.net/vo6tgf74/1/

**Comment by highslide-software** [comment]
Fails since 98daef9

@stephanevanraes Probably the new flag, `postTranslate`, isn't set properly.
