### ISSUE TITLE
No API documentation for axis.autoRotation

### ISSUE THREAD

**Issue by tomascassidy** [highslide-software/highcharts.com#3820]
The latest changelog for 4.1.0 mentions a new setting axis.autoRotation and links to http://api.highcharts.com/#xAxis.autoRotation for documentation.  This does not yet exist on the API site.

**Comment by highslide-software** [comment]
Sorry for that! The correct link would be http://api.highcharts.com/highcharts#xAxis.labels.autoRotation.
