### ISSUE TITLE
Tooltip fails with script error when chart contains flag series

### ISSUE THREAD

**Issue by tomascassidy** [highslide-software/highcharts.com#3821]
Example: http://jsfiddle.net/gh/get/jquery/1.9.1/highslide-software/highcharts.com/tree/master/samples/stock/demo/flags-general/

This is using the flags demo fiddle from http://www.highcharts.com/stock/demo/flags-general.

Browser: Firefox 35.0.1 Ubuntu 14.04 x64

When the chart has a flag series, the tooltip will fail to show on mouseover.

The browser console is reporting an error at https://github.com/highslide-software/highcharts.com/blob/master/js/highstock.src.js#L9543.

```TypeError: kdpoints[i] is undefined```

This appears to be caused by https://github.com/highslide-software/highcharts.com/blob/master/js/highstock.src.js#L9518, as ```s.searchPoint(e)``` is returning undefined for the flag series.

**Comment by bazineta** [comment]
This seems not to be constrained to flags; we also see it on a line chart.  In our case, the issue appears when the line chart is added as a second series to a preexisting area spline chart.

**Comment by stephanevanraes** [comment]
@bazineta: That does not sound like the same bug, maybe it is related to #3816, if not please create a seperate issue

@tomascassidy: we are looking into the problem, for the moment, a possible workaround is too set tooltip.shared to false

**Comment by gmisiolek** [comment]
This haven't fix my issue. Or it's another related issue ;)

I'll try to describe this:

I use Highstock and I have two series of data 
- one is for example from 01-01-2014 to 31-12-2014
- one is for example from 01-07-2014 to 31-12-2014

And here we go:
- if I set zoom from 01-11-2014 to 01-12-2014 it's all right, all works (I see all series of data)
- if I set zoom from 01-06-2014 to 01-08-2014 it's also all right
- but if I set zoom from 01-05-2014 to 01-06-2014 I see only one series and on hover this error appears... Second series is `undefined` in kdpoint array.

So in my opinion adding ` && defined(s.searchPoint(e))` to line 9518 fixes this issue.

What do you think, guys?
