### ISSUE TITLE
[Docs] Broken JSFiddle Link for Zones

### ISSUE THREAD

**Issue by markmsmith** [highslide-software/highcharts.com#3822]
For the docs for the new Zones feature in 4.1 has a broken link.
1) Go to http://www.highcharts.com/docs/chart-concepts/series#zones
2) Click on the 'Try it here' link below the example chart
3) You get an error from jsfiddle: 
Github responded with 404
https://api.github.com/repos/highslide-software/highcharts.com/contents/samples/highcharts/series/color-zones-simple/e
Is your URL valid?

**Comment by stephanevanraes** [comment]
The link was indeed broken, it is fixed now. Thanks for reporting.

**Comment by markmsmith** [comment]
There's also a contradiction the in description before the example chart, where it says:
"By default zoning is done on the xAxis"
while the API docs have the default zoneAxis as y:
http://api.highcharts.com/highcharts#plotOptions.series.zoneAxis

Very cool feature though, keep up the good work guys :)

**Comment by stephanevanraes** [comment]
The API is correct, the default is indeed the yAxis, I have corrected the article.

**Comment by markmsmith** [comment]
Wow, impressive turn around time on both of these, you guys are awesome! :)
