### ISSUE TITLE
Pie Chart does not work with highstock 2.1

### ISSUE THREAD

**Issue by thomdask** [highslide-software/highcharts.com#3823]
After the latest release of highcharts/highstock it seems that the highstock js file is not a superset of highcharts anymore since the pie chart generates a js error.
The following jsfiddle is the example from the demo page used with the highstock instead of highcharts.
http://jsfiddle.net/zL01rs40/

The error reported is Uncaught TypeError: Cannot read property 'options' of undefined

**Comment by highslide-software** [comment]
Duplicate of #3817
