### ISSUE TITLE
Uncaught TypeError: Cannot read property 'plotX' of undefined in HighStock

### ISSUE THREAD

**Issue by it-can** [highslide-software/highcharts.com#3824]
Getting this error: highstock.js:9543 (I used the github version)

```
Uncaught TypeError: Cannot read property 'plotX' of undefined  
```

http://jsfiddle.net/xqjt4dz3/1/

"One" is enabled by default, and works perfectly. But when you select "Two" and hover over points it will generate the error.

**Comment by ewaltman** [comment]
:+1:
