### ISSUE TITLE
setData throw error with pie chart in version 4.1.0

### ISSUE THREAD

**Issue by ipoly** [highslide-software/highcharts.com#3828]
The official demo: [http://jsfiddle.net/gh/get/jquery/1.7.2/highslide-software/highcharts.com/tree/master/samples/highcharts/members/series-setdata-pie/]

will throw this error:

    Uncaught TypeError: Cannot read property 'names' of undefined

**Comment by stephanevanraes** [comment]
it works with the latest version on github 
http://jsfiddle.net/1o11nwar/

**Comment by ipoly** [comment]
Thanks @stephanevanraes.

**Comment by highslide-software** [comment]
Fixed since 82f63459fe. The latest release, 4.1.1, includes this fix.
