### ISSUE TITLE
After updating "xAxis" categories empty (Data defined in a HTML table)

### ISSUE THREAD

**Issue by ATLANT1S** [highslide-software/highcharts.com#3830]
chart.xAxis[0].update({labels: {rotation: -90}});
thereafter categories empty

Example: http://jsfiddle.net/34Lcs27z/1/

**Comment by highslide-software** [comment]
Simplified to not using data module. It's a problem with category axis: http://jsfiddle.net/highcharts/34Lcs27z/3/
