### ISSUE TITLE
Highcharts.version still reports 4.0.4 even though I'm using 4.1.1

### ISSUE THREAD

**Issue by seiyria** [highslide-software/highcharts.com#3831]

**Comment by pawelfus** [comment]
For me works properly: http://jsfiddle.net/mozsvLob/

**Comment by highslide-software** [comment]
Closing this, please provide a live demo if it's not resolved by cache issues

**Comment by seiyria** [comment]
It's because of highcharts-all not having been updated: https://github.com/highslide-software/highcharts-release/blob/master/highcharts-all.js

**Comment by highslide-software** [comment]
The `highcharts-all.js` file was something we used internally for Highcharts Cloud, I'm sorry it was included in the repo.
