### ISSUE TITLE
Format strings no longer accept thousands separator

### ISSUE THREAD

**Issue by instanttim** [highslide-software/highcharts.com#3833]
Format strings like:
    pointFormat: "Value: {point.y:,.0f} mm"
No longer are respecting the "," portion meant to specify the thousands separator.

The demo linked to in the documentation: http://jsfiddle.net/highcharts/rmTWS/
It worked in 4.0.4: http://jsfiddle.net/jqnLp2p4/

But has been broken in 4.1.0 and 4.1.1.

**Comment by highslide-software** [comment]
It still works, but the default thousandsSeparator is now a single space. See http://api.highcharts.com/highcharts#lang.thousandsSep . 

The rationale behind this choice is language compatibility and standardization. Quoting from Wikipedia:
> The convention for digit group separators varies but usually seeks to distinguish the delimiter from the decimal mark. Typically, English-speaking countries employ commas as the delimiter—10,000—and other European countries employ periods or spaces: 10.000 or 10 000. Because of the confusion that can result in international documents, the withdrawn SI/ISO 31-0 standard advocates the use of spaces[13] and the International Bureau of Weights and Measures and International Union of Pure and Applied Chemistry advocate the use of a "thin space" in "groups of three".[14][15] Within the United States, the American Medical Association's widely-followed AMA Manual of Style also calls for a thin space.[12] In some online encoding environments (for example, ASCII-only) a thin space is not practical or available, in which case a regular word space or no delimiter are the alternatives. The Metrication Board proposed this system for the United Kingdom and, while it is not universally adopted, it is standard within the country's construction industry.

**Comment by instanttim** [comment]
It's kinda confusing that the char you use in the format string is literally a comma "," yet it's an abstract for the thousands separator specified elsewhere. It would be more clear if the format syntax didn't appear to be literal.

**Comment by highslide-software** [comment]
I see your point, but the format syntax is borrowed from Python, which actually does the same. It is defined by a comma in the format, but what is actually inserted depends on the culture.

**Comment by instanttim** [comment]
The more I thought about it, the more I realized the .0f portion of the syntax has the same issue for countries/languages that use a comma for the decimal separator. 

Coincidently, have you ever thought about having a property for "lang" that bundles up all the conventions for a given region or language? In OS X you set a region and all the sub-options are set to a reasonable default for where you live. You can of course override them individually.

![screen_shot_2015-02-19_at_9_29_16_am](https://cloud.githubusercontent.com/assets/6156678/6272111/2c3639c4-b81a-11e4-841c-bdce85b0ab47.png)
