### ISSUE TITLE
Waterfall yAxis.min setting causes chart to render incorrectly

### ISSUE THREAD

**Issue by bschnelle** [highslide-software/highcharts.com#3835]
When setting the yAxis min property to something other than 0 the chart no longer renders correctly.  It looks like this same issue was addressed previously, but I am currently experiencing what I believe is the same problem.

Old issue: https://github.com/highslide-software/highcharts.com/issues/2241
fiddle: http://jsfiddle.net/v38sfzyu/2/

**Comment by highslide-software** [comment]
This is also affected by #3839. Now that that one is fixed, the waterfall doesn't look so bad during animation. http://jsfiddle.net/highcharts/v38sfzyu/3/

**Comment by bschnelle** [comment]
Awesome, thanks for the quick response.
