### ISSUE TITLE
Heatmap: Cells displaying blanks - tooltip shows data exists

### ISSUE THREAD

**Issue by SamProtas** [highslide-software/highcharts.com#3837]
I have a 16 X 16 heatmap that's been working properly for well over a month. I noticed today there is a display issue where roughly half of the cells are shown blank.

http://jsfiddle.net/q69ngL9k/1/

The provided tooltips indicate the data is being properly received and understood by highcharts.js/heatmap.js so I believe this is a rendering issue.

I only noticed the issue today but it may have been introduced in the 2015-02-16 or 2015-02-17 changes. I have confirmed that this issue appeared on a dataset that has not changed between when this solution worked and when the display issue was introduced.

**Comment by highslide-software** [comment]
It's the new feature, `dataLabels.allowOverlap`. You can set it to true to go back to how it was: http://jsfiddle.net/highcharts/q69ngL9k/2/.

But the  algorithm also seems to be too agressive when detecting overlap in this case, so we'll mark it a bug.
