### ISSUE TITLE
isIntermediateSum in Waterfall chart not workig correctly since last week

### ISSUE THREAD

**Issue by fisi2000** [highslide-software/highcharts.com#3840]
Since last week the isIntermediateSum is not working correctly.

As you see in the chart the intermediateSum is posititioned correctly but showing the value of the total sum. 

![unbenannt](https://cloud.githubusercontent.com/assets/11056822/6244126/469224ac-b74f-11e4-8a43-2209acaed6c5.PNG)

Strange thing is, that in the source code the value (y: -104) is correctly but this is not shown in the chart. What's the problem here?

Source code:
{
name: 'IntermediateSum',
isIntermediateSum: true,
y: -104     // chart showing 1246          
}

**Comment by fisi2000** [comment]
![unbenannt](https://cloud.githubusercontent.com/assets/11056822/6244103/e8bddb5a-b74e-11e4-826f-efe177bdcbe6.PNG)

**Comment by highslide-software** [comment]
First thing that comes to mind is that the intermediate sum point shouldn't have a y value. And the point you circled doesn't look like an intermediate point. The yellow column does. See http://jsfiddle.net/gh/get/jquery/1.9.1/highslide-software/highcharts.com/tree/master/samples/highcharts/demo/waterfall/.

If you disagree with this, please set up an online demo showing your problem. It can be done by editing the fiddle above and clicking Save.

**Comment by stephanevanraes** [comment]
The API states for **isIntermediateSum** : *Waterfall series only. When this property is true, the points acts as a summary column for the values added or substracted since the last intermediate sum, or since the start of the series. The y value is ignored. Defaults to false*

It does not do this, instead it makes the sum up to that point 8as if no previous intermediate has been made)

Fiddle: http://jsfiddle.net/qj3w31nm/

**Comment by fisi2000** [comment]
Hi together and thanks for your replies.

http://jsfiddle.net/67jb84b3/

Here is the demo with my values. And here is what I expect in the waterfall with the isIntermediateSum:

![unbenannt-1](https://cloud.githubusercontent.com/assets/11056822/6262713/5d79eeec-b809-11e4-9395-465c662bf0cb.jpg)

As you see, the new values since the first IntermediateSum are 3 and -7 so I expect the second IntermediateSum to be calculated as -4 and not as 1131 ? This was correctly calculated for months but since one week it is calculated in that way. But why? Thanks in advance!

**Comment by fisi2000** [comment]
Updated my highcharts-more.src.js like in 

https://github.com/highslide-software/highcharts.com/commit/c522cae17a76c702c1bd43d4de6d4acdb7aa3e2d

and now it works perfectly! Thanks!

![waterfall](https://cloud.githubusercontent.com/assets/11056822/6262904/8862d502-b80d-11e4-8127-2c9ce9debb6c.PNG)
