### ISSUE TITLE
3d miltiple column - wrong rendering - HC 4.1

### ISSUE THREAD

**Issue by sebastianbochan** [highslide-software/highcharts.com#3841]
Example: http://jsfiddle.net/kpafoke1/

**Comment by stephanevanraes** [comment]
This is caused by a bug in the part that calculates the number of stacks in the chart.
As a possible work around you can set stacking to true and assign a different stack to each series.

**Comment by highslide-software** [comment]
Still fails... http://jsfiddle.net/highcharts/kpafoke1/1/
