### ISSUE TITLE
logarithmic axis on gauge not displaying correctly

### ISSUE THREAD

**Issue by susiej** [highslide-software/highcharts.com#3852]
The latest release of highcharts broke all my gauges that used logarithmic axis.
This is from the old version.
![image](https://cloud.githubusercontent.com/assets/11070361/6262477/d94a7ef8-b83e-11e4-83fc-2dad572c2879.png)

This is the new version:
![image](https://cloud.githubusercontent.com/assets/11070361/6262472/cf077a0e-b83e-11e4-997f-394b911418d0.png)

A slight modification to the speedometer example in jsfiddle:
http://jsfiddle.net/5x8cmvy7/
As you can see, the arrow seems to point to the right position (if the axis was correctly placed), but the axis is all squished at the top.

**Comment by highslide-software** [comment]
Fails since abec994
