### ISSUE TITLE
shared tooltip not working for polar chart

### ISSUE THREAD

**Issue by rule88** [highslide-software/highcharts.com#3856]
Please see the following jsFiddle:

http://jsfiddle.net/gfzyc3ur/1/

For the polar chart tooltip.shared option is set to true. Expected is that the values of both data points are shown, but this is only the case if both points are directly vertically aligned.

The jsfiddle example is a slightly modified version of the highcharts demo.

using version 4.1.1 highcharts

**Comment by rule88** [comment]
Most likely the "shared" values are calculated from the X axis to the top and all matching values will then be shown in the tooltip. This will work for all "normal" graphs, but not for 360 graphs

**Comment by highslide-software** [comment]
It's a regression, worked in 4.0: http://jsfiddle.net/highcharts/gfzyc3ur/2/

**Comment by rule88** [comment]
Also not working for 4.1
