### ISSUE TITLE
Highstock: Problem with panning over breaks 

### ISSUE THREAD

**Issue by highslide-software** [highslide-software/highcharts.com#3857]
Demo: http://www.highcharts.com/stock/demo/intraday-breaks

Use the mouse to pan to the left (not scrolling, but panning on the main chart itself).

The ordinal counterpart to this chart works well: http://www.highcharts.com/stock/demo/intraday-area

**Comment by drainx** [comment]
I believe https://github.com/highslide-software/highcharts.com/commit/43724356ac675d5b420d03329bd40e25a02c4e4b is the culprit, though removing what was added causes other issues with ordinal, but fixes several issues with breaks on the yAxis.
