### ISSUE TITLE
Exported bar chart data label not working on v4.1.1

### ISSUE THREAD

**Issue by emmang** [highslide-software/highcharts.com#3864]
Steps to reproduce: 

1. Go to Highchart website jsfiddle example for bar chart: 
http://jsfiddle.net/gh/get/jquery/1.9.1/highslide-software/highcharts.com/tree/master/samples/highcharts/demo/bar-basic/

2. Click the export button to download jpg or png image

3. Open the image and the data labels for the bars look messed up

I am using Chrome browser Version 40.0.2214.111 (64-bit). I believe this issue is reproducible in both Firefox and IE. 

![chart](https://cloud.githubusercontent.com/assets/9773717/6281444/67f278ae-b876-11e4-8d90-5ee822e3b339.jpeg)

**Comment by highslide-software** [comment]
This is the same case as #3649, but the fix for that one doesn't work in this case.

The workaround is to set `dataLabels.style.textShadow` to "none".

Internal note: I have started working on a fix, but have to leave now. The progress so far is stored at http://jsfiddle.net/highcharts/1j6znqne/ .

**Comment by ValentinH** [comment]
I noticed the same issue with pies: http://www.highcharts.com/demo/pie-basic

**Comment by emmang** [comment]
Thank you for the quick reply. I applied your suggested workaround and it works!
