### ISSUE TITLE
Highstock: In IE11-9 - Range selector buttons do not react on click event

### ISSUE THREAD

**Issue by KacperMadej** [highslide-software/highcharts.com#3865]
Highstock: In IE11, IE10, IE9 - Range selector buttons do not react on click event. 
In IE8 this seems to work fine.

Example: http://www.highcharts.com/stock/demo/basic-line

You need to double click range selector buttons to change range.

**Comment by ekomisarenko** [comment]
Same issue here. Please suggest how to fix the problem. Is there any workaround? Thanks!

**Comment by KacperMadej** [comment]
Same issue occurs with 'reset zoom' button.
Example: http://jsfiddle.net/gh/get/jquery/1.9.1/highslide-software/highcharts.com/tree/master/samples/highcharts/demo/line-time-series/

**Comment by LioKlio** [comment]
highstock.src.js  (today) has fixed, but they do not work

Line 3440: addEvent(label.element, isIE ? 'mouseover' : 'mouseenter', function () { 
Line 3446: addEvent(label.element, isIE ? 'mouseout' : 'mouseleave', function () {

**Comment by highslide-software** [comment]
It's a regression, works well with Highstock 2.0: http://jsfiddle.net/kp6p5x2y/

**Comment by highslide-software** [comment]
Fails since edd19f0
