### ISSUE TITLE
Multi-series multi-level bar chart: errors on drillup

### ISSUE THREAD

**Issue by wojcikstefan** [highslide-software/highcharts.com#3867]
See http://jsfiddle.net/pypaq94t/36/.

1. Click on "California".
2. Click on "Santa Clara" or any bar under that label.
3. Drill up.
4. Drill up and see the error.
    
Console says: `Uncaught TypeError: Array.prototype.forEach called on null or undefined`
    
Just to point you in the right direction, the error comes from `oldSeries.animateDrillupFrom(level);` line in drilldown.js's `Chart.prototype.drillUp` function. `oldSeries.points` is undefined.

**Comment by wojcikstefan** [comment]
Following up on this one @highslide-software

**Comment by highslide-software** [comment]
Demo with the fix applied: http://jsfiddle.net/pypaq94t/38/
