### ISSUE TITLE
Passing mouse over graph will prevent Point.update to work (nasty bug)

### ISSUE THREAD

**Issue by natsumme** [highslide-software/highcharts.com#3873]
Hello,

In highcharts 4.1.1
The sequence (Point.update + redraw) won't work if you have passed the mouse over the graph before.
The lines of codes that break the sequence are within  runPointActions.
When commenting from line 9515 to line 9530 (in highcharts.src.js), the sequence works again.

Please note that if your repeat the sequence (Point.update + redraw), then the 3rd, the 4th sequences,... will work but not the first (I am not sure about the 2nd sequence, but anyway,...). 

Please also note, that this bug is very nasty and very difficult to detect and will produce different results depending if the user has pass the mouse over the graph or not before Point.update.

Please also note that this bugs only occurs in 4.1.1 (4.0.4 is OK)

**Comment by natsumme** [comment]
I made a mistake:
Read: When commenting from line 9513 to line 9535 (not line 9515 to line 9530) ...

**Comment by highslide-software** [comment]
Thanks, but I can't see the problem at http://jsfiddle.net/328tg8uc/. Can you describe how to reproduce the error, or make changes to the fiddle so it is reproducable?

Also, for reference, the lines you are referring to is the block beginning at https://github.com/highslide-software/highcharts.com/blob/v4.1.1/js/highcharts.src.js#L9513 .

**Comment by natsumme** [comment]
Hi

I forked the fiddle:
http://jsfiddle.net/848dayw0/
If you pass the mouse on the graph before clicking the button the update
won't work.

PS1: it seems the problem happens with bar (or inverted column and column
range). It is OK for column
NB1: In my example i changed the x to resort the bar. I know changing the x
for bars/columns is not so recommanded; but it opens awesome feature : neat
and clean resorting very easy.

Ryad

**Comment by highslide-software** [comment]
Simplified demo: http://jsfiddle.net/highcharts/848dayw0/1/
1. Hover the first point (category 0)
2. Click "Update first point"
3. Observe that the last point is updated, not the first. 

This only happens when the point has first been hovered.

**Comment by natsumme** [comment]
Thanks for your intervention

Cheers
Ryad
