### ISSUE TITLE
Waterfall with y axis starting at >0 broken in 4.1.x

### ISSUE THREAD

**Issue by micw** [highslide-software/highcharts.com#3886]
I have a waterfall chart that starts with an y axis >0 to make the diferences between values better visible.

That works fine in 4.0.4: http://jsfiddle.net/tctgj2t3/1/
But starting with 4.1.0 it's broken: http://jsfiddle.net/tctgj2t3/2/

**Comment by stephanevanraes** [comment]
The error seems to occur when the y-value is less than the threshold: http://jsfiddle.net/LLExL/4179/

**Comment by micw** [comment]
Which threshold?

**Comment by stephanevanraes** [comment]
the minimum you set on the y-axis

**Comment by micw** [comment]
That's true, But it should not since all values in waterfall are added to the previous value, so the resulting value that is shown in the chart is always > threshold.

**Comment by highslide-software** [comment]
Fails since fe70adb
