### ISSUE TITLE
Treemap export button hidden if no title

### ISSUE THREAD

**Issue by ValentinH** [highslide-software/highcharts.com#3888]
When using the exporting module on a treemap with no title, the export button is hidden behind the treemap: http://jsfiddle.net/hk6g4otj/.

It would be preferable to keep some margin for the button (when the export module is present)

**Comment by highslide-software** [comment]
This also happens to other chart types given the right configuration: http://jsfiddle.net/highcharts/ts93x26d/ .

#### Workaround
Add a `chart.marginTop`: http://jsfiddle.net/highcharts/hk6g4otj/1/. Or move the context button.

**Comment by ValentinH** [comment]
Yes I'm using the marginTop workaround.
