### ISSUE TITLE
cannot use errorbar combined graph on stacked column graph

### ISSUE THREAD

**Issue by mikk150** [highslide-software/highcharts.com#3890]
I cannot use errorbar  graph combined with stacked column

says undefined is not a function, and is on correctFloat function on a num.toPrecision(14) function because arrays that are casted to strings(for whatever reason) do not have toPrecision function

jsfiddle: http://jsfiddle.net/c4gnzxfg/1/

**Comment by stephanevanraes** [comment]
This is because you cannot stack discrete numbers with ranges. If you turn off stacking for the errorbar the error dissappears.

**Comment by highslide-software** [comment]
Our fix would be to make sure the stacking setting doesn't lead to an error and crash

**Comment by mikk150** [comment]
yes, fix found
jsfiddle: http://jsfiddle.net/y06wbr8c/1/
