### ISSUE TITLE
[Highcharts map module] chart display is completely messed up when series.setData is called

### ISSUE THREAD

**Issue by maheshjag** [highslide-software/highcharts.com#3894]
See here: http://jsfiddle.net/maheshjagadeesan/kez11sm0/1/

Type in a value in the text box below the chart. As you can see, this value is used to update the `data` array, and `chart.redraw` is called. This, however, mangles the chart completely

**Comment by pawelfus** [comment]
Workaround: 
Work on the copy of the data: http://jsfiddle.net/kez11sm0/8/

**Comment by pawelfus** [comment]
Looks like bug in 1.1.x version. 1.0.4 works fine: http://jsfiddle.net/kez11sm0/11/

**Comment by highslide-software** [comment]
Fails since 17ad662
