### ISSUE TITLE
Candlestick bar color issue while updating live

### ISSUE THREAD

**Issue by arnabk** [highslide-software/highcharts.com#3897]
I am trying to update candlestick bar live with a feed. Everything is working fine except that the color is wrong. It corrects itself when I hover over mouse. Please watch this 4 minute video.

I am using following plotOptions - 
```xml
plotOptions: {
                    candlestick: {
                        lineColor: 'black',
                        color: 'red',
                        upColor: 'green',
                        upLineColor: 'black',
                        shadow: true
                    }
                }
```

And updating candlestick with following code - 
```xml
var last = mainChartSeries.data[mainChartSeries.data.length - 1];
last.update([last.x, open, high, low, close]);
```

[Untitled Screencast.webm | uploaded via ZenHub](https://files.zenhub.io/54f00f87e81013bc7aee2462)

[Untitled Screencast.webm | uploaded via ZenHub](https://files.zenhub.io/54f00f99e81013bc7aee2463)

[Untitled Screencast.webm | uploaded via ZenHub](https://files.zenhub.io/54f00f9ee81013bc7aee2464)

**Comment by highslide-software** [comment]
Demo: http://jsfiddle.net/highcharts/9mtnfy1k/
1. Click the "Swap" button.
2. Observe how the data labels change, but the colors don't.
3. Hover the points. The colors change.

**Comment by arnabk** [comment]
Is that a feature or an issue. This is what I was trying to explain in the video. When the data value changes, I was expecting it to change the color too. Because in live stock charts as the values are changing for the forming bar, the color of the bar should change accordingly.

**Comment by arnabk** [comment]
When does it get released to CDNJS? I see that the version @CDNJS is very old for highstock

**Comment by highslide-software** [comment]
> When does it get released to CDNJS?

I have no idea... We don't maintain that. Our official CDN is http://code.highcharts.com.
