### ISSUE TITLE
Tooltip - sometimes displays for null points

### ISSUE THREAD

**Issue by KacperMadej** [highslide-software/highcharts.com#3901]
Example: http://jsfiddle.net/xqmhx8qs/13/
Steps:
1. hover mouse pointer over second bar
2. wait for tooltip
3. move pointer into the tooltip's text "Series 1"
4. move pointer straight down to where null bar would be

If useHTML is set to true then null point tooltip is displaying separately content and graphics (background and border).

Problem occurs also in line type series.
Example: http://jsfiddle.net/xqmhx8qs/15/
Steps: 
hover rapidly from left to right over points to see that broken tooltip is being displayed

**Comment by fridaymeng** [comment]
always occurs in highcharts v4.2.4
