### ISSUE TITLE
Pie - allowOverlap has no effect

### ISSUE THREAD

**Issue by KacperMadej** [highslide-software/highcharts.com#3903]
It seems that allowOverlap is not working for pie type series.
allowOverlap set to:
true - http://jsfiddle.net/4d6qt4xe/3/
false - http://jsfiddle.net/4d6qt4xe/

Small or negative padding allow labels to be placed closer or overlap - http://jsfiddle.net/4d6qt4xe/1/

...but this does not work for rotated labels - http://jsfiddle.net/4d6qt4xe/2/

**Comment by highslide-software** [comment]
Pies have a different layout algorithm for data labels, and padding doesn't apply on rotated labels. Both these things are noted in the docs now.
