### ISSUE TITLE
Switching off series cause formatted data loose format

### ISSUE THREAD

**Issue by manigor** [highslide-software/highcharts.com#3907]
On chart built, before any actions done 
![look4](https://cloud.githubusercontent.com/assets/161838/6420428/0c4944ee-bed7-11e4-9fd7-3658c3f16d6f.jpeg)
After "IN" series was switched off
![look5](https://cloud.githubusercontent.com/assets/161838/6420430/0f4bfd80-bed7-11e4-8892-927887a6992c.jpeg)
Switching "IN" on again doesn’t help
![look6](https://cloud.githubusercontent.com/assets/161838/6420445/2e900ede-bed7-11e4-8f40-5e6b516d3323.jpeg)

**Comment by highslide-software** [comment]
Live demo please? Or at least code example...

**Comment by manigor** [comment]
sorry  for delay
appeared to bug of formatter code
After fix works fine.So please consider solved.
