### ISSUE TITLE
Shared tooltip generate lots of events up to few thousands 

### ISSUE THREAD

**Issue by kjm** [highslide-software/highcharts.com#3908]
When shared tooltip is enabled mouseOver event on series point fires lots of times instead of one time. 
It fires up to few thousands in a few seconds of moving mouse cursor.

Here's example:
http://jsfiddle.net/kmxqom0w/1/

Regards

**Comment by highslide-software** [comment]
@stephanevanraes Didn't you resolve a similar one?

**Comment by stephanevanraes** [comment]
This is actually fixed (in some way) now mouseOver is only fired when the 'closest' point changes, so if you stay nearby the same point it is ok.

**Comment by highslide-software** [comment]
Demo with fixed code: http://jsfiddle.net/highcharts/kmxqom0w/2/
Closing this, please reopen if necessary.

**Comment by kjm** [comment]
Thank you for fast response and fix. Iw works properly :)
As i understand it is at github code only for now and i should use this version.

Regards

**Comment by kjm** [comment]
At the moment, it turns out that, unfortunately, did not work properly. Each mouseover event is generated as many times as series. I've checked out on the same provided demo code.

**Comment by stephanevanraes** [comment]
That is actually expected behaviour, you are *going over* all 4 series, so you get a mouseover event for each of them.
