### ISSUE TITLE
Data Label Duplication on iOS Devices With Retina Displays

### ISSUE THREAD

**Issue by richardhd** [highslide-software/highcharts.com#3911]
Version 4.1.2 introduced a display anomaly in iOS Retina displays. The problem is also present in 4.1.3. Here's the issue:
![img_0048](https://cloud.githubusercontent.com/assets/6981942/6430795/9b8c3060-bfe7-11e4-9dba-7b78f1dcc2bd.jpg)

Here's the same graph with 4.1.1:
![img_0049](https://cloud.githubusercontent.com/assets/6981942/6430796/b3acf1c0-bfe7-11e4-8b60-96ff2c3923e4.jpg)

My iPad Air 2 and iPhone 6, both with iOS 8.1.3, display the duplicate labels. I have an older iPad 2, also with iOS 8.1.3, but no Retina display, and the chart looks fine. The problem seems to only impact Retina displays.

**Comment by highslide-software** [comment]
It's the same underlying issue as #3649. The new observation is that it happens on Retina but not on 1:1 screens, that's why we accidentally removed the workaround in 4.1.2.

**Comment by highslide-software** [comment]
It fails since a8fd5c205da1.

Before that, Safari was marked as a browser that didn't support text-shadow. It was removed because in our tests on a 1:1 display, Safari applied both the native text-shadow and the shim. The check should be refined to only apply for Retina displays, and when the shim runs (if we don't find a workaround), the native implementation should not apply.

**Comment by houmark** [comment]
This is only partly fixed for me. I have a formatter function that adds some more text and those are still duplicated. Would there be a way to disable these problematic text-shadows completely for now?

**Comment by highslide-software** [comment]
> Would there be a way to disable these problematic text-shadows completely for now?

Yes of course, you set that in the style options: http://jsfiddle.net/highcharts/qetr3dkp/

> This is only partly fixed for me. I have a formatter function that adds some more text and those are still duplicated. 

Demo please?

**Comment by houmark** [comment]
I don't have an isolated demo, but I can provide a screendump and the JS from the formatter function if that's of any help? I will try disabling the textShadow to see if that fixes it.

**Comment by houmark** [comment]
Here is a screendump of the labels being duplicated:

![image](https://cloud.githubusercontent.com/assets/467330/6610983/6d7fafa8-c834-11e4-882d-a8118f94a76d.png)

As you hopefully can see, the first line is NOT duplicated, while the rest are.

The JS for the dataLabel formatter function is (room for improvement of course):

```
                formatter: function() {
                  // This is the formatter that shows the labels next to or on top of the bar/pie
                  var s = '';
                  var valueDecimals = (data.valueDecimals ? data.valueDecimals : 0);
                  var valuePrefix = (data.valuePrefix ? data.valuePrefix : '');
                  var valueSuffix = (data.valueSuffix ? ' '+ data.valueSuffix : '');

                  if (data.formatter === 0) {
                    return this.value;
                  } else {
                    s = '<b>'+ this.key +'</b><br><b>'+ valuePrefix + Highcharts.numberFormat(this.y, valueDecimals, ',', '.') +'</b>'+ valueSuffix;
                  }
                  if (this.percentage) {
                    s += '<br/>'+ Highcharts.numberFormat(this.percentage, 2, ',', '.') + '%';
                  }
                  return s;
                }
```

I hope this is helpful. Creating a JSFiddle will take me more time, but if you need that, let me know.

Disabling text-shadow fixes it - also in Safari as expected.

**Comment by highslide-software** [comment]
Thanks, we have enough information now. New issue created at #3974.
