### ISSUE TITLE
tickAmount on datetime axis

### ISSUE THREAD

**Issue by pawelfus** [highslide-software/highcharts.com#3914]
2) Example: http://jsfiddle.net/meuyq2Lf/4/
Number of ticks differs when resizing browser.

___
Edit: Moved fist issue to #3925.

**Comment by highslide-software** [comment]
It was only supposed to work for linear axes, for the purpose of aligning ticks and gridlines on charts with multiple Y axes. I have added this to [the docs](http://api.highcharts.com/highcharts#xAxis.tickAmount):

> http://api.highcharts.com/highcharts#xAxis.tickAmount

On other axis types, it is still recommended to use `tickPixelInterval`, `tickInterval` etc.
