### ISSUE TITLE
Tree map - hover on first point - datalabel is missing

### ISSUE THREAD

**Issue by sebastianbochan** [highslide-software/highcharts.com#3915]
1. Example: http://jsfiddle.net/072ym2v1/
2. Hover over first "point" with A label, this disappears

**Comment by jon-a-nygaard** [comment]
When hovering a point, for instance in this example A1, it will get a higher z-index than the other points. The result is that the point which is hovered and its own data label will always be visible, and lie in front of all other elements.
I will update the Treemap docs article with information about this.

**Comment by scristescu** [comment]
Hi Jon,

Is there a way to override this 'default logic' ?
- I still like to keep the level 2 labels on top of all, as we had it in the beta version.

Regards,
Sorinel C.

**Comment by jon-a-nygaard** [comment]
You can extend or overwrite the pointClass.setState function. Below is the example of how this code looks in treemap today:
```javascript
pointClass: extendClass(H.Point, {
  setState: function (state, move) {
    H.Point.prototype.setState.call(this, state, move);
    if (state === 'hover') {
      console.log(this);
      if (this.dataLabel) {
        this.dataLabel.attr({ zIndex: 1002 });
      }
    } else {
      if (this.dataLabel) {
        this.dataLabel.attr({ zIndex: (this.pointAttr[''].zIndex + 1) });
      }
    }
  }
}),
```
**this** has the context of the point which has a change of state (e.g. from normal to hover). A reference to the **dataLabel**, and the **id of the parent** is stored on the point. So you can loop over all its parent points and set a new z-index for their dataLabels. You would have to set the z-index to the previous value again after hover.

Read more about extending highcharts here: http://www.highcharts.com/docs/extending-highcharts/extending-highcharts

**Comment by FraktalInverTer** [comment]
It would be really nice if it could be a setting to keep the labels on top. If you want to be able to drill down on a higher level in the treemap, it is really hard if the higher levels label sneaks away.

As a side note on the subject of labels and treemaps: It would be awesome if the logic that handles overlapping labels would be a little nicer for the treemap scenario. With the current situation, you either need to disable the functionality with allowOverlap, or you choose either the one or the other label to be shown using the labelrank. It would be nicer if highcharts automatically prioritize the label that is alone where the mouse pointer is when you have a collision. So, if you hover on a place where only one label exists, that label takes preference and the other label is hidden.
