### ISSUE TITLE
highcharts-release: error from JSLint while pulling Highcharts via bower

### ISSUE THREAD

**Issue by KacperMadej** [highslide-software/highcharts.com#3918]
While pulling Highcharts code via bower, and JSLint is throwing an error on line 153 (function merge() ) - '&&' should be on end of line, not on beginning.

**Comment by highslide-software** [comment]
Can you give more details? What file, point to the location of the error etc..

**Comment by ibedek** [comment]
I've reported it on forum, function should look like this (not sure which file):
http://grab.by/FdKE
Hope that helps
