### ISSUE TITLE
Pie with gradient fill + drilldown painting issue

### ISSUE THREAD

**Issue by gigib82** [highslide-software/highcharts.com#3920]
When applying the gradient color technique from http://www.highcharts.com/demo/pie-gradient to a pie with drilldown (http://www.highcharts.com/demo/pie-drilldown), after the transition to the drilldown series all the pie slices are painted solid black. Each slice is then correctly painted upon mouseover.

Tested on Chrome 40 and Firefox 36

Example: http://jsfiddle.net/fwpcLwgp/

**Comment by highslide-software** [comment]
The console logs [error 23](http://www.highcharts.com/errors/23).

**Comment by gigib82** [comment]
In my code I'm actually using a set of hex colors (updated jsFiddle: http://jsfiddle.net/fwpcLwgp/1/)
Can you explain me why error 23 is still relevant?
Thank you!

**Comment by highslide-software** [comment]
@gigib82 Error 23 is relevant because the actual gradient structure is an unsupported "color".
