### ISSUE TITLE
Chrome crash: area zoom with horizontal dashline

### ISSUE THREAD

**Issue by alvarezguille** [highslide-software/highcharts.com#3923]
Related to #3201 but I can't reopen it.
Chrome crashes with "Aw, snap" message when zooming multiple times a chart with a shortDot line.
The example included in #3201 works with the fix as shown in: 
http://jsfiddle.net/9wku48nd/
But adding an horizontal line still fails:
http://jsfiddle.net/wsfcuu1o/

**Comment by highslide-software** [comment]
Hi, I have run 200 iterations of your loop without crashing. Running Chrome 40 on the Mac. What version are you on? How many iterations do you run before it snaps?

**Comment by alvarezguille** [comment]
Sorry, forgot to detail the environment: I'm testing in chrome 40 for windows (Chrome Version 40.0.2214.115 m; Windows 7 Enterprise SP1)

**Comment by alvarezguille** [comment]
Hi, any news about this? did the environment info help to reproduce it?
Thanks!

**Comment by vijayasekaran** [comment]
Hi ,
     Any update ? Its been a long time .Can you tell me the  latest estimation for reproducing and fixing the issue , So that i will update the same to my management colleagues

**Comment by highslide-software** [comment]
I still can't reproduce it. Tried on Windows 7 with Chrome 41. Ran 200 iterations without a problem. 

* Does updating to Chrome 41 fix it for you? 
* How many iterations do you run before it crashes?

**Comment by alvarezguille** [comment]
Hi, I updated Chrome to latest available (Version 41.0.2272.101 m) and got the "Aw, Snap!" after zoom #10.

**Comment by highslide-software** [comment]
Exactly the same OS and browser I am using...

**Comment by stephanevanraes** [comment]
same here, do you run any extra plugins or addons ?

**Comment by alvarezguille** [comment]
Nothing extra, it's a VM, that's the only special thing I can think of, just a clean VM with a clean installation of chrome.

**Comment by alvarezguille** [comment]
Just tried with another win7 32bits (not a VM this time) and found the issue after 11th iteration. Chrome version was 41.0.2272.89 m in this case.

**Comment by Ansku** [comment]
Hi, have you managed to reproduce the problem yet? Any estimate for the fix?

**Comment by alvarezguille** [comment]
Hi, were you able to reproduce the issue after my last update? I tried again updating to latest chrome (41.0.2272.118 m) and latest highcharts (4.1.5) in a 32-bit Windows environment and still fails with "Aw, Snap!"

**Comment by highslide-software** [comment]
Got it! Now I'll go bug hunting.

**Comment by alvarezguille** [comment]
Sorry I didn't get any notification of the edited post.
Are you still able to reproduce it?

**Comment by Ansku** [comment]
Hi! Any progress with this one?

**Comment by Ansku** [comment]
It's been three weeks since the last update to this issue, has anyone had time to look into this after that?

**Comment by highslide-software** [comment]
I was able to reproduce it long enough to see what I think is the problem, but then it stopped failing again. But please test this fix, and report back if it fixes the problems for you. If it does, I'll apply it to the next maintenance release.

In highcharts.src.js, find this line:
```js
point.plotX = plotX = xAxis.translate(xValue, 0, 0, 0, 1, pointPlacement, this.type === 'flags');
```

Replace it with this:
```js
point.plotX = plotX = mathMin(mathMax(-1e5, xAxis.translate(xValue, 0, 0, 0, 1, pointPlacement, this.type === 'flags')), 1e5); // #3923
```

**Comment by alvarezguille** [comment]
Great! I tested the fix and it works.

http://jsfiddle.net/alvarezg/Lcbm5j85/

Should the change also be done in same files affected in eb5906ddea6422774d8357805ea21354f023dc6e ? Looks like this is the same change but for X

Thanks!

**Comment by highslide-software** [comment]
Excellent, thanks for your patience! Fix coming up with all affected files changed.
