### ISSUE TITLE
tooltip does not update to hovered point in polar charts

### ISSUE THREAD

**Issue by ghost** [highslide-software/highcharts.com#3927]
demo: http://jsfiddle.net/prmz8Lg8/

sometimes tooltip remains stuck to a certain point

**Comment by highslide-software** [comment]
Looks like actually hovering the element causes the tooltip not to work, while it works well when hovering in the empty plot area around the points.

**Comment by pawelfus** [comment]
Looks similar to #3893

**Comment by pawelfus** [comment]
Works perfectly fine in 4.1.8: http://jsfiddle.net/prmz8Lg8/1/
