### ISSUE TITLE
animate xAxis line, if no animation

### ISSUE THREAD

**Issue by icebob** [highslide-software/highcharts.com#3928]
I found a bug: http://jsfiddle.net/icebob/610gag8u/

This fiddle is update first serial without animation every 3 sec but the x-axis line and title is animating.
Latest v4.1.3 highcharts version.

**Comment by stephanevanraes** [comment]
The problem is that you only call **addSeries** with animation explicitly turned off, if you call **setCategories** the xAxis is animted.  It is best to call that one without redraw:
```javascript
    chart.xAxis[0].setCategories(categories, false);
```

**Comment by icebob** [comment]
Thx!
