### ISSUE TITLE
Visual bug if x values is not sorted

### ISSUE THREAD

**Issue by icebob** [highslide-software/highcharts.com#3929]
Issue: http://jsfiddle.net/icebob/98x1oq71/2/

Latest v4.1.3 version.

**Comment by stephanevanraes** [comment]
You get an [error 15](http://www.highcharts.com/errors/15) in console.

**Comment by highslide-software** [comment]
Duplicate of #1900

**Comment by highslide-software** [comment]
Workaround 1: sort the data up front.

Workaround 2: provide a `pointRange` setting: http://jsfiddle.net/highcharts/98x1oq71/3/

**Comment by icebob** [comment]
Great!
