### ISSUE TITLE
Highchart switch to date categorization if the category ends with a number

### ISSUE THREAD

**Issue by ddombrowskii** [highslide-software/highcharts.com#3933]
Highchart will switch the categories of the x axis to dates if the title of one categoriy end with a number.

See for yourself :

http://jsfiddle.net/gh/get/jquery/1.9.1/highslide-software/highcharts.com/tree/master/samples/highcharts/demo/column-parsed/

http://jsfiddle.net/azkdppo6/

But if the category is within a span, it will work just as fine.

http://jsfiddle.net/oLg2dwyL/

**Comment by highslide-software** [comment]
It happens because the browser actually parses "Apples 1" into a valid date.

```js
Date.parse('Apples 1');
```
The remedy is simply to specify what kind of axis you want: http://jsfiddle.net/highcharts/azkdppo6/2/
