### ISSUE TITLE
Pointer events are not getting reset

### ISSUE THREAD

**Issue by natalan** [highslide-software/highcharts.com#3937]
If chart is destroyed in an event handler for a point (maybe other scenarios too), the Pointer object is still listening for 'mousemove' event and throws an error because handler function is null.

Reproduces here: http://jsfiddle.net/v2SRD/2/
Click on a point while having your console open, then move mouse cursor.

**Comment by natee** [comment]
I have the same question on highchart v4.1.3

**Comment by kentandersen** [comment]
I had the same problem in v4.1.3, fixed by downgrading to v4.1.1 for now.

**Comment by stephanevanraes** [comment]
offending commit: 0cc6ba3

**Comment by DenisVuyka** [comment]
Are there any estimates on the release date of this fix via public channel? We are having blocking issues with highstock 2.1.3 and this change should solve the problems. Thanks.

**Comment by highslide-software** [comment]
We will probably release a maintenance version next week. Until then, you can just apply the fix to the current release.

**Comment by natee** [comment]
@highslide-software 
After you do this bug fix,there comes another bug:When there is a single point , hover the colum from bottom to top,the tooltip doesn't show.Only move your cursor from left , top and right can trigger tooltip.

demo:http://jsfiddle.net/f9m0b5q3/

**Comment by highslide-software** [comment]
@natee It's fixed in the dev branch: http://jsfiddle.net/highcharts/f9m0b5q3/1/
