### ISSUE TITLE
Axis labels - not using the available space

### ISSUE THREAD

**Issue by maheshjag** [highslide-software/highcharts.com#3938]
In this example: http://jsfiddle.net/maheshjagadeesan/7yubtj3v/, you can see that autoRotation has been turned off for the x-axis labels. However, when you drag the slider to the right, the ellipsis is still in effect for each label even if there is sufficient space to display it. 

This becomes more pronounced when you drag the slider to the left so as to cause only one or two characters to display and then drag it across far to the right (to give it a significant amount of space).

**Comment by highslide-software** [comment]
Interestingly, if you set `autoRotation` to `false` it does reclaim the space: http://jsfiddle.net/highcharts/7yubtj3v/4/

**Comment by maheshjag** [comment]
That workaround could be useful, thanks! Is there a way to avoid the ellipsis altogether?

**Comment by highslide-software** [comment]
Not as I can think of... Unless you set steps. You can probably hack it though.

**Comment by highslide-software** [comment]
Closed by 62f769bce
