### ISSUE TITLE
Highcharts 4.1.x freezes Chrome, Firefox

### ISSUE THREAD

**Issue by Soliah** [highslide-software/highcharts.com#3939]
I've tried narrowing down why this is happening but can't seem to figure it out. Here's a JSFiddle: 

## [Link](http://jsfiddle.net/znrsako0/16/) **WARNING: This will crash the browser**

I'm on OSX 10.10.

Safari 8.0.3 works fine, but Firefox 35.0.1 and Chrome Version 41.0.2272.76 (64-bit) freeze and CPU gets pegged.

This doesn't happen with 4.0.x with the same options.

**Comment by Soliah** [comment]
Here's a fiddle with 4.0.4: http://jsfiddle.net/znrsako0/19/

**Comment by stephanevanraes** [comment]
Note: does not freeze on Windows (same Chrome version)

**Comment by highslide-software** [comment]
Running Chrome Versjon 41.0.2272.76 (64-bit) on OSX 10.10 and it does not freeze... Firefox also doesn't freeze. 

PS: Bug in Chrome and Firefox on OSX, not reproduceable by myself - sounds familiar. May it be connected to #3935?

**Comment by Soliah** [comment]
Just tried it on my rMBP and same issue.

OSX 10.10.2 (14C109)
Chrome 41.0.2272.76 (64-bit)
Locale is set to Sydney, Australia

I've tried this on the 4 iMacs (non 5k) we have in the office and a Macbook Air, all running OSX 10.10.2 and Chrome 41.0.2272.76 (64-bit).

Note all were under the Sydney, Australia locale.

**Comment by Soliah** [comment]
@highslide-software interestingly #3935 is also reproducible on my rMBP.

**Comment by highslide-software** [comment]
Still no problem here. Any debugging info you can provide is interesting. Use the `highcharts.src.js` file for readable code.

**Comment by Soliah** [comment]
Not sure what I can do to debug. Trying to load the fiddle freezes that particular tabs process, so I can't start the inspector.

Can you think of any other way to debug?

**Comment by highslide-software** [comment]
I usually go about this by having a fiddle where the offending code is commented out. Then add alerts or console.log in the Highcharts source code so I can see how far it will run before it crashes. Chrome is nice that way - when it crashes, you can just refresh and it continues with the same setup you were running. It will probably take some time before you find out how to follow the threads in Highcharts, but a good starting point could be to add alerts in the Chart.render method and you can drill in from there. I'm sorry I can't help you more that that, but it is hard when we can't reproduce the issues on our own machines.

**Comment by Soliah** [comment]
Removing `xAxis: { type: "datetime" }` stops the freezing.

**Comment by highslide-software** [comment]
Okay, so the Axis object would be a good place to look

**Comment by Soliah** [comment]
Ok so stepping through the code it looks like it gets stuck in `getOffset`, in this part:

```
			each(tickPositions, function (pos) {
				if (!ticks[pos]) {
					ticks[pos] = new Tick(axis, pos);
				} else {
					ticks[pos].addLabel(); // update labels depending on tick interval
				}
			});
```

Just loops there forever.

**Comment by Soliah** [comment]
On this line: https://github.com/highslide-software/highcharts.com/blob/master/js/highcharts.src.js#L8068 `tickPositions` is a giant array:

![screen shot 2015-03-07 at 12 29 46 am](https://cloud.githubusercontent.com/assets/141213/6526029/2762edb8-c461-11e4-82c1-588a475b3ac2.png)

There seem to be a number of iterations over this array in `getOffset`.

**Comment by highslide-software** [comment]
That's it. And it also looks like #3935. So the next step will be to find out _why_ we generate that many tick positions. There's a method called `getTimeTicks` in the axis object, there may be something fishy there. Inspect the incoming min and max values. Check the `while` loop and see what is pushed to the array. When working correctly, min should be -0.1, max should be 10.1 and there should be 12 tick positions.

**Comment by Soliah** [comment]
Ok so I bet this is caused by `getTimeTicks`. My feeling is that in certain timezones, in my case and in #3935 its because we're in UTC+9/+10 this function returns something wrong.

**Comment by Soliah** [comment]
```
		var time = minDate.getTime(),
			minMonth = minDate[getMonth](),
			minDateDate = minDate[getDate](),
			localTimezoneOffset = (timeUnits.day + 
					(useUTC ? getTZOffset(minDate) : minDate.getTimezoneOffset() * 60 * 1000)
				) % timeUnits.day; // #950, #3359
```

This sets the time to `-3600000`.

**Comment by Soliah** [comment]
Ok confirmed that in 4.0.4 `minDate.getTime()` returns `-0`, whereas 4.1.4 returns as above.

**Comment by Soliah** [comment]
4.1.4: `minDate` is `Thu Jan 01 1970 10:00:00 GMT+1100 **(AEDT)**`
4.0.4: `minDate` is `Thu Jan 01 1970 10:00:00 GMT+1000 **(AEST)**`
