### ISSUE TITLE
Axis labels - option to turn off ellipsis

### ISSUE THREAD

**Issue by maheshjag** [highslide-software/highcharts.com#3941]
The recent change to introduce ellipsis in place of the 'overflow' option has resulted in decreased usability in at least some cases. See http://jsfiddle.net/maheshjagadeesan/so9wz1x6/ for example. 

When you increase the width of #container to a slightly higher number (580px on my Retina MBP), the category labels wrap nicely to many lines. However, at 570px, the ellipsis appears. I'd recommend an option to at least turn it off.

**Comment by highslide-software** [comment]
At https://github.com/highslide-software/highcharts.com/blob/v4.1.3/js/parts/Axis.js#L1488 you'll see what happens. If the slot size is less than 80, we apply the ellipsis logic on the assumption that we risk clipping words if we apply word-wrap. If the size is greater than 80 pixels, there is less chance that we clip words, so we apply word-wrap. 

Not the ideal solution, at least this border value could be an option. The ideal logic would be to inspect the string for long words, but that would be heavy on the performance.

**Comment by maheshjag** [comment]
Thanks for your response. It looks like the case where autoRotation is turned off (set to [0] as suggested in the API) isn't being considered while 'unsquishing'. Agree that there would be performance considerations / issues here, but it'd be nice to at least leave it to the user to make that decision instead of eliminating that possibility altogether.

**Comment by highslide-software** [comment]
In your case, auto rotation is turned off by setting it to `false`: http://jsfiddle.net/so9wz1x6/2/

**Comment by highslide-software** [comment]
@maheshjag Your demo with the new option applied: http://jsfiddle.net/so9wz1x6/3/

PS: You should use `autoRotation: false` to turn off auto rotation. I have added this recommendation to the API.

**Comment by maheshjag** [comment]
Thanks a bunch for this fix, I've now pulled it in to our codebase.

**Comment by ngriesser** [comment]
Hi,
I am trying to get rid of the ellipsis here:
http://jsfiddle.net/ucw646jp/2/
autoRotation and autoRotationLimit does not seem to help.
Any advice?

**Comment by highslide-software** [comment]
In the latest dev code it is better, but now it overlaps, and doesn't extend to the full width of the chart: http://jsfiddle.net/highcharts/ucw646jp/3/

**Comment by ngriesser** [comment]
We cannot go on dev code, as we have a commercial software.

**Comment by highslide-software** [comment]
Of course, but this means the bug will be fixed in the next maintenance release.

**Comment by ngriesser** [comment]
Thank you.
Is there already a deadline for the next maintenance release?

**Comment by dub4u** [comment]
I still have an issue with this that I can not resolve. I too would prefer if there was an option to disable automatic ellipsis generation: Take this example which works fine on 4.0 but totally breaks on 4.1 where 'Today' gets truncated http://jsfiddle.net/16cs1s0w/4/

**Comment by highslide-software** [comment]
@dub4u, two things went wrong in Highcharts here.

First, the right label is supposed to be aligned/overflowed against the right side of the chart, as determined by the chart.spacing option. But in your case, the margin is 0, which overrides the spacing. Consequently, the label was shortened when it didn't have to. Fixing this issue alone, makes your chart behave like it used to: http://jsfiddle.net/highcharts/16cs1s0w/6/

Secondly, we would expect that we could set `style.textOverflow = 'none'` to disable ellipsis, but we couldn't. If we make your last category longer, we can see the new default with the margin fixed: http://jsfiddle.net/highcharts/16cs1s0w/7/. Now if we disable the textOverflow, this is the result: http://jsfiddle.net/highcharts/16cs1s0w/8/.

**Comment by dub4u** [comment]
Awesome support Torstein, thank you!! I was scratching my head as to why style.textOverflow was overridden before.

**Comment by highslide-software** [comment]
You're welcome!

> I was scratching my head as to why style.textOverflow was overridden before.

So that confirms that the new implementation makes sense.

**Comment by ldong** [comment]
Besides:

```
     xAxis: {
        labels: {
          autoRotation: false
       }
    }
```

You could also do it yourself by using

```
      xAxis: {
        labels: {
          useHTML: true,
          formatter() {
            let label = this.value;
            let style = `text-overflow: ellipsis; overflow: hidden;`; // YOUR OWN STYLE
            return `<div style="${style}" title="${label}">${label}</div>`;
          }
        },
      },
```
