### ISSUE TITLE
Unable to use valueSuffix (or valuePrefix) and Format String at the same time

### ISSUE THREAD

**Issue by natalan** [highslide-software/highcharts.com#3944]
I am trying to use both [valueSuffix](http://api.highcharts.com/highcharts#tooltip.valueSuffix) (and valuePrefix) together with [Format String](http://www.highcharts.com/docs/chart-concepts/labels-and-string-formatting) functionality and the tooltip does not show valueSuffix (or valuePrefix) value:

Reproduce bug demo: http://jsfiddle.net/adptr9pj/1/

The issue is in `Point.prototype.tooltipFormatter` that doesn't expect the string to use formatting options and utilizing simple replace call:

```javascript
if (valuePrefix || valueSuffix) {
    pointFormat = pointFormat.replace(key + '}', valuePrefix + key + '}' + valueSuffix);
}
```

Link to the original source in Master: https://github.com/highslide-software/highcharts.com/blob/master/js/parts/Point.js#L201

**Comment by natalan** [comment]
@highslide-software please check my comment regarding another issue after this commit
https://github.com/highslide-software/highcharts.com/commit/64e43e7f5d842915418e9d524088d49cc7d35c57

**Comment by highslide-software** [comment]
I reverted these changes as they broke the thousands separator in http://jsfiddle.net/highcharts/y8mc78n7/. 

I'm not sure it's even a bug, I would expect when a pointFormat is defined that the prefix and suffix were included in the format itself. The current implementation was initially meant like a backwards-compliant support for `valuePrefix`, `valueSuffix` and `valueDecimals` from before pointFormat was implemented.
