### ISSUE TITLE
Drilldown activeLabelStyle gets broken during scroll

### ISSUE THREAD

**Issue by DenisVuyka** [highslide-software/highcharts.com#3951]
I have a column chart (via highstock) with drilldown and scrolling/zooming enabled. So typically tick (category) labels have expected behavior, they are: bold, with underlined text, pointer cursor and mouse click support. Here's what I see for the "style":
**style="color:#0d233a;cursor:pointer;font-size:11px;fill:#0d233a;font-weight:bold;text-decoration:underline;"**
Once user starts scrolling/zooming labels that go off-screen get destroyed, also expected behavior. However when user scrolls back labels lose previous style and get the following:
**style="color:#606060;cursor:default;font-size:11px;fill:#606060;"**
Both styling and mouse click behavior disappears.

**Comment by highslide-software** [comment]
Demo: http://jsfiddle.net/highcharts/kqu16t4g/
Click the two buttons in succession and observe missing styling on the X axis labels.

**Comment by DenisVuyka** [comment]
Are there any plans to fix this bug in the near future?
