### ISSUE TITLE
[Waterfall] negative sums not displayed correctly

### ISSUE THREAD

**Issue by maheshjag** [highslide-software/highcharts.com#3952]
See this example: http://jsfiddle.net/maheshjagadeesan/uwqxu5xa/

If you use the 4.1.1 version of highcharts-more.src.js under External Resources, you'll see that the intermediate aggregates are plotted correctly.

**Comment by stephanevanraes** [comment]
for the intermediate aggregates you should use `isIntermediateSum`

http://api.highcharts.com/highcharts#series.data.isIntermediateSum

**Comment by maheshjag** [comment]
I tried that now, and here's the result: http://jsfiddle.net/maheshjagadeesan/uwqxu5xa/4/

Is there a limit on how many intermediates there can be?

**Comment by stephanevanraes** [comment]
I am not sure what I am missing, which of the intermediates is wrong / what should the values be ?

**Comment by maheshjag** [comment]
The bar for the second intermediate sum isn't quite right.

**Comment by stephanevanraes** [comment]
Ok, I found the problem and abstracted here: http://jsfiddle.net/7s81me3b/ 
If sum (or intermediate sum) is negative the column has a negative height and is not displayed correctly.

**Comment by stephanevanraes** [comment]
Can you post a sample of this using the latest development branch ? (use github.highcharts.com/high ....)
