### ISSUE TITLE
Error: Invalid value for <text> attribute x="NaN"

### ISSUE THREAD

**Issue by TAMMENY** [highslide-software/highcharts.com#3956]
html:
＜highchart config="chartConfig"＞＜/highchart＞
js:
    rest.query("jobs", {limit: 0})
        .then(function (response) {
             $scope.chartConfig={...}
        });

When i put the $scope.chartConfig into the function, the chrome console will throw out "Error: Invalid value for <text> attribute x="NaN"", but the chart is normal. However, when i put $scope.chartConfig out of the  function, the error was no longer being thrown. 

If you know how to solve this problem, please let me know, thank you.

**Comment by highslide-software** [comment]
Actually I don't recognize this at all as Highcharts code... Are you using some kind of third party wrapper?

**Comment by pawelfus** [comment]
Looks like highcharts-ng [github](https://github.com/pablojim/highcharts-ng). I think there should be this reported?

**Comment by TAMMENY** [comment]
@highslide-software Yes, i am using AngularJS.

**Comment by TAMMENY** [comment]
@pawelfus Thank you for your advice。

**Comment by TAMMENY** [comment]
I defined a default value for $scope.chartConfig, then update this value in rest function. As far as I'm concerned, the issue is over and done with. Thank you all.
