### ISSUE TITLE
Highstock: setting a break over data on x axis causes error

### ISSUE THREAD

**Issue by KacperMadej** [highslide-software/highcharts.com#3960]
Break on x axis causes error: "Uncaught TypeError: Cannot read property 'destroyElements' of undefined" 

Examples: 
http://jsfiddle.net/fkc7ady5/ (from demo: changed night break 'to' time from 8:00 to 9:00) 
http://jsfiddle.net/0w24m5rp/2/ (simplified example)

**Comment by pawelfus** [comment]
Fixed since 2.1.6: http://jsfiddle.net/0w24m5rp/6/
