### ISSUE TITLE
Horizontal Bar chart: default tooltips prevent drilldown click

### ISSUE THREAD

**Issue by josecanciani** [highslide-software/highcharts.com#3962]
Reproduce case: http://jsfiddle.net/4yrub2gd/1/

You can see that 3 of the "John" (blue) bars are covered by the tooltip and cannot be clicked.

I've worked around using positioner, showing the tooltip 50 pixels above the bar:
```js
                    positioner: function(labelWidth, labelHeight, point) {
                        return  {x: point.plotX - 20, y: point.plotY - 50};
                    }
```

But the workaround looses the little arrow, is not so pretty.

Thanks,
Jose Canciani
Avature.net (Highcharts client)

**Comment by highslide-software** [comment]
The official workaround for this issue, and the default for pies and some other series types, is to set the `followPointer` option to `true`: http://jsfiddle.net/highcharts/4yrub2gd/2/.

But it also loses the little arrow.

**Comment by highslide-software** [comment]
Here's a test case for each of the four edges of the chart: http://jsfiddle.net/highcharts/4yrub2gd/3/

**Comment by josecanciani** [comment]
Thanks for the fix!
