### ISSUE TITLE
BLOCKER: highcharts-release All files 0 bytes

### ISSUE THREAD

**Issue by radiolips** [highslide-software/highcharts.com#3963]
Highcharts 4.1.4 highcharts-release - All files are empty! Any server that pulls latest version of highcharts-release will not work. This has broken for my server, so I have temporarily pointed to a specific point version. Please fix ASAP! Thanks!

**Comment by highslide-software** [comment]
Sorry for that! Update script was too smart for its own good. It's fixed now.

**Comment by radiolips** [comment]
Great, thanks!
