### ISSUE TITLE
Export Server: at export.highcharts.com - when '%' is used, Error: Not Found

### ISSUE THREAD

**Issue by KacperMadej** [highslide-software/highcharts.com#3964]
Steps:
.1. Open http://export.highcharts.com/
.2. Add '%' anywhere in Options (even as comment) or use this example:

    {
	title: {
		text: '%'
	},
	series: [{
		data: [29.9, 71.5, 106.4, 129.2, 144.0, 176.0, 
			135.6, 148.5, 216.4, 194.1, 95.6, 54.4]
	}]
    };

.3. Press Preview button
.4. Error: Not Found

Exporting from chart works fine, error occurs only at http://export.highcharts.com/

**Comment by gvaartjes** [comment]
Tried it, and it works for me. 

The fiddle : http://jsfiddle.net/8y52oL6c/ also works when I export

**Comment by pawelfus** [comment]
Just tested with the above example - doesn't work too. Tested with Version 41.0.2272.89 (64-bit). Make sure you are trying to load "preview" ;)

**Comment by gvaartjes** [comment]
This is due to #4033
