### ISSUE TITLE
Shared tooltips breaks point click events on stacked columns

### ISSUE THREAD

**Issue by smithk58** [highslide-software/highcharts.com#3966]
Version 4.1.4 partially fixed this issue (previously, shared tooltips broke click events on more charts and broke stacked column click events entirely), but there's still some edge cases I found.

JS Fiddle: http://jsfiddle.net/d724xgdy/4/

If you click anywhere on the bottom half of the blue bar, you'll get the value of the black bar. If you click on the top half of the blue bar you will get its correct value. So, it appears that bars are taking up half of the bar above them for click events.

Click events also don't work if you turn stacking off in the above example (so the two bars are side by side in the same category). I didn't see any obvious patterns as to why though.

**Comment by smithk58** [comment]
Any update on this issue?

**Comment by highslide-software** [comment]
Sorry for the delay. It appears that #3985 is a duplicated of this one, so it is already fixed. 

See your [fiddle with the fix applied](http://jsfiddle.net/highcharts/d724xgdy/5/).
