### ISSUE TITLE
Highmaps Legend Not Properly Showing 0 Values and rescaling on zoom

### ISSUE THREAD

**Issue by imasonaz** [highslide-software/highcharts.com#3969]
I found this issue in the example graphs for US states:
http://jsfiddle.net/gh/get/jquery/1.11.0/highslide-software/highcharts.com/tree/master/samples/mapdata/countries/us/us-al-all

It seems that the legend doesn't display zero values, even though they are given in the data series. They will display if you remove the colorAxis min, but it seems that if a number lands on the min, it should still be displayed. If you change the min to 1, it will still show it on the legend.

Also, if you zoom in on the map, it slides the location of outer 2 labels on the legend inward, making them incorrect in their placement. Once you zoom back out to normal, they slide back outward again.

I've attached photos for both issues:

![0 data](https://cloud.githubusercontent.com/assets/5715364/6594004/905c688a-c79a-11e4-99dd-f622c09d91dc.jpg)
![zoomed](https://cloud.githubusercontent.com/assets/5715364/6593954/3838dc4c-c79a-11e4-9394-3989ce3837ae.jpg)

**Comment by stephanevanraes** [comment]
For the first part of your question: 
What do you mean with 'does not display 0 values' ? The name of *Bibb* does not appear due to an algorithm that prevents label collision (just like *Chilton* is not diplayed). And it looks like not being filled because the color at that point is `#EFEFEE` so almost white. If you set `minColor: '#FF00FF'`you will what I mean.

**Comment by imasonaz** [comment]
I mean that if you hover on any county except one that have a '0' value (not color) it shows up on the legend, at the bottom, with an arrow. If you hover over a '0' county, it won't be referenced on the scale at the bottom.

**Comment by wolfsbane90** [comment]
Is there a way to fix the count of partitions in the legend? The issue above has 3 partitions and i want to fix it to 3 partitions only. I tried searching the api website but couldn't find any way to do so.

**Comment by KacperMadej** [comment]
@wolfsbane90 For technical support please use other support channels as we are trying to keep github for bugs. https://www.highcharts.com/support

To adjust number of ticks on color axis please use ticks related options for colorAxis, like [colorAxis.tickPositioner](http://api.highcharts.com/highmaps/colorAxis.tickPositioner).
Demo: http://jsfiddle.net/hz7fgwmt/
