### ISSUE TITLE
Highcharts 4.1: Cannot disable xAxis.labels.step when using xAxis.labels.rotation

### ISSUE THREAD

**Issue by b1c1l1** [highslide-software/highcharts.com#3971]
The documentation for xAxis.labels.step states "By default, the step is calculated automatically to avoid overlap. To prevent this, set it to 1.".  However, setting step to 1 does not prevent this when using rotated labels.

To reproduce, set xAxis.labels.step to 1 and xAxis.labels.rotation in a container with a width too small for all labels.  Observe that the step setting does not disable automatic overlap calculations.

Example: http://jsfiddle.net/a8g87gm8/

**Comment by dmitrygorbenko** [comment]
I have the same issue. You can try it here:
http://jsfiddle.net/1vLhpLcb/1/
With rotation angle of 1 all labels expect first disappear (bug).
Try to change rotation to 0 and see results (expected).

**Comment by dmitrygorbenko** [comment]
Thank you !
