### ISSUE TITLE
Exporting as PNG, JPEG, and PDF broken when using zones in series chart

### ISSUE THREAD

**Issue by andrewr88** [highslide-software/highcharts.com#3972]
The resulting image from using the built-in exporting buttons is not being rendered correctly.

I modified the example jsfiddle for using zones and added the exporting module to show the resulting image - http://jsfiddle.net/2tg5tgu4/

**Comment by highslide-software** [comment]
The fix will be to upgrade to PhantomJS 2.0 on the export server, but we still have some testing to do. 

PS: @gvaartjes - didn't we already have an open issue for this?

**Comment by gvaartjes** [comment]
You closed these.. see #3649 and #3759

**Comment by andrewr88** [comment]
@gvaartjes @highslide-software any update as to when this issue will be fixed?

**Comment by radiolips** [comment]
@highslide-software @gvaartjes  I'm having this issue as well and it's imperative that I am able to export my charts. Until now I've relied on the exports server on Highcharts. Should I host my own server and rely on that? I have verified that PhantomJS2 fixes the issue.

**Comment by gvaartjes** [comment]
I'm sorry to keep your waiting, we would also like to launch the server with Phantomjs2, but we haven't setup the tests yet. It might break other things. I will consult with @highslide-software if we can prioritize this.

**Comment by highslide-software** [comment]
Tests are performed now. Comparing the output of Phantom 2 against Phantom 1, these differences occur:

* The current issue with translation and negative colors and zones is fixed.
* In semi transparent filled areas, the generated color has changed by one byte. This is not significant and is probably a result of rounding in Phantom, so we consider this okay. 
* All text elements, regardless of font family, are slightly bolder than with Phantom 1. With Phantom 2 they are rendered more in line with how it looks in the browser, so we consider this too okay.

The conclusion is we are ready to switch to Phantom 2 on the export server without further testing.

**Comment by gvaartjes** [comment]
Great!!

We expect to roll out an updated server in the end of this week

**Comment by radiolips** [comment]
Thanks, guys! Looking forward to it!

**Comment by level420** [comment]
Sorry for kicking in here. But I've done some tests with phantomjs 2.0 and have encountered problems when exporting as pdf  as others have, see https://github.com/ariya/phantomjs/issues/12685.

The pdf output is scaled/zoomed by some factor.

**Comment by wergeld** [comment]
Also seeing issues with PDF export using highstock 2.1.5 via our own internal export server using PhantomJS v2. The PDFs are grossly oversized.

**Comment by gvaartjes** [comment]
Thanks @level420 , @level420 

**Confirmed the oversized PDF.**
I don't expect so much trouble with finding a solution, we'll already do some clipping and scaling to make it fit the page

**Comment by gvaartjes** [comment]
Bummer; Looks like we have to wait for running phantomjs 2 on the Highcharts export server. I have tried several attempts installing, and trying it to compile by hand on Amazon. But failed... 

From [here](http://phantomjs.org/download.html)
    Binary packages for Linux are still being prepared. There are still issues to be solved until a static build is available (see [issue 12948](https://github.com/ariya/phantomjs/issues/12948) for more details).

**Comment by level420** [comment]
@gvaartjes Besides the compilation problems on amazon it would be great to have an adapted highcharts-convert.js which creates pdf files with the same dimensions in phantomjs 1.9.7 an 2.0

**Comment by davidwindell** [comment]
Don't know if it's of any help but I built a binary last week of PhantomJS 2.0.0 on Ubuntu 14.04 - https://github.com/outeredge/edge-phantomjs-binaries/releases

**Comment by gvaartjes** [comment]
@davidwendell Thanks,but I think it will have dependencies pointing to wrong locations.

**Comment by gvaartjes** [comment]
@level420 you're right we should work on that in the meantime.

**Comment by level420** [comment]
@gvaartjes any progress with this issue?

**Comment by gvaartjes** [comment]
Hi,

This patch will fix the page layout issues with PDF export

https://gist.github.com/gvaartjes/db82ddb6288364eb38e8

**Comment by level420** [comment]
@gvaartjes It would be great to have a common highcharts-convert.js file for phantomjs < 2 and phantomjs >= 2. It should be a simple if block testing the phantomjs version (https://github.com/ariya/phantomjs/blob/master/examples/version.js)

**Comment by level420** [comment]
@gvaartjes I've tested your patch and it works. The size of the rendered PDF is still oversized compared to the phantomjs 1.9.7 output. 

I had to multiply the scale parameter supplied to highcharts-convert.js by a factor of ~ 0.56 while using the same values for width and height. (http://www.highcharts.com/docs/export-module/render-charts-serverside)

I think the goal should be to be able to drop replace phantomjs v 1.9.x with v 2.0.x.

**Comment by gvaartjes** [comment]
@level420 I agree it should support both v1.9 and v2.0. I can add the block.

I don't think we can aim for a drop replace of phantomjs right now. It's perhaps not worth to build a script which is based on a phantomjs version with this bug messing up dpi settings and page.zoomfactor

What do you think?

**Comment by gvaartjes** [comment]
I agree on version checking, but I think we should not aim for drop replacement yet.

**Comment by gvaartjes** [comment]
Linking also this issue: https://github.com/ariya/phantomjs/issues/12936

**Comment by gvaartjes** [comment]
Export server is upgraded with PhantomJS version 2, no issue any long with http://jsfiddle.net/2tg5tgu4/
