### ISSUE TITLE
Column graph shows wrong values when zooming

### ISSUE THREAD

**Issue by Svancara** [highslide-software/highcharts.com#3973]
When zooming to "All" the chart shows wrong columns values like 100, 150 or 200. 
But there are no such data! Actually all data are under 50!
The correct columns are shown when zooming to other timeframes.

The same in all browsers.

Example: https://jsfiddle.net/bsvancara/3r430m4m/10/

![highstocks_wrong_values](https://cloud.githubusercontent.com/assets/109393/6609081/b8427296-c84d-11e4-86b5-52d11ce47369.png)
![highstocks_correct_values](https://cloud.githubusercontent.com/assets/109393/6609090/c6996d54-c84d-11e4-9281-892d1b4a9590.png)

**Comment by highslide-software** [comment]
See [dataGrouping](http://api.highcharts.com/highstock#plotOptions.column.dataGrouping). The default data grouping for columns is `sum`. Which makes sense, as your tooltip header says "Week from...", as an indication that this is a summary. Data grouping can be turned off.
