### ISSUE TITLE
Data label duplication with multiline labels on Retina displays 

### ISSUE THREAD

**Issue by highslide-software** [highslide-software/highcharts.com#3974]
This is a special case of #3911 (fixed).

Demo: http://jsfiddle.net/highcharts/kq9tmjro/

#3911 was a duplication of the text below the original when text-shadow was applied. It only happened when the `y` attribute was used for positioning, so we fixed it by setting `y` to 0 and position the text by translate instead. But the problem now is the subsequent lines of text, contained by `tspan`s where the `dy` attribute causes the bug.

**Comment by arambert** [comment]
Hi,
Any news on this ?
Thanks
:+1:

**Comment by MehdiSv** [comment]
Hi,
Any news for this bug ?

Keep up the good work, awesome lib!

**Comment by highslide-software** [comment]
We finally made a breaktrough, by discovering that the `text-rendering` CSS property can be used to prevent it:

http://jsfiddle.net/kq9tmjro/1/

Tested with Safari on OSX, however it seems it still doesn't work on PhantomJS.

**Comment by arambert** [comment]
:clap: 
That's good news, thank you for your time !
