### ISSUE TITLE
overflow:justify not working when using linkedTo (and even workaround is now broken)

### ISSUE THREAD

**Issue by drmrbrewer** [highslide-software/highcharts.com#3975]
The right-most label on the top x axis is cut off in the following (at least when the chart area is sized deliberately small enough), despite overflow:justify being used:

http://jsfiddle.net/drmrbrewer/qvztq2qy/7/

I understand that this issue was reported back in 2002 (https://github.com/highslide-software/highcharts.com/issues/1328) so it's a bit frustrating that the issue is still there.

Nevermind, what is more frustrating for now is that a workaround for this issue has now also broken in the latest highcharts.

The workaround was to unlink the axes and to ensure to use the same settings for both axes.  This is a working solution in highcharts 4.0.4:

http://jsfiddle.net/drmrbrewer/qvztq2qy/10/

But even that is now broken in highcharts 4.1.4:

http://jsfiddle.net/drmrbrewer/qvztq2qy/11/

Hopefully the root cause can be addressed so that a workaround is no longer required?  Second best would be to make the workaround work again :-)

**Comment by drmrbrewer** [comment]
Is there any plan to look at this?

Thanks.

**Comment by highslide-software** [comment]
overflow:justify was deprecated since 4.1.x and replaced by an automatic ellipsis when text overflows. So the question now is why the ellipsis doesn't show. I'll work on that right away.

**Comment by drmrbrewer** [comment]
Great, thanks.

**Comment by drmrbrewer** [comment]
Great, look forward to a new release soon with this fix applied.  BTW, I think your copyright/licence notices in the code need updating to use 2015 as the latest year!
