### ISSUE TITLE
Floating legend height

### ISSUE THREAD

**Issue by GMartigny** [highslide-software/highcharts.com#3976]
Hello,

I'm having trouble with legend box. I want to draw pie charts next to each other, so I want to align charts and legends. Legends items count can be very different, so I have to fixed the position.

So, I align legend to top and move it down. But although, there's space left, legends trigger navigation. Which leaves me with huge blank space.

You can see an example here : http://jsfiddle.net/sym1sfor/6/

**Comment by highslide-software** [comment]
It's a regression introduced with a6ed098
