### ISSUE TITLE
[MINI CHART] tooltip content are sometimes displayed outside the tooltip

### ISSUE THREAD

**Issue by ncoquelet** [highslide-software/highcharts.com#3977]
Hi,

I try to use highcharts to create minicharts (150x35px)

With spline chart, the tooltip content are sometimes displayed outside the tooltip border !

Here an example : http://jsfiddle.net/0y7f7z0o/1/

Regards

**Comment by iki** [comment]
+1 on highcharts-4.1.5 ... we found this also happens with column charts after zoom-in, and pie charts when moving the cursor to the very edge of the pie chart circle

**Comment by highslide-software** [comment]
It only happens when `useHTML` is true.
