### ISSUE TITLE
Event click fails on polygon series

### ISSUE THREAD

**Issue by epplestun** [highslide-software/highcharts.com#3979]
In the last version of Highcharts.StockChart, click event don't works in polygon series.

Working with Highcharts.Chart http://jsfiddle.net/3bs68jr7/1/
Don't working with Highcharts.StockChart http://jsfiddle.net/3bs68jr7/2/

Any idea?

Thx!

**Comment by highslide-software** [comment]
Sorry for the delay! It seems to be the `tooltip.shared` option that makes the difference: http://jsfiddle.net/highcharts/3bs68jr7/3/. It is true by default in Highstock and false by default in Highcharts.

**Comment by epplestun** [comment]
Ok, thanks!
