### ISSUE TITLE
Relative sizing in Bubblechart is wrong (2)

### ISSUE THREAD

**Issue by GeorgeLordsOfCastle** [highslide-software/highcharts.com#3981]
The smallest and the gratest bubbles are ALWAYS shown in a wrong proportion.

http://jsfiddle.net/9cqu7a3q/5/
In this chart remove and add the third series to understand what I mean.
When you remove the third series the smallest and the greatest bubbles change and it's evident the proportion bug.

**Comment by highslide-software** [comment]
Do you mean that the series don't take each other's data into account when determining the bubble size? In that case you can use `zMin` and `zMax` to align the sizes across series. [View demo](http://jsfiddle.net/highcharts/9cqu7a3q/6/).

**Comment by GeorgeLordsOfCastle** [comment]
Thanks a lot!!
