### ISSUE TITLE
Export Server: exporting in .pdf format - size is lowered

### ISSUE THREAD

**Issue by KacperMadej** [highslide-software/highcharts.com#3982]
Example: http://jsfiddle.net/afp7su87/

Exporting to i.e. png will result in 500x500 px image, but exporting to pdf format result in image that in actual size (100%) has about 425x425 px size.

**Comment by highslide-software** [comment]
@gvaartjes Don't know if this really matters... The idea of PDF is that it is vectorized so the pixel size doesn't affect the quality.

**Comment by barrystaes** [comment]
It does matter, because my graph now looks like DUPLO when blown up, i cant even see the trend lines underneath the huge dots.

Also, i need the PDF to be A4 sized and in landscape 99% of the time. Do we really need to bother with pixels?

**Comment by highslide-software** [comment]
> We cant even see the trend lines underneath the huge dots, making it pretty useless.

This indicates that you see something different than what is presented in the demo above. In the demo above, everything scales equally. Please elaborate with a live demo.

**Comment by sebastianbochan** [comment]
Internal note: 
The problem seems to be with dpiCorrection correction, because its 1.4. In my scenario when I for example update to 1.65 for specific chart, then is sizes are proper.

**Comment by gvaartjes** [comment]
Yes dpi could differ from system to system. That's why I implemented this settting. Could we close the issue then?

**Comment by sebastianbochan** [comment]
I think that value should be calculated dynamically, cause at this moment I need to replace 1.4 with 1.65 in source code. It means that is not proper calculated.

**Comment by pawelfus** [comment]
How about making this dpi as variable which can be passed altogether with other options (`sourceWidth` etc.)?

I'm not sure if we can close that ticket - generated pdf has still different size from the expected result (see Kacper's demo: 500x500 in options and ~425x420 in the result).

**Comment by gvaartjes** [comment]
We're using new logic to determine the zoomfactor of the page without dpi corrrection. See commit e839a6c879953434017af719e7f8abf5def8e0a9

Exporting the fiddle http://jsfiddle.net/afp7su87/ resulted in a 500x500 PDF.
