### ISSUE TITLE
When plotBand is scrolled out of view the label is still shown

### ISSUE THREAD

**Issue by wergeld** [highslide-software/highcharts.com#3983]
This looks like the same issue as #2328 that was closed over a year ago. This is under Highstock 2.1.4.
Example: http://jsfiddle.net/wergeld/o06wfexv/

When first loaded note that the labels are on the left side. As you scroll through the xAxis that encompasses the plotBand ranges the label moves into view again where they should. As you pass the location of the plotBand then the label is moved off to the right side of the chart.

**Comment by highslide-software** [comment]
Simplified demo: http://jsfiddle.net/highcharts/o06wfexv/2/. It happens with the highstock.js file, but also with Highcharts constructor. Worked correctly in Highstock 2.1.1.

**Comment by highslide-software** [comment]
Fails since 7e3b417

**Comment by highslide-software** [comment]
Ultimately the same issue (and fix) as #3836, but the StockChart version of the code is extended for multiple panes.
