### ISSUE TITLE
Click event registering incorrectly on column charts

### ISSUE THREAD

**Issue by prigney** [highslide-software/highcharts.com#3985]
While using Highstocks, I'm running into an issue with the series click event handlers.  When the series is of type 'line,' the event seems to work as intended; however, with 'column' series, the handler passing along the wrong series (it seems almost random)... 

I was able to recreate this issue in a [fiddle] (http://jsfiddle.net/mrpo2am4/2/).  You will notice the difference in the click events between the two charts.

**Comment by highslide-software** [comment]
Simplified: http://jsfiddle.net/highcharts/7zxhcnq0/

**Comment by highslide-software** [comment]
It worked in 4.1.3. Broken by c9d4fc7.
