### ISSUE TITLE
Candlestick bar weird structure while updating live for longer period of time

### ISSUE THREAD

**Issue by arnabk** [highslide-software/highcharts.com#3986]
I am showing live charts using highstock. If I keep it running for more than 24 hours, this is what I see after sometime. I am not sure how I can put that in JSFiddle since I cannot share our date feed publicly.
![snapshot1](https://cloud.githubusercontent.com/assets/446864/6657202/8b8d0f68-cb09-11e4-856c-01dabc7be75a.png)

Please let me know the best way to explain the issue.

**Comment by highslide-software** [comment]
Sorry for the delay!

How often do you add data points? Can you set up a script that runs quicker, so that you can replicate the effect within a shorter amount of time?

**Comment by arnabk** [comment]
I figured it out. It looks like I have to set 
```
series.isDirty = true;
series.isDirtyData = true;
```

Is there any better documentation on these variables somewhere?

**Comment by highslide-software** [comment]
No, those are internals and you shouldn't have to worry about it. Are you able to set up a live demo?
