### ISSUE TITLE
Export ignores dynamic font sizes

### ISSUE THREAD

**Issue by tomascassidy** [highslide-software/highcharts.com#3987]
I forked the fiddle from http://highcharts.uservoice.com/forums/55896-highcharts-javascript-api/suggestions/2258241-implement-dynamic-font-size into a new fiddle that enables exporting at http://jsfiddle.net/rcncL/23/.

If I increase the chart font size to be large (eg. 36px) and then export the chart, the exported png/svg is created with the original chart font size instead of the updated larger font size.

**Comment by highslide-software** [comment]
In the fiddle above, the font size is set on the containing div, and cascaded down into the SVG. In exported chart however, the SVG is pulled out of the HTML context, so the font size must be set on the top-level SVG instead: http://jsfiddle.net/highcharts/r8w2etgp/.
