### ISSUE TITLE
Highcharts 4.1.4: legend item markers and text do not vertically align on large font sizes AND large marker sizes 

### ISSUE THREAD

**Issue by level420** [highslide-software/highcharts.com#3988]
Running highcharts 4.1.4.

I'm in need to scale up the chart legend to font sizes up to 60px and legend item marker sizes up to 60x40. The larger the font size and marker sizes get, the more you'll observe a vertical misalignment between marker and text.

To reproduce please use http://jsfiddle.net/257onc2p/

I've seen that this was already adressed in issue #1804, but the fix does not seem to work well on large legend text font AND legend marker sizes.

PS.: I'm currently running into this, because I'm implementing a sort of "oversampling" e.g. creating large image sizes in phantomjs to overcome conversion accuracy problems when exporting to pdf and png: I'm scaling everything up by factor 4 and then set a zoom of 0.25 which gives a far more accurate rendering result.

**Comment by level420** [comment]
Here is a solution for this: https://github.com/highslide-software/highcharts.com/pull/4007

**Comment by level420** [comment]
Finally understood (I hope so) the build structure of highcharts: https://github.com/highslide-software/highcharts.com/pull/4009

**Comment by level420** [comment]
Reuse SVGRenderers fontMetrics method for fontSize calculation: https://github.com/highslide-software/highcharts.com/pull/4016

**Comment by highslide-software** [comment]
A slider demonstrates the problem: http://jsfiddle.net/highcharts/257onc2p/1/

**Comment by level420** [comment]
Yes! this shows the problem. 

Btw. cool demo!

**Comment by highslide-software** [comment]
This simplified code works well for my cases. The +1 preserves pixel-perfection towards the existing defaults: 
```js
	drawRectangle: function (legend, item) {
		var symbolHeight = legend.options.symbolHeight || 12;
		
		item.legendSymbol = this.chart.renderer.rect(
			0,
			legend.baseline - symbolHeight + 1,
			legend.symbolWidth,
			symbolHeight,
			legend.options.symbolRadius || 0
		).attr({
			zIndex: 3
		}).add(item.legendGroup);		
		
	},
```

**Comment by level420** [comment]
Does it also work if e.g. symbolHeight is small and fontSize large or the opposite symbolHeight is large and fontSize small?

Here is the fiddle: http://jsfiddle.net/257onc2p/2/

**Comment by highslide-software** [comment]
In my opinion it works optimal - it aligns to the baseline of the text. You
can try the fiddle yourself by applying the snippet in your project, and
give your opinion.​

**Comment by level420** [comment]
Please note my use case: I'm scaling everything in highcharts by a factor of 4 (line widths, paddings, font sizes, width and height of the chart) and let phantomjs render all with a zoom factor of 0.25.

This should in theory give the same dimensions as without scaling / zooming, but leads to far more accurate rendering to PDF or PNG. Without this the rendering quality of phantomjs is really poor (no change here between phantomjs 1.9.8 and 2.0)

In this situation an additional not scalable dimension like the +1 as you proposed is again not scaled up which leads to different results using different scale / zoom factors.

**Comment by level420** [comment]
In my opinion it would be optimal to center the horizontal axis of the symbol to the visual middle of the first symbol text line.

**Comment by level420** [comment]
I've tested your fix and could live with that solution, but centering the symbol and the first text line is imho visually nicer.

**Comment by highslide-software** [comment]
Your use case is interesting - we do the same thing on the export server with the http://api.highcharts.com/highcharts#exporting.scale option. You can see how we are doing it in the [highcharts-convert.js](https://github.com/highslide-software/highcharts.com/blob/master/exporting-server/phantomjs/highcharts-convert.js) script. We do it without scaling up the chart elements one by one, which seems like a very cumbersome approach.

> In this situation an additional not scalable dimension like the +1 as you proposed is again not scaled up which leads to different results using different scale / zoom factors.

Yes it is unfortunate. And maybe we should change this, and also while we're at it I think a more logical default value for the symbolHeight is to use use the fontSize as default. They are both 12 by default now, so a change wouldn't hurt.
​

**Comment by level420** [comment]
I'll have a look into highcharts-convert.js on monday.

With my method the result is not a pdf or png with scaled up dimensions. The dimensions are unchanged, but the result is more accurate.

Especially when rendering pdf files I dont want to create a pdf with doubled or quaded dimensions.

Till monday: have a nice weekend and thank you for your help. Very appreciated!

**Comment by highslide-software** [comment]
Then probably the dpi of the output should be altered. Changing the
Highcharts options output just to achieve scaling of the image sounds wrong
to me.

**Comment by level420** [comment]
> Then probably the dpi of the output should be altered. Changing the
> Highcharts options output just to achieve scaling of the image sounds wrong
> to me.

But how to do that if (as I suspect) phantomjs renders the image at a low quality or precision?
Please see the following example: http://jsfiddle.net/0mL030wj/3/

Please use the export button and export the chart as svg and open it with e.g. chrome. phantomjs (or highcharts) seems to do calculations based on one pixel precision internally, which leads to unsteady bar distances and widths. This output is not sufficient for printing.

There is an old pull request for phantomjs https://github.com/ariya/phantomjs/pull/11846 which did not made it into the repo dealing with dpi settings.

**Comment by highslide-software** [comment]
> Please see the following example: http://jsfiddle.net/0mL030wj/3/

> Please use the export button and export the chart as svg and open it with e.g. chrome. phantomjs (or highcharts) seems to do calculations based on one pixel precision internally, which leads to unsteady bar distances and widths. This output is not sufficient for printing.

This is Highcharts' internal crisping feature. It rounds to the nearest pixel for sharp rendering on screen. You can see some of the considerations done at https://github.com/highslide-software/highcharts.com/issues/2694.

**Comment by level420** [comment]
From the commit there I see that the crisp feature is not configurable. So it may turn out that I worked around the crisp feature of highcharts.

**Comment by level420** [comment]
Thank you for fixing the issue.

**Comment by level420** [comment]
Moved the crisp, accuracy, precision problem over to a new issue http://jsfiddle.net/0mL030wj/3/

**Comment by MiroLiska** [comment]
I still do not like the vertical positioning of the legend symbols. the drawRectangle and drawSymbol functions are using different alignment strategies. See here: http://jsfiddle.net/257onc2p/4/ . 

![i0](https://cloud.githubusercontent.com/assets/23024867/26405505/ce80dcb0-4095-11e7-9bdd-1636157bc9e4.png)

(Unfortunately, I have such a chart in real life).

**Comment by TorsteinHonsi** [comment]
Good point. As you can see, in the Tokyo line series, the emphasis in on the line item, so it is aligned in the middle of the lowercase letters.

**Comment by MiroLiska** [comment]
I know that the idea was to center the line. However, I use line series without lines, just to display markers. And these combined with column charts lead to the issue described above. See the real-life example at http://jsfiddle.net/66mj20ss/ (with legend item symbol fixed). There is a discrepancy anyway - the legend symbol for column chart is crisp, the rectangle symbol for line is blurry. My code fixes both.
