### ISSUE TITLE
Problem with drilldown after destroying and re-initialising chart

### ISSUE THREAD

**Issue by 83N** [highslide-software/highcharts.com#3990]
There seems to be a problem in the drilldown module after destroying and re-initialising the chart.  This occurs when a drilldown series in the new chart existed in the previous chart.  

From what I can make out, calling destroy() on the chart doesn't reset the variables in the drilldown module, meaning that it fails to find the seriesOptions in doDrilldown as the series still exists in the dupes array.  If you are able to drilldown into a different series, and then drill back up, you are able to drilldown into any of the series as the drilldown module rights itself.

Fiddle:   http://jsfiddle.net/dxdzdw5q/
Steps:   Drilldown into Animals series.  Re-initialise the chart.   Try to drilldown into the animals series again. 

As a temporary workaround, I am clearing out the dupes array at the start of doDrilldown  (approx line 515 in drilldown.src.js).

Thanks

**Comment by smj-hosseini** [comment]
this problem still exist and drilldown not work properly!
plz fix it

**Comment by KacperMadej** [comment]
@smj-hosseini 
Please post a live demo of the problem. The link in the first comment is working (according to the required steps for recreating the issue).
