### ISSUE TITLE
Highstock: flags outside plot area

### ISSUE THREAD

**Issue by KacperMadej** [highslide-software/highcharts.com#3991]
Example: http://jsfiddle.net/12js2yd1/

Flags are outside plot area (overlaying range selector buttons and after manipulating navigator flags can overlay chart context menu).

In that fiddle is also present problem with tooltip that is displayed over flags (when hovering over flags).

**Comment by prettycode** [comment]
This is what I use as the workaround:

http://jsfiddle.net/12js2yd1/7/

**Comment by highslide-software** [comment]
Duplicate of #419

**Comment by dev-katiyar** [comment]
try this https://api.highcharts.com/highstock/plotOptions.flags.clip
