### ISSUE TITLE
When datalabels useHTML is true, fontStyle is not working

### ISSUE THREAD

**Issue by Atte902** [highslide-software/highcharts.com#3996]
Example: http://jsfiddle.net/hk6hmsz2/

fontStyle: "italic" works when turning useHTML to false

**Comment by highslide-software** [comment]
Here's a drop-in fix you can use for Highcharts 4.1.4 while waiting for the next maintenance:

```js
    // Drop-in fix for #3995
    Highcharts.SVGElement.prototype.textProps.push('fontStyle');
```
[View live demo](http://jsfiddle.net/hk6hmsz2/1/).

Another option is to use CSS styling by `.highcharts-data-labels span'.
