### ISSUE TITLE
Standard bar chart works incorrect. Middle bar labels aren't present.

### ISSUE THREAD

**Issue by RomanKostenko** [highslide-software/highcharts.com#3998]
Go to http://jsfiddle.net/gh/get/jquery/1.9.1/highslide-software/highcharts.com/tree/master/samples/highcharts/demo/bar-basic/
Some labels aren't present.
I've checked it in the last Chome and Safary. Mac OS X 10.10. The problem is also reproduced in Windows (only one label is absent).

The labels are present in SVG but opacity="0".

![2015-03-16 17 07 22](https://cloud.githubusercontent.com/assets/9323224/6669086/c08ca3a8-cbff-11e4-8cf4-0521d5d3d7b1.png)
![2015-03-16 17 11 09](https://cloud.githubusercontent.com/assets/9323224/6669087/c0f3ffee-cbff-11e4-8329-67601990b068.png)

**Comment by RomanKostenko** [comment]
If somebody has the same problem you can use my dirty workaround.
It has a blink artifact.
You can try it just put this snippet to the plotOptions:
```
           series: {
                animation: {
                    complete: function () {
                        $(YOUR_CONTAINER).find('g').attr('opacity', '1');
                    }
                }
            }
```
Example: http://jsfiddle.net/68zgcboz/

**Comment by Atte902** [comment]
You can also use this: http://api.highcharts.com/highcharts#plotOptions.column.dataLabels.allowOverlap

Set the allowOverlap to true.
