### ISSUE TITLE
Wrong width of columns when there are only two separate values in a Column chart.

### ISSUE THREAD

**Issue by DAreRodz** [highslide-software/highcharts.com#3999]
If you put two single data values far apart from each other on the X axis, both columns are plotted wider, as if there was no space between them.

Demo: http://jsfiddle.net/Lrmqnm9j/

It seems to work if you add a third point to the series: http://jsfiddle.net/ae9f4wex/

**Comment by DAreRodz** [comment]
I have done more tests. If there are no two adjacent columns, the columns will still show wrong.
Demo: http://jsfiddle.net/Lrmqnm9j/1/

**Comment by DAreRodz** [comment]
Ok, just had to set the pointRange property equal to 1 in plotOptions.column: http://jsfiddle.net/Lrmqnm9j/2/

**Comment by highslide-software** [comment]
Duplicate of #2013
