### ISSUE TITLE
PhantomJs and exporting URL

### ISSUE THREAD

**Issue by MoboDK** [highslide-software/highcharts.com#4000]
Hi i cant figure out how i can get phantomjs to render an image locally?

I am using c# but i guess it shouldnt matter:
```c#
var request = (HttpWebRequest)WebRequest.Create("http://127.0.0.1:3003");

            string postData = "{\"globaloptions\":\"{exporting:{url: 'http://localhost:63811/Handlers/HighchartsExport.ashx'}}\", \"infile\":\"{xAxis: {categories: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']},series: [{data: [29.9, 71.5, 106.4, 129.2, 144.0, 176.0, 135.6, 148.5, 216.4, 194.1, 95.6, 54.4]}]};\",\"constr\":\"Chart\"}";
            var data = Encoding.ASCII.GetBytes(postData);

            request.Method = "POST";
            request.ContentType = "application/x-www-form-urlencoded";
            request.ContentLength = data.Length;

            using (var stream = request.GetRequestStream())
            {
                stream.Write(data, 0, data.Length);
            }

            var response = (HttpWebResponse)request.GetResponse();
```
I have also tried to make changes to highcharts-convert.js, but without any luck. Can anybody please share how this is done - if possible.

Thanks
Morten

**Comment by gvaartjes** [comment]
Hi,

I think you have to change the content-type to _application/json_ Phantomjs is expecting the json in the request body. Not as url parameters.

Gert
Highsoft

**Comment by MoboDK** [comment]
Hi Gert, 
Thank you for your reply. The question is related to exporting url (to specify an local processing server). The above code work fine, but is not invoking my local server. So how can i change the exporting url, either in highcharts-convert.js or through the json string eg:

 string postData = "{\"globaloptions\":\"{exporting:{url: 'http://localhost:63811/Handlers/HighchartsExport.ashx'}}\", \"infile\":\"{xAxis: {categories: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']},series: [{data: [29.9, 71.5, 106.4, 129.2, 144.0, 176.0, 135.6, 148.5, 216.4, 194.1, 95.6, 54.4]}]};\",\"constr\":\"Chart\"}";

**Comment by gvaartjes** [comment]
Hi,

I think you misunderstood the function of  the exporting.url 

This doesn't make sense to me. You're posting to phantomjs on 127.0.0.1:3003 for converting Highcharts options to an image. 

The exporting.url option is only for javascript charts running in a browser. Then the "Download as PNG|JPEG|PDF" is posting to the server specified by exporting.url

In your case (rendering locally) you don't need to specify exporting.url for render locally an image

Gert

**Comment by MoboDK** [comment]
Thanks Gert, 
Yes i got it wrong! I thought PhantomJs was only to be able to render charts serverside, but that it still would request the actual image through Highcharts rendering service. 

Thank you for your support!
Morten

**Comment by gvaartjes** [comment]
Thanks! You're welcome
