### ISSUE TITLE
Export Server: charts with "id=" in labels fails

### ISSUE THREAD

**Issue by KacperMadej** [highslide-software/highcharts.com#4003]
Example: http://jsfiddle.net/fjpu6ycv/1/

The issue regards exporting a chart with urls in labels.
This URLs have query strings with parameters ending in "id".
The export fails because of this line in the exporting module, getSVG function:

    .replace(/id=([^" >]+)/g, 'id="$1"')

getSVG() will return this:

    <text x="13" style="color:#000;cursor:default;font-size:13;white-space:nowrap;text-transform:lowercase;background-color:#f00;fill:#000;width:188px;text-overflow:clip;" text-anchor="start" transform="translate(0,0)" y="57" opacity="1">http://this-has-[id]-in-querystring-all-labels-below-wont-be-exported/?id="highcharts</text">

Notice the quote surrounding "highcharts</text" (very end of the code block)

**Comment by highslide-software** [comment]
There are probably more cases like this, where text replacement done in `Chart.sanitizeSVG` will have unwanted effects against certain very narrow content strings in the chart. In this case we can resolve it by adding a space before the `id` in the regex, thereby supporting the original oldIE issue but resolving this one.
