### ISSUE TITLE
Highcharts column chart returning incorrect series index on click when using shared tooltip

### ISSUE THREAD

**Issue by cutbko** [highslide-software/highcharts.com#4020]
Here is fiddle: http://jsfiddle.net/a9mp9vhj/1/

Click on the top of the first column and you will see the message: "column index: 0" which is correct. Click on the middle or bottom of the first column and you will see other indeces.

if you set tooltip to be not shared everything starts working.

**Comment by stephanevanraes** [comment]
Work in latest master branch.
Probably related to #3985
