### ISSUE TITLE
Gauge final label does not display

### ISSUE THREAD

**Issue by juanpex** [highslide-software/highcharts.com#4021]
Sometimes the last label value does not appear.

Here is my example.

http://jsfiddle.net/juanpex/weaqbebf/

How can I show as last value the "max" value?

**Comment by highslide-software** [comment]
Highcharts by default writes labels on round numbers. Use the [tickPositions](http://api.highcharts.com/highcharts#xAxis.tickPositions) setting or [tickPositioner](http://api.highcharts.com/highcharts#xAxis.tickPositioner) callback for more control.

PS: This is our bug tracker. For general support, please use www.highcharts.com/support in the future.
