### ISSUE TITLE
Adding, removing and then adding back a subpanel causes rendering issue

### ISSUE THREAD

**Issue by arnabk** [highslide-software/highcharts.com#4022]
http://jsfiddle.net/arnabk/c6aopawt/
Steps - 
> Click Add ATR 2 times
> Click Remove ATR 2 times
> Click Add ATR again
> You will notice that the ATR series chart is not rendering properly

You will clearly see that in both add and remove cases, I am calling chart.redraw(); explicitly to redraw the chart properly.

![image](https://cloud.githubusercontent.com/assets/446864/6773643/96b65b1c-d0d9-11e4-9f0c-38e99e2c4181.png)

**Comment by sebastianbochan** [comment]
Please supply browser details, because in the newest Chrome all works properly.

**Comment by arnabk** [comment]
![image](https://cloud.githubusercontent.com/assets/446864/6804381/f4f0d23c-d202-11e4-9f27-f86701b48b4b.png)

Do you the above steps couple of times. Attaching one video.
https://docs.google.com/a/regentmarkets.com/file/d/0B-SvgdYmyOyKUzVETTJSTG9uYTA/edit?usp=drivesdk

When I resize browser, it fixes itself. This gave me an idea to call reflow, but calling reflow programmatically is not solving this problem.

**Comment by highslide-software** [comment]
Apparently something goes wrong with clipping the pane, though I have not found out exactly what.

A valid workaround is to remove the clipBox that is computed in the Series.render method: 

```js
    H.wrap(H.Series.prototype, 'render', function (proceed) {
        proceed.call(this);
        this.clipBox = null;
    });
```
[View it on JSFiddle](http://jsfiddle.net/highcharts/c6aopawt/2/)

**Comment by arnabk** [comment]
Thank you. This work around works. I will close the defect. In case you want to find out right solution later, you may reopen it.

**Comment by arnabk** [comment]
I have to reopen this issue. Take a look at this updated JSFiddle.
http://jsfiddle.net/arnabk/05u6zf21/3/

![image](https://cloud.githubusercontent.com/assets/446864/6841298/9eba6a8a-d34d-11e4-9b25-bf36f2f36ecf.png)

Steps - 
> Click Add ATR
> Click Add one point
> Click Update one point and you will notice this error message
