### ISSUE TITLE
Highcharts 4.1.4: undocumented arguments "customcode" and "dataoptions" in highcharts-convert.js

### ISSUE THREAD

**Issue by level420** [highslide-software/highcharts.com#4028]
While delving into highcarts-convert.js I've discoverd the additional parameters customcode and dataoptions which are not documented in http://www.highcharts.com/docs/export-module/render-charts-serverside .

I was searching a possibility to execute custom code which manipulates the submitted chart options.

**Comment by pawelfus** [comment]
Do you refer `callback` option? From docs:

> Filename containing a callback JavaScript. The callback is a function which will be called in the constructor of Highcharts to be executed on chart load. All code of the callback must be enclosed by a function. Example of contents of the callback file: function(chart) { chart.renderer.arc(200, 150, 100, 50, -Math.PI, 0).attr({ fill : '#FCFFC5', stroke : 'black', 'stroke-width' : 1 }).add(); }

**Comment by level420** [comment]
No I mean:

https://github.com/highslide-software/highcharts.com/blob/master/exporting-server/phantomjs/highcharts-convert.js#L76

**Comment by gvaartjes** [comment]
Hi,

The reason for not having them in the documentation is that these options are experimental. They could change in the future, although not likely. 

This is an example of an JSON file send to the export server, using the options _customcode_ and _dataoptions_
```json
{"constr":"Chart","dataoptions":"{\n  \"seriesMapping\": [\n    {\n      \"x\": 0\n    },\n    {\n      \"x\": 0\n    },\n    {\n      \"x\": 0\n    },\n    {\n      \"x\": 0\n    }\n  ],\n  \"columnTypes\": [\n    \"float\",\n    \"float\",\n    \"float\",\n    \"float\",\n    \"float\"\n  ],\n  \"csv\": \"row,Tokyo,New York,Berlin,London\\n1,7,-0.2,-0.9,3.9\\n2,6.9,0.8,0.6,4.2\\n3,9.5,5.7,3.5,5.7\\n4,14.5,11.3,8.4,8.5\\n5,18.2,17,13.5,11.9\\n6,21.5,22,17,15.2\\n7,25.2,24.8,18.6,17\\n8,26.5,24.1,17.9,16.6\\n9,23.3,20.1,14.3,14.2\\n10,18.3,14.1,9,10.3\\n11,13.9,8.6,3.9,6.6\\n12,9.6,2.5,1,4.8\"\n}","width":"205","infile":"{\n  \"plotOptions\": {\n    \"series\": {\n      \"dataLabels\": {\n        \"enabled\": true\n      },\n      \"stacking\": \"percent\"\n    }\n  },\n  \"credits\": {\n    \"text\": \"Highcharts\",\n    \"href\": \"//cloud.highcharts.com/\",\n    \"enabled\": true\n  },\n  \"series\": [\n    {\n      \"index\": 0\n    },\n    {\n      \"index\": 1\n    },\n    {\n      \"index\": 2\n    },\n    {\n      \"index\": 3\n    }\n  ],\n  \"chart\": {\n    \"type\": \"column\",\n    \"inverted\": true\n  }\n}","type":"png","customcode":"// Sample of extending options:\nHighcharts.extend(options, Highcharts.merge(options, {\n    chart: {\n        backgroundColor: \"#bada55\"\n    },\n    plotOptions: {\n        series: {\n            cursor: \"pointer\",\n            events: {\n                click: function(event) {\n                    alert(this.name + \" clicked\\n\" +\n                          \"Alt: \" + event.altKey + \"\\n\" +\n                          \"Control: \" + event.ctrlKey + \"\\n\" +\n                          \"Shift: \" + event.shiftKey + \"\\n\");\n                }\n            }\n        }\n    }\n}));\n"}
```

**Comment by level420** [comment]
@gvaartjes: Thank you for your answer.

I've sent your example code via POST to phantomjs, but got no response (syntax error):

```
Highcharts.options.parsed
SyntaxError: Parse error

SyntaxError: Parse error

ReferenceError: Can't find variable: dataOptions

  phantomjs://webpage.evaluate():114
  phantomjs://webpage.evaluate():164
  phantomjs://webpage.evaluate():164
TypeError: 'null' is not an object (evaluating 'svg.imgUrls')

  /usr/local/phantomjs/lib/highcharts/highcharts-convert.js:233
  /usr/local/phantomjs/lib/highcharts/highcharts-convert.js:541
  :/modules/webpage.js:281
```

Do you have a working example for me?

My goal is to be able to assign a function to the xAxis option tickPositioner after options parsing in highcharts-convert.js but before instantiation of the chart object. I could do that in the callback parameter, but that is to late.

Any help would be great.

**Comment by level420** [comment]
Another options would be to have a parameter named prepareoptions which should be a function with one parameter options eval-ed in higcharts-convert.js which would allow manipulating the options e.g. for assigning functions:

```
function(options) {
    options.xAxis.tickPositioner => function () {
		  var arr = [], i;
		                
		  for (i = this.min + 1; i <= this.max; i += this.tickInterval ) {
		      arr.push(i);
		  }
		  
		  return arr;
        }
}
````

**Comment by gvaartjes** [comment]
I'm not getting it (yet). 

Why not sending these options, including tickPositioner to the export server?

````js
{

        title: {
            text: 'Custom tick positions'
        },

        subtitle: {
            text: 'through axis.tickPositions and axis.tickPositioner'
        },

        xAxis: {
            tickPositions: [0, 1, 2, 4, 8]
        },

        yAxis: {
            tickPositioner: function () {
                var positions = [],
                    tick = Math.floor(this.dataMin),
                    increment = Math.ceil((this.dataMax - this.dataMin) / 6);

                for (tick; tick - increment <= this.dataMax; tick += increment) {
                    positions.push(tick);
                }
                return positions;
            }
        },

        series: [{
            data: [
                [0, 1],
                [1, 3],
                [2, 2],
                [4, 4],
                [8, 3]
            ]
        }]
    }
```

**Comment by level420** [comment]
It's because I'm creating the options in my perl backend as a hash and transform it into a JSON-structure. So I don't have the possibility to define a javascript function there.

In the end I'm communicating with phantomjs which is running as a webservice by POSTing a json structure.

The postprocessing option, which should be a simple string which is eval-ed in higcharts-convert.js, would allow to run code in higcharts-convert.js, which itself could assign functions to options.

I somehow need to transfer javascript code along with the POST data which is executed before the chart is instantiated.

**Comment by gvaartjes** [comment]
It's possible.. but you have to do it yourself. Just follow the same pattern as the _globaloptions_

Disclaimer: this is a very rough sketch

add around L.352 in highcharts-convert.js
```js
if (tickPositionerArg !== 'undefined') {
	loadScript('tickPositioner', tickPositionerArg);
}
```
With the above you make sure the ```tickPositioner``` holds te tickPositioner function, provided by the tickPositionerArg

At L.402 add this code;

```js
if (tickPositioner) {
  options.yAxis.tickPositioner = tickPositioner 
}
```
and you have to change the method signature of the ```createChart``` function

**Comment by level420** [comment]
Thank you Gert.

I already have a solution implemented myself, but was searching for a possibility to not patch highcharts-convert.js, thus using the original distributed file.

Is there any chance a pull request with a new parameter "postprocessoptions" for highcharts-convert.js get's accepted? The javascript code passed to postprocessoptions will then be  enveloped in a function:

```
if(postprcessoptionsArg !== 'undefined') {
    loadScript('postprocessOptions', 'function(options) { ' + postprocessoptionsArg + ' }');
}

postprocessOptions(options);
```

**Comment by gvaartjes** [comment]
No, I don't think so, the recommended way is to post process before you're sending it to PhantomJS. 

But you're welcom to list a feature request at [uservoice](http://highcharts.uservoice.com)

Best regards,

Gert

**Comment by level420** [comment]
Gert, thank you for your patience.

Regards
Dietrich

**Comment by berlinger-rarents** [comment]
Fyi, I'm currently happily using the `customcode` parameter to run some custom code _before_ HighCharts starts rendering. In my case I need (_need_ is a big word of course, there are always alternatives) to set a global variable used by some custom module.

Would be nice though if `-dataoptions` was optional.

```js
// file dataoptions.js
{}
```

```js
// file customcode.js
window.myVar = 'something';
```

```sh
phantomjs highcharts-convert.js -dataoptions dataoptions.js -customcode customcode.js
```

**Comment by TorsteinHonsi** [comment]
@larsac07 @cvasseng I believe this belongs in the highcharts-export repo?

**Comment by larsac07** [comment]
@TorsteinHonsi Yes, it looks that way. Since we're phasing out the `highcharts-convert.js`-script, and as this is an enhancement, I think it should only be relevant for the node-export-server repo. Agree, @gvaartjes @cvasseng @TorsteinHonsi ?

**Comment by gvaartjes** [comment]
@larsac07 Agree

**Comment by gvaartjes** [comment]
@berlinger-rarents Hi, the nodejs based export server will be the preferred highcharts export server. makes it sense for you to move over to nodejs? Then we can recreate the issue in the repo there.
