### ISSUE TITLE
[Waterfall charts] Intermediate sums with the same value are not plotted

### ISSUE THREAD

**Issue by maheshjag** [highslide-software/highcharts.com#4030]
In this chart: http://jsfiddle.net/maheshjagadeesan/6e3aauhL/, intermediate sums to the left and right of "Operating Profit" aren't drawn

**Comment by stephanevanraes** [comment]
OPEX/COGS has a value of 0 so it is normal it is not drawn.
Sales & Marketing also has a value of 0 so it is also not drawn.

Operating is a intermediateSum, but intermediateSum gives you the change relative to the last intermediateSum (revenue TOTAL in your case) which is, in your case, 0. (the only value between the 2 is OPEX/COGS which is 0).
