### ISSUE TITLE
HighCharts 4.1.4: off-by-one error in line hover width (JSFiddle)

### ISSUE THREAD

**Issue by mcayland** [highslide-software/highcharts.com#4035]
Within our application we allow the user to specify the hover style (particularly line width) on a per-series basis. Since upgrading to HighCharts 4.1.x series, there appears to be an off-by-one error in the lineWidth calculation which gives a lineWidth change on hover even when series.lineWidth === series.states.hover.lineWidth.

To reproduce:

1) Visit the JSFiddle at http://jsfiddle.net/gfuc2j1o/2/

2) Hover the mouse over the line series

Note that while both the series lineWidth and the series hover lineWidth are both set to 3, there is still a visible change in lineWidth during the hover.

Some initial investigation indicates that the lineWidth is being altered in Series.setState():

<pre>
if (state) {
    lineWidth = (stateOptions[state].lineWidth || lineWidth) + (stateOptions[state].lineWidthPlus || 0);
}
</pre>

Since lineWidthPlus always appears to be present and set to 1, the hover lineWidth will always be different to the series lineWidth during the hover state, even when set to the same numeric value.

**Comment by highslide-software** [comment]
#### Workaround
Set `lineWidthPlus` to 0. [View it on JSFiddle](http://jsfiddle.net/highcharts/gfuc2j1o/3/).
