### ISSUE TITLE
Documentation for tooltip.pointFormat is obsolete

### ISSUE THREAD

**Issue by Resposta42** [highslide-software/highcharts.com#4037]
By reading [this description](http://api.highcharts.com/highcharts#tooltip.pointFormat):

> ### pointFormat: String
> The HTML of the point's line in the tooltip. Variables are enclosed by curly brackets. Available  variables are `point.x`, `point.y`, series.name and series.color and other properties on the same form. Furthermore, `point.y` can be extended by the `tooltip.yPrefix` and `tooltip.ySuffix` variables. This can also be overridden for each series, which makes it a good hook for displaying units.
>
> Defaults to ● `{series.name}`: `{point.y}`
>
> Try it: [A different point format with value suffix](http://jsfiddle.net/gh/get/jquery/1.7.2/highslide-software/highcharts.com/tree/master/samples/highcharts/tooltip/pointformat/)

It seems that `yPrefix` and `ySuffix` options doesn't exist anymore, and they were replaced with `valuePrefix` and `valueSuffix`, but missed to also reflect that change on the above excerpt.

**Comment by highslide-software** [comment]
Thanks! It's fixed now.
