### ISSUE TITLE
Highstock: Occurs error 'setAttribute' undefined during switching series with different ranges 

### ISSUE THREAD

**Issue by PrzemekGonera** [highslide-software/highcharts.com#4039]
In my case when I am trying to update series with different ranges of dates (they should be provide as object, not array of points) I am getting error on console that element has no method setAttribute. First time it works but when I click button again in order to set data to the first series I get the mentioned error (see attached below image). Also I noticed that this issue causes that in navigator the series isn't updated as well.

![image](https://cloud.githubusercontent.com/assets/9800507/6843732/d3562902-d3a5-11e4-8d05-8998f309f79d.png)

Example: http://jsfiddle.net/7o8u5L9v/15/

**Comment by pawelfus** [comment]
Looks properly in 4.1.8: http://jsfiddle.net/7o8u5L9v/16/ - could you confirm?

**Comment by PrzemekGonera** [comment]
Everything looks fine. Thanks.
