### ISSUE TITLE
printing pie's dataLabels numbers with commas

### ISSUE THREAD

**Issue by Danny-weebo** [highslide-software/highcharts.com#4041]
hey, I'm trying to print numbers with commas (showing 9,000 instand of just 9000), this is the way I'm setting the format
format: '{point.name}: {point.y}'

I cant find a way to get {point.y} into a function that will return the wanted result, 
I tried this way format: '{point.name}: '+ numberWithCommas(point.y) but then of course point is not defined I'm not sure how to handle it,
any direction how can I make it work ?

thanks

**Comment by stephanevanraes** [comment]
you have to set the global language options to use , as a thousands seperator, add this part before the code that generates the charts:
```javascript
Highcharts.setOptions({
    lang: {
        thousandsSep: ','
    }
});
```

API: http://api.highcharts.com/highcharts#lang.thousandsSep
