### ISSUE TITLE
Treemap: drilldown to 3rd level through single elem. in 2nd level does not work

### ISSUE THREAD

**Issue by KacperMadej** [highslide-software/highcharts.com#4046]
Example: http://jsfiddle.net/8tuzgm28/
Steps:
1. Click to drill down into lvl 0
2. Click to drill down into lvl 1
Only back button text changed, but no drill down is performed.
Cannot access lvl 2C (to show lvl 3)

Expected behavior as in this example: 
http://jsfiddle.net/8tuzgm28/1/
(lvl 0 > lvl 1 > lvl 2C > lvl 3)

**Comment by jon-a-nygaard** [comment]
Problem: when the axis extremes were the same values as last redraw, the series.isDirty was newer set to true. isDirty is now set explicit to true before chart.redraw().

Any users who would like to avoid downloading a new version of the treemap.js can fix this issue manually by:
1. Open treemap.js in a text editor.
2. Search and locate the function drillToNode.
3. Insert <code>this.isDirty = true;</code> on a new line before the following code <code>this.chart.redraw();</code>
