### ISSUE TITLE
setExtremes not working in 4.1.4

### ISSUE THREAD

**Issue by SteveSchreiner** [highslide-software/highcharts.com#4047]
![set-extremes-broken-in-4 1 4](https://cloud.githubusercontent.com/assets/1679643/6874656/6a8c59f6-d48f-11e4-9c9b-44c706c3c7ca.png)

**Comment by highslide-software** [comment]
Live demo please?

**Comment by pawelfus** [comment]
Simple test: http://jsfiddle.net/euqx3ps3/ - works fine, I think.

**Comment by highslide-software** [comment]
Okay, I'm closing this. Feel free to open it again when a live demo is available.
