### ISSUE TITLE
Series pointStart and pointEnd not working for data format{x:xval,y:yval} for linear x axis

### ISSUE THREAD

**Issue by salunkenagesh14** [highslide-software/highcharts.com#4048]
series pointStart and pointEnd values are not working for linear axis with series data format
series:[{
   data : [{x:value,y:value}]
}]

Please see the demo : http://jsfiddle.net/5okppb3q/2/

**Comment by stephanevanraes** [comment]
The API states: *If no x values are given for the points in a series, pointStart defines on what value to start.*
Your data has x values defined so pointStart is ignored.
