### ISSUE TITLE
Dynamic dataGrouping and variable time intervals for data

### ISSUE THREAD

**Issue by mattheworiordan** [highslide-software/highcharts.com#4050]
I am having quite a few problems getting HighStock to present data the way I would like it, and keep hitting odd runtime errors.

To give you some background, I am loading in time series data with varying granularity based on the recency, so for metrics less than 8 hours, the granularity of the data is per minute, for any data up to 14 days, it's by hour, and for data beyond 14 days it's measured per day.  I assumed `dataGrouping` could be used, but I am having a number of problems, see http://jsfiddle.net/xckaxaf2/8/.

The issues I am having are:

* If I specify a dataGrouping of say `units: [ ['minute', [1]], ['hour', [1]], ['month', [1]] ]`, I have no way of controlling when each type of grouping is used. This is a problem because if the extremes are set for a time that is before the 1 minute interval 8 hours data and it uses minute then the data is incomplete, and equally by default the groupings are not right when less than an hour.  I need some explicit way of setting the grouping.
* If I change the dataGroupings programatically I get two errors: `Uncaught TypeError: object is not a function(index):83, Highcharts.StockChart.chart.events.redraw` and `Uncaught TypeError: Cannot read property 'length' of undefined, jquery-1.9.1.js:747 jQuery.extend.grephighstock.js:259`.  You can see this error easily in the JSFiddle above by clicking on 24h or 1m.
* The yAxis seems to be using values outside of the current extremes.  You will notice that when the JSFiddle loads the extremes are set to exactly data within the 8 hour window, yet the yAxis is scaled based on a value that is just before the 8 hour window that is approximately 60 times greater.  If you look in the console you will see the greatest value is written to the console.  It seems that the extremes are affected by values adjacent to the values within the extremes.

If there is anything specifically I can do to help I'll do what I can.  I've spent over a day trying to work around this but not had any luck unfortunately.

**Comment by pawelfus** [comment]
Possible workaround/solution:

Wrap method responsible for dataGrouping, and set that option there: http://jsfiddle.net/xckaxaf2/9/

    (function (H) {
        H.wrap(H.Series.prototype, "processData", function (c) {

            var chart = this.chart,
                dg = this.options.dataGrouping,
                currentUnits = dg.units[0][0],
                min = chart.xAxis[0].min,
                targetUnit = getUnitFromRangeStart(min);


            if (currentUnits !== targetUnit) {
                console.log('Changing interval from ' + currentUnits + ' to ' + targetUnit);
                /* Change grouping for all charts other than the navigator */
                dg.units = [
                    [targetUnit, [1]]
                ];
            }
            c.call(this);

        });
    })(Highcharts);

`dataGrouping.forced` option needs to be set to true of course.

**Comment by mattheworiordan** [comment]
@pawelfus, thanks so much for the reply, it's really appreciated.  However, I've tried that JSFiddle and it's not working, am I missing something?  The problems I am seeing are:

* The bottom navigator is not interval aware and therefore thinks half the data in minutes is half the data, whereas it is only 8 hours of more granular data.
* The 8h, 7d, 1m buttons don't do anything?  I see the console message is called, but then nothing happens beyond that?
* Using the navigator to zoom in one data is not possible now?

Thanks again, but I am not clear on how that has solved the problem?

**Comment by pawelfus** [comment]
Two things:

- navigator needs to be removed
- my mistake when calling default method from the prototype

Fixed version: http://jsfiddle.net/xckaxaf2/11/

    (function (H) {
        H.wrap(H.Series.prototype, "processData", function (c) {

            var chart = this.chart,
                dg = this.options.dataGrouping,
                currentUnits = dg.units[0][0],
                min = chart.xAxis[0].getExtremes().min,
                targetUnit = getUnitFromRangeStart(min);

            if (currentUnits !== targetUnit && this.name !== "Navigator") {
                dg.units = [
                    [targetUnit, [1]]
                ];
            }
            c.apply(this, Array.prototype.slice.call(arguments, 1));
        });
    })(Highcharts);

By the way, in your `getUnitFromRangeStart` shouldn't you use `<=`? Also, `min` can be undefined in my solution - consider such case.

**Comment by mattheworiordan** [comment]
@pawelfus thanks again.  The navigator is pretty important, can you think of any way we could make the navigator work correctly so that it groups the data based on the entire duration of time?

**Comment by pawelfus** [comment]
But do you want to update navigator's dataGrouping too? Then simply remove `&& this.name !== "Navigator"`. But IMHO it looks strange when you change extremes in the navigator and navigator updates itself..

**Comment by mattheworiordan** [comment]
@pawelfus, thanks again.

I agree the navigator should not update when the extremes change, so instead the navigator should always group by day whereas the other series can group based on the extreme selected.

I managed to get it all working as expected at http://jsfiddle.net/xckaxaf2/12/.  For others doing this, please note that I had to add the dataGrouping approximation to the navigator series explicitly so that the message count was `sum`ed instead of averaged.

@pawelfus I believe this issue can be closed, although it seems odd that we have to "hack" into Highcharts to achieve this functionality, it's a shame there isn't an API available to handle this sort of pre-processing before render.

**Comment by highslide-software** [comment]
For your informaion, I did a little experiment with defining data grouping on each range selector button. [View jsFiddle](http://jsfiddle.net/gh/get/jquery/1.7.2/highslide-software/highcharts.com/tree/master/samples/highcharts/studies/series-datagrouping-dynamic/).

**Comment by mattheworiordan** [comment]
@highslide-software, interesting, but I am not sure that really solves the problem well because then any changes made in the slider would not update the grouping correctly.  Nice solution for users who click the range buttons though, thanks.

**Comment by highslide-software** [comment]
@mattheworiordan Yes that's a problem. I did some work now to make it release the forced data grouping whenever the slider or input boxes are touched, but it still doesn't work correctly.

**Comment by highslide-software** [comment]
@mattheworiordan I've fixed that problem now. Once the range is changed using either the slider or the input boxes, the forced data grouping is removed.

**Comment by highslide-software** [comment]
Finished the implementation and added it to the master. The result can be seen at http://jsfiddle.net/tqyyqmzs/. It will be part of the next release.

**Comment by nopchok** [comment]
Can I change type of chart? (from Stock to Column)

**Comment by sebastianbochan** [comment]
Hi @nopchok,
The github is our bugtracker, so for general [support](http://www.highcharts.com/support) questions, please use the forum / stackoverflow or email.
