### ISSUE TITLE
"min" and "max" in the navigator

### ISSUE THREAD

**Issue by Vangi** [highslide-software/highcharts.com#4053]
I already posted a question in [stackoverflow](https://stackoverflow.com/questions/29011989/using-of-min-and-max-in-the-navigator) but I didn't get any solution. 

So, here is the demo: [http://jsfiddle.net/Vangi/fpnayfuq/6/](http://jsfiddle.net/Vangi/fpnayfuq/6/). 

Expected result: The left navigator handler (highcharts-navigator-handle-left) should be at the beginning of the navigator (highcharts-navigator).

Actual result: There is a gap from the beginning of the navigator and the left navigator handle.

Note: This occurs after I updated the Highstock version from 1.3.8 to 2.1.2.

**Comment by highslide-software** [comment]
The bug is that `navigator.xAxis.min` and `navigator.xAxis.max` are ignored if the dataMin and dataMax is exceeding the setting.
