### ISSUE TITLE
Stacked Perecentage Column click event: wrong series

### ISSUE THREAD

**Issue by banejo** [highslide-software/highcharts.com#4058]
It seems that starting with version 4.1.0, when the click event fires, you are unable to accurately access the series that was clicked.

Current Version (you almost always get "Joe" when clicking on either series.  sometimes you can get "Jane" if you click on "Jane" series before clicking on "Joe" series):
http://jsfiddle.net/ra1bbaLr/

Version 4.0.4 (you get "Jane" when clicking on "Jane" series, and "Joe" when clicking on "Joe" series)
http://jsfiddle.net/yvu6xqmr/1/

Version 4.1.0 (similar behavior as current version)
http://jsfiddle.net/dsvckdkp/1/

**Comment by highslide-software** [comment]
This is fixed in the latest dev branch: http://jsfiddle.net/ra1bbaLr/1/.
