### ISSUE TITLE
IE8: 3d scatter points does not respond to clicks

### ISSUE THREAD

**Issue by KacperMadej** [highslide-software/highcharts.com#4059]
Example: http://jsfiddle.net/1o4a3v4u/

(3d column works fine: http://jsfiddle.net/1o4a3v4u/2/embedded/result/show/)

**Comment by pawelfus** [comment]
It's general issue connected to the halo. Disable it to make it work: http://jsfiddle.net/1o4a3v4u/5/

Closing this ticket, see general issue here: #4363
