### ISSUE TITLE
code.highcharts.com does not give 304's.

### ISSUE THREAD

**Issue by hichris1234** [highslide-software/highcharts.com#4060]
I'm currently using highcharts in my webapp. When I load my app for the second time, http://code.highcharts.com/highcharts.js and http://code.highcharts.com/modules/exporting.js output a `200 OK` instead of a `304 Not Modified` even if nothing has changed. This makes load take around 1.5 seconds longer. Could the CDN please give 304's to speed up load? Thanks!

**Comment by gvaartjes** [comment]
Hi, I just changed some settings, now it's returning a 304. Thanks for letting us know!

Best regards, 

Gert

**Comment by hichris1234** [comment]
Thank you!
