### ISSUE TITLE
setData with different amount of values is not animating

### ISSUE THREAD

**Issue by beregovoy** [highslide-software/highcharts.com#4064]
http://jsfiddle.net/r9ms3nwc/ here is example

**Comment by pawelfus** [comment]
I think this is how it works, according to the [docs](http://api.highcharts.com/highcharts#Series.selected): 

> updatePoints: Boolean
> When the updated data is the same length as the existing data, points will be updated instead of replace. This option prevents this, and makes setData behave like it did prior to Highcharts 3.0.10.

**Comment by beregovoy** [comment]
Oh. Yeah. you are right. My fault. Sorry
