### ISSUE TITLE
null color rendered as black in bar charts with colorByPoint enabled

### ISSUE THREAD

**Issue by borys-p** [highslide-software/highcharts.com#4068]
When colorByPoint is enabled, then series' "null" color is silently cast to 0, which renders as black. It should behave as "undefined" and be simply ignored.

**Comment by borys-p** [comment]
Example: http://jsfiddle.net/fhmorgkg/

**Comment by stephanevanraes** [comment]
Technically it behaves as expected, in SVG a fill color of **null** is rendered like that: http://jsfiddle.net/x4snb59j/

**Comment by borys-p** [comment]
I see, but this is a SVG quirk, very unintuitive IMHO.

In JS null is... well, null ;) Nor empty nor undefined. I would expect it to silently skip a "null" color as invalid. We (users) shouldn't be expected to know all the SVG rendering issues, we have only the JS API available.

Also, skipping null makes it easier to output datapoints directly from database, without extra conditions like "if color is not defined then remove this value from the array".
