### ISSUE TITLE
SetVisible on Pie Charts are very slow on chart with large legend in IE11

### ISSUE THREAD

**Issue by dejongch** [highslide-software/highcharts.com#4069]
Looking into it it looks like between [4.1.1](http://jsfiddle.net/Luh4nf7m/) and [4.1.2](http://jsfiddle.net/849ux00y/) something changed and made changes to the legend of large pie graphs incredibly slow. So something like hiding an item from the legend or updating the series to set the hideHiddenPoint option takes upwards of 20 seconds in IE11

**Comment by highslide-software** [comment]
It seems to come from this commit: 5bd795a

**Comment by dejongch** [comment]
I am still having a few issues with the Pie chart in version 4.1.2 and higher

Specifically I have a button that when pressed with either enable or disable all the pie slices depending on if all the slices are currently selected.

This jsfiddle (http://jsfiddle.net/hs9z6o2v/) has something similar to what I am doing and with it the legend items and the datalabels do not update properly. This works fine in 4.1.1.

On my application I also get more serious issues where in IE 11 the enable all button seems to completely freeze the system and it never comes back. In Chrome it freezes for awhile but does come back however the pie only has some slices drawn and the redraw function does not seem to see the changes done to the visible bools. I can't however get this to reproduce in a jsfiddle.
