### ISSUE TITLE
Column blurry in pdf export

### ISSUE THREAD

**Issue by mikegodber** [highslide-software/highcharts.com#4071]
Hi,

I have set out a fiddle to show the issue - http://jsfiddle.net/sfyex6tb/3/

When plotting column and line series on the same chart, and then exporting as pdf, sometimes the column series appear blurred. It appears to depend on the order the series are declared, so if the columns are declared first and the line last then the columns will be blurred but if a column is declared last then the resultant pdf should be fine.

This appears to be similar to a bug that has recently been fixed with line charts where all but the last series were blurred.

Many thanks,
Mike Godber

**Comment by mikegodber** [comment]
Hi,

Is there any more info on this?

Mike

**Comment by highslide-software** [comment]
I can't seem to find the issue that you mention, where lines were blurry. Tested with multi-line charts some versions back, but they all seem to render fine. 

However, I found #1782 that is probably related.

Also, I found that by removing the individual series clipping at https://github.com/highslide-software/highcharts.com/blob/v4.1.4/js/parts/StockChart.js#L579, the problem goes away. Which is probably safe unless we're using multiple panes.

**Comment by mikegodber** [comment]
Hi,

Am I right in thinking this is now fixed? I've just looked through my fiddle and all seems to be working.

If so, was the fix in the export server, and is the fix in a tagged version or just the master?

Cheers,

Mike

**Comment by highslide-software** [comment]
Okay, then we can assume it is working. I wasn't able to reproduce it. 

> If so, was the fix in the export server, and is the fix in a tagged version or just the master?

I'm not sure, but if you have time, you can try old Highcharts versions to check when it was fixed.

**Comment by mikegodber** [comment]
I just tried specifying the Highstock version 2.1.5 js files in my fiddle and the problem came back, so it looks like simply upgrading the js should fix the issue for us.

Thanks

**Comment by highslide-software** [comment]
Ok, great!
