### ISSUE TITLE
Second line of title centered with CSS in exported chart is rendered outside the viewport

### ISSUE THREAD

**Issue by borys-p** [highslide-software/highcharts.com#4073]
I believe this is a very low priority issue, but quite weird.

I've been trying to add some padding to the centered title in exported charts and ran into this:
http://jsfiddle.net/fhmorgkg/3/

Effect:
![chart-5](https://cloud.githubusercontent.com/assets/10867553/7042900/9ed77376-dde5-11e4-99f4-6620425cc3fc.png)

I know that `title: { align: center }` works properly, but I need more control to add custom logo in the top left corner and force the title not to overlap it.

**Comment by highslide-software** [comment]
It's basically the same as #2473. I see you are using the `allowHTML` flag in your demo, but that doesn't help without also applying [the patch](https://gist.github.com/highslide-software/7582596).

I set up a demo where the contents of the gist are pulled out into a snippet: http://jsfiddle.net/highcharts/6ubtyu3b/

**Comment by borys-p** [comment]
Yes, I've seen #2473 and added this extra useHTML just to be sure :) But I didn't see the last comment which is exactly my problem, sorry, you can close this ticket as duplicate.
