### ISSUE TITLE
Threshold and negative color create rendering issues on Highstock charts

### ISSUE THREAD

**Issue by groseb** [highslide-software/highcharts.com#4075]
I am using dataGrouping to group data by month, trimester or year.
When combining this with threshold and negativeColor, changing the grouping range makes the renderer go crazy and several lines appear and stay.

Disabling the negativeColor attribute fixes the rendering.

Demo :
http://jsfiddle.net/groseb/k6erv8yu/2/

**Comment by highslide-software** [comment]
Simplified demo: http://jsfiddle.net/rc7b1eda/

The problem is that the zone elements don't get destroyed on update.
