### ISSUE TITLE
yAxis.showLastLabel seems to be defaulting to false, not true as the documentation says 

### ISSUE THREAD

**Issue by caguthrie** [highslide-software/highcharts.com#4080]
http://api.highcharts.com/highcharts#yAxis.showLastLabel

This seems to be defaulting to false, the documentation says it's defaulting to true.

**Comment by highslide-software** [comment]
It is true by default: http://www.highcharts.com/demo/line-basic . 

Are you sure you're not talking about Highstock? http://api.highcharts.com/highstock#yAxis.showLastLabel
