### ISSUE TITLE
Map of Iowa (USA): wrong lat / lon

### ISSUE THREAD

**Issue by KacperMadej** [highslide-software/highcharts.com#4084]
It seems that map of Iowa (USA) - http://code.highcharts.com/mapdata/countries/us/us-ia-all.js - has wrong lat / lon coordinates.

Example: http://jsfiddle.net/pg3ambaL/7/

Compare with map of USA: http://jsfiddle.net/gh/get/jquery/1.9.1/highslide-software/highcharts.com/tree/master/samples/maps/demo/latlon-advanced/
Compare with Google Maps: https://www.google.pl/maps/place/Iowa,+USA/

**Comment by schinckle** [comment]
We noticed the same issue with a few other US state maps listed below:

Michigan
http://code.highcharts.com/mapdata/countries/us/us-mi-all.js

New Mexico
http://code.highcharts.com/mapdata/countries/us/us-nm-all.js

New York
http://code.highcharts.com/mapdata/countries/us/us-ny-all.js

North Carolina
http://code.highcharts.com/mapdata/countries/us/us-nc-all.js

North Dakota
http://code.highcharts.com/mapdata/countries/us/us-nd-all.js

Pennsylvania
http://code.highcharts.com/mapdata/countries/us/us-pa-all.js

South Carolina
http://code.highcharts.com/mapdata/countries/us/us-sc-all.js

West Virginia
http://code.highcharts.com/mapdata/countries/us/us-wv-all.js

**Comment by schinckle** [comment]
I tried using the <em>"hc-transform": { "default"</em> values from the corresponding state congressional maps and the points appeared to be in the right place for all maps that are listed above. So fixing those values may be enough to address the issue.

**Comment by vishalrp** [comment]
Is there a temporary fix available for this issue?

**Comment by oysteinmoseng** [comment]
The current temporary fix is to use the "hc-transform" object from the corresponding congressional map, and hope that it works... 

Example: http://jsfiddle.net/pg3ambaL/8/

We are looking into the details of the issue to find out what's gone wrong.

**Comment by oysteinmoseng** [comment]
This seems to be an issue with the Proj4 library, that has been fixed in later versions. Simply updating the library fixes the problem: http://jsfiddle.net/pg3ambaL/9/

**Comment by vishalrp** [comment]
Thank you!

**Comment by schinckle** [comment]
Great - thanks!

**Comment by the-codepunker** [comment]
Hi there,

This seems to still be an issue for Michigan. 
Have a look: http://jsfiddle.net/jqLheob1/1/

The geo coordinates I used in the example above are valid Michigan coordinates, but in high-maps they are  way off. See examples below: 

https://www.google.ro/maps/place/42%C2%B053'13.9%22N+83%C2%B036'11.9%22W/@42.7406946,-83.8216211,9z/data=!4m5!3m4!1s0x0:0x0!8m2!3d42.8872!4d-83.6033

https://www.google.ro/maps/place/42%C2%B000'51.5%22N+86%C2%B030'13.3%22W/@41.2475874,-87.5382065,3490303m/data=!3m1!1e3!4m5!3m4!1s0x0:0x0!8m2!3d42.0143!4d-86.5037

Can you guys help ?

**Comment by sebastianbochan** [comment]
There seems to be an issue with some of the USA admin2 map projections. It's not yet clear if this is an issue with Proj4js or a problem on our end. For now, there are a few workarounds.

1: Instead of using the Michigan map, use the highest detail country-wide map of USA, and remove the states you don't want included. Example: http://jsfiddle.net/v9ke6dbk/

2: Use the Michigan map, but use the lat/lon transform data from the Michigan Congressional Districts map. Example: http://jsfiddle.net/goL6rL5k/

3: Create your own custom map (http://www.highcharts.com/docs/maps/custom-geojson-maps) and add lat/lon transform data to it manually (http://www.highcharts.com/docs/maps/latlon).

**Comment by oysteinmoseng** [comment]
@the-codepunker See https://github.com/highcharts/highcharts/issues/5714

**Comment by the-codepunker** [comment]
This works perfectly... Thank you @sebastianbochan @oysteinmoseng !

**Comment by zxlin** [comment]
It's not an issue with `proj4`, using `proj4` version 2.5.0, I'm seeing this issue on Michigan state: http://jsfiddle.net/pabvce4f/ (the points are so far away, it doesn't even show the points in Michigan) 

And of course, we yoink the `hc-transform` from the congressional map, it works: http://jsfiddle.net/s5bLjcgw/

This seems like the normal Highmaps definitions (`/mapdata/countries/us/us-mi-all.js`) are incorrect, @sebastianbochan is that an accurate assessment?

**Comment by KacperMadej** [comment]
@zxlin 
Thank you for reporting about the problem.
I have moved your issue report to the correct repository - if you have any comments to add please do: https://github.com/highcharts/map-collection-dist/issues/40
