### ISSUE TITLE
usage of momentjs in getTimezoneOffset example

### ISSUE THREAD

**Issue by zenob** [highslide-software/highcharts.com#4085]
The sample code in http://jsfiddle.net/gh/get/jquery/1.7.2/highslide-software/highcharts.com/tree/master/samples/highcharts/global/gettimezoneoffset/, accessible from Highcharts API reference/global/getTimezoneOffset contains a mistake in the usage of momentjs:

The used function `timezoneOffset = moment.tz.zone(zone).parse(timestamp)` is supposed to take a local time constructed from date.UTC, not a UTC timestamp. This cause problem on the day of dst change.( see http://momentjs.com/timezone/docs/#/zone-object/parse/ )

If the example is modified to display a point per hour instead of day we can spot the error: the time of dst change is 05:00->04:00 instead of 03:00->02:00 as seen here : http://jsfiddle.net/rwyx14h7/
The code I can propose to replace it is : `timezoneOffset = -moment.tz(timestamp, zone).utcOffset();`
this corrects it : http://jsfiddle.net/bLnxgjyL/

This is not a major issue but I guess people wanting to use this functionnality will copy the code of the example and have trouble figuring out what is happening (like I just did ... )

**Comment by Attrash-Islam** [comment]
That fix caused as to fix a bug in our HighCharts usage at the company. Thanks a lot :heart:
