### ISSUE TITLE
Repeated click on the date in the "From - To" fields does not trigger expected result.

### ISSUE THREAD

**Issue by Cybermage83** [highslide-software/highcharts.com#4091]
Hello Highsoft AS  team,

In highStock, clicking on the date the first time, works as expected, but when clicked elsewhere and clicked back on the date field, nothing happens.  The only way to change the date is to click on the alternative date and return. 

This should not be the case, please look into this and resolve. We can not release a new version of your library because of this bug. Thank you.

http://jsfiddle.net/gh/get/jquery/1.9.1/highslide-software/highcharts.com/tree/master/samples/stock/demo/basic-line/

**Comment by highslide-software** [comment]
Fixed since 872c94e5.

This will be released with the next maintenance. To apply it to the current release, see [Apply a fix](https://github.com/highslide-software/highcharts.com#apply-a-fix).
