### ISSUE TITLE
Timeseries data does not work for waterfall charts

### ISSUE THREAD

**Issue by fredpe** [highslide-software/highcharts.com#4094]
Using xAxis type `datetime` does not work for waterfall charts. Instead it's always showing "Jan 1st" for all data points. See http://jsfiddle.net/6c6ugyhj/1/ . I would expect the same behavior as for type `line`.

**Comment by highslide-software** [comment]
The actual issue isn't with `datetime` axis, but rather with array point definitions. Which means you can work around the problem by defining points as objecs instead: http://jsfiddle.net/highcharts/6c6ugyhj/2/

**Comment by fredpe** [comment]
That was fast, awesome job :+1:
