### ISSUE TITLE
Highstock: Tooltip's crosshairs relating to y axis show wrong data for multiple panes

### ISSUE THREAD

**Issue by KacperMadej** [highslide-software/highcharts.com#4095]
Example is created by adding tooltip options from Highstock demo: http://jsfiddle.net/9fxurLhb/

Hovering over first pane creates horizontal crosshair in second pane. The crosshair is placed at same pixel distance from top of second y axis as the distance from first crosshair to top of first y axis. Expected behavior seems to be for crosshairs to mark the value of corresponding point.

**Comment by stephanevanraes** [comment]
Duplicate of #2888
