### ISSUE TITLE
Stacking + threshold - wrong colors

### ISSUE THREAD

**Issue by sebastianbochan** [highslide-software/highcharts.com#4096]
It seems as possibly bug, because shapes are printed from threshold value and when we set color with transparency, chart looks like incorrect.

Example: http://jsfiddle.net/hz8fopan/5/

**Comment by highslide-software** [comment]
How should sub-threshold points be drawn do you think? They can't be drawn below the threshold (like with a 0 threshold) as they are not really negative. Skipping them also feels wrong...

**Comment by highslide-software** [comment]
Stacking seems to be wrong also for positive values. When I stack 1 + 2 + 3 on a threshold on -10, I would expect them to stack up to -4. But now it totals to 6: http://jsfiddle.net/highcharts/hz8fopan/13/

**Comment by stephanevanraes** [comment]
It might *feel* wrong, but it is technically not, the *total value* is 6, if you have set only **3** on a threshold of -10 you would not expect it to go to -9 neither.

**Comment by highslide-software** [comment]
Maybe we need to treat it differently depending on whether the columns are stacked or not. Given that the threshold is -10:

* If the columns are __not__ stacked, a column with value 5 will extend from the threshold to 5 on the Y axis, and a column with value -5 will extend from -10 to -5. This is how it currently works, see [jsFiddle](http://jsfiddle.net/highcharts/sc9vtujr/).
* If the columns are stacked, a column with value 5 will extend from the threshold and 5 units up, thus ending on -5 on the Y axis. A column with value -5 will extend from the threshold and 5 units down, ending on -15 on the Y axis. Now subsequent series will be stacked either on top or below these values.

**Comment by josefsachsconning** [comment]
Torstein, I absolutely agree with the second point (regarding stacked bars).
As for the first point (regarding non-stacked bars), it seems to me that
whether stacked or not, the length of each bar should correspond to the
magnitude of the observation value.  It seems to me that is a basic tenet
of bar charts.  As the [Wikipedia article](http://en.wikipedia.org/wiki/Bar_chart) says, "with rectangular bars with lengths proportional
to the values that they represent".

**Comment by highslide-software** [comment]
This makes sense @josefsachsconning . I've implemented this as an option for now. And it only works on stacks, as it would require more logic to make it work on non-stacked columns. View [demo on jsFiddle](http://jsfiddle.net/highcharts/hz8fopan/14/).

There's also a question what to do with stacked areas. Should we expect them to behave the same?

**Comment by josefsachsconning** [comment]
Is there any way that I can see the new behavior?  code.highcharts.local is not available to me.

**Comment by josefsachsconning** [comment]
As for the stacked area charts, yes, I think they should behave the same, except that mixing positive and negative observations should probably be considered outside the domain for this type of chart, since it would not be sensible to connect adjacent observations with different signs.  If that is not sufficiently clear, let me know and I'll provide an example.

**Comment by highslide-software** [comment]
Sorry, updated fiddle at http://jsfiddle.net/highcharts/hz8fopan/15/

**Comment by josefsachsconning** [comment]
Thanks, that looks just like I wanted it.  It also looks like the "incorrect colors" were an artifact of this problem, though I don't exactly understand the connection.

**Comment by josefsachsconning** [comment]
Could you tell me what the documentation will say for plotOptions.column.startFromThreshold?  It appears that my desired behavior requires that this option has the default value of 1, correct?

**Comment by highslide-software** [comment]
With the current implementation in the dev branch, it is `true` by default on columns, but not on area. And it only works when stacking is enabled. A more thorough treatment is probably needed, but that would take more time.
