### ISSUE TITLE
Linked category names demo does not work.

### ISSUE THREAD

**Issue by KacperMadej** [highslide-software/highcharts.com#4101]
Label on click do not open the link.

Demo: http://jsfiddle.net/gh/get/jquery/1.7.2/highslide-software/highcharts.com/tree/master/samples/highcharts/xaxis/labels-formatter-linked/

Demo can be found in API reference: http://api.highcharts.com/highcharts#xAxis.labels.formatter

**Comment by pawelfus** [comment]
It's caused by the same origin policy, from the Chrome web tools:

>  Refused to display 'http://www.google.pl/search?q=foo&gws_rd=cr&ei=-baCVcVigZqwAanAgagC' in a frame because it set 'X-Frame-Options' to 'SAMEORIGIN'.
