### ISSUE TITLE
Highmaps: Tooltip covers points in top of the chart

### ISSUE THREAD

**Issue by KacperMadej** [highslide-software/highcharts.com#4110]
Example: http://jsfiddle.net/xzd39mt8/
Steps:
1. Zoom in, so plot area is full of countries.
2. Hover over top of the chart.
3. Move over countries and over tooltip at the same time.
4. Move horizontally to other country.
5. Tooltip is not changing and covers points.

If followPointer is true (by default in Highmaps), then in tooltip's getPosition function point doesn't have h variable (point.h is undefined) and later y position is returned as NaN when cursor is in top of the chart.

**Comment by pawelfus** [comment]
Works fine in 1.1.8: http://jsfiddle.net/x06b0xre/
