### ISSUE TITLE
Regression module - setting exponential type doesn't work

### ISSUE THREAD

**Issue by sebastianbochan** [highslide-software/highcharts.com#4111]
Example: http://jsfiddle.net/3vruC/132/

**Comment by sebastianbochan** [comment]
Reported in author's github: https://github.com/streamlinesocial/highcharts-regression/issues/13

**Comment by Infinite2mekashyap** [comment]
again when i am going to change the regression type into logarithmic.. it is not rendering. series data is same. (http://jsfiddle.net/3vruC/137/)

**Comment by pawelfus** [comment]
I suggest to post that info on plugins repo. It looks like first point is the culprit, changing from `0` to `0.x` resolves issue: http://jsfiddle.net/3vruC/138/

**Comment by Infinite2mekashyap** [comment]
Exponential Regression is not working on negative value.
kindly fix this issue : http://jsfiddle.net/3vruC/178/

**Comment by pawelfus** [comment]
I suggest to post your request on the plugin's repo.. ;)
