### ISSUE TITLE
Broken tooltips in pie charts when useHTML is enabled

### ISSUE THREAD

**Issue by natalan** [highslide-software/highcharts.com#4117]
When `useHTML` is enabled in pie charts, under some conditions, the position of tooltip background is not consistent with tooltip's content
![image](https://cloud.githubusercontent.com/assets/276187/7235609/10258420-e75d-11e4-845b-fdbcd4463000.png)

Demo: http://jsfiddle.net/L3sdonrf/1/
Hover over 'Other' field to see mentioned above issue. 

I believe it consistently reproduces in all supported browsers, and related to calculated y-value of tooltip's background.

In our setup it's a regression after updating to Highstock v2.1.5 from v2.1.4

**Comment by highslide-software** [comment]
Fails since 1a05759
