### ISSUE TITLE
panning doesn't work combined with inverted

### ISSUE THREAD

**Issue by mhwlng** [highslide-software/highcharts.com#4123]
I am using inverted columnrange chart (Highchart 4.1.5) like this :

http://jsfiddle.net/Ye3Ak/4/

zooming works  (if you use 'y' instead of 'x'), but panning doesn't work :

        chart: {
          zoomType: 'y',
          panning: true,
          panKey: 'shift',
          type: 'columnrange',
          inverted: true
        },

**Comment by KacperMadej** [comment]
Simplified example: http://jsfiddle.net/43tfsgf4/
Same issue as: https://github.com/highslide-software/highcharts.com/issues/4077
