### ISSUE TITLE
Treemap - click on legend item returns error

### ISSUE THREAD

**Issue by sebastianbochan** [highslide-software/highcharts.com#4124]
Example: http://jsfiddle.net/5h5jds8v/

**Comment by scristescu** [comment]
Hello gents,
No change on this ticket yet?

Thanks,
Sorinel C.

**Comment by jon-a-nygaard** [comment]
Quick fix, before the Highcharts options add the following code:
```javascript
Highcharts.seriesTypes.treemap.prototype.pointClass.prototype.setVisible = Highcharts.seriesTypes.pie.prototype.pointClass.prototype.setVisible
```

Treemap is now able to hide the points in dataclasses in the same way as Highmaps.

**Comment by scristescu** [comment]
Hi Jon,

Thank you fro the fix. I tried the workaround with the pie.setVisible handler and I can see cell are hidden are displayed. So, this is a proof that the event from user is processed.

Like usually, you know, I am super happy of the complete solution. In case of pie/bar or line/area charts when a slice/bar/graph is hidden you redo the chart layout, by redrawing the left in a new pie/bar or line charts, as that that wasn't there in the first place.
In the Treemap you just make the cell indivisible, but the layout of the tree remains the same. Imagine, I have a Treemap with one huge cell, and a lot of small ones; then I want to hide the big one and see the ration of the left small cells. With your solution I cannot. 

That why I am asking you for redoing the tree layout with the left visible cells, after hiding one group of cells. (for regular geographical maps this would be not a good approach, but for treemap, I think, this is mandatory).

Thank you very much,
Sorinel C.

**Comment by scristescu** [comment]
One more detail: the same story happens for the Heatmap with dataClasses for the color axis.
- so, you have to fix this over there too !!!
