### ISSUE TITLE
Incorrect number of segments in polar line chart

### ISSUE THREAD

**Issue by cogwire** [highslide-software/highcharts.com#4125]
If xAxis is of type "category", min and max options should be ignored as values are non-numeric.

Example showing behaviour: http://jsfiddle.net/9ur4qh8o/3/
12 segments are shown, while the data contains 13 categories.

![correct number of segments](https://cloud.githubusercontent.com/assets/12067980/7274877/cfd5e50e-e900-11e4-8959-9363fb443133.JPG)

Removing the following lines, or replacing **null** with **undefined**, will display the correct behaviour.

14:     "max": null,
15:     "min": null,

![incorrect number of segments](https://cloud.githubusercontent.com/assets/12067980/7274878/cfedcfc0-e900-11e4-871d-c485007d5303.JPG)

**Comment by highslide-software** [comment]
Not sure I understood this. In your fiddle, 13 categories are shown, as expected.

Min and max values on a category axis refers to the index of the category. Like in [this fiddle](http://jsfiddle.net/highcharts/LLExL/4439/), where the `min` category is 0 (January) and the `max` category is 3 (April).

**Comment by cogwire** [comment]
My bad, I forgot to click "Update" in jsFiddle. Link is updated in the original post, but I include it here as well.
http://jsfiddle.net/9ur4qh8o/3/

**Comment by cogwire** [comment]
Could it be that the issue is only related to **max: null** ? I have tried a few variations of your fiddle and am able to replicate my issue by replacing  max: 3   with max: null

**Comment by highslide-software** [comment]
Yes, use max: undefined instead, or simply leave it out.
