### ISSUE TITLE
Tooltip for bubble series is not displaying on chart that also has different type series

### ISSUE THREAD

**Issue by KacperMadej** [highslide-software/highcharts.com#4126]
Line and bubble - no tooltip for bubble (tooltip just twitches / jumps in place).
Example: http://jsfiddle.net/t8ufsqzw/

**Comment by highslide-software** [comment]
Fails since d228fa0.

**Comment by pawelfus** [comment]
Works fine for 4.1.6+ : http://jsfiddle.net/t8ufsqzw/3/
