### ISSUE TITLE
Series.update - mouse over event - errors

### ISSUE THREAD

**Issue by sebastianbochan** [highslide-software/highcharts.com#4130]
Example: http://jsfiddle.net/2LcnLLLy/4/

**Comment by pawelfus** [comment]
Workaround: add shadows on your own: http://jsfiddle.net/2LcnLLLy/5/

        plotOptions: {
            series: {
                events: {
                    mouseOver: function () {
                        var _self = this;
                        $.each(this.points, function(i, p) {
                            if(p.graphic) {
                                p.graphic.shadow({
                                    color: this.color,
                                    width: 8,
                                    offsetX: 0,
                                    offsetY: 0                                    
                                }, self.group);
                            }
                        }); 
                    },
                    mouseOut: function () {
                        var _self = this;
                        $.each(this.points, function(i, p) {
                            if(p.graphic.shadows) {
                                $.each(p.graphic.shadows, function(j, shadow) {
                                   p.graphic.safeRemoveChild(shadow); 
                                });
                            }
                        });
                    }
                }
            }
        },
