### ISSUE TITLE
polar custom labels

### ISSUE THREAD

**Issue by 1534854467** [highslide-software/highcharts.com#4134]
var lineName = "test";
      var labels = ["North","East", "South", "West" ];
      var yvals = [100, 50, 70, 40];

      drawRadarChart(lineName, labels, yvals);

     function drawRadarChart(lineName, labels, yvals){
	$(function () { 
		var pointInterval = parseInt(360 / labels.length);
		var chartlabel = labels.slice();

    	var t = $('#div-radarChart').highcharts({ 
	        credits:{
			     enabled:false
			},  
	          
	       	chart: {
	            polar: true,
	            width: 300,
	            height:300,
	        },
	        title: {
	            text: '雷达图'
	        },

	        pane: {
	            startAngle: 0,
	            endAngle: 360
	        },

	        tooltip: {
	        	formatter: function(pointInterval, tooltip){
	        		var header = '<span style="font-size: 10px">'+ labels[ this.x / parseInt(360 / labels.length) ] +'</span><br/>'
	        		var point = '<span style="color:' + this.series.color + '">\u25CF</span> ' + this.series.name + ': <b>' + this.y + '</b><br/>';
	        		return header + point;
	        	}
	        },

	        xAxis: {
	            tickInterval: pointInterval,
	            min: 0,
	            max: 360,
	            labels: {
	                formatter: function () {
	                    return chartlabel.shift();
	                }
	            }
	        },

	        yAxis: {
	            min: 0
	        },

	        plotOptions: {
	            series: {
	                pointStart: 0,
	                pointInterval: pointInterval
	            },
	            column: {
	                pointPadding: 0,
	                groupPadding: 0
	            }
	        },

	        series: [{
	            type: 'line',
	            name: lineName,
	            data: yvals
	        }] 
	    });
    });
}

**Comment by KacperMadej** [comment]
In the Highcharts Forum you'll find questions and answers. We use GitHub Issues as our official bug tracker. See rules of reporting issues: https://github.com/highslide-software/highcharts.com/blob/master/readme.md#reporting-issues

Topic is now on forum - please continue there: http://forum.highcharts.com/topic32813/
