### ISSUE TITLE
Highcharts Cloud: Google Spreadsheet data + Custom code in Customize tab gives no data

### ISSUE THREAD

**Issue by KacperMadej** [highslide-software/highcharts.com#4135]
Steps:
1. Inside the Highcharts Cloud editor if you click 'open the grid' 
2. paste in the Spreadsheet code - 1Fbo-5hjMu0Cr-_H6DURWmwREgJ4Ir7u9zAbao_jKrQ8 
3. go to Customize > Code > Custom code 
4. uncomment the default code 
5. 'No data to display'
Using any custom code with google spreadsheet data gives the same error.

Manually adding options from Generated options fixes the problem, so it seems that merging doesn't work as well as it should here.

**Comment by highslide-software** [comment]
Please close this when listed in the Cloud repo. 

PS: Maybe we should have a shadow repo for cloud issues?

**Comment by gvaartjes** [comment]
Hi, 

This is fixed now
