### ISSUE TITLE
Windows 8 IE 11 touch gesture error: Object doesn't support property or method 'onContainerTouchEnd'

### ISSUE THREAD

**Issue by gumatias** [highslide-software/highcharts.com#4137]
I recently got this error from a user, and unfortunatelly doesn't seem to be very easy to replicate. Before I dig into the issue myself I was wondering if this is just me or is it a known bug?

Here's all the relevant info I got from the error:

##### Error message 
Object doesn't support property or method 'onContainerTouchEnd'

##### User info
browser name: IE
browser version: 11.0.0
locale: en-US
OS name: Windows 8.1

##### Target
<path fill="rgba(224, 252, 150, 1)" stroke-linejoin="round" transform="translate(0)" d="M 34.8071 136.927 A 77.5 77.5 0 0 1 29.0198 46.0441 L 48.6639 58.4809 A 54.25 54.25 0 0 0 52.715 122.099 Z">
Type: pointerup
Which: 1

##### Stack trace
https://myapp-com/assets/app-13891fd573fa9a69aae0e956e2108f99.js:26:1948:in `Bb': Object doesn't support property or method 'onContainerTouchEnd' (TypeError)
	from https://myapp-com/assets/app-13891fd573fa9a69aae0e956e2108f99.js:26:2429:in `onDocumentPointerUp'
	from https://myapp-com/assets/app-13891fd573fa9a69aae0e956e2108f99.js:9:16454:in `m.event.dispatch'
	from https://myapp-com/assets/app-13891fd573fa9a69aae0e956e2108f99.js:9:13149:in `r.handle'

##### Line 
"touch"!==a.pointerType&&a.pointerType!==a.MSPOINTER_TYPE_TOUCH||!X[oa]||(d(a),d=X[oa].pointer,d[b]({type:c,target:a.currentTarget,preventDefault:ma,touches:Ub()}))};q(Va.prototype,{onContainerPo

**Comment by highslide-software** [comment]
A search in the issues for "onContainerTouchEnd" gives me this: https://github.com/highslide-software/highcharts.com/pull/4027. This was pulled in and released with Highcharts 4.1.5. Are you using an older version?

**Comment by gumatias** [comment]
Cool! Was actually using 4.1.4. Upgrading right now. thanks!
