### ISSUE TITLE
Legend in IE9 with text-overflow:ellipsis

### ISSUE THREAD

**Issue by pbenes** [highslide-software/highcharts.com#4138]
When the legend is configured with custom width and `text-overflow: ellipsis`, IE9 shows only the first letter of the legend (whereas in ff, chrome, the text is correctly shortened)

http://jsfiddle.net/7m3rv32q/

IE9:
![ie9-legend](https://cloud.githubusercontent.com/assets/998317/7342564/63255930-ecb6-11e4-8897-68084608aae0.png)

Chrome:
![chrome-legend](https://cloud.githubusercontent.com/assets/998317/7342569/66acba1c-ecb6-11e4-8d47-ac6e22be385e.png)

(I did not want to use useHTML: true because it does not allow paging and long legend cannot be scrolled in case there are many series...)

**Comment by highslide-software** [comment]
For some reason, the `overflow: hidden` rule makes the bounding box report a bogus width. So you can work around the issue by removing that: http://jsfiddle.net/7m3rv32q/1/ .

**Comment by pbenes** [comment]
Thank you very much! Works fine, closing the issue.
