### ISSUE TITLE
Is it possible to stretch horizontal colorAxis of Heatmap?

### ISSUE THREAD

**Issue by seleckis** [highslide-software/highcharts.com#4139]
I want to stretch horizontal colorAxis to fit heatmap width. How can I do it? And, by the way, is it possible to flip marker (triangle) of the colorAxis, to position it at the bottom of colorAxis, not above?

**Comment by highslide-software** [comment]
Hi, you have come to the Highcharts issue tracker. For general usage questions, please www.highcharts.com/support.
