### ISSUE TITLE
MinPointLength on stacked bar chart

### ISSUE THREAD

**Issue by GMartigny** [highslide-software/highcharts.com#4140]
Hello,

I tried to add a minPointLength on a percent stacked bar chart in order to visualize empty values. But, it 's not working as expected.
http://jsfiddle.net/f9tzha2s/1/
Point with value to 0 aren't shown and it's quite difficult to compare each stack.
Weirdly, if I comment "reversedStacks: false", minPointLength is effective but not for the last option.

I hope it helps

**Comment by sebastianbochan** [comment]
Seems that the same problem with "default stacked bar".

Example: http://jsfiddle.net/0196fv4L/5/

**Comment by Jmaharman** [comment]
+1 to both of the above.

**Comment by highslide-software** [comment]
Duplicate of #1776
