### ISSUE TITLE
First column not displayed until rangeselector click

### ISSUE THREAD

**Issue by sebastianbochan** [highslide-software/highcharts.com#4147]
Steps to replicate
1) Run example: http://jsfiddle.net/6qusyg6a/2/
2) First column in not displayed, (also when we set pointPadding / groupPadding / pointRange etc)
3) Click on Alle
4) Back to 6M, first column exists

**Comment by pawanvjadhav** [comment]
Any update on this?

**Comment by GreenRover** [comment]
+1

**Comment by prdatur** [comment]
+1

**Comment by sebastianbochan** [comment]
+1
