### ISSUE TITLE
Google indexes description tag for Google News and Alert

### ISSUE THREAD

**Issue by gvaartjes** [highslide-software/highcharts.com#4152]
By indexing the SVG description tag,  the phrase _created by Highcharts_ is part of the text used by Google in Google News and Google Alerts. This is unwanted behaviour. We should move the text to another meta tag, if available

![screen shot 2015-04-30 at 20 39 12](https://cloud.githubusercontent.com/assets/951644/7420011/4b95c91a-ef79-11e4-8cd0-fb099687a050.png)

http://goo.gl/alerts/QhRE

**Comment by highslide-software** [comment]
But that's the description that comes up when Google Alerts is searching
for "Highcharts". When searching differently, like `site:
marylandreporter.com freddie gray`, the description is different.​
