### ISSUE TITLE
Bloated dataLabels compared to 4.0.4

### ISSUE THREAD

**Issue by drmrbrewer** [highslide-software/highcharts.com#4153]
Compare the dataLabels in the latest version:

http://jsfiddle.net/drmrbrewer/y6d67xj3/

to the dataLabels in 4.0.4:

http://jsfiddle.net/drmrbrewer/y6d67xj3/1/

The padding around the text used to be about right: not too much, and evenly spaced all around.  Now, there is more padding (way too much IMHO), and what is more it's asymmetric (more on the bottom than the top).

Is this intentional?  Seems like a backward step IMHO, but maybe there's a way of customising it back to what it was?

**Comment by highslide-software** [comment]
See http://api.highcharts.com/highcharts#plotOptions.series.dataLabels.padding

**Comment by drmrbrewer** [comment]
Hmm, what about the asymmetry?  The use of `padding` doesn't solve that.  See e.g.:

http://jsfiddle.net/drmrbrewer/y6d67xj3/2/

**Comment by highslide-software** [comment]
There is a small difference between browsers, but it you add a glyph that extends below the baseline, you'll see that it needs the space below: http://jsfiddle.net/highcharts/y6d67xj3/3/

**Comment by drmrbrewer** [comment]
For me (in Chrome browser) there is still extra space even below the 'j' compared to the space above... doesn't look good IMHO:

![capture](https://cloud.githubusercontent.com/assets/9009792/7450428/baf11cfe-f23c-11e4-9ca0-ced22535ecda.JPG)

**Comment by highslide-software** [comment]
Yes I can see that too in Chrome on Windows. In Chrome on Mac, the `j` is actually touching the lower border. The problem is that this difference comes from how the browser reports the bounding box of the text element itself, so it is hard for us to go in and override or do best guesses on that.

**Comment by drmrbrewer** [comment]
It just seems to me that 4.0.4 had a better compromise.  On Mac Chrome, what does the 'j' look like in the 4.0.4 version?  Does it actually go outside the box?

latest: http://jsfiddle.net/drmrbrewer/5ygecw1c/6/
4.0.4: http://jsfiddle.net/drmrbrewer/5ygecw1c/7/

screenshots from Windows Chrome:

latest:
![latest](https://cloud.githubusercontent.com/assets/9009792/7451781/a5faa5da-f24c-11e4-8dce-ed34844b3b8b.JPG)

4.0.4:
![old version](https://cloud.githubusercontent.com/assets/9009792/7451784/af6f7a96-f24c-11e4-8e7d-1af0c8e3b6cb.JPG)

**Comment by drmrbrewer** [comment]
And here are screenshots of the bold label from a different Windows PC (running the same version of Chrome!):

latest:

![new](https://cloud.githubusercontent.com/assets/9009792/7451872/ef6afc50-f24d-11e4-837d-a1bbff34c548.JPG)

4.0.4:

![old](https://cloud.githubusercontent.com/assets/9009792/7451873/f46c1de2-f24d-11e4-9515-008e72deb08e.JPG)

**Comment by drmrbrewer** [comment]
Seems that the choices / best guesses made in 4.0.4 were just a bit better than in the latest version, but maybe that's only with my setup.

One option would be to allow the user to set left, right, top, bottom padding separately?

**Comment by highslide-software** [comment]
> but maybe that's only with my setup.

Yes, we increased the padding in order to avoid the text from covering point markers.

> One option would be to allow the user to set left, right, top, bottom padding separately?

It would still be inconsistent between browsers.

**Comment by drmrbrewer** [comment]
> It would still be inconsistent between browsers.

Not if you're rendering the chart on the server with phantomjs and delivering the chart in png format... in that case you have a known and consistent 'browser' environment, and it would be nice to have finer control over the label padding to override defaults to get the optimum appearance.

And, with my dataLabels I know for certain whether I'll have any downward-extending glyphs (I don't have any... they're either numbers of a limited set of letters with all above the base line).  So the extra useless padding at the bottom of each label just makes the whole chart look less 'polished'.

**Comment by pawelfus** [comment]
If this is only for exporting, how about using renderer? So you can freely edit rectangle parameters. Simple demo: http://jsfiddle.net/y6d67xj3/4/

        chart: {
            events: {
                load: function () {
                    var chart = this,
                        r = chart.renderer,
                        box,
                        x, y;

                    Highcharts.each(chart.series[0].data, function (point, i) {
                        if (point.dataLabel) {
                            box = point.dataLabel.getBBox(true);

                            x = point.plotX + box.x + chart.plotLeft - box.width / 2;  // edit X val
                            y = point.plotY + box.y + chart.plotTop - box.height / 2; // edit Y val
                            
                            r.rect(x, y, box.width, box.height, 5).attr({ // box.width && box.height can be changed
                                fill: 'rgba(252, 255, 197, 0.7)',
                                "stroke-width": 1,
                                "stroke": '#AAA'
                            }).add();
                        }
                    });

                }
            }
        }

**Comment by drmrbrewer** [comment]
Thanks, that seems like quite a nice workaround.
