### ISSUE TITLE
Repeating category on scatter does not render correctly

### ISSUE THREAD

**Issue by sergioharo** [highslide-software/highcharts.com#4154]
In a linear x-axis scatter plot, the x-axis is allowed to have duplicate entries. For example, the data could be [[1, 1], [1,2], [2,1]] and this will render correctly as seen in http://jsfiddle.net/smg6d98c/

However, when doing something similar with categories, we get a different behavior. If my data is [["1", 1], ["1",2], ["2",1]], I will instead get 3 x-axis points. See http://jsfiddle.net/8ko8g9op/

**Comment by highslide-software** [comment]
Highcharts doesn't check categories against each other. If you want more control, set xAxis.categories, and use the X value of the point to link to category. See http://jsfiddle.net/highcharts/8ko8g9op/1/.
