### ISSUE TITLE
Missing comma in number format

### ISSUE THREAD

**Issue by pismobiker** [highslide-software/highcharts.com#4157]
In my site and in the highchart examples, where a comma should be displayed "(format :.,0d}" there is only a blank.  You can see this problem at
http://jsfiddle.net/highcharts/rmTWS/
I've implemented a custom formatter to side-step the issue, so there is a work around.

**Comment by highslide-software** [comment]
Duplicate of #3833. See http://api.highcharts.com/highcharts#lang.thousandsSep
