### ISSUE TITLE
Errorbar series and multiple y-axes combo breaks chart

### ISSUE THREAD

**Issue by paulflakstad** [highslide-software/highcharts.com#4158]
Using errorbar series in combination with multiple y-axes breaks the chart.

To reproduce this issue, add an errorbar series to the existing "multiple y-axes" example:
http://jsfiddle.net/gh/get/jquery/1.9.1/highslide-software/highcharts.com/tree/master/samples/highcharts/demo/combo-multi-axes/

For example: 
```javascript
{
    name: 'Rainfall error',
    type: 'errorbar',
    yAxis: 1,
    data: [
        [48.9, 50.9],
        [70.5, 72.5],
        [105.4, 107.4],
        [128.2, 130.2],
        [143.0, 145.0],
        [175.0, 177.0],
        [134.6, 136.6],
        [147.5, 149.5],
        [215.4, 217.4],
        [193.1, 195.1],
        [94.6, 96.6],
        [53.4, 55.4]
    ],
    tooltip: {
        pointFormat: ' {point.low}-{point.high} mm'
    }
}
```

**Comment by pawelfus** [comment]
Maybe you are missing `highcharts-more.js` file in your project? It works fine, I guess: http://jsfiddle.net/11xe37ha/

**Comment by paulflakstad** [comment]
You are right, Paweł. My bad :)
