### ISSUE TITLE
Missing Data Chart is not working for Stacked Area Chart

### ISSUE THREAD

**Issue by raghits** [highslide-software/highcharts.com#4165]
Emulating behavior similar to http://www.highcharts.com/demo/area-missing 

Using same dataset for both scenarios below:
* AreaSpline chart works as expected: http://jsfiddle.net/8a6q671u/6/
* Area chart doesn't work: http://jsfiddle.net/8a6q671u/5/

Also verified it is not fixed in the most recent version.

**Comment by highslide-software** [comment]
This is what we're working on in #2069. Here's what your chart will look like: http://jsfiddle.net/highcharts/8a6q671u/7/

**Comment by raghits** [comment]
Thanks for the update.
