### ISSUE TITLE
Shared tooltip formatter returning false prevents marker to return to normal state on mouseleave chart

### ISSUE THREAD

**Issue by KacperMadej** [highslide-software/highcharts.com#4166]
In Highstock:
When tooltip's formatter returns false (as described in API - to prevent tooltip from showing), then hovering over points (e.g. line series) makes each hovered point change state. If mouse leaves chart state of hovered point should return to normal (as this normally happens), but this is not the case.

Simple example: http://jsfiddle.net/3mw7p4wy/
(Problem visible in Windows 7 on: Chrome, Firefox and IE11)

Workaround: set shared for tooltip to false - http://jsfiddle.net/3mw7p4wy/1/

**Comment by highslide-software** [comment]
Turns out it is not specificly a Highstock problem, it applies with Highcharts too when the tooltip is shared: http://jsfiddle.net/highcharts/3mw7p4wy/2/
