### ISSUE TITLE
Highstock: breaks on yAxis not working

### ISSUE THREAD

**Issue by KacperMadej** [highslide-software/highcharts.com#4167]
After applying breaks on y axis chart breaks.
Highstock: http://jsfiddle.net/ta6rzeoh/
Using Highstock to create Highcharts chart: http://jsfiddle.net/ta6rzeoh/1/

**Comment by stephanevanraes** [comment]
Note: works fine on Highcharts http://jsfiddle.net/ta6rzeoh/2/
