### ISSUE TITLE
Hide pie slice from legend animation

### ISSUE THREAD

**Issue by oysteinmoseng** [highslide-software/highcharts.com#4170]
When hiding a pie slice by clicking on it in the legend, the selection halo is not animated and stays behind.

Can be observed in the [pie legend demo](http://jsfiddle.net/gh/get/jquery/1.9.1/highslide-software/highcharts.com/tree/master/samples/highcharts/demo/pie-legend).

**Comment by pawelfus** [comment]
Simple workaround: http://jsfiddle.net/4r2mr8qr/

    (function (H) {
        H.wrap(H.seriesTypes.pie.prototype.pointClass.prototype, 'setVisible', function (p, v, r) {
            p.call(this, v, r);
            if (!this.visible) {
                this.setState("");
            } else {
                this.setState("hover");
            }
        });
    })(Highcharts)
