### ISSUE TITLE
Heatmaps - drillup / drilldown events not catched

### ISSUE THREAD

**Issue by sebastianbochan** [highslide-software/highcharts.com#4171]
Example: http://jsfiddle.net/nsb181Lc/1/

For column chart works properly.

**Comment by highslide-software** [comment]
The demo shows a treemap, not heatmap as indicated in the title.

Also, it doesn't use the drilldown module and its events, but rather a similar concept that is special to treemaps. While the drilldown module allows drilling between series, the drill-to-node concept in treemaps drills between nodes and levels within the same series.

**Comment by MohanChennu** [comment]
Thanks for your reply. However the reply is not very clear to me. It would be great if you could provide an example (possibly fiddle) of using drill-to-node concept that is used by treemaps (as mentioned in previous reply). Actually what I am trying to do is that I am trying to dynamically set (or reset) the font size (&colors) of the labels for each level as I drill down/up. Your help is greatly appreciated.

**Comment by highslide-software** [comment]
I think it is explained at http://www.highcharts.com/docs/chart-and-series-types/treemap. See the `levelIsConstant` option. You probably want to set a dataLabel font size per level.

**Comment by MohanChennu** [comment]
Greatly appreciate your quick response. However I am trying to change the font/colors of levels as I drill/down. So i don't think it could be done with levelIsConstant option. It would be really great if you could point me to an example on how i could capture the drillup/down events or dynamically changing the font size/color for each level as i drill down/up using the following example. Appreciate your guidance.

http://jsfiddle.net/gh/get/jquery/1.7.2/highslide-software/highcharts.com/tree/master/samples/highcharts/plotoptions/treemap-allowdrilltonode/

Mohan
