### ISSUE TITLE
BarChart xAxis labels ellipsis not showing correctly

### ISSUE THREAD

**Issue by ctaschereau** [highslide-software/highcharts.com#4177]
If we have a very long label for one entry of our xAxis, it will not display correctly until the chart has been reflowd. 

See following jsfiddle : http://jsfiddle.net/6bm3p3cb/9/
You can simply move the vertical separator in jsfiddle to force a reflow.

The workaround that we used in our case was to do this : 

```javascript
// chartCfg gets filled elsewhere in the code. barChartEl is a jQuery element where we want to render
chartCfg.chart.renderTo = barChartEl[0];
(new Highcharts.Chart(chartCfg)).reflow();
```

**Comment by highslide-software** [comment]
Normalized demo: http://jsfiddle.net/highcharts/6bm3p3cb/10/
