### ISSUE TITLE
Highstock can't handle all-zeros series

### ISSUE THREAD

**Issue by illiptic** [highslide-software/highcharts.com#4180]
In highstock, for a multiple-series chart, if any serie is all-zeros, the whole chart is blank, including the overview. The tooltip displays correct values, nevertheless.

This can be seen here: http://jsfiddle.net/gu9rp1fm/

Highcharts has no problem with it: http://jsfiddle.net/wqnpxzcq/

**Comment by highslide-software** [comment]
It's not a problem with Highstock per se. The blank chart is a result of setting compare: percent on the series. Since any positive or negative value is infinate divided by 0, the chart is unable to draw. Here is the same chart without compare: http://jsfiddle.net/highcharts/gu9rp1fm/1/

**Comment by illiptic** [comment]
My bad, sorry for the bother!
