### ISSUE TITLE
Highchart: Series mouse events (click/mouseOver/mouseOut) report wrong series for line-chart

### ISSUE THREAD

**Issue by mikedaly** [highslide-software/highcharts.com#4181]
I'm using a line chart to display multiple series which may not have data samples at the same intervals. So when hovering over a line for one of the series, there may not be a data point on that series that is close to the x-location of the cursor. The behavior of the mouseOut/mouseOver/click events is confusing and (I think) wrong.

Here is a fiddle which clearly shows the behavior:
  https://jsfiddle.net/27bp59fp/

In the input data in the fiddle, Series 1 has two gaps where Series 2 has data: Feb and Apr. If you move the mouse over the Series 1 line in those sections, the mouseOver event will fire but it will indicate that you have moused over Series 2. This is clearly wrong, as the mouse is nowhere near that series. I think this is a bug. The point property of the event object passed to the handler is set to the point on Series 2, and this is set to the Series 2 object. The click, mouseOver, and mouseOut events all exhibit this same behavior.

I am open to workarounds, but I haven't been able to figure out how to get the information I need. I am trying to figure out what series lines are actually under the cursor when it is clicked so that I can do something useful with that series. Thoughts?

**Comment by highslide-software** [comment]
It seems to be fixed already in the development branch: http://jsfiddle.net/highcharts/27bp59fp/1/

**Comment by mikedaly** [comment]
Yep, I've confirmed it as well. Thanks!
