### ISSUE TITLE
There is no value displayed in Navigator if chart height is too low in Highstock

### ISSUE THREAD

**Issue by roman-dybinchyk** [highslide-software/highcharts.com#4186]
Hi, I need to show only navigator with possibility to set extremes by some button. If I set chart height param to value when graph is not seen, there is no data in Navigator. But if I set height value higher - graph and navigator have all needed data. 

That because (as I see), that height value of rect element of clipPath svg element is set to 0 in first case.

Reproduced in Chrome and FF in last Highstock JS version (v2.1.5 (2015-04-13))

working example : http://jsfiddle.net/Romeroo/s9L3kv9o/
not working example : http://jsfiddle.net/Romeroo/m2LdjL05/1/

**Comment by roman-dybinchyk** [comment]
up

**Comment by highslide-software** [comment]
This is already fixed in the latest dev code: http://jsfiddle.net/highcharts/m2LdjL05/2/.

We are currently testing the next maintenance release, that should be out during this week.
