### ISSUE TITLE
Refresh tooltip after chart.redraw (for Highstocks)

### ISSUE THREAD

**Issue by uaoleg** [highslide-software/highcharts.com#4188]
Can't figure out how to keep (or refresh) tooltip for a hovered point after chart.redraw() is called

**Comment by pawelfus** [comment]
It's not part of the official API, but you can try this way:

    chart.tooltip.refresh(point | array_of_points);

Use `point` for non-shared tooltip and `array_of_points` for shared one. 

For future problems I suggest to use one of our [support channels](http://www.highcharts.com/support) like forum/email ;)
