### ISSUE TITLE
Pie chart, text in middle not responsive

### ISSUE THREAD

**Issue by pedropcruz** [highslide-software/highcharts.com#4190]
Hello all,

My problem is the span that i created, can't be responsive and i need that. Can anyone help me with this?

http://codepen.io/pedropcruz/pen/PqNGar

Best Regards,

Pedro Cruz

**Comment by highslide-software** [comment]
Hi Pedro, this is the Highcharts issue tracker. For general tech support, please see www.highcharts.com/support.
