### ISSUE TITLE
tooltip problem in 4.1.5 for first point in multi series chart

### ISSUE THREAD

**Issue by HeaveNsHzj** [highslide-software/highcharts.com#4195]
Here is fiddle: http://jsfiddle.net/d724xgdy/6/
![08087aaa-d831-4fc5-a62e-3567323754d1](https://cloud.githubusercontent.com/assets/3302452/7665666/bf1163e4-fbf5-11e4-88f4-ac668c3ebd2a.png)

I update highcharts version from 4.1.4 to 4.1.5 to fix issues #4020,
but  4.1.5 cause tooltip on first point display in wrong way。

**Comment by highslide-software** [comment]
Duplicate of #3977 (fixed). 

Your demo looks like this with the fix applied: http://jsfiddle.net/d724xgdy/6/
