### ISSUE TITLE
Highstock v2.1.5 axis can't handle the option "ordinal" change properly

### ISSUE THREAD

**Issue by dreamershl** [highslide-software/highcharts.com#4196]
In the beforeSetTickPositions(), it will calculate the "ordinalPositions" if the axis.options.ordinal is true. But if the application change the axis.options.ordinal from "true" to "false", the function doesn't set the flag "axis.doPostTranslate" properly. So in the translate(), the axis will still believe the tick position should still rely on the outdated "ordinalPositions" array.

**Comment by highslide-software** [comment]
Demo: http://jsfiddle.net/highcharts/knvrz35z/

When starting with `ordinal:false` it correctly updates to `ordinal:true`.

**Comment by dreamershl** [comment]
This issue is more on the "ordinalPositions" re-calculation after the ordinal flag is changed. The demo is using the same data. While my case is I change the data array as well as the ordinal flag is changed. Later will change your example to demo this issue. Thx

**Comment by dreamershl** [comment]
I have modified the example to demo the issue. In the modified example, if I change the seriers data without redraw flag to true, the axis ticks are wrong even I put the "chart.redraw();" to redraw the chart later.

http://jsfiddle.net/pdu7Lp7f/3/

          chart.series[0].setData(!xAxis.options.ordinal ? data: data2, false);

**Comment by highslide-software** [comment]
Seems to work as expected with the fix applied: http://jsfiddle.net/highcharts/pdu7Lp7f/4/

**Comment by dreamershl** [comment]
Yes.. thx for the fast fix. now I can remove my patch in my app. Thx again
