### ISSUE TITLE
Treemap - ignoreHiddenPoint has no effect

### ISSUE THREAD

**Issue by jon-a-nygaard** [highslide-software/highcharts.com#4197]
Hidden points should be excluded from the area calculation. Right now they are hidden, but they still take up space.

Example with dataClasses. Click on one of the legend items to hide all points within a dataClass: http://jsfiddle.net/jon_a_nygaard/5h5jds8v/2/

**Comment by scristescu** [comment]
Hi Jon,

No solution for  this issue yet?

Thanks,
Sorinel C.

**Comment by jon-a-nygaard** [comment]
This will be released in the next maintenance.

**Comment by pawelfus** [comment]
Looks like still we can observer problems.

Case: `ignoreHiddenPoint` to true, and one of the leafs value = 0.

Demo: http://jsfiddle.net/ft9x6v59/

**Comment by scristescu** [comment]
Same thing happens for values < 0. So, Treemap should be able to manage (ignore) the leaf cells with values <= 0. 

And also to hide the parent cells which have all children hidden from the legend click !!!!

Thanks,
Sorinel C.

**Comment by pawelfus** [comment]
Temporary workaround: http://jsfiddle.net/0bwg3erv/1/

**Comment by jon-a-nygaard** [comment]
This new issue is fixed in a later version after commit 125b210eff76d8f7dbccee2dc99845a1990b3dda. 
I don't have a good quickfix for this, so I would recommend replacing the treemap module file with this commit version: https://raw.githubusercontent.com/highslide-software/highcharts.com/840b9f9810b5c785fb7166503727ff25120036cc/js/modules/treemap.src.js
