### ISSUE TITLE
plotBands zIndex

### ISSUE THREAD

**Issue by GreenRover** [highslide-software/highcharts.com#4207]
Hello,

this example: http://jsfiddle.net/qnrd7q4d/4/
Has a line and some plotBands.
If i open it with rangeSelector:all everything looks like it should.
All plotBands are behind the line.
If i open it with rangeSelector:1M and move the range selector to see all.
The plotBands that was displayed newly are above the line.

Please watch this Video.
https://youtu.be/Z8gyRABlmtw

**Comment by highslide-software** [comment]
You have given the plot bands a z index of 3, which is the same as the series group. When elements have the same z-index, the one that is last created will come out on top. To avoid that, use a z index of 2.5: http://jsfiddle.net/highcharts/qnrd7q4d/5/

**Comment by GreenRover** [comment]
Can you please add this fact to plotBand.zIndex documentation?
I dindt found any information about a build in zIndex of series Groups.

**Comment by highslide-software** [comment]
It's done, thanks!
