### ISSUE TITLE
Allow the DOM click to bubble

### ISSUE THREAD

**Issue by aldendaniels** [highslide-software/highcharts.com#4208]
#### Current Behavior
Highcharts stops propagation for `click` events occurring within the chart. 

Example: http://jsfiddle.net/fyrn31cv/

#### Expected Behavior
HighCharts should allow DOM events to bubble so that they can be handled be the containing page.

**Comment by highslide-software** [comment]
The cancellation comes from [this line](https://github.com/highslide-software/highcharts.com/blob/v4.1.5/js/parts/Pointer.js#L606) in highcharts.src.js:

`e.cancelBubble = true; // IE specific`

A quick research shows that the line dates back to [version 1.1](http://code.highcharts.com/1.1.0/highcharts.src.js), before we had issue tracking on GitHub and Highcharts was canvas based with an image map on top detecting clicks. 

Which means this line is due for reconsideration. I'll check if removing it has any unforeseen consequences in IE.

**Comment by aldendaniels** [comment]
@highslide-software - thanks!
