### ISSUE TITLE
Decimal tickIntervals should be disallowed for a category axis.

### ISSUE THREAD

**Issue by jgerigmeyer** [highslide-software/highcharts.com#4217]
If using a ``category`` axis without setting ``allowDecimals: false``, ``normalizeTickInterval`` can sometimes return a ``tickInterval`` of ``2.5``. This causes a ``tick.pos`` of ``2.5``, which in turn causes ``categories[pos]`` to be ``undefined`` and results in an incorrect label.

I would think this could be solved in a number of ways:

1. Not calling ``normalizeTickInterval`` on a ``category`` axis, by adding ``&& !categories`` to https://github.com/highslide-software/highcharts.com/blob/master/js/highcharts.4.1.4.js#L7412.

2. Adding ``!!categories`` to the fourth arg passed to ``normalizeTickInterval``: https://github.com/highslide-software/highcharts.com/blob/master/js/highcharts.4.1.4.js#L7420.

3. Defaulting ``allowDecimals`` to ``false`` for a ``category`` axis.

**Comment by highslide-software** [comment]
Can you show a live demo of this? You can use http://jsfiddle.net/highcharts/as25s8ga/ as a starting point.

**Comment by jgerigmeyer** [comment]
Sure. You can see a live demo of the bug at http://jsfiddle.net/jgerigmeyer/h705n915/.

I'm not sure if it only happens when you have two linked ``category`` axes, but that seemed to be the easiest way to demonstrate it.

**Comment by jgerigmeyer** [comment]
:+1:
