### ISSUE TITLE
A spelling issue confused me in label and string formatter 

### ISSUE THREAD

**Issue by minglotus** [highslide-software/highcharts.com#4220]
In Labels and string formatting(http://www.highcharts.com/docs/chart-concepts/labels-and-string-formatting) , I meet with the following lines:
**Variables are inserted width a bracket notation, for example "The point value at {point.x} is {point.y}".**
However, I wondered if "width" here is meant to be "with".
Thank you for your notation.

**Comment by highslide-software** [comment]
Absolutely. That's what you get when a front end developer writes plain English :)
