### ISSUE TITLE
Tooltip shows only year when xAxis.closestPointRange < 1 msec

### ISSUE THREAD

**Issue by vickychijwani** [highslide-software/highcharts.com#4223]
Demo: http://jsfiddle.net/vickychijwani/k6fjp52y/

The tooltip shows only the year even though timestamps are in sub-millisecond resolution. This is happening because [`timeUnits['millisecond'] > closestPointRange` is false](https://github.com/highslide-software/highcharts.com/blob/6ea3eb87a07ed44f91cbbc4cf06f43a6519d8f28/js/highstock.src.js#L9331) and [`lastN` is not initialized](https://github.com/highslide-software/highcharts.com/blob/6ea3eb87a07ed44f91cbbc4cf06f43a6519d8f28/js/highstock.src.js#L9318). I believe initializing `lastN = 'millisecond'` will fix the issue (works for me, at least).

**Comment by vickychijwani** [comment]
@highslide-software, tangential question: should I open a new issue if an option is undocumented in the Highstock reference but documented in Highcharts? I'm referring to http://api.highcharts.com/highcharts#Highcharts.dateFormats.

**Comment by highslide-software** [comment]
Yes, issues may also refer to issues with the docs
