### ISSUE TITLE
Axis.breaks doesn't display all points

### ISSUE THREAD

**Issue by pawelfus** [highslide-software/highcharts.com#4229]
Example: http://jsfiddle.net/uf06qk0a/3/

Steps:

- use scrollbar and move it to the right

In the console observe errors: 

> Invalid value for <path> attribute d="M -Infinity 281 L -Infinity 291
> Invalid value for <text> attribute x="-Infinity"

Image: 
![axis_breaks](https://cloud.githubusercontent.com/assets/1453926/7815968/e69a92ae-03cb-11e5-8920-ce9d1703ef1a.png)

`gapSize` is not necessary, but it's easier to observe the issue.

**Comment by sebastianbochan** [comment]
+ 1

**Comment by highslide-software** [comment]
Apparently the navigator doesn't translate correctly to the main X axis. The offset accumulates as we scroll towards the right, and culminates at the far right where we run out of corresponding X values.

The problem seems to lie in the `breakSize` option. When it is 0, the translation is correct: http://jsfiddle.net/highcharts/uf06qk0a/19/

**Comment by highslide-software** [comment]
The commit above fixes the problems in the right end of the navigator.

The remaining problem now is when scrolling the navigator across the empty area (the weekend). It gives a straight line, and sometimes even full sections of the main series. See http://jsfiddle.net/highcharts/uf06qk0a/20/. Click "Set extremes 2".

**Comment by grzesiekgs** [comment]
I've tested your example and found something which might be related to this issue.

http://jsfiddle.net/uf06qk0a/47/

click "set extremes 3" at least twice. Observe extremes in console. Navigator seems to stay in one place, but extremes change every time the button is clicked.
You can also recreate it by clicking "set extremes 3" once, and moving navigator just a little bit.

**Comment by highslide-software** [comment]
Thanks, but I think that's a problem with the test rather than with Highstock itself. The test is based on mouse movements, but not all information is added to the simulated handlers.
