### ISSUE TITLE
Export server: Using + produces an internal server error

### ISSUE THREAD

**Issue by KacperMadej** [highslide-software/highcharts.com#4232]
Example code to place in Options field on https://export.highcharts.com/

```js
{
	series: [{
		data: [29.9, 71.5, 106.4, 129.2, 144.0, 176.0, 
			135.6, 148.5, 216.4, 194.1, 95.6, 54.4],
      dataLabels: {
        enabled: true,
        formatter: function(){
          return 6+3;
        }
      }
	}]
};
```

In strings + are treated as spaces.
Example for formatter in above code:
return '6+++3';

Example of working code in jsFiddle: http://jsfiddle.net/5xedgptc/

**Comment by highslide-software** [comment]
@gvaartjes Another case of URL encoding

**Comment by gvaartjes** [comment]
I pasted the code into the demo page on export.highcharts.com. And it works... ? Am I doing something wrong?

**Comment by KacperMadej** [comment]
It works now. It wasn't working when I reported the issue.

**Comment by gvaartjes** [comment]
ok, glad it works now
