### ISSUE TITLE
Zooming in on a histogram with datetime axistype makes the plot disappear

### ISSUE THREAD

**Issue by reactormonk** [highslide-software/highcharts.com#4234]
Fiddle: https://jsfiddle.net/7nk5vap5/1/ - zoom in into e.g. 2012 to 2014. All the data disappears.

**Comment by pawelfus** [comment]
You have errors in the console:

> Highcharts error #15: www.highcharts.com/errors/15

So, sort your data by `x` values ascending, and will work: http://jsfiddle.net/7nk5vap5/2/
