### ISSUE TITLE
Inverted chart: plot not visible if negativeColor is set

### ISSUE THREAD

**Issue by KacperMadej** [highslide-software/highcharts.com#4237]
If inverted is set to true and negative color is set, then plot is not visible.
This applies to line type series and other types connected.

Example: http://jsfiddle.net/tnxqhzzr/2/

Issue is not present in 4.1.4: http://jsfiddle.net/tnxqhzzr/3/

**Comment by pawelfus** [comment]
Bug applied only to 4.1.5 version. 4.1.6 works fine.
