### ISSUE TITLE
Highstock: arearange nor areasplinerange do not work with dataLabels enabled

### ISSUE THREAD

**Issue by KacperMadej** [highslide-software/highcharts.com#4244]
In Highstock arearange nor areasplinerange series types are not working when dataLAbels.enabled is set to true. Error in Chrome console: "Uncaught TypeError: Cannot read property 'high' of undefined".

Example based on arearenge Highstock demo: http://jsfiddle.net/vgkboff8/1/

The issue is present in Chrome and IE11, but in Firefox the chart is working fine.

**Comment by pawelfus** [comment]
Workaround: disable `rangeSelector.selected`. Demo: http://jsfiddle.net/vgkboff8/3/

It looks like in `highcharts-more.js` method `drawDataLabels` doesn't check if point is currently visible.
