### ISSUE TITLE
High Chart x-axis zoom in bug on y-axis break

### ISSUE THREAD

**Issue by dragonlive** [highslide-software/highcharts.com#4247]
demo: http://jsfiddle.net/wmscqdf4/

Try to zoom in the chart with one of the break column but WITHOUT the highest column. It will show nothing after zoom in.

zoom in:
![screen shot 2015-05-29 at 7 08 27 pm](https://cloud.githubusercontent.com/assets/7044520/7895236/2a5f4180-0636-11e5-8bc0-4d2525676795.png)

After zoom in:
![screen shot 2015-05-29 at 7 07 59 pm](https://cloud.githubusercontent.com/assets/7044520/7895238/34c60172-0636-11e5-9cd6-90dccdbc7b6d.png)

**Comment by highslide-software** [comment]
It's a problem with axis breaks. When we zoom in starting on the points that lie within the break, all data is gone. 

Simplified demo: http://jsfiddle.net/highcharts/wmscqdf4/1/

**Comment by highslide-software** [comment]
Your demo with the fix applied: http://jsfiddle.net/highcharts/wmscqdf4/2/
