### ISSUE TITLE
xAxis labels overlapping

### ISSUE THREAD

**Issue by chtefi** [highslide-software/highcharts.com#4250]
Hi,

When I have a lot of labels (or not actually), I sometimes can see some label overlapping that I don't want.

If you take a look at this jsfiddle, you will see some labels overlapping each other at the end of the xAxis: http://jsfiddle.net/f0v3p4oe/1/
(moreover, if you refresh it multiple times, you can see different results.)

If I change any properties (spacing, rotation..), that can fix itself. But I can't, they are generated automatically from a given config. The fiddle is the minimum config core that still generate the issue.

Is there a workaround for now ?
Or a possible bug fix directly in the source ?

Thanks

**Comment by pawelfus** [comment]
Could you describe what is the expected result? Clearly, you have more categories, than available space. Allowing default rotation (or setting different values) is the best solution for that case, I think. 

As workaround, you can set fixed `tickInterval`, but I'm not sure how would be different from setting `rotation`. See: http://jsfiddle.net/f0v3p4oe/3/

**Comment by chtefi** [comment]
The expected result would be only dots, Highcharts displaying some labels
is a bug.

I can't change the rotation nor the tickInterval, there are user driven.
(he defines a custom chart style and the data inside can change according
to some filters)

**Comment by highslide-software** [comment]
I can confirm that some text is sometimes loaded in your demo. Probably it has to do with the async loading of Google Fonts.

I can't reproduce it with latest dev branch though. Please see http://jsfiddle.net/highcharts/f0v3p4oe/4/. Maybe the issue is fixed already.

Otherwise, in order for Highcharts to know the exact size of the rendered text, you probably need to hold the chart generation until the fonts are loaded.

**Comment by chtefi** [comment]
The thing is that the font is already loaded when the chart is created,
it's encapsulated in a setTimeout(, 500) in the jsfiddle to ensure that.

But indeed, the last version of Highcharts seems to fix it, I'll wait for
its release.

Thanks !
