### ISSUE TITLE
module/map.js don't support mapbubble map

### ISSUE THREAD

**Issue by zhy1stgg** [highslide-software/highcharts.com#4251]
when use highcharts and highmaps together 

```
<script src="http://code.highcharts.com/highcharts.js"></script>
<script src="http://code.highcharts.com/maps/modules/map.js"></script>
```

and one of  series type  is "mapbubble", it work out as [Highcharts error #17](http://www.highcharts.com/errors/17)

When use highmaps.js is ok

demo :  http://jsfiddle.net/nh97oeqx/

does't  modules/map.js update with highmaps?

**Comment by pawelfus** [comment]
For simple Highcharts, don't forget to attach `highcharts-more.js` for bubble type series. Demo: http://jsfiddle.net/nh97oeqx/1/

**Comment by zhy1stgg** [comment]
ok Thank you very much
