### ISSUE TITLE
Last candlestick doesn't show up after dragging (scrolling)

### ISSUE THREAD

**Issue by webscout** [highslide-software/highcharts.com#4253]
http://jsfiddle.net/ret601f2/4/

To reproduce:
1. Zoom in chart to last values
2. Drag main chart area left and then drag it back to right. 
3. Last candlestick doesn't show up, so you see an empty space instead. http://imgur.com/3ZXpLrO

It's only reproduces by dragging the main area. Dragging bottom navigator or scrollbar works fine (http://imgur.com/NSeHRGQ)
I tested in Chrome 41.0.2272.118, Firefox 37.0.1, but I think it's reproduces in all browsers.

**Comment by pawelfus** [comment]
Duplicate #4076
