### ISSUE TITLE
Waterfall Chart isSum dataLabel position

### ISSUE THREAD

**Issue by cludden** [highslide-software/highcharts.com#4256]
I've noticed when drawing a waterfall chart with a specified yAxis range (eg min: 90, max: 150), the label for the ending bar (isSum bar) is drawn at the bottom of the chart:

![image](https://cloud.githubusercontent.com/assets/4565917/7944025/8aa7e1ac-0968-11e5-94c3-91511880851e.png)

Is this an error, or do I need to specify something in the dataLabel options to position this correctly?

**Comment by highslide-software** [comment]
Can you share with us a live demo? It doen't happen here: http://jsfiddle.net/gh/get/jquery/1.7.2/highslide-software/highcharts.com/tree/master/samples/highcharts/demo/waterfall/

**Comment by cludden** [comment]
I've updated the fiddle to demonstrate the issue:

http://jsfiddle.net/6tp1dLof/
