### ISSUE TITLE
Highstock: Custom Attributes

### ISSUE THREAD

**Issue by craigp1231** [highslide-software/highcharts.com#4258]
I am trying to use custom attributes to pass information based on a user click to show a popup.

Please take a look at http://jsfiddle.net/6e84moyj/

Its a very simple example. If you click the blue 10, it alerts undefined, but why does it not show 96 as defined in the series data?

Using a similar example using Highcharts (instead of Highstock) as seen http://jsfiddle.net/bh7x3hw4/ it shows 96 correctly, why is this?

Kind Regards

Craig

**Comment by pawelfus** [comment]
It's caused by `dataGrouping`, simple un-forcing it: http://jsfiddle.net/6e84moyj/1/ makes it work. I short, when points are grouped by values, then all custom options are not passed on.
