### ISSUE TITLE
xy zoom bug with stacked column chart

### ISSUE THREAD

**Issue by keithmdragon** [highslide-software/highcharts.com#4264]
stack segments are not shown accurately after a zoom

run this: http://jsfiddle.net/kdragon/3c1x8c6y/

do a click hold / mouse drag to zoom in on the blue segment of america, with a small margin all the way around. 

you will notice that the other stacked segments will not be drawn correctly, often resulting in the green or black segments for all the other columns being drawn so their bottoms are aligned to the top of the blue segment 

here is before the zoom:
![chart 1](https://cloud.githubusercontent.com/assets/12547077/7989238/335ba718-0ab6-11e5-8994-f1f5e1b91406.jpeg)

here is after the zoom, with the corruption: 
![chart](https://cloud.githubusercontent.com/assets/12547077/7989226/1c75f4fe-0ab6-11e5-89ea-c27ef46f2598.jpeg)

notice that the black segment above the blue segment is now green and all the other columns now have green segments displayed where they shouldn't be

i'm doing this on win 7 64 bit, latest chrome

this is an issue with both old and new versions of highcharts

Thanks
Keith

**Comment by highslide-software** [comment]
Reliable reproduction (click the Zoom button): http://jsfiddle.net/highcharts/3c1x8c6y/2/

**Comment by keithmdragon** [comment]
thanks for the speedy fix! worked like a charm!

Keith
