### ISSUE TITLE
Nashorn to invoke highcharts in core java

### ISSUE THREAD

**Issue by agaddale** [highslide-software/highcharts.com#4265]
Is there a way to make use of nashorn to invoke highcharts function in core java to generate images based on my data in JSON format instead of using javascript chart options?

**Comment by highslide-software** [comment]
For general tech support questions, please see www.highcharts.com/support. I'm closing this issue, but copying our Java expert @gvaartjes to answer your question.

**Comment by agaddale** [comment]
Any update on this @gvaartjes

**Comment by gvaartjes** [comment]
This is something that's to my knowledge not possible. We use phantomjs that's a headless browser build on top of Webkit. I don't think there's a headless browser available for Nashorn.
