### ISSUE TITLE
Colors in column chart with negativeColor don't change on dynamic data change until mouseover

### ISSUE THREAD

**Issue by forty8bit** [highslide-software/highcharts.com#4267]
See http://jsfiddle.net/ZujZ3/4/ for an example. To reproduce:

1. Click on the `Change Data` button to change values.
2. You'll notice that when new values cause the column to cross threshold the color doesn't change.
3. Hover over the column(s) and the color should change to expected color.

Any known workarounds for the meantime?

**Comment by Jollyfant** [comment]
See this hacky workaround by triggering columns hover state.

http://jsfiddle.net/jq0bne8c/1/

Jolly

**Comment by highslide-software** [comment]
@pawelfus The fix doesn't work when applied to Highcharts 4.1.8... All columns become red after a while. Any idea?

**Comment by pawelfus** [comment]
See #4430 - before that commit is used to work.

**Comment by highslide-software** [comment]
Can you work out a fix that works with both cases?

**Comment by highslide-software** [comment]
@pawelfus Is this ready to be merged? There was a conflict with the updated master?

**Comment by pawelfus** [comment]
Let me double check this. I am pretty sure I resolved that issue a while ago.

**Comment by pawelfus** [comment]
I don't see any issue with that anymore (tested with latest, merged master and bug fix branches).

However I found new bug: #4670

**Comment by pawelfus** [comment]
Edit: found required commit: [this one](https://github.com/highslide-software/highcharts.com/commit/79fce150a7ce72d29d6c511fee757030511dbd8d).

**Comment by highslide-software** [comment]
So which commits do I need to cherry-pick in order to keep safe?

**Comment by pawelfus** [comment]
These two:

- fix for the issue above: [this](https://github.com/highslide-software/highcharts.com/commit/89f66e1335a2e8173fc8251191eef672d2df96c5)
- test for the issue above: [this](https://github.com/highslide-software/highcharts.com/commit/5ff75b66bee56bca12a3e7802311f0e586ed96f4) (sorry for missing tests in the above)


Fix for merge master&bugfix: #3636 - but those are already on the master branch.
