### ISSUE TITLE
Comment on fix #1843

### ISSUE THREAD

**Issue by Jollyfant** [highslide-software/highcharts.com#4268]
In the latest Highcharts build markers still displace slightly after being hovered over (previously reported as #3643). This behavior appears to be caused by the fix issued for ticket #1843:

**Highcharts.src.js, line 13333**
`plotX = mathFloor(point.plotX);`

The problems previously reported in ticket #3643 are caused by the initial flooring of plotX and appears to be corrected after a marker is being hovered over as plotX is re-evaluated in the setState function:

**Highcharts.src.js, line 17298**
`plotX = point.plotX;`

I have solved the issues I have been having with misaligned markers by disabling fix #1843 and keeping PlotX equal to point.plotX. This will naturally unfix #1843 and require a workaround.

Jolly

**Comment by highslide-software** [comment]
Closed by 8c154994b61633a11dfe6ec11dbf971f7f6da311
