### ISSUE TITLE
Exporting not working due to this.exportSVGElements

### ISSUE THREAD

**Issue by chevin99** [highslide-software/highcharts.com#4272]
This fiddle http://jsfiddle.net/kadams/uy05zby3/6/ used to work fine a few days ago, but not now.  When selecting an export option from the menu, `this.exportSVGElements` comes up as undefined, so export won't work.  Seems like something changed very recently that caused this to not work.

**Comment by pawelfus** [comment]
It's not a bug. Just when exporting chart,  `this.exportSVGElements` will be undefined, since exported chart doesn't contain exporting button.

Working demo: http://jsfiddle.net/uy05zby3/7/
