### ISSUE TITLE
Long Subtitle/Title goes to left when exporting with useHTML set true

### ISSUE THREAD

**Issue by angelocavallet** [highslide-software/highcharts.com#4279]
Title example: http://jsfiddle.net/sq12r17w/9/
Subtitle example: http://jsfiddle.net/fu2q1bjr/4/

Steps: Just try to export to PNG, JPEG, PDF or SVG

**Comment by highslide-software** [comment]
As stated in the docs, useHTML generally doesn't work with exported charts. See #2473 for possible workarounds.
