### ISSUE TITLE
Highstock: strangle flags for lineWidth = 3 or 5 or 7 etc.

### ISSUE THREAD

**Issue by KacperMadej** [highslide-software/highcharts.com#4285]
If lineWidth for flag series is equal to 3 + 2n for n in {0,1,2,...}, then flag looks like square
Example: http://jsfiddle.net/7x7oknnk/2/

**Comment by pawelfus** [comment]
I love that description! ;)

**Comment by highslide-software** [comment]
Here's a test case for non-matematicians :) http://jsfiddle.net/highcharts/7x7oknnk/3/
