### ISSUE TITLE
Pie series size 100% overlaps with the legend

### ISSUE THREAD

**Issue by andrei-picus-hs** [highslide-software/highcharts.com#4286]
This looks like a regression or an undocumented breaking change.

4.0.4 http://jsbin.com/qecoluzele/1/edit?html,js,output
4.1.5 http://jsbin.com/qotexatadu/edit?html,js,output

As you can see, the pie is bigger in 4.1.5 and overlaps with the legend.

**Comment by highslide-software** [comment]
It's because `auto` is not a valid setting for `legend.align`. Since the legend fails at aligning, it is placed on top of the plot area and the pie. Setting the alignment to `center` fixes your chart: http://jsfiddle.net/highcharts/LLnnj2o6/

**Comment by andrei-picus-hs** [comment]
@highslide-software thanks! Curious why the legend wasn't failing at aligning in 4.0.4 with the same `auto` option.

**Comment by highslide-software** [comment]
That's because of an internal rewrite of the legend alignment, but `auto`
was never a valid option. It just accidentally worked.​
