### ISSUE TITLE
Highstocks - Stacked area chart doesn't stay stacked at small widths

### ISSUE THREAD

**Issue by jessicavreeland** [highslide-software/highcharts.com#4287]
When using a Highstock stacked area chart, the data series aren't always stacked at smaller screen sizes.  In the example provided, the two data series are stacked if the chart width is set to 400 but are not longer stacked if the chart width is set to 300.

Example: http://jsfiddle.net/43rtbsju/5/
Seen in Chrome and Firefox.

**Comment by highslide-software** [comment]
It comes from data grouping. One of the series is grouped, the other not. If you disable grouping, it's ok: http://jsfiddle.net/highcharts/43rtbsju/6/

**Comment by jessicavreeland** [comment]
Thank you, this solves my issue.
