### ISSUE TITLE
Updating point color using Point.update() hides point

### ISSUE THREAD

**Issue by the1979** [highslide-software/highcharts.com#4290]
Since the latest Highcharts release (4.1.6), using the update() method to change a point's color hides that point in the graph. The <rect>'s "visibility" is being set to "hidden".
Fiddle: http://jsfiddle.net/nxs68wv0/2/

Using v4.1.5 solves the issue: http://jsfiddle.net/nxs68wv0/3/.

Running Chrome 43.0.2357.124 on OSX 10.10.3

**Comment by highslide-software** [comment]
Sorry for the regression. Duplicate of #4284. It's fixed and will be part of the next maintenance.
