### ISSUE TITLE
Series.length return +1 count and cause navigator draw

### ISSUE THREAD

**Issue by yarlenvas** [highslide-software/highcharts.com#4292]
If I try to iterate using chart.series.length, allways obtain a +1 count, (if I have 6 series, its return 7), this cause a bad navigator draw

see this fiddle

http://jsfiddle.net/yarlenvas/tfb69gtn/

**Comment by pawelfus** [comment]
Navigator contains one series too. You are adding to each of the series, so navigator gets unsynchronized with the first series data. See fixed demo: http://jsfiddle.net/tfb69gtn/1/
