### ISSUE TITLE
Crosshair behaviors

### ISSUE THREAD

**Issue by pawanvjadhav** [highslide-software/highcharts.com#4293]
Crosshair is displayed as band when we add categories in x axis:
http://jsfiddle.net/pawanvjadhav/hg0voopv/

Corsshair is displayed as line when we dont set categories in x axis:
http://jsfiddle.net/pawanvjadhav/q2npLf5n/1/

We can fix this difference by setting style but why you have added this difference?

This difference was not there in previous version.

**Comment by highslide-software** [comment]
The rationale is that the categories covers a span on the X axis, just not a singular point. It becomes obvious when grouping columns within the category: http://jsfiddle.net/highcharts/hg0voopv/2/. The old default behaviour does not make sense in this case: http://jsfiddle.net/highcharts/hg0voopv/3/.

Anyway, there is no change needed, as the `width` option will give you what you want: http://jsfiddle.net/highcharts/hg0voopv/4/.

**Comment by pawanvjadhav** [comment]
Agree with you.
But if this occurs even if you have linear axis and tickmarkPlacement is "ON".

**Comment by highslide-software** [comment]
Yes, I see that... [http://jsfiddle.net/highcharts/hg0voopv/5/](Here's a case) where it may be more natural with a line, though a band isn't wrong either. And it _is_ optional.
