### ISSUE TITLE
Highstock navigator not show all series

### ISSUE THREAD

**Issue by yanshuai** [highslide-software/highcharts.com#4296]
In the following chart, it shows two series, bytes_recv and bytes_sent in upper part, but show dropin in its navigator. How to let highstock show all series in navigator, or not show any series? 
![1](https://cloud.githubusercontent.com/assets/745813/8204591/561412ac-151c-11e5-81ac-81a7e9da722a.png)

**Comment by pawelfus** [comment]
See [user voice ticket](http://highcharts.uservoice.com/forums/55896-highcharts-javascript-api/suggestions/2361925-allow-navigator-to-have-multiple-data-series).
