### ISSUE TITLE
Treemap will works wrong when add new datas to series after drilling down to next level.

### ISSUE THREAD

**Issue by zq210wl** [highslide-software/highcharts.com#4298]
I'm using a treemap dataset chart of supporting drill down for some semi-frequently updating data (~3/s).  If I don't click one slice to drill down to next level, the chart works well. But, If I drill down to next level, then add new data to series, in this time, the chart will works wrong. 

The jsfiddle link: http://jsfiddle.net/zhangqi/Lpy2r1bv/6/ 

The steps to reproduce the issue:
  1. Click one slice "A" or "B" to drill down to next level.
  2. Click "AddNewData" button to add new data to category A.

**Comment by zq210wl** [comment]
Hope this issue can be fixed quickly.

**Comment by jon-a-nygaard** [comment]
Hi, you could do something like this:
```javascript
function addNewData() {
  var series = chart.series[0];
  // Add child data to category A
  series.addPoint({
    id: "A_AA1",
    name: "A_AA1",
    parent: "A"
  }, false);
  series.addPoint({
    id: "A_AA1_AAA1",
    name: "A_AA1_AAA1",
    parent: "A_AA1",
    value: 30
  });
  series.drillToNode(series.rootNode); // It sets the axis extremes to the new values, then a redraw.
}
```
You can still see some ugly flickering, which is the new points being drawn on the side. It helps a bit visually to turn of the animation.

**Comment by jon-a-nygaard** [comment]
@highslide-software Should the axis extremes automatically be updated if new points are added?
And if so, would it be better to wrap the series.addPoint function, or to detect in series.translate if the length of series.points/data has changed?

**Comment by zq210wl** [comment]
Thank you. 
I have try this way you suggested, but it has ugly flickering as you said. So, I'am afraid I can not use this way.
I don't need to update the axis extremes.

**Comment by highslide-software** [comment]
> Should the axis extremes automatically be updated if new points are added?

Yes, they should be updated to fit the bounding box of the drilled node. A second case is chart resize. On resize, the layout algorithm runs again, and the drilled node may be moved. So we need to update the extremes accordingly.

**Comment by highslide-software** [comment]
@zq210wl : This workaround temporarily disables animation to avoid the flickering:

```js
function addNewData() {
      var series = chart.series[0], 
          elProto = chart.renderer.Element.prototype,
          animate;
      // Add child data to category A
      series.addPoint({
          id: "A_AA1",
          name: "A_AA1",
          parent: "A"
      }, false);
      series.addPoint({
          id: "A_AA1_AAA1",
          name: "A_AA1_AAA1",
          parent: "A_AA1",
          value: 30
      });
      
      animate = elProto.animate;
      elProto.animate = elProto.attr; // Temporarily disable animation
      series.drillToNode(series.rootNode); // It sets the axis extremes to the new values, then a redraw.
      elProto.animate = animate;
      
  }
```
[View demo on jsFiddle](http://jsfiddle.net/highcharts/Lpy2r1bv/7/).
