### ISSUE TITLE
Crash on error in Firefox when inside a hidden iframe

### ISSUE THREAD

**Issue by highslide-software** [highslide-software/highcharts.com#4309]
Highcharts crashes with a JavaScript error when rendered inside an iframe that has `display: none`.

Outer file HTML
```html
<html>
<head></head>

<body>
<iframe id="iframe" src="iframe.htm" style="display: none; width: 610px; height: 400px"></iframe>

</body>
```

Iframe HTML:
```html

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xml:lang="en" xmlns="http://www.w3.org/1999/xhtml" lang="en">
<head>
  <meta http-equiv="content-type" content="text/html; charset=UTF-8"/>
  <title>Highcharts test tool - jsFiddle demo by highcharts</title>
  
  <script type='text/javascript' src='//code.jquery.com/jquery-git.js'></script>
  
  
  
  <style type='text/css'>
    #container {
    min-width: 300px;
    max-width: 800px;
    height: 300px;
    margin: 1em auto;
}
  </style>
  


<script type='text/javascript'>//<![CDATA[ 
$(function(){
$('#container').highcharts({

    xAxis: {
        categories: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 
            'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
    },

    series: [{
        data: [29.9, 71.5, 106.4, 129.2, 144.0, 176.0, 135.6, 148.5, 216.4, 194.1, 95.6, 54.4]
    }]

});

});//]]>  

</script>


</head>
<body>
  <script src="http://code.highcharts.local/highcharts.js"></script>
  <script src="http://code.highcharts.local/modules/exporting.js"></script>

  <div id="container"></div>
</body>
</html>
```

**Comment by highslide-software** [comment]
The commit above adressed another issue, probably unrelated. This issue is still active.

Demo: https://jsfiddle.net/bcrxnp2e/1/

@oysteinmoseng There is a piece of code in Chart.js that takes care of cases when the container is hidden. From `getContainer` it calls a method called `cloneRenderTo`. Probably we need to extend the cases where we need to run this, after that we can rely on already existing code.

**Comment by oysteinmoseng** [comment]
Fixed in latest version?

**Comment by highslide-software** [comment]
Turns out the fixing commit was right after all. The JS error in question was with `window.getComputedStyle`.

**Comment by oysteinmoseng** [comment]
Is this still an issue? Highcharts version has been updated on Cloud, but still does not work in firefox.

Also see http://jsfiddle.net/hmczLyz2/ for a non-cloud demo that seems to fail

**Comment by highslide-software** [comment]
I think your demo has double iframes, and possibly other issues. The simple case, with one iframe containing a HTML page with a chart, works in Firefox: http://jsfiddle.net/hmczLyz2/1/

**Comment by oysteinmoseng** [comment]
Aha, that helps. Still an issue with using Cloud embed, but this is a Cloud issue, then? https://jsfiddle.net/bcrxnp2e/1/

**Comment by highslide-software** [comment]
The same chart works well when running Highstock 2.1.8 from jsFiddle: http://jsfiddle.net/bcrxnp2e/6/.

Is Highcharts properly updated on the cloud?

**Comment by oysteinmoseng** [comment]
Your fiddle fails when loading the cloud Highcharts code https://cloud.highcharts.com/resources-1.0.008/js/highstock-cloud.js so looks like there's something there

**Comment by oysteinmoseng** [comment]
Turns out it fails once the standalone framework is used. http://jsfiddle.net/bcrxnp2e/7/
