### ISSUE TITLE
data labels verticalAlign on gauge.

### ISSUE THREAD

**Issue by Dams591** [highslide-software/highcharts.com#4315]
Hey there,

It seems that verticalAlign property doesn't behave properly on gauge dataLabels.
please see the fiddle below.

http://jsfiddle.net/f3b7u09a/

**Comment by highslide-software** [comment]
The tricky part here is the `y` has the default value of 15. If you set `y` to 0, you'll see that `verticalAlign` settings make sense: http://jsfiddle.net/highcharts/f3b7u09a/2/

**Comment by Dams591** [comment]
Hum your latest example still doesn't work for me.
I've updated your fiddle and I've set the verticalAlign to be bottom and now I see it on top .. 

Could it be related to my browser ? Chrome 43.0.2357.130 m

http://jsfiddle.net/f3b7u09a/3/

**Comment by highslide-software** [comment]
> I've set the verticalAlign to be bottom and now I see it on top ..

This sounds weird but it makes sense: Imagine a label that is aligned inside a box. If vertical align is "top", the top of the label is aligned to the top of the box. If vertical align is "bottom", the bottom of the label is aligned to the bottom of the box. 

Now imagine a label that is aligned to a singular point, like in the gauge (where the label is aligned to the center point). If vertical align is "bottom", the bottom of the label is aligned to the point. If vertical align is "top", the top of the label is aligned to the point.

This is how it is handled in HTML too, see http://jsfiddle.net/highcharts/f3b7u09a/4/
