### ISSUE TITLE
Stacking Area chart leaks memory when using addPoint

### ISSUE THREAD

**Issue by CodingFabian** [highslide-software/highcharts.com#4320]
See jsbin for a repro case
http://jsbin.com/qubowahoha/edit?html,css,js,output

It uses a stacking area chart where you have an initial data set and use shift to "scroll through" the data.

open this url in chrome:
http://output.jsbin.com/qubowahoha
Open Developer Tools and perform a heap snapshot
Search for "StackItem"

do another snapshot and search for StackItem again.
you see that Stackitem instances are increasing.
When you look at the data you can see that the Area somehow keeps references to all StackItem ever created.
![screen shot 2015-06-24 at 18 39 32](https://cloud.githubusercontent.com/assets/176132/8335836/678e7b24-1aa0-11e5-83b1-feef906dca2b.png)

when looking at the code "Stacking.js" I saw where those Items are created, but I could not find the corresponding place where they are removed when the old data points are shifted out.

**Comment by bripkens** [comment]
+1

**Comment by CodingFabian** [comment]
it looks like this problem was fixed by @highslide-software here:
https://github.com/highslide-software/highcharts.com/commit/03a460967828e3dfbcc67d130ecf69d2391feefd

but the change does not seem to have survived.

**Comment by CodingFabian** [comment]
yep the change got lost when merging "new stacking logic" by @slawekkolodziej about 2 years ago.
