### ISSUE TITLE
Tooltip not displayed on flags (IE only)

### ISSUE THREAD

**Issue by sebastianbochan** [highslide-software/highcharts.com#4324]
Example: http://jsfiddle.net/qbcg5r1d/1/

Problem appears only in IE9/10/11

**Comment by smartredfox** [comment]
I'm hitting this issues as well. It seems to only be a problem when using a custom image rather than one of the built in shapes. Example with one working, but the others not:

http://jsfiddle.net/qbcg5r1d/2/

**Comment by highslide-software** [comment]
I observed that the images don't capture mouse events in IE11 because the fill attribute is none. When removing the attribute through the console, the mouse events work. Tomorrow we will prevent the renderer from setting `fill="none"` on image symbols.
