### ISSUE TITLE
Boxplot max/min calculation with negative values

### ISSUE THREAD

**Issue by souvik1997** [highslide-software/highcharts.com#4327]
The default tooltip for the boxplot shows the maximum and minimum values in the series data. When the data has all negative numbers, the maximum shown by the tooltip is the maximum absolute value, not the actual maximum value. The same thing happens for the minimum value.

**Comment by highslide-software** [comment]
It seems to be handled correctly here: http://jsfiddle.net/highcharts/0yto5v9k/

Note that the order of the data values matters, it should be min, q1, median, q3 and max.

I'm closing this, please re-open if you have a live demo.

**Comment by souvik1997** [comment]
The first boxplot on this example exhibits the problem: https://jsfiddle.net/0yto5v9k/1/

**Comment by highslide-software** [comment]
The first point in your demo is misconfigured. According to [the docs](http://api.highcharts.com/highcharts#series<boxplot>.data), the order of the data array should be `low,q1,median,q3,high`. In your data set, you have -100 as the `low` value. The `low` value must by definition be lower that q1, median, q3 and high.
