### ISSUE TITLE
BoundingBox for SVG Render is not cached correctly

### ISSUE THREAD

**Issue by CodingFabian** [highslide-software/highcharts.com#4328]
when "chart.redraw()" is called, it performs a check "renderer.isHidden()",
which in turn will call "return !this.boxWrapper.getBBox().width;"
This however will never hit the cache, because it does not have a text String set. "cacheKey" will be undefined.
At the end of this method, the cache entry will be set anyways: "renderer.cache[cacheKey] = bBox;" even with "undefined"

I see a great chance for optimization here, because I assume the boundingbox indeed should be cached.
Also I see a potential for leakage, because the entry is cached using undefined:
![screen shot 2015-06-26 at 11 00 57](https://cloud.githubusercontent.com/assets/176132/8374092/b424dc3c-1bf2-11e5-8054-1bdb0a735158.png)

Caching it would improve the rendering of charts, because right now the get bounding box call forces a layout.

**Comment by highslide-software** [comment]
> Caching it would improve the rendering of charts, because right now the get bounding box call forces a layout.

But if we cache it we don't find out whether it's hidden...

**Comment by CodingFabian** [comment]
true, which brings the interesting question when this cache here is invalidated.

**Comment by highslide-software** [comment]
The point of `renderer.isHidden()` is to check whether the chart SVG is visible at all, because trying to render a chart into a display:none block gives various problems.

**Comment by CodingFabian** [comment]
yep, I get that. point is that we are evaluating highcharts for a real time use case, and the border box calculations kill our framerate.

**Comment by highslide-software** [comment]
I see. When I put `console.time` around the isHidden method, it reports times below 1 ms. Are these calculations not measurable in the script? Do you have any suggestion on how to measure the overhead? If so, we could try to find a cheaper way to find out whether the chart is hidden.
