### ISSUE TITLE
Tick Label Bounding boxes could use more clever caching

### ISSUE THREAD

**Issue by CodingFabian** [highslide-software/highcharts.com#4329]
Hi,
right now if you have an x axis which displays time, it is very likely to never see the same tick label again. so it is not really helpful to cache the tick label bounding boxes for its textStr (actually its a waste to check for it because its guaranteed to be new when its called).
However for example in Date formatted axes, you have patterns like %H:%M which could perform the same optimization, because it is a static length.
Also if you have decimal separators on the Y axis the same applies.

Maybe, as first attempt to solve this, common date and decimal formats might be added to this: https://github.com/highslide-software/highcharts.com/blob/348d420f8092fff7d6a32f59dac45c9da5c2c975/js/parts/SvgRenderer.js#L699 ?

**Comment by highslide-software** [comment]
> right now if you have an x axis which displays time, it is very likely to never see the same tick label again

It is very likely that it sees the same label again when you resize the chart or update it with new data (add a point etc.), or show/hide series etc. 

> Maybe, as first attempt to solve this, common date and decimal formats might be added

Yes, but only numeric ones so we wouldn't gain much.

**Comment by CodingFabian** [comment]
The estimated gain is surely subjective. in my case we have only numeric labels.
But you assesment regarding the label is not applicable here. You are right that you still see the label when you add points, but the relevant code is executed when the label is created. If it just moves it is not executing this code again. This effectively makes the cache in its current implementation have a very low hit rate.
