### ISSUE TITLE
Column chart - double datalabels in export

### ISSUE THREAD

**Issue by sebastianbochan** [highslide-software/highcharts.com#4330]
Example: http://jsfiddle.net/r7L47830/

Chrome: 43.0.2357.130

**Comment by zhy1stgg** [comment]
it's ok on my own exporting server, you can try it through  http://export.hcharts.cn
```
exporting: {
  url: 'http://export.hcharts.cn'
}
```

**Comment by pawelfus** [comment]
Duplicate of #3649
