### ISSUE TITLE
Treemap: drilling to node doesn't work when using standalone framework

### ISSUE THREAD

**Issue by KacperMadej** [highslide-software/highcharts.com#4331]
Not working, Standalone framework: http://jsfiddle.net/eobzwghv/

Working, jQuery: http://jsfiddle.net/eobzwghv/1/

**Comment by pawelfus** [comment]
Workaround: replace `drillTo` method, like this: http://jsfiddle.net/eobzwghv/3/

Just a guess, that native `H.addEvent()`/`H.removeEvent()` won't recognize `click.drillTo` as element:

- https://github.com/highslide-software/highcharts.com/blob/master/js/modules/treemap.src.js#L751
- https://github.com/highslide-software/highcharts.com/blob/master/js/modules/treemap.src.js#L733

**Comment by highslide-software** [comment]
> Just a guess, that native H.addEvent()/H.removeEvent() won't recognize click.drillTo as element:

@jon-a-nygaard That's probably right. Try with a pure alphabetical event name.
