### ISSUE TITLE
Missing data labels for multiple series

### ISSUE THREAD

**Issue by stefanodcIT** [highslide-software/highcharts.com#4333]
My chart is missing some data labels for some columns without an explanation.

http://jsfiddle.net/4vvvbebq/3/

For the same data i have different result as missing data labels (i.e. i see all data labels for that chart, but i'm using dynamic data, but on a 2nd graph on the same page i'm missing data label. And every time the data change the missing labels move from column to colmn).

Any idea?

**Comment by stefanodcIT** [comment]
Fiddle updated with the 2nd chart.
As is clearly visible the 2nd chart is missing data labels on different columns compared to the 1st chart

**Comment by stefanodcIT** [comment]
Opss.  Fiddle link: http://jsfiddle.net/4vvvbebq/4/

Sorry. I'm new to this

**Comment by pawelfus** [comment]
Each data-label has padding which with addiction of anty-collision algorithm will hide some of the labels. You can prevent hiding labels by simple setting `allowOverlap: true`. See demo: http://jsfiddle.net/4vvvbebq/7/

**Comment by stefanodcIT** [comment]
Thanks.
