### ISSUE TITLE
How to make rangeSelector do dataGrouping of multiple series

### ISSUE THREAD

**Issue by carlosdubus** [highslide-software/highcharts.com#4335]
See here: http://jsfiddle.net/6751x0yj/1/

If you group by day only the first series is grouped. How can I make it so it groups both series.

In the above example, both series have the same data, but my current situation consists of two series with the same x value but different y values.

Thanks!

**Comment by pawelfus** [comment]
Workaround and probably solution is to update series in descending order. When updating series, previous one is removed to update, so we need to keep proper order.

    var H = Highcharts;

    H.wrap(H.Axis.prototype, "setDataGrouping", function (p, dg, r) {
        if (!dg) {
            dg = {
                forced: false,
                units: null
            };
        }
        
        if (this instanceof H.Axis) {
            for(var i = this.series.length - 1; i >= 0; i--) {
                this.series[i].update({
                    dataGrouping: dg
                }, false);
            };
        }

        p.call(this, dg, r);
    });


And demo: http://jsfiddle.net/6751x0yj/2/
