### ISSUE TITLE
Updating data with setData seems to alter initial set

### ISSUE THREAD

**Issue by alexfortoul** [highslide-software/highcharts.com#4337]
I am drawing a chart using Highcharts, with my data passed to javascript as data attribute, and this works perfectly fine.

I want to be able to change the data, what I am doing like that :

chart.highcharts().series[0].setData(chart.data().secondset, true);
chart being properly defined, this works fine as well.

Then, if I try to go back to my initial data using the exact same code :

chart.highcharts().series[0].setData(chart.data().firstset, true);
it does not work, and it seems like my initial data has disappeared, so Highcharts would alter my initial data.

Here is the fiddle: http://jsfiddle.net/8zwL0cv3/1/

Thanks for your help

**Comment by highslide-software** [comment]
To avoid wasting memory by copying datasets (that may be thousands of points), Highcharts by default works on the original arrays when dynamically updating the charts.

To avoid that, simply copy your array before applying it, by running `slice(0)`. [View live jsFiddle](http://jsfiddle.net/highcharts/8zwL0cv3/4/).
