### ISSUE TITLE
Highcharts touch events give an error on IE

### ISSUE THREAD

**Issue by maximvelichko** [highslide-software/highcharts.com#4339]
IE10/11, HighCharts v4.1.7 (2015-06-26)
When users touch a graph's point and "drags" it, they get an exception.

It works properly on non-IE browsers. 
This is the errors users get:

TypeError: Object doesn't support property or method 'attr'
	at sr.prototype.drag (${root}/highchart?v=q1N9Ayl8nyLy4eWwVrlfKp03jTYgDkuZCR8qcRjk4501:1:83504)
	at sr.prototype.onContainerMouseMove (${root}/highchart?v=q1N9Ayl8nyLy4eWwVrlfKp03jTYgDkuZCR8qcRjk4501:1:85164)
	at t.onmousemove (${root}/highchart?v=q1N9Ayl8nyLy4eWwVrlfKp03jTYgDkuZCR8qcRjk4501:1:86168)

The error is thrown on attempt to address attr in the following part (highcharts.src.js#9857):

            // adjust the width of the selection marker
            if (this.selectionMarker && zoomHor) {
                size = chartX - mouseDownX;
                this.selectionMarker.attr({
                    width: mathAbs(size),
                    x: (size > 0 ? 0 : size) + mouseDownX
                });
            }

I read that the problem tracks down to a different implementation of touch events in Internet Explorer. Unfortunately I didn't find a way to fix it, or at least disable touch handling in Highcharts on IE.

Thank you,
Max

**Comment by maximvelichko** [comment]
...And when the error happens, this.selectionMarker is set to {"x":84,"y":10,"width":1085,"height":277},"2":"object","3":"{\"x\":84,\"y\":10,\"width\":1085,\"height\":277}

I have no idea why attr() is not defined though.

To workaround the problem I did the following fix, but it really does not look right, only suppress errors for users. So please suggest a better workaround or fix...

            // adjust the width of the selection marker
            if (this.selectionMarker && zoomHor) {
                if (this.selectionMarker.attr) {
                    size = chartX - mouseDownX;
                    this.selectionMarker.attr({
                        width: mathAbs(size),
                        x: (size > 0 ? 0 : size) + mouseDownX
                    });
                } else {
                    console.warn(
                        "Highcharts.drag patch (zoomHor): this.selectionMarker (%s) is defined, but this.selectionMarker.attr is not: %s, %s", 
                        this.selectionMarker, 
                        typeof(this.selectionMarker), 
                        JSON.stringify(this.selectionMarker));
                }
            }

**Comment by sebastianbochan** [comment]
+1

**Comment by dhuntermn** [comment]
this.selectionMarker.attr() appears to be a setter method, so one way to fix this is to set the attributes directly:

			// adjust the width of the selection marker
			if (this.selectionMarker && zoomHor) {
				size = chartX - mouseDownX;
				this.selectionMarker.width = mathAbs(size);
				this.selectionMarker.x = (size > 0 ? 0 : size) + mouseDownX;
			}
			// adjust the height of the selection marker
			if (this.selectionMarker && zoomVert) {
				size = chartY - mouseDownY;
				this.selectionMarker.height = mathAbs(size);
				this.selectionMarker.y = (size > 0 ? 0 : size) + mouseDownY;
			}

**Comment by maximvelichko** [comment]
Thanks!

Your suggestion seems to work.
Any chances you'll bring it to the following Highcharts release?

-Max

**Comment by dhuntermn** [comment]
I am not a HighCharts developer.

**Comment by maximvelichko** [comment]
Thanks even more then!
I hope someone from developers would notice and consider it.

I am unblocked myself, but an official fix would benefit all users.

**Comment by highslide-software** [comment]
> I hope someone from developers would notice and consider it.

We did, even though you closed the issue :) 

I tried to replicate it in jsFiddle at http://jsfiddle.net/highcharts/jmnouoq9/show, but I can't see an error when trying to touch-drag the big points. Can you help us with a reproduction?

**Comment by maximvelichko** [comment]
Sorry, my mistake! :-)

I can reproduce using your JSFiddle, actually. So, the question is how can I help?
What I did is:
1) Use Internet Explorer 11 (11.0.0600.17905), desktop version. (To be absolutely precise, user agent "Mozilla/5.0 (Windows NT 6.3; WOW64; Trident/7.0; .NET4.0E; .NET4.0C; .NET CLR 3.5.30729; .NET CLR 2.0.50727; .NET CLR 3.0.30729; InfoPath.3; rv:11.0) like Gecko" - but I've tried the original bug on many machines/different IE 10/11 builds with equal result.)
2) Open  http://jsfiddle.net/highcharts/jmnouoq9/show
3) F12 for developers tools (it looks like it's required. We capture and log./show to user window.onerror, it looks that's why we see it all the time, while otherwise it's silently suppressed, at least in most of the cases)
4) Drag series line with a finger.
5) Breaks into debugger immediately, at the line, and with the exception I described in my original question.

Please let me know if you need more info, or how can I "hand over" this repro, in case it does not work for you.


-Max

**Comment by maximvelichko** [comment]
Thank you!
