### ISSUE TITLE
[Gif] HighStocks - Graph/series go out of bounds

### ISSUE THREAD

**Issue by bluejamesbond** [highslide-software/highcharts.com#4340]
The graph/series go out of bounds when the axis are added dynamically. Any solutions/workaround to this issue?

Problem shown in vid below:
[GFYCAT](http://gfycat.com/ExcellentMediumJapanesebeetle)

**Comment by pawelfus** [comment]
Yes, that's how it suppose to work. Could you create an example? Simple test case: http://jsfiddle.net/pm917cko/

**Comment by bluejamesbond** [comment]
@pawelfus There was some confusion in the way I had set up the links. Take a look at the gif now.

**Comment by pawelfus** [comment]
Great, edited issue, now my comment makes no sense ;) 
What happens in your video, shouldn't happen (unless you change to different video ;) ). Please, setup jsFiddle demo with the issue.

**Comment by bluejamesbond** [comment]
The problem is caused when having a <base> tag (possibly in the <head>) which skews the clip-path urls. Removing the base tag fixes all of the issues.
