### ISSUE TITLE
Axis lineWidth fails when 3D module is loaded

### ISSUE THREAD

**Issue by pawanvjadhav** [highslide-software/highcharts.com#4343]
We have included below latest Highchart 4.1.7 release JS in our project. We are also using treemap
https://github.com/highslide-software/highstock-release/blob/master/highcharts-3d.js
https://github.com/highslide-software/highstock-release/blob/master/highcharts-more.js
https://github.com/highslide-software/highstock-release/blob/master/highstock.js

After this change,Axis line width has stopped working.

**Comment by highslide-software** [comment]
It works here: http://jsfiddle.net/highcharts/u5ujnb43/1/. Can you reproduce a case where it fails?

**Comment by pawanvjadhav** [comment]
You are trying only with Highchart.js.

Try with all JS i have specified.

**Comment by pawanvjadhav** [comment]
See the difference http://jsfiddle.net/u5ujnb43/2/

**Comment by highslide-software** [comment]
It works in 4.1.5, but fails in 4.1.6: http://jsfiddle.net/highcharts/u5ujnb43/4/. It fails when the highcharts-3d.js file is loaded (highcharts-more.js and highstock.js) are not needed to reproduce it.

**Comment by pawanvjadhav** [comment]
Yes, you are right. Its working on 4.1.5.

**Comment by pawanvjadhav** [comment]
Thanks
