### ISSUE TITLE
Zoom selection issue after setting xAxis.offset

### ISSUE THREAD

**Issue by Oliboy50** [highslide-software/highcharts.com#4344]
I had to set an xAxis.offset in my chart but the only issue I've noticed so far is with the Zoom selection. 

Visually, it does not reach the xAxis. And I can't either make a zoom selection if I click on the "offset" part of the chart.

I didn't know that Highcharts was on Github so I opened a question on [SO](http://stackoverflow.com/questions/31156928/highcharts-zoom-selection-issue-after-setting-xaxis-offset) where you'll find more informations including a screenshot.

EDIT: http://jsfiddle.net/z7d88d8v/1/

**Comment by pawelfus** [comment]
Could you create jsFiddle with that issue? Simple test case works fine: http://jsfiddle.net/z7d88d8v/

**Comment by Oliboy50** [comment]
I did it differently.
