### ISSUE TITLE
Invalid value for <rect> attribute x="NaN"

### ISSUE THREAD

**Issue by bblack** [highslide-software/highcharts.com#4345]
The following code results in the following errors, once per datapoint:
```javascript
var serieses = [{type: 'column'}];
var chart = new Highcharts.Chart({
    chart: {
        renderTo: 'container'
    },
    xAxis: {
        type: 'datetime'
    }
});
chart.yAxis[0].setExtremes(null, 308, false);
chart.xAxis[0].setExtremes(
    new Date('2015-07-26'),
    new Date('2015-07-29'),
    false);
chart.addSeries(serieses[0], false);
var inputz = [
    {"date":"2015-07-26","y":5},
    {"date":"2015-07-27","y":5},
    {"date":"2015-07-28","y":5},
    {"date":"2015-07-29","y":5},
    {"date":"2015-07-30","y":5}
];
inputz.forEach(function(row, i){
    // if (i > 3) return;
    chart.series[0].addPoint({
        x: Date.parse(row.date),
        y: row.y
    }, false);
});
chart.redraw();
```
http://jsfiddle.net/du2gjn32/
```
Invalid value for <rect> attribute x="NaN"
Invalid value for <rect> attribute width="NaN"
```

This is on 4.1.7. There are various tweaks to this code that result in no error. Those tweaks include:

* Setting `series: serieses` in the chart creation instead of calling `addSeries` later
* Removing the redraw=false argument from one or more of the calls
* Removing one or more datapoints from `inputz` starting from either end
* Changing the arguments to setExtremes from Date objects to integers (e.g. by using `Date.parse` instead of `new Date`)

I assume that the correct use of setExtremes is to pass numbers anyway, but passing Date objects seems to work in general. If the issue really is that setExtremes shouldn't be taking Date objects, can there be some type-checking there to prevent these harder downstream errors?

**Comment by highslide-software** [comment]
Yes, the arguments to setExtremes should be numbers like defined in the API: http://api.highcharts.com/highcharts#Axis.setExtremes

http://jsfiddle.net/highcharts/du2gjn32/2/

**Comment by bblack** [comment]
Much of the API that takes numbers seems to work with Date objects much of the time, which makes it an an easy mistake for someone to make when dealing with a datetime axis. Are you opposed to the idea of type-checking those arguments to give clearer, more immediate feedback to the developer?

**Comment by highslide-software** [comment]
We could add type checking, but then again we should consistently add type checking for all methods and options, and that would mean a lot of performance and weight overhead. Currently we do type checking for y values, which was a common mistake. (People threw in strings for data values).
