### ISSUE TITLE
Set range selector dates on same date

### ISSUE THREAD

**Issue by corneavrazvan** [highslide-software/highcharts.com#4346]
1/ Go to http://jsfiddle.net/gh/get/jquery/1.9.1/highslide-software/highcharts.com/tree/master/samples/stock/demo/basic-line/
2/ Change the from input date to 2015-06-19
3/ IT IS CHANGED AUTOMATICALLY TO 2015-06-14

How to set range selector dates on same date from inputs or dragging the navigator handles?
Thanks.

**Comment by highslide-software** [comment]
Set the `xAxis.minRange` to 1: http://jsfiddle.net/highcharts/bfam3z3m/
