### ISSUE TITLE
tooltip is displayed for points out of area

### ISSUE THREAD

**Issue by sebastianbochan** [highslide-software/highcharts.com#4348]
Example: http://jsfiddle.net/zojkxg1h/11/

Steps to reproduce:
1) hover over violet series 
2) move cursor to right direction

**Comment by sebastianbochan** [comment]
Next example: http://jsfiddle.net/s2gfjLph/

**Comment by pawelfus** [comment]
Duplicate of #4149

**Comment by sebastianbochan** [comment]
Related case #3916
