### ISSUE TITLE
Simple pie chart failing on Highstock > 2.1.5

### ISSUE THREAD

**Issue by pitermarx** [highslide-software/highcharts.com#4350]
see this fiddle https://jsfiddle.net/pitermarx/9hwMJ/9/

I get this error
> Uncaught TypeError: Cannot read property 'len' of undefined

if you use highcharts instead of highstock it works 
if you use highstock 2.1.5 it works

**Comment by highslide-software** [comment]
You should use the `Highcharts.Chart` constructor for pies: https://jsfiddle.net/highcharts/9hwMJ/10/

**Comment by pitermarx** [comment]
Well, it worked up to version 2.1.5...
Isn't this a regression?
Was it never intended to work?

**Comment by highslide-software** [comment]
It was never intended to work, and as you see you also needed to disable the navigator. But anyway, it was a simple fix so I committed a fix and a regression test to prevent us from breaking it again.

**Comment by pitermarx** [comment]
Thank you
