### ISSUE TITLE
Calling setSize does not resize the container

### ISSUE THREAD

**Issue by BenoitZugmeyer** [highslide-software/highcharts.com#4351]
JSFiddle: http://jsfiddle.net/LLExL/4879/ (click on resize to resize the chart: the container with a red border isn't resize)

The method `chart.setSize` is using the `Fx` instance by passing values with units, but the `Fx` instance expects unitless values. As a result, the `this.now` value of `Fx` is always `NaN`, and the final value is always `"200pxpx"` as it tries to add the unit on a value with units.

**Comment by highslide-software** [comment]
Highcharts isn't supposed to modify the `renderTo` div. There's a div created inside the `renderTo`, that is internally referred to as `chart.container`. This div scales when you set the size: http://jsfiddle.net/highcharts/LLExL/4883/ .

**Comment by BenoitZugmeyer** [comment]
I'm sorry, my example was wrong, and the issue is actually with the standalone adapter. Please see the updated jsfiddle http://jsfiddle.net/LLExL/4884/

As you can see, by using the standalone adapter, the div `.highcharts-container` isn't resized.

**Comment by highslide-software** [comment]
Thanks for the updated demo. Confirmed!

**Comment by highslide-software** [comment]
Fixed by bbca887c76379b6852732335b8610629a46e2765
