### ISSUE TITLE
Tooltip.shape on series level

### ISSUE THREAD

**Issue by pawelfus** [highslide-software/highcharts.com#4358]
According to the [docs](http://api.highcharts.com/highcharts#plotOptions.series.tooltip.shape) we can set `tooltip.shape` for each series separately. I'm not sure if this is bug in docs, or it suppose to work, demo: http://jsfiddle.net/0xuby21j/1/

**Comment by highslide-software** [comment]
It wasn't supposed to work, I have removed it from the docs
