### ISSUE TITLE
Pie chart - drilldown - incorrect color after click

### ISSUE THREAD

**Issue by sebastianbochan** [highslide-software/highcharts.com#4359]
Steps to reproduce:
1) Example: http://jsfiddle.net/jbs01j7k/1/
2) Click on dark green slice
3) Click on light green slice
4) As a result light green is replaced with dark green

**Comment by m1neral** [comment]
Not only drilldown, I have this bug in simple pie chart with costum color palette.

**Comment by sebastianbochan** [comment]
Workaround: set for drilldown series `color: null`, see: http://jsfiddle.net/jbs01j7k/5/

**Comment by m1neral** [comment]
@sebastianbochan I have this problem not in a drilldown, drilldown as live example, which I found.
http://forum.highcharts.com/highcharts-usage/crop-lighting-of-piechart-serie-t33310/
I think a bug deeper, necessary research the use of custom palettes.

**Comment by pawelfus** [comment]
I have found that issue is only in drilldown.js module. Do you have demo without drilldown? Or could you setup one, so we will fix it once for good?

**Comment by m1neral** [comment]
@sebastianbochan  @pawelfus Thank you! I solved the problem - you led me to the right idea - in my case was override colors, we one configuration if colors for all charts and series.

**Comment by pawelfus** [comment]
So, could you confirm that issue is only for drilldown module?

**Comment by m1neral** [comment]
Yes, I confirm. In my case was like this: http://jsfiddle.net/8QufV/1095/

**Comment by jpla2005** [comment]
Using color: null doesn't work for 3D charts. Any suggestion?

**Comment by pawelfus** [comment]
Demo: http://jsfiddle.net/at78s3eu/

Problem is that 3D arc animates only shape, not the color..

**Comment by pawelfus** [comment]
Temporary workaround for 3D is do disable the animation: 

    Highcharts.seriesTypes.pie.prototype.animateDrilldown = function() {};

Demo: http://jsfiddle.net/at78s3eu/1/

**Comment by highslide-software** [comment]
The fix causes a regression when drilling from a series with colorByPoint: true to one without colorByPoint. In [this fiddle](http://jsfiddle.net/gh/get/jquery/1.7.2/highslide-software/highcharts.com/tree/master/samples/highcharts/drilldown/basic/), the fix causes color change on the drilled series.


The base issue is not with drilldown, but it is that the `color` option trumps `colorByPoint` on selected slices: http://jsfiddle.net/highcharts/8qc69vLc/1/.

**Comment by pawelfus** [comment]
Ok, I don't see differences in behavior for [your jsfiddle](http://jsfiddle.net/gh/get/jquery/1.7.2/highslide-software/highcharts.com/tree/master/samples/highcharts/drilldown/basic/). Could you explain?
