### ISSUE TITLE
3d doughnut pie chart - center circle render issue

### ISSUE THREAD

**Issue by jossef** [highslide-software/highcharts.com#4370]
## Description

![image](https://cloud.githubusercontent.com/assets/1287098/8599118/522f7242-2667-11e5-98d7-f4a29054b384.png)

The center circle of the 3d doughnut pie is messed up, seems like a rendering bug.
## How to reproduce
do a resize once the 3d doughnut pie is rendered

![damn](https://cloud.githubusercontent.com/assets/1287098/8599095/2c34d294-2667-11e5-87a7-e73f89c6815f.gif)

**Comment by KacperMadej** [comment]
Problem seems to be fixed by this commit https://github.com/highslide-software/highcharts.com/commit/650eee6ca9f3c1c4ae1b345997041840eb164de5
Example: http://jsfiddle.net/qaagrstL/1/
Could you confirm?
