### ISSUE TITLE
Multiple yAxis causes clipping of last line segments on the side of labels

### ISSUE THREAD

**Issue by Triztian** [highslide-software/highcharts.com#4371]
On line charts when a second yAxis is added and given an offset, after the lines finish being animated the last line segments (marker connections)  that are on the side of the yAxis labels are erased/cleared.

Browser:
Google Chrome Version 43.0.2357.130 (64-bit)

Demo 1: [Simple two line chart](http://jsfiddle.net/triztian/xqtqxrcc/1/)
Demo 2: [Doc's example](http://jsfiddle.net/gh/get/jquery/1.7.2/highslide-software/highcharts.com/tree/master/samples/highcharts/yaxis/offset-centered/)

**Comment by pawelfus** [comment]
Offensice [commit](https://github.com/highslide-software/highcharts.com/commit/72ee767501d1481cfe0394c7fbf85454bf31d437). Connected to the #4308
