### ISSUE TITLE
Highstock must have same hide show markers functionality as in highcharts

### ISSUE THREAD

**Issue by likwifi** [highslide-software/highcharts.com#4373]
Currently in highcharts series, point markers are appearing and hiding dynamically according to  datagrouping options http://jsfiddle.net/s4r3crwd/.
However in Highstocks lib this feature is missing.

**Comment by pawelfus** [comment]
Example for that feature with Highstock library: http://jsfiddle.net/y2po444L/5/ (using Highcharts constructor).

**Comment by highslide-software** [comment]
The only difference is that the marker is disabled by default in Highstock, while in HIghcharts it defaults to `null`, which is auto. See http://jsfiddle.net/highcharts/s4r3crwd/1/. I'll update the API docs so this comes out clearer.

**Comment by highslide-software** [comment]
Updated docs: 
* http://api.highcharts.com/highcharts#plotOptions.series-marker.enabled
* http://api.highcharts.com/highstock#plotOptions.series-marker.enabled
