### ISSUE TITLE
Misaligned ticks even with alignTicks set to true

### ISSUE THREAD

**Issue by pawelfus** [highslide-software/highcharts.com#4374]
Example: http://jsfiddle.net/mh5vya94/

Click on the legend (temperature), each axis use separate ticks and gridlines.

**Comment by pawelfus** [comment]
Workaround is to force axis to recalculate scale: 

        H.wrap(H.Axis.prototype, 'setScale', function(p) {
            if(this.options.alignTicks !== false || this.chart.options.alignTicks !== false) {
                 this.forceRedraw = true;   
            }
            p.call(this);
        });
    })(Highcharts)

Demo: http://jsfiddle.net/mh5vya94/1/

*Internal note:*
Responsible [line](https://github.com/highslide-software/highcharts.com/blob/master/js/parts/Axis.js#L1253). 

It would be better to check if any other of the axes need to be redrawn in advance instead of the workaround above.

**Comment by highslide-software** [comment]
There's a [code block](https://github.com/highslide-software/highcharts.com/blob/v4.1.7/js/parts/Axis.js#L1147-L1167) checking if there are other series that needs to be aligned. One option would be to move this out to its own method so that it can be reused in order to force redraw.

**Comment by snoopyjc** [comment]
Note these lines are causing the problem in the initial chart draw also:

                // If the plot area size has changed significantly, calculate tick positions again
		redoHorizontal = tempWidth / chart.plotWidth > 1.1;
		redoVertical = tempHeight / chart.plotHeight > 1.1;

In my case, the tempHeight is 580 and the chart.plotHeight is 567 as my legend is at the bottom and spans 2 lines, so the ratio is 1.02 and redoVertical is set to false.  The consequence of not redoing, however, is that the Y axes have a tickAmount of 10 (ceil(580/72)+1), but when data is added to the plot causing a redraw, getTickAmount() returns 9 (ceil(567/72)+1), causing the mis-aligned axes.

My proposed fix is to set redoVertical = tempHeight != chart.plotHeight;
