### ISSUE TITLE
Dotted points when first element in data is a string

### ISSUE THREAD

**Issue by jcrrad** [highslide-software/highcharts.com#4376]
when declaring any chart that is a line, area, spline, etc. and if the first element in the data array is a String, Highcharts accepts the rest of data after the String but does not display a line, area, spline as intended and instead defaults to points. there is no error is given for this to aid in figuring out why the intended graph is not displayed

http://jsfiddle.net/ouozt8wq/

**Comment by highslide-software** [comment]
The series.data array doesn't allow strings, as specified in http://api.highcharts.com/highcharts#series<line>.data.

This is handled in the [optionsToObject](https://github.com/highslide-software/highcharts.com/blob/v4.1.7/js/parts/Point.js#L67) function. We could add a test for string types here, but for long series you would notice the performance overhead.
