### ISSUE TITLE
Plot labels displaying incorrectly on exported images

### ISSUE THREAD

**Issue by audioarchitect** [highslide-software/highcharts.com#4378]
When exporting images of chart, a second plot label is displayed underneath the first one and is partially cut off. Tested on Chrome, Firefox and Safari with similar behavior on each. See image below:

![highcharts_export](https://cloud.githubusercontent.com/assets/2197750/8630666/a1762a10-271d-11e5-9633-18c94470ad82.png)

Here's an example in JSFiddle:
http://jsfiddle.net/audioarchitect/tuy886xo/1/

**Comment by pawelfus** [comment]
Duplicate of #3649
