### ISSUE TITLE
Can't programmatically select points at the chart

### ISSUE THREAD

**Issue by AlexKovalevych** [highslide-software/highcharts.com#4381]
Weird issue - if i have <=240 points at the chart i'm able to programmatically select any point http://jsfiddle.net/ycvady88/.
Otherwise i can't (same data + 1 point) - http://jsfiddle.net/mquabuco/

**Comment by pawelfus** [comment]
Cased by dataGrouping, see: http://jsfiddle.net/mquabuco/1/

**Comment by AlexKovalevych** [comment]
Thank you.
