### ISSUE TITLE
Invalid date in rangeSelector when data is missing

### ISSUE THREAD

**Issue by pawelfus** [highslide-software/highcharts.com#4384]
Example: http://jsfiddle.net/pp3sz2zx/2/

In the rangeSelector inputs we can see `Invalid Date`.

**Comment by gvaartjes** [comment]
Ok thanks for reporting

**Comment by highslide-software** [comment]
It's supposed to print that when it doesn't have a date. No data => no bounds on the X axis => no dates for the range selector. 

If you have suggestions for what else to print, please go ahead. Maybe just an empty date field?

**Comment by pawelfus** [comment]
I would go with empty field. Another solution is to display 00:00:00 (or something similar), but this may be misleading for users, I think.

**Comment by highslide-software** [comment]
Thanks for your view. I ended up adding a new lang option which is an empty string by default. Now the implementer can choose to set "Invalid date" or "00:00:00". [View live jsFiddle](http://jsfiddle.net/highcharts/pp3sz2zx/3/).
