### ISSUE TITLE
Highchart axis time labels are inaccurate with small chart and axis min,max are set

### ISSUE THREAD

**Issue by hmedhat** [highslide-software/highcharts.com#4387]
If you check this fiddle
http://jsfiddle.net/sgmbvkvx/

you will find that the minimum x-axis is set to (April 8th, 2015 12:10 PM) and the maximum is set to (July 14th, 2015 11:42 AM). The data for the chart lies between (July 13th, 2015 2:00 PM) and (July 13th, 2015 4:02 PM). However if you take a look at the chart you will find that the x-axis shows July 15th at the end and the data appears after July 15th which is wrong, it should be somewhere between June 15th and July 15th

![image](https://cloud.githubusercontent.com/assets/7040181/8671158/196ee860-2a23-11e5-891d-87f247e06c7f.png)

**Comment by pawelfus** [comment]
It's 1st July of 2015 ;) It's year, not day of the month.

**Comment by hmedhat** [comment]
ah ok :laughing: Thanks for the quick reply
