### ISSUE TITLE
Large 3d column charts - problem with title overlapping.

### ISSUE THREAD

**Issue by sebastianbochan** [highslide-software/highcharts.com#4388]
Example: http://jsfiddle.net/Akixi/krdabjda/

On large (>1200x1000px) 3D column or bar graphs, the vertical axis title text is often placed over the top of the y-axis labels or its vertical grid line.
It seems therefore that the internal algorithm used to automatically set the title's "offset" property doesn't work well for large chart sizes.

**Comment by sebastianbochan** [comment]
Example of xAxis: http://jsfiddle.net/Akixi/gdmL1g9j/

**Comment by pawelfus** [comment]
Depths are improper:
- http://jsfiddle.net/krdabjda/5/ 
- http://jsfiddle.net/gdmL1g9j/3/

Still, long category name can overlap legend: http://jsfiddle.net/gdmL1g9j/4/
