### ISSUE TITLE
Area - incorrect shape when points have the same x value

### ISSUE THREAD

**Issue by sebastianbochan** [highslide-software/highcharts.com#4391]
Stacking: http://jsfiddle.net/Akixi/so4dbdqL/

**Comment by gvaartjes** [comment]
Reported wrong area stacking for area

**Comment by highslide-software** [comment]
In line and area series, multiple points on the same X value does not work well. You'll also see problems with the tooltip. 

How would you expect this stacked chart to look? Perhaps an arearange chart is a better choice for this data?

**Comment by highslide-software** [comment]
Simplified, we would expect a stacked chart with a single series to look like it were not stacked: http://jsfiddle.net/highcharts/t73cbv1r/

**Comment by highslide-software** [comment]
Demo with the fix applied: http://jsfiddle.net/highcharts/so4dbdqL/12/

For the records, the provided solution treats single-x stacks the same as Google Spreadsheets, except we also display the markers of the points lower in the stacks:
![skjermbilde 2015-11-18 kl 11 19 40](https://cloud.githubusercontent.com/assets/227836/11238520/90f0d520-8de6-11e5-92fa-402ef4376a42.png)

**Comment by sebastianbochan** [comment]
Internal note:
http://jsfiddle.net/Akixi/so4dbdqL/ should look like: http://jsfiddle.net/gwwuw6k2/
