### ISSUE TITLE
Issue with pane when width is decreased.

### ISSUE THREAD

**Issue by Sureshraj0** [highslide-software/highcharts.com#4398]
![solid_gauge](https://cloud.githubusercontent.com/assets/12712771/8728984/f47cc574-2c05-11e5-9694-7675817c91fd.png)

here is the JSfiddle link http://jsfiddle.net/6y23k46L/. Is there any workaround for this issue?

**Comment by pawelfus** [comment]
Hello,

This is our bugtracker. For support questions, please use our forum/contact with us by e-mail.

And to answer your question: this is caused by `size: "140%"` - so size is bigger than available space. See: http://jsfiddle.net/6y23k46L/1/
