### ISSUE TITLE
high charts xAxis labels cannot be displayed

### ISSUE THREAD

**Issue by DudnykOleksandr** [highslide-software/highcharts.com#4399]
I have a column chart. For some columns xAsis labels are hidden until zoom. 
I tried setting a lot of options. Nothing gave me expected result. I want them all to be shown anyway.

Similar issue is here
http://stackoverflow.com/questions/24960423/high-charts-xaxis-label-cannot-be-display-after-reset-zoom

Here is my reproduction:
http://jsfiddle.net/Oleksandr_Dudnyk/5tux15s9/4/

Thanks

**Comment by pawelfus** [comment]
How about setting `axis.tickInterval: 1` ? Like this: http://jsfiddle.net/5tux15s9/5/

**Comment by DudnykOleksandr** [comment]
Thanks, that works for my case. But does't for this:
http://stackoverflow.com/questions/24960423/high-charts-xaxis-label-cannot-be-display-after-reset-zoom

**Comment by pawelfus** [comment]
Of course, gut in the question formatter is broken. There are cases when nothing is returned. For example: 

   if( this.value % 3 == 0 ) {
       return ...
   }

Where is `else` which will return something else? For example: http://jsfiddle.net/3WxsY/1/

Proper options: 


            labels: {
                formatter: function () {
                    var ex = this.axis.getExtremes();

                    if ((ex.max - ex.min) > 12) {
                        if (this.value % 3 == 0) {
                            if (xCategoriesMonth[this.value] == "Jan")
                                return xCategoriesMonth[this.value] + "<br>" + xCategoriesYear[this.value];
                        }
                    }
                    else {
                        if (this.value % 3 == 0)
                            return xCategoriesMonth[this.value] + "<br>" + xCategoriesYear[this.value];
                    }
                    
                    return xCategoriesMonth[this.value];
                }
            },
            tickInterval: 1,
            //tickPixelInterval: $('#container').width() / 36,

**Comment by DudnykOleksandr** [comment]
You are right. Thanks a lot.
