### ISSUE TITLE
incorrect mouseOver events in column charts

### ISSUE THREAD

**Issue by pahans** [highslide-software/highcharts.com#4410]
http://jsfiddle.net/pahans/nts554bu/ . hover over chart and check console. mouseOver triggers 6 times x value of 5  items are correct but the `this.x` of last one is incorrect.

I can get expected result by removing this line https://github.com/highslide-software/highcharts.com/blob/master/js/highcharts.src.js#L9634 and this `if` condition https://github.com/highslide-software/highcharts.com/blob/master/js/highcharts.src.js#L9629.

**Comment by pahans** [comment]
I can get expected result by removing https://github.com/highslide-software/highcharts.com/blob/master/js/highcharts.src.js#L9634 and this `if` condition https://github.com/highslide-software/highcharts.com/blob/master/js/highcharts.src.js#L9629.

**Comment by jon-a-nygaard** [comment]
Thanks for reporting, we will have a look at the issue, and come back to you with an answer. Due to summer vacations, you might experience longer response time than usual.

**Comment by highslide-software** [comment]
Simplified reproduction:
1. Open http://jsfiddle.net/highcharts/nts554bu/1/
2. Hover the plot area above the columns without hovering the columns themselves.
3. In the console, observe that the mouseOver event for _Series 1_ is triggered over and over again for the first X value reported.

**Comment by pahans** [comment]
thanks

**Comment by guinguo** [comment]
but, hover the plot (top down , not in series) nothing log in console when tooltip.shared = false
see : [http://jsfiddle.net/guin_guo/03nbq4f9/](http://jsfiddle.net/guin_guo/03nbq4f9/)
why it not react when tooltip.shared = false, thanks

**Comment by guinguo** [comment]
but, hover the plot (top down , not in series) nothing log in console when tooltip.shared = false
see : [http://jsfiddle.net/guin_guo/03nbq4f9/](http://jsfiddle.net/guin_guo/03nbq4f9/)
why it not react when tooltip.shared = false, thanks
@TorsteinHonsi

**Comment by TorsteinHonsi** [comment]
Because when the tooltip is not shared, each column triggers its own tooltip. And the tooltip doesn't appear until the actual column shape is hovered.
