### ISSUE TITLE
Change the navigator interval as you zoom in?

### ISSUE THREAD

**Issue by bluejamesbond** [highslide-software/highcharts.com#4413]
This allows for zooming in from months to days to seconds to have more fine-grained control over which data is shown.

**Comment by jon-a-nygaard** [comment]
Thank you for reporting. Due to vacations you might experience longer response time than usual.

**Comment by highslide-software** [comment]
Do you mean you want to specify the data grouping as you click buttons on the range selector? That feature is already supported, see http://jsfiddle.net/gh/get/jquery/1.7.2/highslide-software/highcharts.com/tree/master/samples/stock/rangeselector/datagrouping/.

If this was not what you had in mind, please elaborate.

**Comment by highslide-software** [comment]
Closing this now, please reopen if needed.
