### ISSUE TITLE
How can we set margin between two points on X Axis?

### ISSUE THREAD

**Issue by pawanvjadhav** [highslide-software/highcharts.com#4414]
How can we set margin between two points on X Axis?
e.g : spacing between bars

**Comment by jon-a-nygaard** [comment]
Hi @pawanvjadhav 

I think what you are looking for is the pointPadding option. To read more about it, have a look in our api at [plotOptions.bar.pointPadding](http://api.highcharts.com/highcharts#plotOptions.bar.pointPadding)
