### ISSUE TITLE
No wrap when step is set

### ISSUE THREAD

**Issue by sebastianbochan** [highslide-software/highcharts.com#4415]
In case when we set a step as 1, then labels are not wrapped. 

Example: http://jsfiddle.net/wmmeky37/5/

Workaround: set staggerLines as 1, instead of step.

**Comment by gboanea** [comment]
Hi,

If the label doesn't contain a white space, the labels overlap: http://jsfiddle.net/fm6oqLk6/1/
Is there a workaround for autoRotation and step 1?

Thank you,
Georgeta

**Comment by TorsteinHonsi** [comment]
Setting `textOverflow: 'ellsipsis'` seems to help: http://jsfiddle.net/highcharts/fm6oqLk6/2/

**Comment by sebastianbochan** [comment]
You can also set useHTML as true and set CSS styles to break words.

http://jsfiddle.net/4k0hb2we/

**Comment by gboanea** [comment]
Thank you for your suggestions :)

I would prefer the solution with autoRotation, is there a way to enable autoRotation and step1? Or can autoRotation only work if not all the values are displayed?

**Comment by vchalub** [comment]
Hi guys,
I also would like something like setting step to 1 with autorotation. Is this possible? It seems that when I set step, autorotation stops working.
