### ISSUE TITLE
Setting min and max for y axis

### ISSUE THREAD

**Issue by pawanvjadhav** [highslide-software/highcharts.com#4417]
I am trying to set min and max for Y Axis. See below url.
http://jsfiddle.net/pawanvjadhav/owuc2gLh/

I am not getting required result. I want to set Y Axis min to 5 and max : 200
I played with attribute startontick, minpadding, maxpadding but no success.

**Comment by sebastianbochan** [comment]
You should set tickInterval: http://jsfiddle.net/owuc2gLh/1/

For general support question, please contact with us by email / stackoverflow / forum. More informations, you can find here: http://www.highcharts.com/support

**Comment by pawanvjadhav** [comment]
what if i dont want to set interval? is this the only option?

**Comment by sebastianbochan** [comment]
You can use tickPositions / tickPositioner. 

Docs:
- http://api.highcharts.com/highcharts#xAxis.tickPositioner

**Comment by pawanvjadhav** [comment]
I feel that, this is workaround.
As library is provided option to set Min and Max, it should behave accordingly. If we set Min and Max, it should draw points accordingly.

Cant we fix this in library itself? or my requirement is wrong?

**Comment by highslide-software** [comment]
You only need to set `startOnTick` and `endOnTick` to false for the desired effect: http://jsfiddle.net/owuc2gLh/3/

**Comment by pawanvjadhav** [comment]
Thanks for this :+1:  I am close to what i want. Just the last thing, see below URL:
http://jsfiddle.net/owuc2gLh/4/

I want to show specified min value as first label, at start of axis. In our example : 10 (as min : 10)
YAxis.showFirstLabel is not giving me the expected result. It considers 50 as first label :(

**Comment by highslide-software** [comment]
Okay, for that you need the `tickPositioner`. This code snippet will take care of it: 

```js
            startOnTick: false,
            endOnTick: false,
            tickPositioner: function () {
                this.trimTicks(this.tickPositions, false, false);
                if (this.tickPositions.indexOf(this.min) === -1) {
                    this.tickPositions.unshift(this.min);
                }
                if (this.tickPositions.indexOf(this.max) === -1) {
                    this.tickPositions.push(this.max);
                }
            }
```

[See live jsFiddle](http://jsfiddle.net/owuc2gLh/6/).

I agree it is kind of a workaround, but then again it is not a very common case, so we haven't created an option structure for it.

**Comment by pawanvjadhav** [comment]
Ok Thanks for this
