### ISSUE TITLE
Cannot hide x-axis gridline with 3d columns

### ISSUE THREAD

**Issue by ripla** [highslide-software/highcharts.com#4420]
Use case: I want to set x-axis grid line width to zero in the global options, so that I don't ever get x-axis grid lines.

However, if I'm using a 3d column chart with an array of x-axis, the grid lines appear. Minimal test case: http://jsfiddle.net/x7s0h84f/

Note that just having a single x-axis object, or removing the options3d object fix the issue.

**Comment by jon-a-nygaard** [comment]
Thank you for reporting, I will take a look at the issue and see what I can do.
