### ISSUE TITLE
tickAmount - min and max calculated incorrectly for area charts

### ISSUE THREAD

**Issue by MargaritaZolotareva** [highslide-software/highcharts.com#4423]
Let's compare:
* chart with line and area
http://jsfiddle.net/017oz2vv/

* line chart
http://jsfiddle.net/a2zhhpht/

* area chart
 http://jsfiddle.net/qqrfb75q/

When I set tickAmount in the 1st or 3rd example I expect that min and max values will be calculated automatically and the chart will be like in the 2nd example.

**Comment by jon-a-nygaard** [comment]
Thank you for reporting. Due to vacations you might experience longer response time than usual.

**Comment by highslide-software** [comment]
Area charts have a default threshold of `0`, whereas line charts has `null`. See http://api.highcharts.com/highcharts#plotOptions.area.threshold.
