### ISSUE TITLE
x axis tickInterval problem

### ISSUE THREAD

**Issue by imrefarkas** [highslide-software/highcharts.com#4424]
Hi, 

Can you check this fiddle? Is it a bug? 
http://jsfiddle.net/3bv4z45v/

if I comment out the tickInterval the x axis label is fine.

thx in advance
-imre farkas

**Comment by jon-a-nygaard** [comment]
Thank you for reporting. This seems like a bug, a tickInterval of 0.025 should give the same result as the "auto" tickInterval, but it somehow breaks.
We will look into the issue, but due to vacations you might experience longer response than usual.

**Comment by highslide-software** [comment]
We need a fixed with in order to reproduce this reliably: http://jsfiddle.net/3bv4z45v/2/. It looks like JavaScript roundoff errors. A workaround would be to force two decimals: http://jsfiddle.net/3bv4z45v/3/.

**Comment by imrefarkas** [comment]
thanks your response.
