### ISSUE TITLE
Data module - solid gauge not working with spreadsheets

### ISSUE THREAD

**Issue by sebastianbochan** [highslide-software/highcharts.com#4427]
Example: 
http://jsfiddle.net/AYYCv/279/

I limited a data to single point, but still receive error in prototype (see console).

**Comment by sicuro** [comment]
at the Highchart cloud it works. I have the same problem. If you can make it work .. please let me know.

**Comment by highslide-software** [comment]
The `solidgauge.js` file was missing. Working demo: http://jsfiddle.net/AYYCv/281/.

**Comment by sicuro** [comment]
YOU ARE GOD!

**Comment by sebastianbochan** [comment]
Sorry for my simple overlook.
