### ISSUE TITLE
Fill for tooltip's ● (\u25CF) is not defined for normal points when negativeColor is used

### ISSUE THREAD

**Issue by KacperMadej** [highslide-software/highcharts.com#4430]
This applies for line, area, column.
Area example: http://jsfiddle.net/3Lbdzsjc/
Hover last point to see that ●'s fill is empty and it is black instead of light blue.

For scatter series negativeColor for ● is not applied and every time it's fill is color of series.
Example: http://jsfiddle.net/3Lbdzsjc/1/

**Comment by KacperMadej** [comment]
Scatter type series issue is not changed - http://jsfiddle.net/3Lbdzsjc/2/

**Comment by pawelfus** [comment]
Huh, that commit breaks [this one](https://github.com/highslide-software/highcharts.com/commit/89f66e1335a2e8173fc8251191eef672d2df96c5). 

In case threshold.color is undefined, shouldn't be `series.color` used? See: #4238
