### ISSUE TITLE
If series type if bar then changing series type to scatter and next to line breaks tooltip.

### ISSUE THREAD

**Issue by KacperMadej** [highslide-software/highcharts.com#4431]
Series type: 'bar' -> 'scatter' -> 'line' => broken tooltip (not showing)
Example: http://jsfiddle.net/5toptdn6/1/
Steps:
1. change type of series to scatter from bar (scatter button)
2. change type of series to line from scatter (line button)
3. Tooltip is not being displayed when hovering over series as it should

Workaround: before changing type to line, change if briefly to bar.
Example: http://jsfiddle.net/5toptdn6/2/

**Comment by highslide-software** [comment]
The base problem is that after switching twice, the `directTouch` flag is erroneously set on the line series. The problem probably originates from these lines where prototype properties are changed, but this fails when the series type is changed twice.

```js
		// Destroy the series and delete all properties. Reinsert all methods 
		// and properties from the new type prototype (#2270, #3719)
		this.remove(false);
		for (n in proto) {
			this[n] = UNDEFINED;
		}
		extend(this, seriesTypes[newOptions.type || oldType].prototype);
```

**Comment by pawelfus** [comment]
Only pie and column series have set `directTouch` so when extending prototype, value from column remain.
