### ISSUE TITLE
Manhattan Style bar chart

### ISSUE THREAD

**Issue by rahilwazir** [highslide-software/highcharts.com#4432]
Is there way to configure [HighCharts 3D Column](http://www.highcharts.com/demo/3d-column-interactive) as Manhattan Style bar chart, something like:
![1]

[1]: https://demos.devexpress.com/XtraChartsDemos/DXB.axd?DXCache=69325070-2bf3-4f6c-8854-0aa9c74f9ad3
If possible, how the data needs to be structure in series? [Fiddle](http://jsfiddle.net/rahilwazir/7qqs77e5/)

**Comment by highslide-software** [comment]
For general tech support, please see www.highcharts.com/support.
