### ISSUE TITLE
Demo of "Ajax loaded data, clickable points" doesn't work in jsFiddle because of highslide files being not found

### ISSUE THREAD

**Issue by KacperMadej** [highslide-software/highcharts.com#4433]
Demo: http://www.highcharts.com/demo/line-ajax
In jsFiddle: http://jsfiddle.net/gh/get/jquery/1.9.1/highslide-software/highcharts.com/tree/master/samples/highcharts/demo/line-ajax/

Clicing doesn't work because www.highcharts.com/media/com_demo/highslide* files are not found ( Failed to load resource: the server responded with a status of 404 (Not Found) ).

**Comment by pawelfus** [comment]
It works again.
