### ISSUE TITLE
hover flag with useHTML -> flag loses focus

### ISSUE THREAD

**Issue by iweindesmedt** [highslide-software/highcharts.com#4435]
http://jsfiddle.net/rkj7ou5h/

1. hover the flag
2. the tooltip jumps to the other serie

it works without ```useHTML```

**Comment by iweindesmedt** [comment]
this is working with the master branch. i'll leave this open until the next release.

**Comment by highslide-software** [comment]
Thanks. We're closing issues as they are fixed in the master.
