### ISSUE TITLE
how to change shap of point tooltip

### ISSUE THREAD

**Issue by dieuhd** [highslide-software/highcharts.com#4439]
![screen shot 2015-08-06 at 5 54 58 pm](https://cloud.githubusercontent.com/assets/3165692/9107730/ada1822e-3c64-11e5-8e25-59a0dd996324.png)

I want to change square to circle.
Please help me.

**Comment by sebastianbochan** [comment]
Github is our bugtracker.
For general support questions please contact with us by emai / forum / stackoverflow. Further information here: http://www.highcharts.com/support
