### ISSUE TITLE
Rotation labels - doens't work when resize window

### ISSUE THREAD

**Issue by sebastianbochan** [highslide-software/highcharts.com#4443]
Steps to reproduce:
1) Run this example: http://jsfiddle.net/1g7uay8k/show/ (full screen, resolution 1280x768)
2) Labels are not rotated, correct
3) Resize window to small resolution, until labels will be rotated. Correct.
4) When we resize again to first step, then labels are not like in point 1, because still rotated.

**Comment by highslide-software** [comment]
Normalized demo: http://jsfiddle.net/highcharts/1g7uay8k/4/

Tip: Always use fixed widths to demonstrate issues that have to do with dynamic layout.

**Comment by sebastianbochan** [comment]
Seems that labels width are incorrect. 

Demo: http://jsfiddle.net/1g7uay8k/5/
Click step1 / step2 and observe labels.

**Comment by highslide-software** [comment]
_Internal note_
The labels' `whiteSpace` property is set to `nowrap` by the ellipsis handling, and not released when expanding the chart.

**Comment by AlisonNiu** [comment]
thanks, look like the label 'width' property need reset or remove to make it correct in some situations too.

**Comment by sebastianbochan** [comment]
Seems that problem still appears, demo: http://jsfiddle.net/6souk48x/ . Click step 3 and then step 2.

**Comment by TorsteinHonsi** [comment]
When I click Step 2, two of the labels don't have ellipsis, which can be considered a bug.

When I click Step 3, I don't see anything wrong.

Do you agree with this?

**Comment by sebastianbochan** [comment]
I agree.

**Comment by AlisonNiu** [comment]
click Step 2, then click Step 3, then click Step 2 again. We can see the second is wrapped to two lines, but the first and third label only show part. which is wrong. 
Do you two agree with this?
 http://jsfiddle.net/6souk48x/ . click Step 2, then click Step 3, then click Step 2

**Comment by AlisonNiu** [comment]
Is there any progress?
thanks

**Comment by AlisonNiu** [comment]
Is there any progress?
