### ISSUE TITLE
Highmaps zoom bug

### ISSUE THREAD

**Issue by pliasetski** [highslide-software/highcharts.com#4444]
Hello,

Map zooms "in" when doing continuous double click on “Zoom Out (-)” or "Plot Area"

You could check it in this video:
https://dl.dropboxusercontent.com/u/73896408/highmaps_zoom_bug.mp4

With best regard

**Comment by highslide-software** [comment]
Reproduction:

1. Go to http://jsfiddle.net/gh/get/jquery/1.7.2/highslide-software/highcharts.com/tree/master/samples/maps/demo/color-axis/
2. Double click minus sign
