### ISSUE TITLE
legend: UseHTML=true, rtl=true  - not properly displaying of legend items 

### ISSUE THREAD

**Issue by DimaCommugen** [highslide-software/highcharts.com#4449]
Example: http://jsfiddle.net/jsDima/qx2z7f26/4/
Highcharts: 4.1.7
Browsers:  
    Chrome: 44.0.2403.130 ( lastest), 
     IE:10
    ( I suppose in all browsers left position of legend items is calculated wrong )

If to set useHTML or rtl to false 
then  items of legend will be displayed right

**Comment by pawelfus** [comment]
Introduced by [this commit](https://github.com/highslide-software/highcharts.com/commit/ec6f89715b4a0a41d2e71b3d0f06831a21d9f02e#diff-5d3aad1ab4221eaad4e4ba17c165d2a7L10638). 

It should be enough to move this line:


				.css(merge(item.visible ? itemStyle : itemHiddenStyle)) // merge to prevent modifying original (#1021)
				.attr({
					align: ltr ? 'left' : 'right', // move line -->
					zIndex: 2
				})

To be called after setting new text, here:

 		// Always update the text
		legend.setText(item);
		li.attr({
			align: ltr ? 'left' : 'right' // #4449 - text may be changed, so bbox should be updated to
		});

However, I'm not convinced - why always update `align` property when `useHTML` flag is set? Shouldn't `getBBox()` (or rather `getBBox(true)` ?) handle this case?

**Comment by highslide-software** [comment]
I agree it should be handled on a lower level. [This fiddle](http://jsfiddle.net/highcharts/9tgk4qbz/) demonstrates the root cause, isolated to the SVGRenderer. When setting the `.text()` method's fourth parameter to false in order to use SVG rendering, it behaves correctly.
