### ISSUE TITLE
minRange adds extra ticks

### ISSUE THREAD

**Issue by pawelfus** [highslide-software/highcharts.com#4450]
Demo: http://jsfiddle.net/cvdmwqdd/22/

We set `minRange: 10`, but yAxis scale is 0-12. 

It is caused by `startOnTick` and `endOnTick` options, which adds an additional ticks, which are unnecessary (I think). 

I'm not sure if this is a bug, or intentional, but if this is not a bug, then small note in the API would be a good idea. 

**Workaround:**
Set `startOnTick` and `endOnTick` to false, demo: http://jsfiddle.net/cvdmwqdd/23/

**Comment by highslide-software** [comment]
It's also the `minPadding` and `maxPadding` that affect the result: http://jsfiddle.net/highcharts/cvdmwqdd/24/. What happens is probably that the maxPadding increments the max, then the `endOnTick` setting dictates it to round up to 12.

**Comment by pawelfus** [comment]
Yes, that's probably it. 

As I said above, I don't think that is a bug, but it's worth to add such information in the docs for `minRange` - as reported by one of the clients, it's weird to set `minRange = 10` and get scale of 12 on the yAxis. Simple explanation of such behavior would be enough, since it's not very intuitive.

**Comment by highslide-software** [comment]
Done!
