### ISSUE TITLE
rangeSelector doesn't appear after series.setData()

### ISSUE THREAD

**Issue by ysavary** [highslide-software/highcharts.com#4452]
Highstock 2.1.7
Chrome 44
Firefox 39
Safari 7.1

Similar to issue #3486 

After calling setData() on a empty series, the rangeSelector will appear only if you try to move the series with the mouse or resize the windows.

http://jsfiddle.net/m4pmmd20/

**Comment by highslide-software** [comment]
#### Workaround

Mark the X axis `isDirtyExtremes` true. 
```js
$('#container').highcharts().xAxis[0].isDirtyExtremes = true;
```
[View live jsFiddle](http://jsfiddle.net/highcharts/m4pmmd20/1/).
