### ISSUE TITLE
Printing can include tooltip in chrome

### ISSUE THREAD

**Issue by kingoleg** [highslide-software/highcharts.com#4453]
jsfiddle: http://jsfiddle.net/PEtv7/7/

When you click export menu and then print - it click on print button and then hover over chart, so tooltip is shown on chart and on print svg.

Similar to https://github.com/highslide-software/highcharts.com/issues/1707

**Comment by highslide-software** [comment]
I can't reproduce this - I assume you need to be really quick?

**Comment by kingoleg** [comment]
I record a screen cast for this. I am not really quick. And I am not using doubleclick

https://www.youtube.com/watch?v=WpGJZ8Jfzi4&feature=youtu.be

**Comment by kingoleg** [comment]
Chrome Version 43.0.2357.134 m

**Comment by kingoleg** [comment]
Retested with recent Chrome Version 44.0.2403.155 m. Reproduced.

**Comment by pawelfus** [comment]
Reproduced on W7 - it's connected to the fact we remove all margins for the body when printing. In that moment, chart is moved to the top which cause tooltip to show up. 

Better example in our [API](http://api.highcharts.com/highcharts#exporting.buttons.contextButton.y) - [this one](http://jsfiddle.net/gh/get/jquery/1.7.2/highslide-software/highcharts.com/tree/master/samples/highcharts/navigation/buttonoptions-verticalalign/).

**Comment by kingoleg** [comment]
Can you remove label "cant reproduce" according to @pawelfus comment?

**Comment by sebastianbochan** [comment]
Reprocudable in each browser, set longer hideDelay. 

Example:
- http://jsfiddle.net/LLExL/5392/

Workaround:
- http://jsfiddle.net/LLExL/5368/
