### ISSUE TITLE
Legend behavior change in alignment and verticalAlignment between 4.0.4 and 4.1

### ISSUE THREAD

**Issue by ericpedia** [highslide-software/highcharts.com#4458]
Starting in 4.1, the behavior of legend alignment appears to have changed when using these settings:

```javascript
legend: {
    floating: false, 
    align: 'right', 
    verticalAlign: 'top'
}
```

- With HighCharts 4.0.4, the legend appears *to the right of the graph* at the top. So the graph is compressed horizontally.
- Starting in HighCharts 4.1.0, the legend appears *above the graph*, right-aligned, so the graph is compressed vertically.

![highcharts behavior chage - github](https://cloud.githubusercontent.com/assets/806060/9203535/c2ed4ebe-4025-11e5-9186-c46ed9154b04.gif)

Is there any way to achieve the old behavior of a legend to the right of the graph, top-aligned? The only way I can get a legend to appear to the right now is by using `verticalAlign: 'middle'`. I can see how there is a natural ambiguity in which alignment would be expected to take precedence. So perhaps it would need an additional option (`outside: 'top'/'bottom'/'right'/'left'`?) or a modification of an existing option (like adding additional values to the `floating` option).

Example here with 4.0.4 (you can comment the script inclussions to see the difference between each version): http://jsfiddle.net/8n4j8t5u/5/

**Comment by pawelfus** [comment]
I think, you want to set layout too: http://jsfiddle.net/8n4j8t5u/6/ - in other words, it's not a good idea to resize the plotting area to fit right aligned legend, when layout is `horizontal` and you choose top vertical alignment. Imagine using multiple series, like 10 of them, then chart won't be visible, compare:

- http://jsfiddle.net/8n4j8t5u/7/
- http://jsfiddle.net/8n4j8t5u/8/

**Comment by highslide-software** [comment]
Yes, @pawelfus is correct. In the corner position, the legend will be placed on top if the layout is horizontal, and on the side when the layout is vertical.

I have added this information to the API: http://api.highcharts.com/highcharts#legend.align
