### ISSUE TITLE
Having to call setExtremes after dynamically loading data to correctly show from/to dates

### ISSUE THREAD

**Issue by mitar** [highslide-software/highcharts.com#4460]
Reproduction: https://jsfiddle.net/mwpLu9b5/1/

Without `chart.xAxis[0].setExtremes(null, null, true);` line at the end, "from" and "to" shows "invalid date".

**Comment by pawelfus** [comment]
It's already fixed on master branch: http://jsfiddle.net/mwpLu9b5/2/
