### ISSUE TITLE
Highmaps: updating dataClasses of colorAxis when legend in disabled causes error

### ISSUE THREAD

**Issue by KacperMadej** [highslide-software/highcharts.com#4464]
When trying to update dataClasses on chart with legend disabled, error is thrown:
`Uncaught TypeError: Array.prototype.forEach called on null or undefined`

Example: http://jsfiddle.net/vu8rfe9f/1/
Click 'Toggle' button and see console.

**Comment by highslide-software** [comment]
Demo with fix applied: http://jsfiddle.net/vu8rfe9f/2/
