### ISSUE TITLE
Highcharts dual x axis column + line is adding ticks to secondary x axis

### ISSUE THREAD

**Issue by jamesallchin** [highslide-software/highcharts.com#4469]
I am seeing strange behaviour with highcharts when using dual x-axis. Essentially highcharts is adding extra ticks to the end of the second axis.

Background - Why I'm doing this.

Trying to create a column chart with fixed categories (x-axis) and counts (y-axis) and then trying to plot a secondary plot-line which represents a percentage (i.e. somewhere between 0 and 100). In order to do this I use a secondary x-axis, and to avoid conflict with the column chart I also use a secondary y-axis that's based on a spline (but with no data in the series).

Unfortunately, for some reason the secondary x-axis (used for the plot-line) has extra ticks added to end. In the fiddle below it's going from 0 to 160 even though the min and max on this x-axis is set from 0 to 100.

Any idea how to force the secondary axis to stay between 0 and 100?

Fiddle:

http://jsfiddle.net/5ypnffww/

Highchart config:

    {
        "chart": {},
        "title": {
            "text": "This survey run"
        },
        "xAxis": [
            {
                "title": {
                    "text": null
                },
                "categories": [
                    "Very low",
                    "Low",
                    "Neutral",
                    "High",
                    "Very high"
                ]
            },
            {
                "title": {
                    "text": null
                },
                "opposite": true,
                "plotLines": [
                    {
                        "color": "red",
                        "dashStyle": "longdashdot",
                        "value": 50,
                        "width": 2
                    }
                ],
                "labels": {
                    "enabled": true,
                    "step": 1
                },
                "min": 0,
                "max": 100
            }
         ]
    }

**Comment by pawelfus** [comment]
Hi,

This is caused by `alignTick` option. Set it to false, to prevent this behavior, see: http://jsfiddle.net/5ypnffww/1/

**Comment by pawelfus** [comment]
*Internal note:*
`alignTicks` doesn't really aligning ticks, see: http://jsfiddle.net/5ypnffww/2/ - or rather aligns if the categorized axis would be linear type. As we set categories on the axis, then only existing categories are displayed which mismatches ticks back.

**Comment by jamesallchin** [comment]
Thanks so much - I had tried setting alignTicks to true thinking that by default it was set to false.

My mistake - as per docs this is by default set to true

http://api.highcharts.com/highcharts#chart.alignTicks

Thanks for your help. Much appreciated.
