### ISSUE TITLE
Highstock: Series titles overlap w/ ignoreHiddenSeries enabled

### ISSUE THREAD

**Issue by chezmix** [highslide-software/highcharts.com#4471]
Example: http://jsfiddle.net/dwqxoj3u/

When clicking on Series 1 in the legend, the title on the y axis overlaps with Series 2's labels.  It seems like this bug only happens when the titles are on the right side.  When the titles are on the left side, they don't overlap (see http://jsfiddle.net/LsrfLo6e/).  Tested on Chrome and Firefox.

**Comment by pawelfus** [comment]
By default, left yAxis has `labels.x` set to `x: -15` and is aligning label to display them **inside** the plotting area. When you have two axes, then the second one is trying to display labels inside the plotting area too (by `x: -15`). 

To prevent this, simply set options for yAxis:

            labels: {
             	align: "left",
                x: 0
            }

Demo: http://jsfiddle.net/dwqxoj3u/1/

**Comment by chezmix** [comment]
That works, thank you!
