### ISSUE TITLE
Bar charts are not displaying the label when values are zeros, just some of them are random

### ISSUE THREAD

**Issue by daniijackson** [highslide-software/highcharts.com#4473]
When using Bar chart and having 1 serie, values from 0 to 10, and data is zero in some cases the labels are not displayed for all the zero values given.

We found this when using the chart and after that we went to the live code tool you guys have and fount exactly the same.

![image001](https://cloud.githubusercontent.com/assets/10951343/9254986/0f3addae-41ac-11e5-8c8f-fead27926fe0.png)

**Comment by highslide-software** [comment]
I recreated this in a live demo: http://jsfiddle.net/highcharts/t4dx8L7n/1/

What happens is that the data labels are colliding, so we remove some of them. This can be prevented through the `allowOverlap` setting: http://jsfiddle.net/highcharts/t4dx8L7n/2/.

In addition to that, you'll probably notice that the labels aren't really overlapping. We found that the algorithm was too sensitive (including a 5px padding on each label), so we have fixed that for the next release: http://jsfiddle.net/highcharts/t4dx8L7n/3/
