### ISSUE TITLE
Two separate zones breaks exporting

### ISSUE THREAD

**Issue by pawelfus** [highslide-software/highcharts.com#4481]
Demo: http://jsfiddle.net/x13z8bgw/1/

Export to png - almost everything is missing (labels, second series etc.): 

![chart 82](https://cloud.githubusercontent.com/assets/1453926/9306699/3d34cc32-44fa-11e5-84d4-2ada98854501.png)

Note: SVG is proper.

**Comment by highslide-software** [comment]
Duplicate of #3972.

The status is that we're waiting for PhantomJS 2 to be released for the Linux build we're using on the export server, but we're considering moving the export server to Ubuntu which works. @gvaartjes .
