### ISSUE TITLE
Line disappears during animation if series.step is enabled

### ISSUE THREAD

**Issue by davidmeeker** [highslide-software/highcharts.com#4482]
When adding a new point to a line chart with step enabled, the line disappears during animation then reappears after all the point markers have slid to the their new locations. 

In the linked fiddle, press the "Add point" button to illustrate.

http://jsfiddle.net/h13L5aqt/

Observed with Chrome 44.0 on Windows 8.1.

**Comment by sebastianbochan** [comment]
+!

**Comment by dawidgorus** [comment]
+1
