### ISSUE TITLE
Including highcharts-3d.js breaks axis style

### ISSUE THREAD

**Issue by chtefi** [highslide-software/highcharts.com#4490]
Hi,

I have a chart with some xAxis styling (`lineColor`, `lineWidth`).
http://jsfiddle.net/2v6ru51z/1/

It's working properly, until I include the script `highcharts-3d.js` into the page (uncomment the `<script>` in the jsfiddle). The axis color disappears.

**Comment by pawelfus** [comment]
It's fixed on master branch, take a look: http://jsfiddle.net/2v6ru51z/2/

**Comment by chtefi** [comment]
Indeed.

Thanks !
