### ISSUE TITLE
Highcharts Pie Chart - Renders partially off screen to right hand side

### ISSUE THREAD

**Issue by jamesallchin** [highslide-software/highcharts.com#4491]
Hi, 

For some reason, with the following Pie chart config it is rendering across to the right hand side. Half of it is missing. 

https://jsfiddle.net/ddowak3g

$(function () {
    $('#container').highcharts(
    
{
    
        "exporting": {
            "buttons": {
                "contextButton": {
                    "text": "EXPORT",
                    "menuItems": [
                        {
                            "textKey": "printChart"
                        },
                        {
                            "textKey": "downloadSVG"
                        }
                    ]
                }
            }
        },
        "title": {
            "text": "Results",
            "style": {
                "font-size": "20px"
            }
        },
        "tooltip": {
            "pointFormat": "{series.name}: <b>{point.percentage:.1f}%</b>"
        },
        "plotOptions": {
            "pie": {
                "animation": false,
                "minSize": 200,
                "allowPointSelect": true,
                "cursor": "pointer",
                "dataLabels": {
                    "useHTML": true,
                    "enabled": true,
                    "style": {
                        "color": "black",
                        "width": "170px",
                        "textShadow": ""
                    },
                    "connectorColor": "silver"
                }
            }
        },
        
    "series": [
        {
            "type": "pie",
            "name": "Responses",
            //"innerSize": "50%",
            "data": [
                [
                    "Yes, I am highly convinced XXXX will now stay in the XXXX and puts the XXX issue to bed.",
                    1
                ],
                [
                    "Yes, I am somewhat convinced XXXX will now stay in the XXXX and the market should move on.",
                    17
                ],
                [
                    "Neutral / No view",
                    6
                ],
                [
                    "No, I am somewhat convinced it is not enough and / or XXXX will not deliver and the Greek issue is likely persist",
                    19
                ],
                [
                    "No, I am highly convinced that it is not enough and/or XXXX cannot possibly deliver and the Greek issue will persist.",
                    14
                ]
            ]
        }
    ]
}    
    
    
    
    );
});

With different data - I don't seem to get the issue. It could be to do with the size of the labels. However, I am using the workaround for fixing the width and therefore making sure that the text wraps. 

Thanks for any help. 

James

**Comment by jamesallchin** [comment]
Looking at this further the bug appears to be with useHTML set to true on the data labels

If I remove this setting then the chart aligns correctly

This bug seems to be long labels with useHTML set to true (or could be my poor usage of it whereby I am not applying any HTML tags)

**Comment by pawelfus** [comment]
It's fixed on the master branch, check this: http://jsfiddle.net/ddowak3g/1/
