### ISSUE TITLE
Wrong stacking

### ISSUE THREAD

**Issue by likwifi** [highslide-software/highcharts.com#4492]
Hi guys.
I have two series in stacked mode (stacking:normal) and if one of the series don't have others x timestamp stacking is broken please see attachment.
If second serie x value doesnt exist highstock should calculate it by projecting it on another one.
http://jsfiddle.net/2nhLqk7d/1/

![bug](http://forum.highcharts.com/resources/image/5115?sid=fe960f86566d20ee4d3ae00078195693)

**Comment by pawelfus** [comment]
Looks like specific case for #2285 (duplicate). Also, check this discussion: #2069
