### ISSUE TITLE
Gauge VU meter demo chart tooltip not visible

### ISSUE THREAD

**Issue by maxdeepfield** [highslide-software/highcharts.com#4494]
On this page http://www.highcharts.com/demo/gauge-vu-meter I get following result:
![image](https://cloud.githubusercontent.com/assets/1029366/9378488/7e4654a2-472a-11e5-9fd6-b318696041ab.png)

Windows 10 Build 10240 (64-bit)
Chrome 44.0.2403.155 m (64-bit)

**Comment by pawelfus** [comment]
Tested on Chrome 44 on osx - works fine (tooltip not visible at all). 
Simply, demo is set without `tooltip.positioner` which is rendered below the visible plotting area. See: http://jsfiddle.net/qs7fj75y/


Snippet: 

        tooltip: {
          	positioner: function(w, h, p) {
             	return {
                 	x: p.plotX - w /2,
                    y: 50
                }
            }
        },
