### ISSUE TITLE
Flags series.group.toFront() does not work

### ISSUE THREAD

**Issue by gevgeny** [highslide-software/highcharts.com#4495]
I tried to use the flags series element in `flags.events.mouseOver` handler in order to change its z-index via `this.group.toFront()` but found out this does not work. In [the demo](http://jsfiddle.net/ttxr4th6/)  I expected to see this element on flag `mouseOver` event
```html
<g class="highcharts-markers highcharts-tracker" visibility="visible" zIndex="0.1" transform="translate(10,45) scale(1 1)" style="">...</g>
``` 
since this node contains all appropriate paths, but displayed this one: 
```html
<g class="highcharts-series" visibility="visible" zIndex="0.1" transform="translate(10,45) scale(1 1)" clip-path="url(#highcharts-1)"></g>
```
which is empty.

**[jsFiddle](http://jsfiddle.net/ttxr4th6/)**
**Highstock JS v2.1.8**
**Chrome 46.0.2456.0**

**Comment by pawelfus** [comment]
Why this is wrong? Event is set on a series level, and series contains group element, which contains other groups, shapes etc. 

Maybe instead you want  `this.markerGroup.element` ?

**Comment by gevgeny** [comment]
Agree. I was just confused by this example http://jsfiddle.net/xjgRY/13/ but now i see the difference. And `this.markerGroup.element` works as I wanted. Thanks!
