### ISSUE TITLE
After todays update V4.1.8 NoData label remains on chart

### ISSUE THREAD

**Issue by onemenny** [highslide-software/highcharts.com#4496]
after upgrade to 4.1.8 no data label text remains on chart even after adding data series with data to chart

**Comment by highslide-software** [comment]
Live demo please? It works as advertised in the [official sample](http://jsfiddle.net/gh/get/jquery/1.7.2/highslide-software/highcharts.com/tree/master/samples/highcharts/no-data-to-display/no-data-line/).

**Comment by onemenny** [comment]
sorry, no easy reproduced on fiddle. 
it seems that the series.dataMax and series.dataMin are undefined when checking hasData(). while the series defiantly has data - does this rings any bells related to your other changes in this version?

**Comment by highslide-software** [comment]
Not off the top of my head - is this Highstock?

**Comment by onemenny** [comment]
highcharts not highstock

**Comment by sebastianbochan** [comment]
Which browser? cause in the newest Chrome works well.

**Comment by onemenny** [comment]
chrome and ff. unfortunately i'll be oof this week. so i'll try and repro it in fiddle later. you can close this issue and i'll reopen it later on.
