### ISSUE TITLE
Show legend as a dropdown

### ISSUE THREAD

**Issue by ducnguyenhuy** [highslide-software/highcharts.com#4497]

**Comment by KacperMadej** [comment]
To get support use forum or StackOverflow. For requests use UserVoice. This is github and it is not for posting help request - read our rules for issue reporting and report it on GitHub Issues (https://github.com/highslide-software/highcharts.com/blob/master/readme.md#reporting-issues). It's not a bug, please check with us in one of the support channels first. More information: http://www.highcharts.com/support
