### ISSUE TITLE
How to add label after the bar

### ISSUE THREAD

**Issue by liuhongqiang** [highslide-software/highcharts.com#4506]
How to add label after the bar? like this:
![qq 20150826094459](https://cloud.githubusercontent.com/assets/5810729/9483846/2c31f502-4bd7-11e5-8144-634bd0af29e8.png)
thanks.

**Comment by pawelfus** [comment]
Hello,

This is bug tracker, where we report bugs. For support question, please, use any of our other channels (forum, email, stackoverflow), see [here](http://www.highcharts.com/support).

PS: I would use second xAxis with categories - I think it's the easiest way to achieve that.
