### ISSUE TITLE
[Column chart]: Tooltip stops working when zooming

### ISSUE THREAD

**Issue by JulianLettner** [highslide-software/highcharts.com#4511]
1) http://jsfiddle.net/z8bmmgg4/4/
2) Zoom in deep on the lower part of the chart: tooltip for column 1 (or any bar where the "tooltip snap area" is too far off the viewable area of the chart) stops working

Another experiment with a custom positioner: http://jsfiddle.net/gfuhfhdj/
Note that the positioner isn't even called for colums where the tooltip is not shown.

**Comment by pawelfus** [comment]
Minified demo: http://jsfiddle.net/z8bmmgg4/5/ - in short it's caused by `yAxis.max`, which renders column high and distance for tooltip is bigger than chart's width.
