### ISSUE TITLE
HighStocks 2.1.8 Series Disappears on Zoom Out

### ISSUE THREAD

**Issue by NathanWolf** [highslide-software/highcharts.com#4512]
This issues seems specific to HighStocks, and specific to using the "keys" property to change which data values are used for the y component of a line series. It does not happen with HighCharts, or when not specifying "keys". 

This seems to happen with or without data grouping enabled.

Reproduction case:

http://jsfiddle.net/NathanWolf/qs0fLmcn/1/

No data is visible until you zoom in, at which point the series appears. It disappears again when zooming back out.

**Comment by pawelfus** [comment]
Well, disabling dataGrouping workarounds this issue: http://jsfiddle.net/qs0fLmcn/2/

Or better, add approximation for it, like this: http://jsfiddle.net/qs0fLmcn/3/

*Internal note:*
This is cased by keys and approximation. Approximation by default returns format `[y]` or `[o, h, l, c]`, but when creating point, we are back again in `optionsToObject` method, it tries to apply `keys` array again.

**Comment by NathanWolf** [comment]
Thank you for the work-around! I thought I tried disabling dataGrouping, my apologies.

I think I can work with this, I do need data grouping for the detail view, but the summary view seems to be the only one that exhibits this problem so far.

On a side-note, your approximation code reminded me- I've had some issues with empty series on the graph producing errors due to the data grouping populating an undefined point. Specifically, it can cause tooltip issues, and also errors when calling get() for a series/axis/etc that does not exist- the fallback case to scan through all chart points will throw an error when it gets to the undefined point.

Is that intended behavior (looking at your approximation implementation here, not sure what else it should return in the empty case)? Should I open a separate issue for that if I can make a simple reproduction case?

Thank you again!

**Comment by pawelfus** [comment]
I'm not quite following your case. In general `get()` returns point/series/axis if such item exist. When you have grouped points, then point with expected ID may not exist, since it's grouped into other, grouped, point. You can imagine having each of the points separate ID's - there is no logic for grouping ID's (or any other properties). 

And regarding "empty case" - I'm not sure what do you mean. How approximation should work - see comments in the demo. There shouldn't be any undefined points, but in case all points are null, or there is range without any point, then it should return undefined.

In general, I suggest to contact with us by email, if you are not sure if something is bug or expected behavior - we are trying to keep github tickets as bugs, not support channel.

**Comment by NathanWolf** [comment]
Yes, apologies, I wasn't trying to get support here!

To clarify, I have seen a case where an actual "undefined" value gets into the "points" list for a series. This will cause errors in various places, get() being one example because it can iterate over all points and try to look at their ids. 

I thought it was related to data grouping on an empty series, though I am unsure. At the very least it's not something I've seen happen in HighCharts, only HighStocks.

I am having trouble working up a standalone reproduction case for this, if I can make one I will open a separate Issue.

**Comment by nhitchins** [comment]
Also experiencing a very similar problem after upgrading to Highstock 2.1.8...chart appears blank (but tooltips visible on mouse-over) until a resize/zoom or series hide/show event.

**Comment by pawelfus** [comment]
Could you setup jsfiddle? Have you tried also to setup `approximation` like in my example above?

**Comment by nhitchins** [comment]
I will try reproduce in a simplified jsfiddle when I get the chance. 
I'm surprised there has been a breaking change in the latest version that now requires the custom approximation function to be specified rather then using a sane default. All my charts are highly dynamic and I'm concerned about potential problems this change may cause - although have not had the time as of yet to fully review.

**Comment by highslide-software** [comment]
@nhitchins Maybe your problem with 2.1.8 is the same as #4520?

**Comment by nhitchins** [comment]
2.1.9 seems to have resolved my issue (looks like it was related to #4520).

**Comment by highslide-software** [comment]
Great!
