### ISSUE TITLE
Bubble chart - wrong color after update to negative value

### ISSUE THREAD

**Issue by sebastianbochan** [highslide-software/highcharts.com#4514]
Steps to reproduce:
1) Run example: http://jsfiddle.net/zth3r2yn/9/
2) Click update button
3) As a result bubble has a negative value 
4) Negative color should be applied, but is not. You need to hover on a point and then color is refreshed properly.

**Comment by pawelfus** [comment]
Duplicate of #4267
Fixed on bugfix branch: http://jsfiddle.net/zth3r2yn/10/
