### ISSUE TITLE
Function searchPoint not working correct

### ISSUE THREAD

**Issue by vodun** [highslide-software/highcharts.com#4515]
Function searchPoint not working correct, when using boost module.
Example http://jsfiddle.net/wquaka51/
when cursor in one chart, show incorrect in another charts.
![4c9120e4-4c1c-11e5-8dd3-fc4b1ce05560 1](https://cloud.githubusercontent.com/assets/5072038/9516696/cf3fb800-4cc3-11e5-9a18-51d545ee372b.png)

**Comment by highslide-software** [comment]
Closed by f861c19e87acab46431f35a7aae7bca4276e2ac2
