### ISSUE TITLE
Export Server: Issue with German umlauts under Microsoft Windows

### ISSUE THREAD

**Issue by JHAServiceTrace** [highslide-software/highcharts.com#4517]
Hello,

we use the Highcharts Export Server, which runs within a Tomcat 7 at a Windows 7 host. We encountered an issue while exporting a chart in SVG format. If we tried to open the SVG File the browser shows the exported chart partially and displays an error message.

![chart svg-error](https://cloud.githubusercontent.com/assets/13998086/9520002/1a4b683a-4cc4-11e5-9599-e77c73d104e8.png)

The error can be replicated by sending the following config object to our Highcharts Export Server:

{
	xAxis: {
		categories: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 
			'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
	},
	series: [{
      name: 'öäü',
		data: [29.9, 71.5, 106.4, 129.2, 144.0, 176.0, 
			135.6, 148.5, 216.4, 194.1, 95.6, 54.4]
	}]
};

We cannot replicate the issue with your export server at http://export.highcharts.com/. A code review showed the cause of this issue. Within the class com.highcharts.export.controller.ExportController (exporting-server\java\highcharts-export\highcharts-export-web\src\main\java\com\highcharts\export\controller.ExportController.java) the method outputToStream() converts the string 'output' to a byte array using the following invocation:

output.getBytes()

The method getBytes() uses the character set of the respective operating system. Under Windows 7 this is Windows-1252, which is very similar to the ISO/IEC 8859-1 character set. The export server's HTTP response header specifies UTF-8 as character set. Thus German umlauts (äöü) are formatted wrong: the export server - i.e. the method getBytes() - uses Windows-1252 and the browser tries to decode UTF-8, because the HTTP header specifies UTF-8. To run the export server under MS Windows you should convert the above mentioned string 'output' with the parameterized method getBytes(Charset.forName("UTF-8")). Thus the export server does not depend on the underlying operating system. I solved the issue by changing the mentioned method as follows:

	private ByteArrayOutputStream outputToStream(String output, boolean base64) throws SVGConverterException {
		ByteArrayOutputStream stream = new ByteArrayOutputStream();
		try {
			if (base64) {
				 //decode the base64 string
				stream.write(Base64.decodeBase64(output));
			} else {
				stream.write(output.getBytes(Charset.forName("UTF-8")));
			}
		} catch (IOException ex) {
			logger.error("Error in outputToStream: " + ex.getMessage());
			throw new SVGConverterException("Error while converting");
		}

		return stream;
	}

As mentioned, we cannot replicate the issue at your export server. I guess, your export server runs on an operating system using UTF-8 as default character set.

To use the export server on Windows systems you should specify the character set in the method getBytes().

Regards

  Jochen.

**Comment by gvaartjes** [comment]
Hi, 

Thanks for spotting this! I will change this in the repo soon. It's meant that the export-server forces this to UTF-8.

**Comment by JHAServiceTrace** [comment]
Hello,

yes it's meant to force the character set to UTF-8.


Thanx

   Jochen.
