### ISSUE TITLE
Bubbles plotBackgroundImage setting does not work.

### ISSUE THREAD

**Issue by jarrettj** [highslide-software/highcharts.com#4518]
Hi,

Good day.

Using the highcharts-convert.js to generate a graph image to include in a word document. Bubble chart is generated but the background image is not used. Tried using relative and absolute path to the image. No luck.

Is this feature unsupported?

Cheers.

**Comment by pawelfus** [comment]
Looks like not connected to bubble series, tested with:

    curl -H "Content-Type: application/json" -X POST -d '{"infile":"{xAxis: {categories: [\"Jan\", \"Feb\", \"Mar\"]},series: [{data: [29.9, 71.5, 106.4]}], chart: { plotBackgroundImage: \"test.jpg\"}}", "outfile":"test_4.png"}' 127.0.0.1:3003


It doesn't work for png/jpg but works fine for SVG - but only when SVG is opened in in a folder where path to image is proper (in the example above - test_4.png and test.jpg must be in the same folder). 

Of course, workaround is to use files not from local filesystem, but with `http` path.

**Comment by jarrettj** [comment]
You a legend dude! Using the URL to the image works for png. Thanks!
