### ISSUE TITLE
Invalid minimum range on y-axis detected

### ISSUE THREAD

**Issue by mitar** [highslide-software/highcharts.com#4522]
If you open [this example](http://jsfiddle.net/zdkn6u8w/1/) you will see that y-axis goes from -250 up. And not from 0 or some other value around there. Even more interesting is that if I click on the legend and hide the GOOG series, the y-axis is resized correctly, starting from 0. But GOOG series never goes below 100?

**Comment by stanleyxu2005** [comment]
I have similar problem. I fixed a bit quick and dirty by having this:
```
          yAxis: {
            min: 0,
          },
```
I think there must be a boundary gap threshold for that, but I haven't found.

**Comment by pawelfus** [comment]
It's caused by `minPadding` option, see: http://jsfiddle.net/zdkn6u8w/5/

**Comment by mitar** [comment]
I think the `minPadding` is misbehaving here. I understand that one can workaround by disabling it. But why would adding a series which never go under 100, add negative tick? This is simply wrong. And a bug.

**Comment by pawelfus** [comment]
I agree, this is a bit strange behavior, but this is exactly how `minPadding` works. It adds extra padding for series, to not touch or even come close to the edge of the chart. In the demo above, `0.05` renders yAxis below the zero and with `startOnTick` it makes bigger difference. I'm sorry, but I don't think this is a bug, just a case where `minPadding: 0.05` doesn't suit for the chart and that's why you can set that option to any value you want to. If your value is always positive and you don't want to set `minPadding` option (which directly causes that) then set `min` as mentioned above.

**Comment by highslide-software** [comment]
Actually the problem here is not the `minPadding`, and it's not a bug. It is something that should be discussed though. 

The setting in question is the [threshold](http://api.highcharts.com/highcharts#plotOptions.series.threshold). For area and column series, the default threshold is 0, meaning that we assume the data somehow has to do with volume counting from 0. On line series on the other hand, we can't assume that, because we are just as likely dealing with relative scalar values like growth / decrease or any value crossing the 0 plane.  So the threshold option is null by default. If, like in your case, you want to set a 0 baseline, just add a threshold of 0: http://jsfiddle.net/highcharts/zdkn6u8w/10/

**Comment by pawelfus** [comment]
I'm not sure if we really want to set `series.threshold` - in fact it works almost the same as setting `yAxis.min`, see: http://jsfiddle.net/zdkn6u8w/12/ - it's not necessary to show `0` on the yAxis. More descriptive examples: http://jsfiddle.net/zdkn6u8w/14 vs http://jsfiddle.net/zdkn6u8w/15/

**Comment by mitar** [comment]
But I still do not get how can a series which never goes under 100 make highcharts to draw a tick below 0 to -250. If I in [my example](http://jsfiddle.net/zdkn6u8w/1/) change `names = ['MSFT', 'AAPL', 'GOOG'];` to `names = ['MSFT', 'AAPL'];`, highcharts normally draw y-axis from 0 on. And then I add a series `GOOG` which does not go under 100, and a -250 tick appears. After reading here things I understand that there are some configuration options to direct this behavior, but does it really sound a reasonable automatic behavior?

So my issue here is that I am creating a tool using highcharts to visualize various datasets, where users can add and remove series. It is not that I am creating one chart where I can hard-code such settings. This is why it is surprising that when user adds a series which should not change low limit on y-axis, y-axis changes.

**Comment by highslide-software** [comment]
@mitar Here's the rationale:

* When you display only MSFT and AAPL, the data range is 12.06-130.03. Now we add the minPadding and maxPadding and round to the nearest tick, and the result is 0-150.
* Then we add GOOG. The data range becomes 12.06-653. When we add the minPadding to this larger range, we end up below zero. Then we round to the closest full tick, and end up at -250.

**Comment by highslide-software** [comment]
Now that doesn't mean I don't see the problem. I understand that users expect line series not to cross the zero plane unless the data does so. But for the reasons @pawelfus points out above, the threshold is not the appropriate solution either. What we need is some kind of soft threshold that works like the current threshold option unless the data is far from the threshold setting. Imagine these cases:

* [High dangling data](http://jsfiddle.net/highcharts/p3zqx743/). It should behave like it does currently.
* [Positive, close to zero plane](http://jsfiddle.net/highcharts/p3zqx743/1/). Y axis should not show negative values.
* [Crossing the zero plane](http://jsfiddle.net/highcharts/p3zqx743/2/). It behaves correctly.
* [Negative close to zero plane](http://jsfiddle.net/highcharts/p3zqx743/3/). It should not show positive numbers on the Y axis.
* [Low dangling data](http://jsfiddle.net/highcharts/p3zqx743/4/). It behaves correctly.

What do you think? My impression from looking at user provided data at cloud.highcharts.com tells me that this would the best default behaviour for line series.

**Comment by highslide-software** [comment]
@pawelfus In this case, I think setting `yAxis.floor` to 0 would fix both cases. It will work as long as there are no negative values.

**Comment by mitar** [comment]
What I think I have the biggest issue is that when I open [the example](http://jsfiddle.net/zdkn6u8w/1/), I visually see that there are extra empty vertical pixels before the lowest part of the series and the 0 line. And then Highchart still adds an extra tick. I think I would less complain if visually at least one of the lines would go so close to the 0 line that I could not tell if it is there or if it is crossing. But here is really visible that it is unneeded. In some way, having that extra tick when the series is around 0 would be an useful way to tell to the chart reader that value seems to go over 0. So if it goes just to the 0 (including 0), then no extra tick should be created. But if it goes over, a tick should be created. Then you could reason about those extremes just from looking at the ticks.

**Comment by highslide-software** [comment]
I agree. Here's one from [our own demos](http://jsfiddle.net/highcharts/hrwt3bwj/). Negative wind speeds don't exist, so in the official demo we had to add yAxis.min = 0. But it should be handled automatically.

**Comment by highslide-software** [comment]
Here's your demo with the fix: http://jsfiddle.net/highcharts/zdkn6u8w/17/. The old behaviour is now available by setting `softThreshold` to false: http://jsfiddle.net/highcharts/zdkn6u8w/18/

What do you think?

**Comment by highslide-software** [comment]
@pawel This change breaks a few of the test cases, where the demo data was close to 0. But in all those cases the new behaviour makes more sense I think.

**Comment by pawelfus** [comment]
Ok, thanks for the heads-up!

**Comment by mitar** [comment]
Oh, great! Thanks!
