### ISSUE TITLE
Exporting: allowHTML breaks SVG exported files.

### ISSUE THREAD

**Issue by KacperMadej** [highslide-software/highcharts.com#4525]
When exporting with allowHTML set to true, to SVG format exported file contains error. Double quotes after `y`'s value in `foreignObject` is not closed.

`<foreignObject x="0" y="0 width="200"`

Example: http://jsfiddle.net/RH6kG/2/
Steps: 
1. Export to SVG
2. Open exported SVG in Chrome or Firefox to see the error

Simpler example (same steps): http://jsfiddle.net/4dnrrrf3/

**Comment by pawelfus** [comment]
Responsible [line](https://github.com/highslide-software/highcharts.com/blob/5f31f655b67478454c63c7c7adf366175ca01b1a/js/modules/exporting.src.js#L356).
