### ISSUE TITLE
Highstock: yAxis update doesn't update its clip-path if more axes are using that clip-path

### ISSUE THREAD

**Issue by KacperMadej** [highslide-software/highcharts.com#4526]
In Highstock, when there are multiple yAxes with set top and height. Both are of the same size and are using one clip-path, but have different top option. Only when updating last axis assigned to that clip-path will update clip-path. Updating yAxis that is not the last axis using the same clip-path will not update clip-path and series can get clipped off.

Example: http://jsfiddle.net/gakan637/3/
Steps:
1. Click 'update 1' to update first yAxis in first chart and increase height of axis.
2. Clip-path is not changed and series in first yAxis gets clipped off
3. Click 'update 2' to update second yAxis in second chart and decrease height of axis.
4. Clip-path is changed and series in first yAxis gets clipped off

**Comment by pawelfus** [comment]
Issues comes from [this line](https://github.com/highslide-software/highcharts.com/blob/86383898d27f5e74efd11c792d9f0b2e5cdb8e2d/js/parts/Series.js#L843) - both series share the same clipPath, while should use separate ones. I think adding `options.xAxis` and `options.yAxis` should resolve that issue - added both should prevent when one pane is next to the other (xAxis.left) and when one pane is under the another (yAxis.top).

**Comment by pawelfus** [comment]
*Internal note:* 
It happens only for Highstock, but root of the problem is deeper, as stated above.
