### ISSUE TITLE
Boost module: error with pie charts

### ISSUE THREAD

**Issue by limkinZero** [highslide-software/highcharts.com#4529]
Hi,

I know it this module only used when you have too much data with line, column, area charts but when i push the file boost.js in my project I'm having errors at init pie charts because it hasn´t xAxis.
```
hasExtremes: function (checkX) {
            var options = this.options,
                data = options.data,
                xAxis = this.xAxis.options,
                yAxis = this.yAxis.options;
```
The error is: 
TypeError: Cannot read property 'options' of undefined
    at Object.H.extend.hasExtremes (http://localhost:18080/test/?serverAction=full-screen-js:122179:35)

How could I used the boost module without affecting the type pie charts?

**Comment by highslide-software** [comment]
Until the next maintenance release, add this snippet to your page to work around the issue:

```js
Highcharts.wrap(Highcharts.Series.prototype, 'hasExtremes', function (proceed, checkX) {
    if (this.xAxis && this.yAxis) {
        return proceed.call(this, checkX);
    } else {
        return false;
    }
});
```

[View live demo](http://jsfiddle.net/highcharts/7teteh1n/).

**Comment by limkinZero** [comment]
Thanks, Now it works fine.
