### ISSUE TITLE
Highmaps: postcodes for United Kingdom (gb-all) are not correct

### ISSUE THREAD

**Issue by KacperMadej** [highslide-software/highcharts.com#4531]
For example:
- Portsmouth postcode starts "PO", but the map postal-code is "PS"
- Belfast postcode starts "BT", but the map postal-code is "BF"

The main problem is that gb-all is a map of UK divided into counties, while postcode areas map in the United Kingdom is very different.
Map demo: http://jsfiddle.net/gh/get/jquery/1.11.0/highslide-software/highcharts.com/tree/master/samples/mapdata/countries/gb/gb-all
Postcodes areas: https://en.wikipedia.org/wiki/List_of_postcode_areas_in_the_United_Kingdom

**Comment by highslide-software** [comment]
Our map data is based on Natural Earth. If NE doesn't have the postcode data for UK, it may be out of our league to implement it...

**Comment by oysteinmoseng** [comment]
Our maps are divided into administrative regions. For maps where those do not correspond to postal regions, postal codes won't make sense. Perhaps it should be removed from our UK map, to avoid confusion. Otherwise there isn't much we can do, apart from adding a new map with postal regions.
