### ISSUE TITLE
3D Column Chart with stack /grouping option not working

### ISSUE THREAD

**Issue by pawanvjadhav** [highslide-software/highcharts.com#4532]
3D Column chart with Stack / grouping option is not working in case of 3D option.

Check below url :
with 3D Option disable
http://jsfiddle.net/pawanvjadhav/6e8ds0xe/2/
With 3D Option enable :
http://jsfiddle.net/pawanvjadhav/6e8ds0xe/3/

Here is what i observered:
3D Column has some issue when you specify series.stack option value as string (in my case "m1").

**Comment by pawanvjadhav** [comment]
Just one question, you have resolved this. Now, from where i can download minified version of highchart 3D?

**Comment by pawelfus** [comment]
You can apply changes as described [here](https://github.com/highslide-software/highcharts.com) (Apply a fix).

Or you can download from [here](https://github.com/highslide-software/highcharts.com/blob/31c514bed9ae687eea6f21d8b25f2676b7c135cb/js/highcharts-3d.src.js).

Note: this is fixed only on a bugfix branch now, not in the master.

**Comment by pawanvjadhav** [comment]
https://github.com/highslide-software/highcharts.com/blob/31c514bed9ae687eea6f21d8b25f2676b7c135cb/js/highcharts-3d.src.js

Yes i found this but I need minified version of this file.
