### ISSUE TITLE
pointBreak event - works only in column and yAxis

### ISSUE THREAD

**Issue by sebastianbochan** [highslide-software/highcharts.com#4533]
Seems that break event works in column not in lines. Let's compare:
- http://jsfiddle.net/sssdajsL/3/ works
- http://jsfiddle.net/sssdajsL/4/ doens't work

Next observation is that event is not catched, when we set pointBreak on xAxis.
Example: http://jsfiddle.net/sssdajsL/5/ (doesn't matter what type of serie)

**Comment by pawelfus** [comment]
*Internal note:*
Issue with xAxis: simply, code is prepared to call events for yAxis only.
Issue with different types: it works only for columns (or series which inherits `drawPoints` from columns). We should wrap `Highcharts.seriesTypes.column.prototype` **and**  `Highcharts.Series.prototype`. @highslide-software  - what approach we should choose? 

- Create separate method (`function drawBreaks() {}`) and then use that method in wrappers?
- Create new method for Series: `Highcharts.Series.prototype.drawBreaks` and then write two wrappers to use that method in `drawPoints`? 

The second solution sounds more reasonable - allows to wrap `drawBreaks` method in case it would be necessary.

**Comment by pawelfus** [comment]
Snippet for a second approach:


	H.Series.prototype.drawBreaks = function () {
             ...
        };
 
	wrap(H.seriesTypes.column.prototype, 'drawPoints', function (proceed) {
		proceed.apply(this);
		this.drawBreaks();
	});

	wrap(H.Series.prototype, 'drawPoints', function (proceed) {
		proceed.apply(this);
		this.drawBreaks();
	});

**Comment by highslide-software** [comment]
I say we combine them. It preserves the flexibility and is a little bit shorter than alternative 2:

```js
function drawPointsWrapped (proceed) {
    proceed.apply(this);
    this.drawBreaks();
}
H.Series.prototype.drawBreaks = function () {
    ...
};

wrap(H.seriesTypes.column.prototype, 'drawPoints', drawPointsWrapped);
wrap(H.Series.prototype, 'drawPoints', drawPointsWrapped);

```

**Comment by moses-seeq** [comment]
+1
