### ISSUE TITLE
Highstock with RangeSelector on PrimeFaces Dialog component

### ISSUE THREAD

**Issue by marcellodonvito** [highslide-software/highcharts.com#4534]
Hello,

I am using [PrimeFaces](https://github.com/primefaces/primefaces) 5.2 and Highstock charts for my web application deployed on Tomcat 7.0. 

I have created a [simple maven web project](https://dl.dropboxusercontent.com/u/13253991/test.war) of one [page](http://localhost:8080/test/xhtml/home.jsf) that contains a single Highstock chart with RangeSelector feature enabled. The charts and the feature work good.

When I put a similar chart into a PrimeFaces Dialog component the RangeSelector feature does not work because the following div is not rendered/loaded.

```
<div style="position: relative; height: 0px; z-index: 1;">
<input class="highcharts-range-selector" type="text" name="min" style="position: absolute; border: 0px none; width: 1px; height: 1px; padding: 0px; text-align: center; font-size: 12px; font-family: "Lucida Grande","Lucida Sans Unicode",Arial,Helvetica,sans-serif; top: 51px; left: 1031.92px;">
<input class="highcharts-range-selector" type="text" name="max" style="position: absolute; border: 0px none; width: 1px; height: 1px; padding: 0px; text-align: center; font-size: 12px; font-family: "Lucida Grande","Lucida Sans Unicode",Arial,Helvetica,sans-serif; top: 86px;">
</div>
```
Without this div I cannot set any custom date on Highstock chart into the Dialog.

I do not understand if this issue may be related to the Primefaces Dialog component or it may be related to the Highstock product.

**Comment by highslide-software** [comment]
Hi, you have found our bug tracker, for general tech support, please see www.highcharts.com/support.

PS: If you manage to reproduce the failure on jsFiddle, you have eliminated your backend, and it will be easier for our support engineers to help you. Since Highcharts runs on the client, we generally only support client-side problems.

**Comment by marcellodonvito** [comment]
Hi,
I have reproduced the issue on [JSFIDDLE](http://jsfiddle.net/MarcelloDonvito/db5SX/5812/) using a JQuery Dialog (the same used by PrimeFaces).

**Comment by highslide-software** [comment]
The event binders probably get lost when the contents of the div is moved into the popup. A better approach may be to create the chart after the popup is opened: http://jsfiddle.net/highcharts/db5SX/5813/

**Comment by marcellodonvito** [comment]
Hi,
I see, but even now I cannot insert a date into min or max input field. The two input fields exist but they seems frozen.
