### ISSUE TITLE
API reference in JSON format: chart--type doesn't have 'bar' lsited as a one of possible values

### ISSUE THREAD

**Issue by KacperMadej** [highslide-software/highcharts.com#4537]
Setting 'bar' is working and accordingly to description supported, so it looks like 'bar' is missing in values array.

`{"name":"chart--type","fullname":"chart.type","title":"type","parent":"chart","isParent":false,"returnType":"String","defaults":"line","values":"[\"line\", \"spline\", \"column\", \"area\", \"areaspline\", \"pie\", \"arearange\", \"areasplinerange\", \"boxplot\", \"bubble\", \"columnrange\", \"errorbar\", \"funnel\", \"gauge\", \"scatter\", \"waterfall\"]","since":"2.1.0","description":"The default series type for the chart. Can be any of the chart types listed under <a href=\"#plotOptions\">plotOptions</a>.","demo":"<a href=\"http://jsfiddle.net/gh/get/jquery/1.7.2/highslide-software/highcharts.com/tree/master/samples/highcharts/chart/type-bar/\" target=\"_blank\">Bar</a>","deprecated":false}`

**Comment by highslide-software** [comment]
Fixed, thanks for notifying.
