### ISSUE TITLE
Bubble chart - null radius - missing  tooltip 

### ISSUE THREAD

**Issue by sebastianbochan** [highslide-software/highcharts.com#4543]
In case when we set a null value of radius, then this information is extracted from marker.radius. But the problem is missing value in tooltip (Size label).

Example: http://jsfiddle.net/zth3r2yn/15/

Let's consider if bubble should be printed or not we set a null value of radius.

**Comment by hmha** [comment]
I think it should not draw a marker for null data points, regardless of the minSize.

**Comment by highslide-software** [comment]
Apparently a Z value of null currently gives the same result as 0: http://jsfiddle.net/highcharts/zth3r2yn/16/.

**Comment by hmha** [comment]
Yes, but drawing markers when all values are null or 0(particularly null) is misleading.

**Comment by hmha** [comment]
Thanks for fix.
I have found one case where null values are presented: http://jsfiddle.net/zpw2rtzd/. If you set "sizeByAbsoluteValue: false", nulls arent presented.
