### ISSUE TITLE
flag not receiving mouseover correctly when above serie

### ISSUE THREAD

**Issue by iweindesmedt** [highslide-software/highcharts.com#4546]
http://jsfiddle.net/rkj7ou5h/2/

example is with ```column``` but it is the same effect/bug with other serie types
this is an annoying bug because of the hard-to-get tooltip or click event
happens only with ```tooltip shared:true```

**Comment by highslide-software** [comment]
The same issue happens with pie series within a chart with `shared:true`: http://jsfiddle.net/highcharts/rkj7ou5h/3/
