### ISSUE TITLE
Rendering artefacts

### ISSUE THREAD

**Issue by wysman** [highslide-software/highcharts.com#4547]
Hi,

At the end of the xAxis, we can see the Y line at the top and bottom at the same time,
when we zoom in the bottom line go away. I have create a jsfiddle to reproduce to rendering issue.

I have test with the highstock 2.1.8 version and highcharts-more loaded.
http://jsfiddle.net/wysman/Lp3tpcub/2/
![bug](https://cloud.githubusercontent.com/assets/1042272/9738110/4b3393c0-564a-11e5-9634-35f96de3adc3.png)

Thanks

**Comment by pawelfus** [comment]
You have errors in JS console - that your data isn't sorted. See demo with sorted data: http://jsfiddle.net/Lp3tpcub/4/

**Comment by wysman** [comment]
Thanks you very much, it's look like a issue in my dataset, not the lib :p 
Sorry
