### ISSUE TITLE
Offline exporting: Firefox is unable to create gradient color for PNG

### ISSUE THREAD

**Issue by KacperMadej** [highslide-software/highcharts.com#4550]
Using Firefox (40.0.3 - latest) and offline-exporting module for exporting chart in offline mode to PNG file gradient color is not created properly - is not displaying.

Example: http://jsfiddle.net/7ponnv7r/2/
Steps: 
1. Export to PNG via chart's context menu.
2. Open downloaded PNG file of the chart and see that linear nor radial gradients are not visible.

**Comment by highslide-software** [comment]
@oysteinmoseng It may be related to [this code block](https://github.com/highslide-software/highcharts.com/blob/v4.1.8/js/parts/SvgRenderer.js#L1217-L1222). Firefox has turned out to be particularly sensitive to how internal URLs are used in SVG.

**Comment by oysteinmoseng** [comment]
This seems to be an issue with Firefox, see minimal example: http://jsfiddle.net/wa1xmvt9

Canvas.drawImage does not appear to work with internal references.

**Comment by oysteinmoseng** [comment]
This is apparently a known (and old) [issue](https://bugzilla.mozilla.org/show_bug.cgi?id=841920) with Firefox and Blobs.
