### ISSUE TITLE
Color axis support for Tree map with levels

### ISSUE THREAD

**Issue by pawanvjadhav** [highslide-software/highcharts.com#4551]
In treemap demos, you have two type : 
1) Treemap with Color axis 
http://jsfiddle.net/gh/get/jquery/1.9.1/highslide-software/highcharts.com/tree/master/samples/highcharts/demo/treemap-coloraxis/
2) Tree map with levels
http://www.highcharts.com/demo/treemap-with-levels

Is it possible to integrate coloraxis for 2nd example "Tree map with levels"
So in demo example , For Banana section : Color for "Rick" will be Yellow color with Higher intensity than "Peter".

**Comment by pawelfus** [comment]
Well, it works. Just don't forget to set `colorValue` and include `heatmp.js` file to add colorAxis. 

See demo: http://jsfiddle.net/fvz7wxn3/

**Comment by pawanvjadhav** [comment]
yes. you are right.
But I want group / parent color to be retained. Example you have shown has same color to all group / parent
Bananas : Yellow
Apples : Red
Oranges : orange
Susane : green

**Comment by pawanvjadhav** [comment]
Any comments on this?

**Comment by pawelfus** [comment]
I see one problem here: you want multiple color axes for just one series (if I am correct), however color axis can be set on a series-level, not on a point-level. 

I would suggest to create an idea on the [Uservoice](highcharts.uservoice.com/forums/55896-general).

**Comment by pawelfus** [comment]
You can always use another solution: calculate colors and set them directly in options, just like this (blue one):  http://jsfiddle.net/j6hu529z/

**Comment by pawelfus** [comment]
And one more solution, based on `colorAxis`. This will use only one color axis, but stops will 'split' axis into separate parts: http://jsfiddle.net/fvz7wxn3/2/

Note, that `stops` are required in such case. It bases on modified `colorValue` value to use separate 'part' of the color axis.

**Comment by pawanvjadhav** [comment]
Thanks for this. Stop solution looks good to me.

As you said, i will create an idea on the Uservoice.

Thank You.,

**Comment by highslide-software** [comment]
@jon-a-nygaard FYI

**Comment by pawanvjadhav** [comment]
Have you consider this in any of your release?

**Comment by jon-a-nygaard** [comment]
@pawanvjadhav: At the moment it is not a priority for us to include this in a release. What I will recommend you to do is to suggest this idea on our [Uservoice](http://highcharts.uservoice.com/).
Uservoice is where we track and manage our feature requests. If your suggestion get enough attention from other users, then we will add it to our roadmap.

**Comment by pawanvjadhav** [comment]
Ok. I have added idea on  Uservoice
https://highcharts.uservoice.com/forums/55896-highcharts-javascript-api/suggestions/10787739-color-axis-support-for-map-with-levels

**Comment by pawelfus** [comment]
Hi @milossesiceng 

Please vote for this feature on the UserVoice ticket posted above :) Features that were implemented to the core are flagged with "Completed" tag.
