### ISSUE TITLE
Pie donut chart text shadow in firefox

### ISSUE THREAD

**Issue by g3ortega** [highslide-software/highcharts.com#4554]
I'm having problems when I try to visualize the donut chart in firefox and old versions of chrome. Apparently the inner labels style (text-shadow specifically) is not applying correctly 

![pie_donut](https://cloud.githubusercontent.com/assets/3050965/9778759/01e55fe4-5732-11e5-866a-b188de515ea7.png)

**Comment by pawelfus** [comment]
Could you tell which Chrome/Firefox versions? Also, could you post some demo (jsfiddle, or one of our demos)?

**Comment by pawelfus** [comment]
Ah, I see now which demo: http://www.highcharts.com/demo/pie-donut

The problem is that our demo uses `white` color, while should use `#ffffff`- we don't have logic to recognize colors according to their names ;) See better demo: http://jsfiddle.net/q3c3m973/
