### ISSUE TITLE
Point's MouseOut not fired causing tooltip to remain 

### ISSUE THREAD

**Issue by Rashaine** [highslide-software/highcharts.com#4559]
1) Hover over a point to cause the point to be selected and the tooltip to appear.
2) Unselect and remove the tooltip by moving the pointer to an empty space via a horizontal mouse move. Note the point is no longer selected the the tooltip is removed.
3) Reselect the point and this time move the pointer vertically upwards quickly to unselect the point. Note that the point remains selected and the tooltip remains and follows the point until a new point is selected.

I tracked this down to onTrackerMouseOut(), in this method we only call series.OnMouseOut() if the related target isn't a tooltip. This causes the tooltip to remain if the tooltip is selected (hovered over) when mousing out of the point. This isn't so bad if the tooltip isn't following the pointer in which case the tooltip still points to the point it represents. But if the tooltip is following the pointer this seems very strange.

http://jsfiddle.net/r73cfuxt/

Possible solutions.
1) Ensure that the tooltip isn't following the pointer when checking if the related target is a tooltip or remove this condition all together.
2) Add a mouse out event to the tooltip to dismiss the tooltip and unselect the point.

**Comment by highslide-software** [comment]
Thanks! It's another case of #1686, which I am about to upload a fix for.

**Comment by highslide-software** [comment]
PS: A quick fix is to add this CSS rule:

```css
.highcharts-tooltip {
    pointer-events: none;
}
```

[View live on jsFiddle](http://jsfiddle.net/highcharts/r73cfuxt/2/).

**Comment by dardrone** [comment]
I am getting similar issue, but I'm receiving the error: "Uncaught TypeError: Cannot read property 'defaultView' of undefined". The error fires everytime the tooltip should be disappearing. Any thoughts?

**Comment by pawelfus** [comment]
We don't use in the code `defaultView` property. Just a guess, that something is wrong in your callback. Could you setup jsfiddle demo with that issue?
