### ISSUE TITLE
To Show DC state on US custom state map

### ISSUE THREAD

**Issue by arvind132** [highslide-software/highcharts.com#4564]
HI, 

I want to show all  the states name on the us custom map, but its not showing because of the small state it only shows on zoom in, but i want to show it on the normal view as well, I have found another map to show state name as data labels, but that map doesn't support lat and longitude option.please guide me to show smaller states name as label in the normal view.

**Comment by pawelfus** [comment]
Hi @arvind132, 

We are trying to keep github issues only for bugs. For general support, please use any of the other our support [channels](http://www.highcharts.com/support). Probably you want to set [`allowOverlap`](http://api.highcharts.com/highmaps#plotOptions.map.dataLabels.allowOverlap) option to false.
