### ISSUE TITLE
Disabling animation using `chart.animation` does not work, only when set on series

### ISSUE THREAD

**Issue by jaapz** [highslide-software/highcharts.com#4570]
When `chart.animation` has been set to `false`, the initial animation should *not* run. It does, though.

Only when `animation` is set to `false` on every specific series, is the animation not applied.

http://jsfiddle.net/1tt90gf0/

**Comment by pawelfus** [comment]
Just as described in docs [here](http://api.highcharts.com/highcharts#chart.animation) ;)

**Comment by jaapz** [comment]
Did that change in a previous version? I swear I have been using `chart.animation` as globally disabling animation on the entire chart for a long time.

**Comment by jaapz** [comment]
And there is no option to globally disable the animation then?

**Comment by jaapz** [comment]
Nevermind, setting plotOptions should do what I want, but it doesn't. Looks like something is going wrong in my own code.

**Comment by pawelfus** [comment]
It works that way since I remember. To disable all animations on the chart, do this:

    chart: {
      animation: false
    },
    plotOptions: {
      series: {
        animation: false
      }
    }

**Comment by jaapz** [comment]
@pawelfus yes, thanks for the quick replies though :+1:
