### ISSUE TITLE
Stacking with step 'center' creates gap between two series

### ISSUE THREAD

**Issue by gunjanmodi** [highslide-software/highcharts.com#4582]
Hi,

First of all I would like to congratulate Highcharts team for the awesome charting tool.

I was playing with Highcharts with some random data to understand the functionality and various settings.

Following is the link of my demo for which I have notice some inconsistencies with series
 
http://jsfiddle.net/LLh1g7h5/2/

Basically there are two series with stacking **normal** and with **center** steps. I found some gaps between two series. May be I have used some wrong settings or it is a bug with highcharts.

**Comment by pawelfus** [comment]
Duplicate: #3958 - only value for a step is different, but in general, looks like `stacking` with `step` doesn't work right now.
