### ISSUE TITLE
Point marker changes position on mouse hover leave

### ISSUE THREAD

**Issue by bagryan** [highslide-software/highcharts.com#4586]
Initial marker's position is calculated using mathFloor rounding (according to issue #1843), but marker's position on mouse hover leave calculates without mathFloor rounding and sometimes gives different result. 

As a result marker jumps when mouse pointer leaves it.

Pull request #4587

**Comment by PitBeast** [comment]
Workaround:

```javascript
    var setStateOld = Highcharts.Point.prototype.setState;

    Highcharts.Point.prototype.setState = function () {
        this.plotX = Math.floor(this.plotX);
        setStateOld.apply(this, arguments);
    };
```
or ```enableMouseTracking``` can be set to ```false``` in ```plotOptions.series```

**Comment by highslide-software** [comment]
Live demo please?

**Comment by bagryan** [comment]
http://jsfiddle.net/yuriybagryanskiy/vwpt23r9/6/
Let's try to move mouse over every circle, from the left to the right

**Comment by Jollyfant** [comment]
On this note, #3643 and #4268 can be closed.

**Comment by highslide-software** [comment]
Thanks
