### ISSUE TITLE
animation with column chart to sum or avg the series by right click ? could you ?

### ISSUE THREAD

**Issue by joostshao** [highslide-software/highcharts.com#4597]
http://jsfiddle.net/gh/get/jquery/1.9.1/highslide-software/highcharts.com/tree/master/samples/highcharts/demo/column-rotated-labels/

just like this,  but i will select some data and right click it to choose sum these or avage these ?

just alter a modal to tell .

**Comment by KacperMadej** [comment]
To get support use forum or StackOverflow. For requests use UserVoice. This is github and it is not for posting help request - read our rules for issue reporting and report it on GitHub Issues (https://github.com/highslide-software/highcharts.com/blob/master/readme.md#reporting-issues). It's not a bug, please check with us in one of the support channels first. More information: http://www.highcharts.com/support
