### ISSUE TITLE
Column Chart : getExtreamFromAll is not working properly

### ISSUE THREAD

**Issue by pawanvjadhav** [highslide-software/highcharts.com#4599]
Column / Bar  Chart : getExtreamFromAll is not working properly. See below url:

http://jsfiddle.net/pawanvjadhav/ddb47k76/2/

This is working, if series type is change to line / area.

**Comment by highslide-software** [comment]
#### Workaround
Raise the `cropThreshold` to ensure that all points are considered when analyzing the Y range. [View live demo](http://jsfiddle.net/highcharts/ddb47k76/3/).

**Comment by GaneshBChandgude** [comment]
It is not working when we provide lesser width to the chart.

http://jsfiddle.net/ddb47k76/5/

**Comment by pawanvjadhav** [comment]
@pawelfus Have you considered the comment of @GaneshBChandgude ?

**Comment by pawelfus** [comment]
@pawanvjadhav - demo by @GaneshBChandgude works correctly? Also, just test master branch after fix: http://jsfiddle.net/ddb47k76/8/ - could you confirm?

**Comment by GaneshBChandgude** [comment]
@pawelfus please move scroll bar slowly, you will notice after some category values (about category value 157,158) y axis end range is changing from 750k to 800k.

**Comment by pawelfus** [comment]
I think this is correct. You have different labels width (with rotation), some of them are longer, so plotting area height is decreased. That means, `yAxis.maxPadding` may increase the last tick from 750k to 800k. 

However, for me it works fine, see: 
![test](https://cloud.githubusercontent.com/assets/1453926/10162694/48544546-66ad-11e5-9f4e-b4dc7de51d1f.gif)
