### ISSUE TITLE
highstocks xAxis afterSetExtremes event never fires "mouseup", only "mousemove"

### ISSUE THREAD

**Issue by jbwl** [highslide-software/highcharts.com#4600]
After upgrading to Highstocks 2.1.8, I have trouble with the navigator.

Supposedly the e.DOMEvent.type should be "mouseup" when the user stops dragging either the navigator active area or handles, but it only ever gives the type "mousemove". 
The event doesn't seem to have any attributes to isolate the last event, either.

The use case is to request new data for the new extremes *after* the user is finished adjusting the navigator.

I did browse the repository but haven't found any changes pertaining to the event. Not sure how to debug this. Thank you for your help.

**Comment by highslide-software** [comment]
Live demo and steps to reproduce please?

**Comment by jbwl** [comment]
http://jsfiddle.net/fw2zgv5d/

1. Open in Google Chrome (OS X) Version 45.0.2454.99 (64-bit). Can also be reproduced in Firefox (OS X) 39.0, Safari (OS X) 8.0.8
2. Open the JavaScript console in order to see the log messages
3. Drag the navigator (it doesn't matter if you drag a handle or the whole area)
4. Log messages will show there is no "mouseup" event after finishing the navigator action by letting go of the mouse button. Only "mousemove" events are logged.

**Comment by pawelfus** [comment]
*Internal note:*
Looks like connected to #821 and #4452. It works for `setExtremes`, but for `afterSetExtremes` we have limitation [here](https://github.com/highslide-software/highcharts.com/blob/d2526e3e609cf5c34e9b2632e4d53cf169e2254c/js/parts/Chart.js#L259).

Demo with `setExtremes`: http://jsfiddle.net/fw2zgv5d/4/

**Comment by jbwl** [comment]
Any idea when to expect a fix? This is core functionality and 10 days have passed. I am a paid license holder...

**Comment by highslide-software** [comment]
I don't really see it as a bug. The code snippet that Pawel refers to is there because we don't want to run `afterSetExtremes` when the extremes haven't actually changed. What happens is that the mouse move triggers extremes to update, but when the mouse sits still for a second before we release it, there are no new extremes to set, so we skip it. Which makes sense in my head. 

I would recommend that you take a different approach, like create your own mouseup listener, and add a flag to see whether the axis has changed. [View live demo](http://jsfiddle.net/highcharts/fw2zgv5d/5/).

**Comment by jbwl** [comment]
When I drag the navigator handle or area to a new position, wait half a second, and then release it, then new extremes have definitely been set, at least that's what the user expects. This is reproducible in the example I've given. 
Your example simply moves the problem to another place in the code, because it still is not possible to detect if the user is finished with the navigator change if he does it in a normal speed - because the "mouseup" event is missing in that case.
 
The afterSetExtremes event fires constantly during movement of the navigator, making it no different from the setExtremes event. That is why it is also needed to detect if there was a "mouseup" event, in order to "debounce" the large number of afterSetExtremes events. If there is another way to tell if the user is done adjusting the navigator, I will gladly use it, but I don't see any possibility.

The use case is to start a quite expensive operation to fetch new data after the navigator has changed, so I definitely need to "debounce" the movement and be able to tell the user is finished.
