### ISSUE TITLE
Navigator line color cannot be configured

### ISSUE THREAD

**Issue by dancek** [highslide-software/highcharts.com#4602]
The API documentation leads me to believe that the navigator series color can be changed. Turns out that only the fill color actually changes.

Documentation: http://api.highcharts.com/highstock#navigator.series
Example: http://jsfiddle.net/v4p9kmhj/

**Comment by highslide-software** [comment]
#### Workaround
Set the `lineColor` in addition. [View it live on jsFiddle](http://jsfiddle.net/highcharts/v4p9kmhj/1/).

**Comment by scipper** [comment]
What about multiple series?

**Comment by pawelfus** [comment]
Since v5 you can use [`series.navigatorOptions`](https://api.highcharts.com/highstock/series.line.navigatorOptions) which can be set for each series separately: http://jsfiddle.net/BlackLabel/v4p9kmhj/45/

**Comment by scipper** [comment]
Thanks for the hint! 😊
