### ISSUE TITLE
Difficult flag hover

### ISSUE THREAD

**Issue by xSirrioNx** [highslide-software/highcharts.com#4603]
In older versions in Highstock ou can easily hover the flag.
Example: 
http://jsfiddle.net/m7eruu7t/

But now hover works only on border and symbol inside flag.
Example: 
http://jsfiddle.net/zp57arfe/

**Comment by sebastianbochan** [comment]
Fixed in the newest master branch.

Ref: http://github.highcharts.com/highstock.js

Reopen if problem still appears.
