### ISSUE TITLE
Zone color is not applied properly, when update column

### ISSUE THREAD

**Issue by sebastianbochan** [highslide-software/highcharts.com#4604]
In case when we update column, color is not applied properly.

Example: http://jsfiddle.net/bfb6w1qq/1/

For line chart, all works properly.

http://jsfiddle.net/bfb6w1qq/2/

**Comment by pawelfus** [comment]
Duplicate of #4267 - works fine on bugfix branch: http://jsfiddle.net/bfb6w1qq/3/
