### ISSUE TITLE
Columnrange: dataLabels don't display if high or low of data point are outside axis current range

### ISSUE THREAD

**Issue by KacperMadej** [highslide-software/highcharts.com#4605]
Columnrange: labels are not visible if range of point is outside a range of axis, even though inside for dataLabels is set to true.

Example: http://jsfiddle.net/gwtu3nef/

**Comment by kzoon** [comment]
Any idea when this issue could be fixed? I'm really running into lots of problems due to these missing data labels.

**Comment by highslide-software** [comment]
First of all, the `inside` option centers the labels, so it is perhaps it is better to set them outside but adjust the y offset: http://jsfiddle.net/gwtu3nef/1/

Even when `inside` is true, an offset prevents overlapping: http://jsfiddle.net/gwtu3nef/2/

**Comment by highslide-software** [comment]
A proposed solution is to limit the data label box to the plot area. How does this work for you? http://jsfiddle.net/gwtu3nef/3/

**Comment by kzoon** [comment]
Perfect!
It solves the issue on my column range charts. I checked other chart types and they still render as expected. I think data label rendering on columns that exceed the y-axis scale has actually improved.
So, I'm very happy with the proposed solution.
