### ISSUE TITLE
RangeSelector has hard-coded height

### ISSUE THREAD

**Issue by dancek** [highslide-software/highcharts.com#4609]
RangeSelector overlaps with the chart area if you adjust button styles so the buttons are larger than normal. This is probably because the height is hard-coded at https://github.com/highslide-software/highcharts.com/blob/master/js/parts/RangeSelector.js#L270

Example: http://jsfiddle.net/t2orpcLj/

**Comment by highslide-software** [comment]
Closed by 2c413c19e67eeb58143433d5754e20410ee3d317
