### ISSUE TITLE
y axis tickinterval wrongly set in some conditions (min and max negative plus other)

### ISSUE THREAD

**Issue by ddorigo** [highslide-software/highcharts.com#4611]
I run into a problem that is difficult to reproduce in Fiddle but is clear and I fixed already in my local library.

Description: only in some conditions the tickInterval is calculated by highcharts using the method unsquish. If the axis is limited by min and max and they are both negative the result will be a very big tickInterval.

Solution: The problem is in the line:
      slotSize = this.len / (((this.categories ? 1 : 0) + this.max - this.min) / tickInterval),
If max is negative there is no result (undefined) as slot size.
I fixed in this way:
    slotSize = this.len / (((this.categories ? 1 : 0) + mathAbs(this.max - this.min)) / tickInterval),

best regards
and compliment for the wonderful library

**Comment by highslide-software** [comment]
From your fix it may look like you set a `min` value that was greater than the `max` value? Otherwise you wouldn't have to use `Math.abs`... The `min` setting should always be smaller than `max`.

**Comment by ddorigo** [comment]
actually the min was -150 and the max -50, both negatives.
I tested a bit more with different conditions and I've understood the reason why it failed only with negative max. We enter the value as from input and they are assigned as String. If they are positive javascript can deal otherwise it fails.  
e.g.: var value = (0 + max - min): value is a number for: max = 10, max = "10", max = -10. value is NaN for: max = "-10".  Math.abs(max-min) always return a number.

**Comment by highslide-software** [comment]
Okay, thanks or the explanation! That means you just need to run parseInt of parseFloat on the input values.

**Comment by ddorigo** [comment]
Yes; this was our final solution. 
cheers

Dario
