### ISSUE TITLE
Category labels overlap with chart

### ISSUE THREAD

**Issue by MirnaM** [highslide-software/highcharts.com#4613]
Category labels overlap with chart when rotation and step are set. This happens in v4.1.8 - modified, but not in v4.1.8 (2015-08-20). Here is fiddle with the latest version of Highcharts that contains bug: http://jsfiddle.net/ncyygadv/

**Comment by KacperMadej** [comment]
Workaround: use align 'right' for labels - http://jsfiddle.net/askwd1qm/
