### ISSUE TITLE
Heat map colorAxis is wrongly positioned when useHTML enabled

### ISSUE THREAD

**Issue by amyspark** [highslide-software/highcharts.com#4615]
Version: Highcharts 4.1.8 JS v/Highstock 2.1.8 (2015-08-20) (custom build)

When using a heat map, if I enable `useHTML` on its `colorAxis`, it's positioned at (0, 0) instead of directly below the legend bar.

Expected behavior (`useHTML` disabled):
![correct](https://cloud.githubusercontent.com/assets/13498015/10226677/4f7e9e82-683f-11e5-92a2-fc2705fd9f3c.png)

Instead (`useHTML` enabled):
![bug](https://cloud.githubusercontent.com/assets/13498015/10226683/585d50a2-683f-11e5-856c-e932abf61197.png)

**Comment by highslide-software** [comment]
Live demo: http://jsfiddle.net/highcharts/pfsLh98n/1/

**Comment by petermumford** [comment]
Awesome. Thanks for this. Was having this issue for ages. Now using highcharts v4.1.9
