### ISSUE TITLE
Gradient - wrong poportion when resize

### ISSUE THREAD

**Issue by sebastianbochan** [highslide-software/highcharts.com#4617]
Seems that stops in gradient are not calculated properly. 

Example:
- http://jsfiddle.net/sui_huang/kh02ya9p/

Try to zoom a few times and then we observe that proportion in gradients is different.

**Comment by highslide-software** [comment]
You are using the wrong configuration for the linearGradient (hard coded pixels). 

Demo at http://jsfiddle.net/highcharts/kh02ya9p/1/

**Comment by sebastianbochan** [comment]
Indeed, my bad, sorry.
