### ISSUE TITLE
useHTML:true on series dataLabels causes data labels to pop over tooltip

### ISSUE THREAD

**Issue by dlopuch** [highslide-software/highcharts.com#4619]
![screen shot 2015-10-02 at 3 08 18 pm](https://cloud.githubusercontent.com/assets/1427329/10258968/f9e9fbb8-6917-11e5-8ded-33543fbf7960.png)

fiddle: http://jsfiddle.net/p4vzcpLu/

Problem seems to stem from the fact that setting `useHTML: true` creates dom elements for the data labels outside the svg.  These always float above the svg (and therefore above the tooltip)

As a workaround, we can try to set `useHTML: true` on the tooltip as well (which does something similar -- creates tooltip dom nodes outside the svg) and then try to add z-index css, but this doesn't quite work because even with `tooltip.useHTML:true`, the tooltip's background is still rendered in the SVG.

**Comment by highslide-software** [comment]
It's a known and documented limitation with useHTML, see http://www.highcharts.com/docs/chart-concepts/labels-and-string-formatting#html.

You can create a [full-HTML tooltip](http://jsfiddle.net/gh/get/jquery/1.7.2/highslide-software/highcharts.com/tree/master/samples/highcharts/tooltip/fullhtml/) to avoid the SVG background problem, but still you loose the small chevron that points to the hovered point.
