### ISSUE TITLE
how to draw mapLine with an arrow

### ISSUE THREAD

**Issue by zhaojun12** [highslide-software/highcharts.com#4620]
I am using highmaps, and I want to connect two mapPoints with a mapLine with an arrow. But I do not know how. Thanks.

**Comment by KacperMadej** [comment]
To get support use forum or StackOverflow. For requests use UserVoice. This is github and it is not for posting help request - read Highcharts' rules for issue reporting on GitHub Issues (https://github.com/highslide-software/highcharts.com/blob/master/readme.md#reporting-issues). If it is not a bug, please check one of the support channels. More information: http://www.highcharts.com/support

**Comment by highslide-software** [comment]
@zhaojun12 Check out this study that we made some months ago: http://jsfiddle.net/gh/get/jquery/1.7.2/highslide-software/highcharts.com/tree/master/samples/highcharts/studies/direction-arrows/
