### ISSUE TITLE
datalabels align is mixed up

### ISSUE THREAD

**Issue by MurWade** [highslide-software/highcharts.com#4632]
http://jsfiddle.net/gh/get/jquery/1.7.2/highslide-software/highcharts.com/tree/master/samples/highcharts/plotoptions/series-datalabels-align-left/

check out that example. 

just change the `dataLabels.align` to  `'left'` and the labels will be align to the right. when you set the align to right it will be set to left.

**Comment by KacperMadej** [comment]
This is not a bug. According to the [API reference](http://api.highcharts.com/highcharts#series<line>.dataLabels.align): `... If right, the right side of the label should be touching the point. ...`. Next time please use forum or StackOverflow first if an issue is not certainly a bug - http://www.highcharts.com/support
