### ISSUE TITLE
Pie chart - gradient error in IE7+

### ISSUE THREAD

**Issue by sebastianbochan** [highslide-software/highcharts.com#4639]
Example: http://jsfiddle.net/d5v412vd/1/

![zrzut ekranu 2015-10-09 o 13 32 04](https://cloud.githubusercontent.com/assets/2115686/10392739/2aa42ce8-6e8a-11e5-9550-48bc743bf923.png)

HC 4.1.9, in 4.1.8 works properly.

**Comment by highslide-software** [comment]
Fixed since 9c0a229731b7fc40495e7af349ff2df444c68c1f
