### ISSUE TITLE
data immutability in series.setData method

### ISSUE THREAD

**Issue by poluyanov** [highslide-software/highcharts.com#4642]
Series setData method accepts array of initial points. Why doesn't this method clone array for internal usage?

When updating an array which I have to pass to setData, I've found some cases that could lead to some serious bugs that are very difficult to find.
I understand I must pass immutable array to setData method, but I believe internal cloning (or clarifying the documentation) could really be helpful and would prevent many mistakes.

I can provide a test case

**Comment by highslide-software** [comment]
> Why doesn't this method clone array for internal usage?

You wouldn't want that if you add a large amount of points, like 50,000. It would add to the memory usage. 

I'll add this information to the docs.
