### ISSUE TITLE
connectNulls breaks on point.remove()

### ISSUE THREAD

**Issue by garviand** [highslide-software/highcharts.com#4650]
http://jsfiddle.net/garviand/77ncjp11/1/

When removing a point, the chart automatically connects the two adjacent points.

**Comment by highslide-software** [comment]
There's a difference between a `null` point and a non-existing point. What you probably want is to set the point value to null on click: http://jsfiddle.net/highcharts/77ncjp11/2/

**Comment by garviand** [comment]
Cheers, thank you!
