### ISSUE TITLE
setData - not animate when huge data

### ISSUE THREAD

**Issue by sebastianbochan** [highslide-software/highcharts.com#4655]
In case when we call setData with small amount of points, then all is animated like here:
- http://jsfiddle.net/ryaneui/rtq7k3sp/

But when expand array by more points, then animation is skipped
- http://jsfiddle.net/ryaneui/pz674wod/

**Comment by highslide-software** [comment]
There's a hidden option called `animationLimit`: http://jsfiddle.net/highcharts/pz674wod/2/

The rationale is performance on certain systems.
