### ISSUE TITLE
Bar border visible on zero values for reversed bar

### ISSUE THREAD

**Issue by jegarts** [highslide-software/highcharts.com#4656]
When there is zero data for a series in a  reversed-y-axis bar chart, the border is still visible in the chart. If one uses a "boderWidth:0" there is a 1px line of whatever color the bar is. This is not the case for non-reversed axis bar charts.

See fiddle here:

https://jsfiddle.net/jegarts/6ercLxxz/

**Comment by highslide-software** [comment]
With constant width: http://jsfiddle.net/highcharts/6ercLxxz/1/

Interestingly, the values for 100 and 140 are treated equally.
