### ISSUE TITLE
plotOptions  precedence (series vs all other series types)

### ISSUE THREAD

**Issue by omemina** [highslide-software/highcharts.com#4657]
The chain of precedence between plotOptions.series and plotOptions.{series-type} is not working as it should.
As far as I read, plotOptions.{series-type} options should have a higher precedence than plotOptions.series, which is not the case in the JSFiddle below:
http://jsfiddle.net/q63mwz20/1/

The options for plotting are used from the plotOptions.series options instead of plotOptions.pie options.

A similar issue is already opened https://github.com/highslide-software/highcharts.com/issues/4576, but just for scatter 3d.

**Comment by pawelfus** [comment]
Duplicate of #3881
