### ISSUE TITLE
Bug with multiple Y Axis depending on yAxis parameter

### ISSUE THREAD

**Issue by ferulisses** [highslide-software/highcharts.com#4659]
When I use "yAxis: 1" parameter to create a secondary Y axis, it must be the first data set in the "series" parameter, else the numbers in the legend will be printed in the wrong side of the chart.

I just forked the Two Axis example and changed the yAxis from the first data series to the second data series and it created the chart wrong: 
http://jsfiddle.net/uk47523z/

![image](https://cloud.githubusercontent.com/assets/3842252/10459040/18a6fa4e-71a4-11e5-9138-c03688c7dba8.png)

This get even worse with three or four Y axis:
http://jsfiddle.net/ft8c2t01/

All the others parameters obey the settings, but yAxis mess it.

**Comment by highslide-software** [comment]
In your fiddle, you assigned the Temperature series to yAxis 1, which is the Rainfall axis, which has the _mm_ unit set in the label format.

I'm not sure what you tried to do, but if you want the axes to swap places, you just set the `opposite` option: http://jsfiddle.net/highcharts/rbt3jxqy/.

PS: For general tech support, please see www.highcharts.com/support.
