### ISSUE TITLE
alternateGridColor doesn't shade final category when there's an even number of categories

### ISSUE THREAD

**Issue by clawsout** [highslide-software/highcharts.com#4660]
When **alternateGridColor** is set on the **xAxis** and there is an **even number** of categories, the final category is not correctly shaded.

This seems to be a regression, as it doesn't occur on my older self-hosted version (4.0.4).
**Edit:** I can confirm that this issue was introduced in 4.1.9. Older versions don't exhibit this problem.

I've reproduced this in (latest) Chrome and Firefox running on Windows 7 Enterprise, and I've tried using the latest jQuery versions (1.9 - edge) and both the CDN and Github hosted versions of HighCharts.

Please see this fiddle: http://jsfiddle.net/clawsout/y4w8o772/

Which is a minor alteration (simply moving the alternateGridColor from the yAxis to the xAxis) of this official HighCharts fiddle: http://jsfiddle.net/gh/get/jquery/1.7.2/highslide-software/highcharts.com/tree/master/samples/highcharts/yaxis/alternategridcolor/

**Comment by highslide-software** [comment]
It fails since bc53202

**Comment by clawsout** [comment]
Hi pawelfus, when running the latest highcharts from either:
- http://github.highcharts.com/master/highcharts.js
- http://github.highcharts.com/highcharts.js

on the jsfiddle above (http://jsfiddle.net/clawsout/y4w8o772/2/) the issue doesn't yet appear to be fixed?

**Comment by pawelfus** [comment]
It's fixed on the bugfix branch, see `(i)` note:
![screen shot 2015-10-21 at 1 01 28 pm](https://cloud.githubusercontent.com/assets/1453926/10634690/e63d1006-77f3-11e5-95a7-f4a1db0d63e4.png)
