### ISSUE TITLE
StockChart: rangeSelector input date range jump to random date instead of using user's input

### ISSUE THREAD

**Issue by dragonzone** [highslide-software/highcharts.com#4662]
To reproduce:

1) Go here: http://jsfiddle.net/bv4m3hL7/
2) From: enter '5/1/2011'
3) To, enter '5/22/2011'

Notice the 'From' input value is randomly changed to '3/2/2011' and the 'To' input value is changed to '7/20/2011'

**Comment by highslide-software** [comment]
A couple of modificatione fixes your setup:

* With a custom date format, you need a custom `inputParser` (unless Date.parse handles it correctly): http://jsfiddle.net/highcharts/bv4m3hL7/1/
* You need a lower xAxis.minRange.

See the result at http://jsfiddle.net/highcharts/bv4m3hL7/1/.
