### ISSUE TITLE
highmaps: Point.update not working for changing color

### ISSUE THREAD

**Issue by fegg** [highslide-software/highcharts.com#4666]
mapbubble map

wordData[i].events = {
   update: function() {
       this.color = Util.getRandomOneColor();
   }
};

this is when data change, i want to change the point color. but 

this.color =>  randomcolor()

value is change, but map's point color is not change .

color start change. util I use mouse   over the point,    when i leave this point, color not change.

**Comment by highslide-software** [comment]
Demo: http://jsfiddle.net/highcharts/oxaegq8x/

**Comment by pawelfus** [comment]
It's fixed on a bugfix branch: http://jsfiddle.net/oxaegq8x/1/ (one of the similar issues with updating point and color). Connected to #4267

**Comment by fegg** [comment]
thanks~ ^0^
