### ISSUE TITLE
flag dataoption point event click 

### ISSUE THREAD

**Issue by bharathd** [highslide-software/highcharts.com#4669]
here some portion of the flag is not in click mode ..
http://jsfiddle.net/5q3ufnse/
check for title-->b flag
if it is behaviour and how can i make the click mode for every position in the flag?

**Comment by bharathd** [comment]
'webkitMovementX' is deprecated. Please use 'movementX' instead.

**Comment by pawelfus** [comment]
Should I use some specific browser to see that issue? Tested with latest chrome and works fine, see: 

![click_on_flag](https://cloud.githubusercontent.com/assets/1453926/10573159/2c2343a8-764e-11e5-9225-7cfbf369c9b4.gif)

Regarding `webkitMovementX` see #4568

**Comment by pawelfus** [comment]
@bharathd - do you have some more info about this issue for us?

**Comment by bharathd** [comment]
It is working fine now previously i was using usehtml has true .

**Comment by futurefeeling** [comment]
@bharathd how do you fix it? I meet the same issue;😢

**Comment by futurefeeling** [comment]
my chrome version is 
![image](https://cloud.githubusercontent.com/assets/9881593/10836900/4d42be4e-7eee-11e5-9195-4b5b6cd69e34.png)
is it the reason?

**Comment by pawelfus** [comment]
Just setup jsFiddle demo and post it here. I will reopen issue once we have some reliable sample.
