### ISSUE TITLE
Boost module doesn't seem to remove "tracker" companion path element on "Reset Zoom"

### ISSUE THREAD

**Issue by teeterc** [highslide-software/highcharts.com#4675]
I noticed that the boost module leaves a "highchart-tracker" svg path when the graph is reset.  It's completely reproducible on the demo site. 

http://www.highcharts.com/component/content/article/2-news/175-highcharts-performance-boost

In Safari (No ghosting in chrome, but the tracker element still lingers):
1: zoom to a range smaller then boostThreshold. 
2: zoom to a smaller range that contains only couple hundred points ... notice the ghosting in safari
3: inspect the src svg element <g class="highcharts-series highcharts-series-0 highcharts-tracker" ...> that is created. 
 
note: there are 4 path elements and 1 image element. 

4: click on the zoom reset button in the Highchart graph. 
5: inspect the svg element <g class="highcharts-series highcharts-series-0 highcharts-tracker" ...>

note:  there are now 2 path elements and 1 image element.  

Bug: I believe that the second path element - <path class=" highcharts-tracker"> - should be destroyed in the method boost.src.js:destroyGraphics()  This artifact (depending on the size of the tracker element) can destroy performance and memory in Safari.

node: depending on the threshold the tracker element can be very large.  

Cheers,
Clay

**Comment by pawelfus** [comment]
Indeed, tracker is not removed after zooming out. I'm not sure about this ghosting effect, could you post screenshot and Safari version? Thanks!

**Comment by teeterc** [comment]
Here is a video:
https://www.youtube.com/watch?v=R28Sq-OOrxU&feature=youtu.be

**Comment by pawelfus** [comment]
Should be fixed on the bugfix branch, could you confirm? See: http://jsfiddle.net/a129eret/8/

**Comment by teeterc** [comment]
Look Great, the ghosting and the tracker remnants are gone. Cheers!
