### ISSUE TITLE
How to include exporting module via jspm?

### ISSUE THREAD

**Issue by martinbean** [highslide-software/highcharts.com#4677]
I’ve managed to import Highcharts in my jspm setup like this:

```js
import Highcharts   from 'highcharts';
```

But how do I import the exporting module?

**Comment by highslide-software** [comment]
Hi, this is our bug tracker. For general tech support, please see www.highcharts.com/support.

**Comment by davinkevin** [comment]
+1, a PR has be proposed about this subject.
