### ISSUE TITLE
Resetting zoom doesn't reapply ellipses to all axis labels

### ISSUE THREAD

**Issue by smithk58** [highslide-software/highcharts.com#4678]
If there's too long of a string for a label on an axis it gets cut off with ellipses. If you zoom in on such a chart it may remove the ellipses if there's enough room to display the label now. This works as expected. However, if you do 'reset zoom' it will only reapply the ellipses logic to the labels you were zoomed in on.

jsfiddle: http://jsfiddle.net/p14w0bhr/

Steps:
1. Zoom in on some part of the chart.
2. Click reset zoom
3. You'll see that any labels you weren't zoomed in on will now be fully shown, instead of having the ellipses on them.

**Comment by highslide-software** [comment]
Normalized demo: http://jsfiddle.net/highcharts/p14w0bhr/1/
