### ISSUE TITLE
Shared tooltips with multiple column series shows wrong tooltip

### ISSUE THREAD

**Issue by aliscott** [highslide-software/highcharts.com#4680]
http://jsfiddle.net/jjvrv410/

![tooltip_bug](https://cloud.githubusercontent.com/assets/158824/10666878/27c056d6-78cc-11e5-8af0-1843997eaeab.gif)

When you create a shared tooltip with a chart with two column series, there are instances where you can hover over a column and it shows the tooltip for a different column.

It seems like it's calculating the closest absolute point and showing the tooltip for that, but I would expect that if I hover over any part of a column rectangle that it shows the tooltip for that column.

It looks like it may have been introduced by this commit: https://github.com/highslide-software/highcharts.com/commit/2e53db36da7771cfa639bf6ffc527547c62b7656

**Comment by KacperMadej** [comment]
Looks like the same problem as #4645

**Comment by pawelfus** [comment]
You are right - it is the same issue as #4645. Closing, this one, let's follow just one bug report.
