### ISSUE TITLE
Can I add my own property in 'this' of xAxis labels formatter function in High Charts?

### ISSUE THREAD

**Issue by hoangthau** [highslide-software/highcharts.com#4685]
Hi all!
I have an issue with xAxis labels formatter.
At this link "http://api.highcharts.com/highcharts#xAxis.labels.formatter" highchart api show some additional properties for "this" (chart, axis, value, isFirst, isLast) and get different by this.value. But in my case have many item in categories same value (http://jsfiddle.net/xfetaarL/1/). So is possible for adding more additional properties (ex: id ) for separate item and then we can use that "id" in formatter function ?

 function() {
       var id = this.id // this is my own property that I want to add
	return this.value;
}
Thanks for any your help. :wink:

**Comment by pawelfus** [comment]
Hello, this is our bug tracker, for support related questions please use our other channels, please: http://www.highcharts.com/support

And to answer your question, yes, you can change format for categories, to use objects: 

        xAxis: {
            categories: [{
                name: 'Foobar',
                id: '#1'
            }, {
                name: 'Foobar',
                id: '#2'
            }, {
                name: 'Foobar',
                id: '#3'
            }],

            labels: {
                formatter: function () {
                    return '<a href="' + categoryLinks[this.value.name] + '">' + this.value.name + ' dhlId:' + this.value.id + '</a>';
                }
            }
        },

And demo for you: http://jsfiddle.net/xfetaarL/2/

**Comment by hoangthau** [comment]
Thanks @pawelfus.
