### ISSUE TITLE
series.lineWidth in double quotes results in hover state line width being multiplied

### ISSUE THREAD

**Issue by GaryGen** [highslide-software/highcharts.com#4687]
If the series.lineWidth value is in double quotes, the line appears with the correct width UNTIL it is hovered over, at which point the lineWidth will appear about 10 times larger.
See http://jsfiddle.net/gmr6bjmc/
Behavior seen on Windows 7, Chrome Version 46.0.2490.80 m

**Comment by pawelfus** [comment]
But `lineWidth` should be a number, not a string, see [API](http://api.highcharts.com/highcharts#plotOptions.series.lineWidth).
