### ISSUE TITLE
line chart circle marker misaligned in 4.1.9

### ISSUE THREAD

**Issue by epikhighs** [highslide-software/highcharts.com#4689]
I'm using the line chart's hover state to add a circle marker and modify the halo of the circle marker to get the effect shown in the attached picture.  This was aligning perfectly in 4.1.4 and 4.1.8, but with 4.1.9, the circle markers are misaligned randomly.  On some points it's aligned perfectly and in other points it is offset by a random amount.

Anyone else having this issue?

![highchartsbug](https://cloud.githubusercontent.com/assets/2907558/10746358/2ffbe8cc-7c07-11e5-8208-5985f2e4016b.png)

**Comment by epikhighs** [comment]
I also notice that the distance b/t the bar charts are not all the same either in 4.1.9.  So this issue might not be specific to line charts and circle markers.

**Comment by pawelfus** [comment]
Could you setup live dime, for example jsfiddle? We will check this.

**Comment by highslide-software** [comment]
Most likely this changed after fixing #4586.

Out of curiosity, why don't you apply `fillColor` and `lineColor` to the markers? http://jsfiddle.net/gh/get/jquery/1.7.2/highslide-software/highcharts.com/tree/master/samples/highcharts/plotoptions/series-marker-fillcolor/

**Comment by epikhighs** [comment]
http://jsfiddle.net/vh625ky6/

On mouse hover, you see that some of the circle markers are properly aligned, but some are not.

@highslide-software thanks for the tip.  As I have painfully found out with highcharts, there is so much configuration possible that it's hard to find the desired set of config to use!   As you can see in my fsfiddle, initially, I need solid circles, then on mouse hover I need the doughnut and I need to suppress the halo on mouse hover.  So I'm not sure if your solution will work for my use case.

**Comment by highslide-software** [comment]
FYI, here's how to disable the halo and use only the marker: http://jsfiddle.net/highcharts/vh625ky6/1/

**Comment by highslide-software** [comment]
Closed by 69c1c619ba181e3be6dce38e568ef0ff81cc656f
