### ISSUE TITLE
incorrect opposite y-axis alignment

### ISSUE THREAD

**Issue by pepijnolivier** [highslide-software/highcharts.com#4691]
This bug is present in the latest highcharts version (4.1.9)

When defining `align: 'high'` on an opposite y-axis in a linechart, the title isn't positioned correctly

Demo
http://jsfiddle.net/n8ydvrx2/1/

**Comment by pawelfus** [comment]
Workaround: http://jsfiddle.net/n8ydvrx2/2/ (set `yAxis.title.textAlign = "left"`). 

*Internal notes:*

- `yAxis.title.textAlign`is missing in the docs
- for opposite Axis, we should swap `low` and `high` values [here](https://github.com/highslide-software/highcharts.com/blob/4dcfd548931e9fa5578530cf372bc2ed42162fd5/js/parts/Axis.js#L1777)

**Comment by pepijnolivier** [comment]
Awesome, thanks for the workaround!
