### ISSUE TITLE
Flags overlap 

### ISSUE THREAD

**Issue by bharathd** [highslide-software/highcharts.com#4692]
nearer dates are overlapping each other please provide me the solution .
previously you closed the same issue but solution is not provided (Duplicate of #4674 and #4676)

refer the above number andif it is not possible tell me any other alternate solution

**Comment by pawelfus** [comment]
Hello, 

I think creating duplicated issue on purpose is not a way to go. For now we don't prevent flags overlapping until `x` value for a flag is **exactly the same**. Please, let's just one use bug report (#4674).

**Comment by niketh90** [comment]
Hi

Can this plugin be modified to stack the flags one above the other instead of grouping it and not being shown on the chart.
