### ISSUE TITLE
Axis tick label with StaggerLines option not working properly

### ISSUE THREAD

**Issue by pawanvjadhav** [highslide-software/highcharts.com#4694]
Axis tick label with StaggerLines option not working properly, If we increase count in stagger lines

Check below URL:

http://jsfiddle.net/pawanvjadhav/0ahx86w9/1/

**Comment by pawelfus** [comment]
Hmm.. how should labels behave? 

- ![screen shot 2015-10-28 at 11 09 41](https://cloud.githubusercontent.com/assets/1453926/10785432/792afc6e-7d64-11e5-8d38-532c740194fc.png)
- ![screen shot 2015-10-28 at 11 09 56](https://cloud.githubusercontent.com/assets/1453926/10785433/79ab242a-7d64-11e5-86c6-3e6214baee1e.png)

Imho, first one looks better, but the second one keeps logic the same as for non-`opposite` axis.

**Comment by highslide-software** [comment]
So the question is how the staggerLines should work on an opposite axis? Yes, I agree that the first one looks better.

**Comment by pawanvjadhav** [comment]
First one looks better.
