### ISSUE TITLE
Unable to drag scrollbar on Android (Cordova) 

### ISSUE THREAD

**Issue by spyro92** [highslide-software/highcharts.com#4697]
We are unable to drag the scrollbar on Android devices and I have identified this as the issue.

The pageX is not being calculated correctly on Android devices.
This occurs when using Highstocks with Cordova & Ionic in a hybrid web app.

I think it is better practise to obtain pageX from the touches array rather than directly from the event. 

#4696

**Comment by highslide-software** [comment]
Fixed by b7dfbc760507303e2593744f3323db48310df563
