### ISSUE TITLE
Spurious turboThreshold error after making several point manipulations

### ISSUE THREAD

**Issue by vickychijwani** [highslide-software/highcharts.com#4701]
Demo: http://jsfiddle.net/vickychijwani/kwnrszgp/1/
Old issue: #3604 (closed due to lack of demo)

Open the demo, notice that after 4 seconds (when turboThreshold is exceeded) the navigator breaks and you start getting error 12 ("Highcharts expects point configuration to be numbers or arrays in turbo mode") in your console.

A valid question to ask is, why are so many manipulations of points required in this case? Consider this scenario:

There's a dynamic chart with data points coming in at irregular intervals, i.e., there may be a gap of several seconds (or even a minute) between consecutive points. Now, during those gaps, we don't want the user to feel as if the chart is "stuck" because nothing's moving, so we introduce the concept of a "dummy point", which we add to the end of the series and update every second. When a "real" data point comes in after some time, we *remove* this dummy point and add the real one. This way it looks as if the chart is at least moving every second.

**Comment by pawelfus** [comment]
Looks like `point.update()` changes format from `[x ,y]` array to `{x: x, y: y}` object. In the result we get error-12. 

As for the workaround, have you tried to set `turboThreshold: 0` to disable that option? See: http://jsfiddle.net/kwnrszgp/6/

**Comment by vickychijwani** [comment]
Yes, that's indeed what I did, but the conversion from array to object seems like such a low-level issue that it seems it could cause other bugs as well. Would be good to get it fixed :)
