### ISSUE TITLE
Navigator issues on live Highstock chart on touch devices

### ISSUE THREAD

**Issue by HaiderAtPlero** [highslide-software/highcharts.com#4703]
We have a live Highstock chart in an application meant to run on touch devices.

Sometimes, during the drag of a handle, it goes abruptly back to where the drag started from and comes back.
Sometimes, after the drag is completed, it doesn't stay there but goes back to where the drag started from.
Sometimes, it is more difficult to get the right handle dragging than the left one?

I think the key here is that our chart is live? It works good on 'dead' chart.

**Comment by pawelfus** [comment]
Could you setup jsfiddle demo? Do you encounter the same issue on our demo: http://www.highcharts.com/stock/demo/dynamic-update ?

**Comment by HaiderAtPlero** [comment]
@pawelfus Yes, I could reproduce said issues on your demo page easily. For example, I just opened the link you mentioned on iPhone 5 (iOS 9) Safari and dragged the handle but did not leave the touch and it started to behave like I said above. It also happens when you try to move the window around.

**Comment by HaiderAtPlero** [comment]
@pawelfus @highslide-software Any workaround you can think of before this is fixed?

**Comment by highslide-software** [comment]
I can confirm it is reproducible on the dynamic update demo.

**Comment by highslide-software** [comment]
It can also be observed on the desktop when setting `liveRedraw` to false (at it is on mobile by default): http://jsfiddle.net/highcharts/guL92gbo/.
