### ISSUE TITLE
chart.series[0].update works incorrect with bar

### ISSUE THREAD

**Issue by sevr7gina** [highslide-software/highcharts.com#4709]
I have some troubles in my project using highcharts v. 4.0.4 (the same for v. 4.1.9): chart.series[0].update works incorrect while trying to switch between column and bar charts 
I reproduced this behaviour with the example from http://api.highcharts.com/
On http://api.highcharts.com/highcharts#Series.update there is a link with example of Updating series options http://jsfiddle.net/gh/get/jquery/1.7.2 ... es-update/
I've modified it (changed spline to bar): http://jsfiddle.net/sevr7gina/4awsyLq3/
So now if you'll try to click on "Bar" button, you'll see column chart.

**Comment by pawelfus** [comment]
In fact, "bar" type series is the same as "column", but with option `chart.inverted` set to true ([API](http://api.highcharts.com/highcharts#chart.inverted)). Since there is no `chart.update()` method it is necessary to recreate chart to change `inverted` option.
