### ISSUE TITLE
Font issues in High bar chart in document mode IE8 and ie7 in mvc 

### ISSUE THREAD

**Issue by niteshparihar5** [highslide-software/highcharts.com#4712]
Hi Support Team,

I am getting font issues in High bar chart in document mode IE8 and IE7 in ASP.NET MVC.
Please help me for the same.

THanks 
![highchartissues](https://cloud.githubusercontent.com/assets/14329667/10901600/6e48f3c0-8217-11e5-958c-ff91251ef75b.png)

**Comment by pawelfus** [comment]
It looks like duplicate of #663 - could you try to use solutions posted there?

**Comment by pawelfus** [comment]
And duplicate of #4707 - could we use just one github ticket?
