### ISSUE TITLE
Unable to create pie chart on Internet Explorer 7 and 8

### ISSUE THREAD

**Issue by zanot** [highslide-software/highcharts.com#4716]
Hi,

I want to create a pie chart on my HTA (yes HTA...) but Highcharts raise an error :
'this.renderer.gradients' is null or not an object        highcharts.src.js, line 2314 character 3
(I tried my app in the real IE 8 browser too)

My HTML page has the tag : `<meta http-equiv="x-ua-compatible" content="IE=EmulateIE7" />`
But even with the edge tag (`<meta http-equiv="x-ua-compatible" content="ie=edge" />`) I have the same issue.

I use the latest public version (minified or not) 4.1.9. I tried to use your [master version](http://github.highcharts.com/master/highcharts.js), same issue.
I tried to edit [VMLRadialGradientURL](http://api.highcharts.com/highcharts#global.VMLRadialGradientURL) parameter to set it as local / empty string / null....
However, when I use the version 4.0.4 it works without any problem.

Here is a little demo of my code : http://jsfiddle.net/ms2dydob/1/
([Your demo "pie basic"](http://www.highcharts.com/demo/pie-basic) has the same issue)

When I create column/bar charts (with the latest version) : no problem. (columns on the right in my screenshot).

![highcharts-bug](https://cloud.githubusercontent.com/assets/4114656/10971751/2334ce34-83d6-11e5-8477-849d63fdf1d1.jpg)

**Comment by pawelfus** [comment]
Are you sure that master branch doesn't work for you? Make sure you have cleared cache. As per this ticket: #4639 - it should be already fixed.

**Comment by zanot** [comment]
Sure, I had cache cleared etc. But when is this master file edited? Because now, by using it in my HTML I have a new error `'length' is null or not an object  highcharts_master.js, line 2615 character 21` :+1: .

Too unstable for me.

**Comment by pawelfus** [comment]
`master` file is built every time when a bug is fixed or any new coded is added. Anyway, according to your description, this line is a culprit: https://github.com/highslide-software/highcharts.com/blob/master/js/highcharts.src.js#L2615 - and you are right, `cacheKeys` are not created for VML.

**Comment by pawelfus** [comment]
You can test bugfix branch from here: http://github.highcharts.com/bugfix/highcharts.src.js.

**Comment by zanot** [comment]
It works partially with this fix, thanks.

Partially because I have, again, a new error, should I create a new issue?

**Comment by pawelfus** [comment]
I think it is fine to use the same ticket, since it's the same issue (I mean - not working pie chart in the IE's VML). Anyway, pie chart is rendered for both examples:

- http://jsfiddle.net/ms2dydob/3/ (your base demo has wrong `renderTo` option)
- http://jsfiddle.net/p3tqtad7/1/ (forked from original demo)

**Comment by highslide-software** [comment]
Fixed in master now.
