### ISSUE TITLE
IE11 - Bars not printed in IE8 compatibility mode

### ISSUE THREAD

**Issue by sebastianbochan** [highslide-software/highcharts.com#4718]
Example:
- http://www.highcharts.com/demo/bar-basic

**Comment by highslide-software** [comment]
I have a problem with VMWare at the moment, so I can't open IE11.

Some questions:
* Is it a problem only with the bars, or is it more general? In the image from the client, only the text items are visible, and all VML elements are missing. This points to a problem with vector graphics in general. Check this quote from the FAQ:
> Another case where legacy IE fails to show charts, is when the security setting "ActiveX controls and plug-ins" => "Binary and script behavious" is disabled. This happens very rarely on user computers, but we have seen it from time to time on company networks. In this case, IE fails to draw any of the vector graphics, only the the text is shown. 

* Is it reproducable in IE10 also? I tried, but I couldn't see the problem there.

![image001](https://cloud.githubusercontent.com/assets/227836/11179898/efda48e6-8c56-11e5-81ca-f76c9d9eebb9.png)

**Comment by jaeseaso** [comment]
I think it is with VML elements in general. We checked the settings on the affect computers and "Binary and script behaviors" is enabled. On the same machines, if we change the emulation to IE9 or above, the bars and graph elements render correctly.

We do not have any IE10 machines here, so can't tell.

**Comment by jaeseaso** [comment]
Is there a way to force highcharts to use SVG while in IE11 while emulation IE8?

**Comment by sebastianbochan** [comment]
IE8 uses VML natively, so when you emulate that browser, VML is used.

**Comment by jaeseaso** [comment]
This occurs when VML rendering is disabled by unregistering VGX.dll. Once we re-registered the DLL, charts are rendering. We can close this issue.
