### ISSUE TITLE
Crosshair labels don't respect snap: false

### ISSUE THREAD

**Issue by priikone** [highslide-software/highcharts.com#4722]
When setting snap: false I think it's reasonable to assume that the crosshair labels would then also show the actual position of the mouse pointer.  Example of current behavior: http://jsfiddle.net/1k5ufxsx/

I'd like something similar to http://jsfiddle.net/r7fdh/90/

**Comment by highslide-software** [comment]
Here's your case with the fix applied: http://jsfiddle.net/highcharts/1k5ufxsx/1/

I did some other approvements in the same commit - default padding to align with the X axis labels, hiding the labels on mouse out etc.

**Comment by priikone** [comment]
Works great! Thanks.

**Comment by priikone** [comment]
Well, talked to soon.  Actually it doesn't work with candlesticks.  It doesn't show the labels for example in between the candlesticks, or at any point in the chart that doesn't have some data point.

**Comment by highslide-software** [comment]
Are we talking about the X axis now? Does it help when you set `ordinal:false`? [View live jsFiddle](http://jsfiddle.net/highcharts/fzmL2r5L/).

**Comment by priikone** [comment]
Ok got it, it's the tooltip disabled that breaks it: http://jsfiddle.net/fzmL2r5L/1/  I'm not sure yet if I'm going to keep tooltips disabled in the end but for now I have them disabled.

**Comment by highslide-software** [comment]
Fixed that, see http://jsfiddle.net/highcharts/fzmL2r5L/2/.

**Comment by priikone** [comment]
Great! Thanks.

**Comment by priikone** [comment]
It does appear that the labels don't disappear automatically unless tooltip is enabled.
