### ISSUE TITLE
highstock demo page has a error

### ISSUE THREAD

**Issue by xiongjinpeng** [highslide-software/highcharts.com#4725]
demo url ------http://code.hcharts.cn/highstock/hhhhvT
when i click ‘1y’ of highstock image ，the url returns null，this request url is-----http://www.hcharts.cn/datas/jsonp.php?start=1287086340000&end=1318622340000&callback=jQuery18309539864535909146_1447047988844&_=1447049725420

**Comment by highslide-software** [comment]
Hi @xiongjinpeng 
This is a third party website, please report the issue to www.hcharts.cn.
