### ISSUE TITLE
Exporting: changing some marker options in chartOptions

### ISSUE THREAD

**Issue by KacperMadej** [highslide-software/highcharts.com#4729]
Changing marker enabled, radius, lineWidth, lineColor in chartOptions doesn't work.
fillColor and symbol are working.
Example: http://jsfiddle.net/ovnc9e5t/3/
Step: export to any format - not all changes are applied

Workaround for disabling markers for export - do not set enabled in chart, then markers can be disabled in chartOptions.
http://jsfiddle.net/ovnc9e5t/2/

**Comment by sebastianbochan** [comment]
Duplicate of https://github.com/highslide-software/highcharts.com/issues/4583

Workaround, call series update in load chart event.
