### ISSUE TITLE
Changing part of the series line colour when above plot line value

### ISSUE THREAD

**Issue by triforce** [highslide-software/highcharts.com#4730]
I am using vanilla Highcharts to plot a series and a fixed line (plot line). I require the series line to change colour when the data values in the series are above the fixed line value. I cannot find anything in the API that can do this - Is it currently possible? If not, could this be considered as a future enhancement?

Here is an example of what I need to happen to the series line:

Green line - Original series line colour
Red dash - Plot Line
Red line - Data in the series that is greater than plot line value

![fixedline](https://cloud.githubusercontent.com/assets/1353074/11066371/d509d946-87bf-11e5-8b1e-fa5ab7c7ce0b.png)

Many Thanks.

**Comment by KacperMadej** [comment]
One way - threshold and [negativeColor](http://api.highcharts.com/highcharts#series<line>.negativeColor).
Second way - [zones](http://api.highcharts.com/highcharts#series<line>.zones)

To get support use forum or StackOverflow. For requests use UserVoice. This is github and it is not for posting help request - read Highcharts' rules for issue reporting on GitHub Issues (https://github.com/highslide-software/highcharts.com/blob/master/readme.md#reporting-issues). If it is not a bug, please check one of the support channels. More information: http://www.highcharts.com/support
