### ISSUE TITLE
Hover halo is not opaque when series color is with hex color shorthand (999999 > 999)

### ISSUE THREAD

**Issue by envision** [highslide-software/highcharts.com#4732]
Took a while to track down this bug. So, hover halo's opacity setting doesn't apply when series color is with hex shorthand (for example HEX 999999 shorted to 999) or with named color like 'white'.

**Comment by highslide-software** [comment]
Live demo: http://jsfiddle.net/highcharts/s9ok9qox/.

In general, hex or rgba colors are recommended as noted in [the docs](http://www.highcharts.com/docs/chart-design-and-style/colors).

In the latest master, however, you can plug in to the Highcharts.Color object and define your own parser. For example, here's how to use a script called RGBColor to parse named colors: http://jsfiddle.net/highcharts/s9ok9qox/1/.

Having said that, I think we should use the fill-opacity attribute in this case. Fix coming up.
