### ISSUE TITLE
Tooltip positioner point.plotX is NaN

### ISSUE THREAD

**Issue by lemonbutter** [highslide-software/highcharts.com#4736]
Sometimes on zooming the point.plotX is NaN because one of the hoverPoints is not displayed in the chart and has therefore an undefined plotX. The getAnchor calculation then converts this to NaN.

Used Chrome and Highcharts 4.1.9/Highstock 2.1.9

Here a fiddle: http://jsfiddle.net/0c4jr323
It happens only with column like series and only when the xAxis is not categorized.

How to reproduce:
* Set a conditional breakpoint in the getPosition function of the tooltip prototype and check for 
```javascript
isNaN(point.plotX)
```
* zoom from the beginning to point 256. You have to ensure that the blue zoom indicator is a bit off the point to the left. So the marker nearly jump to the point 255.

**Comment by highslide-software** [comment]
Related to #1003, which fix only checked the first series, but in this case the second series was the culprit.
