### ISSUE TITLE
Funnel Chart not rendered correctly when height/width/center specified.

### ISSUE THREAD

**Issue by PaulLad77** [highslide-software/highcharts.com#4738]
The funnel chart does not render correctly when you specify the options for width/height or centre to change the position where the funnel is drawn.  

The following jsfiddle shows the effects of setting the height/width and centre on a funnel (http://jsfiddle.net/45s5vrg7/1/) 

The current code assumes the funnel will always be drawn relative to the centre and size of the plot area, so if it is moved around or resized the funnel is no longer rendered correctly.
 
I have made some modifications to the latest version of the funnel module file.to render the funnel relative to the specified width/height and its position in the plot area (see attached file).  The changes are marked with TODO comments.  

There is still one outstanding issue that I have not fixed.  If you set the reversed property (to reverse the orientation of the funnel) it is still not drawn correctly.  So this should probably be considered before applying any fix to the code base.

[funnel-chart-fix.txt](https://github.com/highslide-software/highcharts.com/files/33929/funnel-chart-fix.txt)

**Comment by highslide-software** [comment]
Thanks for your contribution!
