### ISSUE TITLE
Long xAxis labels are not trimmed (Bar chart)

### ISSUE THREAD

**Issue by agulov** [highslide-software/highcharts.com#4739]
Using binary search I found this issue can be reprodused since commit d718b4bc5ff918ab48d8ea27a07b7810aef9a0b0

Example:
http://jsfiddle.net/rebelraven/snj9bsz3/

**Comment by highslide-software** [comment]
Ironically, the case for the issue we were fixing has the same bug initially: http://jsfiddle.net/highcharts/p14w0bhr/2/
