### ISSUE TITLE
Exporting pie chart with size property set

### ISSUE THREAD

**Issue by madbull** [highslide-software/highcharts.com#4748]
When you use size property on pie chart, some long labels doesn't fit to chart area after exporting.

http://jsfiddle.net/LLExL/5416/

**Comment by highslide-software** [comment]
It isn't a problem with exporting per se, it is just that the exported chart has a different size. If you use the same size for both screen and export, you'll see the same thing: http://jsfiddle.net/highcharts/LLExL/5417/

**Comment by highslide-software** [comment]
Duplicate of #1581

**Comment by madbull** [comment]
I see, thank you for the quick response
