### ISSUE TITLE
Wrong vertical label position on rotation bar chart

### ISSUE THREAD

**Issue by dmitrygorbenko** [highslide-software/highcharts.com#4756]
Hi,
I found a bug when in bar chart I rotate vertical labels (specified in xAxis ) by 45 degree and it makes them display in wrong place.
It seems like what HC code calculates wrong label length and thinks it (label) should take much more size.
Try it out:  http://jsfiddle.net/DimaGorbenko/b3p9xj9a/

![issue](https://cloud.githubusercontent.com/assets/1971759/11271784/18e14538-8ed1-11e5-8293-b95e47a670d8.jpeg)

Thank you,
Dima

**Comment by dmitrygorbenko** [comment]
here is what I've found: file   hightcharts.js   function   getLabelPosition:

yOffset = mathCos(label.rotation * deg2rad) * (rotCorr.y - label.getBBox().height / 2);

this offset moves the label to the top taking into account:
1) angle
2) position of the rotCorr
3) height of the label

The problem what label.getBBox() returns "rotated height", while that line of code assumes what "label.getBBox().height" is the height of the not-rotated label (that's why it divides it by 2 --- to place it in center).

Here is my patch which fixed this case:

                    var labelHeight, savedAngle = label.rotation;
                    label.rotation = 0;
                    labelHeight = label.getBBox().height;
                    label.rotation = savedAngle;

                    yOffset = mathCos(label.rotation * deg2rad) * (rotCorr.y - labelHeight / 2);

**Comment by highslide-software** [comment]
Drag the handle to see the issue clearly: http://jsfiddle.net/highcharts/b3p9xj9a/2/
