### ISSUE TITLE
Get series object on `chart.events.addSeries`

### ISSUE THREAD

**Issue by jaapz** [highslide-software/highcharts.com#4758]
When a series is added, I want to access the new series in the `chart.events.addSeries` callback. However the callback on gets the `this` set to the Chart instance, and receives an `event` parameter with the `options` hash that was used to create the series.

How can I get the series object that actually contains things like the color, so the series object that you get when calling `chartInstance.series[0]`?

**Comment by pawelfus** [comment]
`chart.events.addSeries` is called **before** series is created (simple test case: http://jsfiddle.net/ux74929j/15/ - "red" series is added before true one). 

Is there some reason why you can't use this:

    var series = chart.addSeries({
        data: [10, 20
    });
   // series variable contains new series

**Comment by highslide-software** [comment]
Closing, please reopen if there is an actual issue.
