### ISSUE TITLE
Bubble chart abnormal axis content when bubble is too large

### ISSUE THREAD

**Issue by changbenny** [highslide-software/highcharts.com#4763]
In bubble chart, when a bubble where is near edge is going too big, highcharts will automatically generate new column or row to fit the bubble area. But the axis of new generated column should be empty, instead of numbered index. Number indexes is weird to the exist categories.

Example:
https://jsfiddle.net/highcharts/LLExL/ (Notice left-most and right-most bubble).

**Comment by pawelfus** [comment]
I think you posted wrong jsFiddle. Could you post the right one? Or update my use case: http://jsfiddle.net/e3Ly3wcw/ ? Thanks!

**Comment by changbenny** [comment]
Oops, sorry for the careless mistake.
Please see this: http://jsfiddle.net/e3Ly3wcw/2/ (Notice the negative number at y-axis).

**Comment by pawelfus** [comment]
Hm, this sounds like a good use case for `Axis.labels.formatter`, something like this:

    labels: {
        formatter: function () {
            var categoriesLength = this.axis.categories.legth,
                num = parseFloat(this.value),
                nan = isNaN(num),
                ret = '';

            if (nan || (!nan && num > 0 & num < categoriesLength)) {
                ret = this.value;
            }
            return ret;
        }
    }

See working demo: http://jsfiddle.net/e3Ly3wcw/4/

**Comment by changbenny** [comment]
Thanks, it's a neat solution.

**Comment by InstanceOfMichael** [comment]
```
this.axis.categories.legth
```
this is a typo

**Comment by pawelfus** [comment]
Thanks! Fixed
