### ISSUE TITLE
inconsistency in Data-label display 

### ISSUE THREAD

**Issue by saurabhshahpune** [highslide-software/highcharts.com#4765]
Inconsistency to display data-label between 3D & 2D chart. I.e 3D chart shows data-label as "null"  when there is no data(value as null) ,while 2D shows nothing.
http://jsfiddle.net/saurabheq/gbvbsahw/3/

**Comment by sebastianbochan** [comment]
Fixed in the newest master branch: http://jsfiddle.net/gbvbsahw/4/

I will reopen if problem still appears.
