### ISSUE TITLE
Setting chart data in quick succession results in wrong plotBands

### ISSUE THREAD

**Issue by markocikos** [highslide-software/highcharts.com#4769]
See http://jsfiddle.net/markocikos/kt0ayh4g/3/

To reproduce the issue, doubleclick on "Update Data" few times. Visibility of red svg fill does not update correctly.

Thank you!

**Comment by highslide-software** [comment]
I'm not sure what to look for... Is it a problem when clicking before the animation is finished? Does it help if you [disable animation](http://jsfiddle.net/highcharts/kt0ayh4g/4/)? Can you show us a sketch of what it looks like after the failure?

**Comment by markocikos** [comment]
Screenshot after failure: http://awesomescreenshot.com/0545fldl86. You can see yAxis goes to 3k, in that rendering the red fill should not be visible. 

Disabling animations does prevent the issue.

**Comment by highslide-software** [comment]
Reliable reproduction (click the Fail button): http://jsfiddle.net/highcharts/kt0ayh4g/5/
