### ISSUE TITLE
Highcharts marginleft issue

### ISSUE THREAD

**Issue by Karlen92** [highslide-software/highcharts.com#4771]
I cannot find the for changing chart margin left dynamically

**Comment by Karlen92** [comment]
i wonder if there is a way to do that

**Comment by highslide-software** [comment]
Hi, this is our issue tracker, for general tech questions please see www.highcharts.com/support.

To answer your question, you need to recreate the chart to do this: http://jsfiddle.net/highcharts/n7cnfvhx/

**Comment by Karlen92** [comment]
Thank you.
