### ISSUE TITLE
Mouseout fires incorrectly when points are at the bottom of the chart

### ISSUE THREAD

**Issue by ehinter** [highslide-software/highcharts.com#900]
See example:
http://jsfiddle.net/hTbsa/

If you position your mouse above the green series and then move it down onto a point, the 'moused over' text is shown (correctly).

If you position your mouse below the green series and then movie up onto a point, the 'moused out' text is shown (incorrectly).

**Comment by mikedaly** [comment]
Why is this incorrect?

**Comment by highslide-software** [comment]
It works correctly in Highcharts 4.1.7.
