### ISSUE TITLE
Connector of inner pie in the donut chart should have a higher zIndex

### ISSUE THREAD

**Issue by sivakumar-kailasam** [highslide-software/highcharts.com#901]
When creating a donut chart, if the inner series is meant to be denoted by the connectors outside the graph, the connector is visible only outside the outer series because of the zIndex assigned to them by default. There should be an option by which we can define a higher zIndex for the connector. Created a fiddle for this, http://jsfiddle.net/Df7Wr/

**Comment by pawelfus** [comment]
Works fine in 4.x+ : http://jsfiddle.net/JBUte/1/
