### ISSUE TITLE
Highstock: Area chart getExtremes returns 0 for dataMin

### ISSUE THREAD

**Issue by xdestiny** [highslide-software/highcharts.com#985]
Calculation of the dataMin extreme fails when share data is presented as an area chart. Try changing the type at the bottom of the HighCharts code to line to see the difference: http://jsfiddle.net/AsyaQ/

**Comment by datanotion** [comment]
Hello!  I know it's been a few years, but is the official fix from Highcharts the above workaround?  Or is this going to be fixed eventually?  It's a bit misleading for dataMin to always return a zero.  Thank you!!!
